// app.js — generated by the modularisation of index.html; see README for what lives where.
import { t } from './i18n.js';
import { applyStaticTexts, adjustMainPadding, applyTheme, closeSheet, cycleTheme, setStatus, showConnectionError } from './ui-common.js';
import { effectivePlanningDate, getISOWeekKey, refreshWeekKey } from './dates.js';
import { S } from './state.js';
import { db, purgeStaleDeviations, syncListeners } from './data.js';
import { renderImpersonateBanner, renderProfile } from './ui-profile.js';
import { recomputeCanEdit } from './coordinator.js';
import { renderSchedule } from './ui-schedule.js';
import { renderBeheer } from './ui-beheer.js';
import { renderMyWeek } from './ui-myweek.js';
import { renderDeviationTab } from './ui-deviation.js';
import { todayKey } from './constants.js';

// Values that need functions from other modules are set here, before anything else runs.
S.currentWeekKey = getISOWeekKey(effectivePlanningDate());
S.scheduleDay = todayKey || "Ma";

// ---------- PWA: service worker registration + install prompt (real on Android/Chrome,
// manual instructions on iOS Safari since it has no install-prompt API at all) ----------
// Long-lived tabs/PWAs: when the planning week rolls over (Saturday 00:00) while the app is
// open or resumed from the background, switch to the new week and purge the old one.
export function checkWeekRollover(){
  if(refreshWeekKey() && S.appReady){ purgeStaleDeviations(); renderAll(); }
}

export async function init(){
  applyStaticTexts();
  renderAll();
  setStatus(t('app.verbinden'));
  try{
    const cred = await db.signIn();
    S.me = cred.user.uid;
  }catch(e){
    setStatus(t('app.niet_verbonden'), true);
    showConnectionError(e);
    return;
  }
  try{
    const coordSnap = await db.doc("config/coordinator").get();
    S.coordinatorExists = coordSnap.exists;
    S.coordinatorConfig = coordSnap.exists? coordSnap.data() : null;
    S.appReady = true;
  }catch(e){
    setStatus(t('app.niet_verbonden'), true);
    showConnectionError(e);
    return;
  }
  recomputeCanEdit();
  // (status line itself is now set by recomputeCanEdit() -> updateStatusLine(), always in sync)
  const navB=document.getElementById('navBeheer');
  if(navB) navB.style.display = S.canEdit?'':'none';
  renderAll();
  try{
    // Only this browser's OWN link doc is readable before it's a member (Firestore rules).
    db.doc("links/"+S.me).onSnapshot(s=>{
      if(s.exists && s.pending) return; // wait until the server has accepted a new link (rules check the code)
      if(s.exists) S.links[S.me]=s.data(); else delete S.links[S.me];
      afterLinksChanged();
    }, err=>{ S.linksLoaded=true; setStatus(t('app.fout_bij_laden_koppeling')+(err&&err.message||err), true); renderAll(); });
  }catch(e){ setStatus(t('app.kon_niet_live_verbinden')+(e&&e.message||e), true); }
  adjustMainPadding();
}

export function afterLinksChanged(){
  S.linksLoaded = true;
  recomputeCanEdit();
  const navB=document.getElementById('navBeheer'); if(navB) navB.style.display = S.canEdit?'':'none';
  syncListeners();
  chooseDefaultTab();
  renderAll();
}

export function renderAll(){ renderProfile(); renderSchedule(); renderBeheer(); renderMyWeek(); renderDeviationTab(); renderImpersonateBanner(); adjustMainPadding(); }

// Switches the visible tab; every switch starts at the top of the new tab.
export function activateTab(tab){
  const btn=document.querySelector(`nav button[data-tab="${tab}"]`);
  if(!btn) return;
  document.querySelectorAll('nav button[data-tab]').forEach(x=>{ x.classList.remove('active'); x.removeAttribute('aria-current'); });
  btn.classList.add('active'); btn.setAttribute('aria-current','page');
  if(tab!=='profile') S.weekschemaWarn = false; // the Weekschema warning only lives while you stay in Mijn gezin
  if(document.getElementById('tab-gate').style.display!=='block'){
    ['schedule','myweek','deviation','profile','beheer'].forEach(t=>{
      const el=document.getElementById('tab-'+t);
      if(el) el.style.display = (tab===t)?'block':'none';
    });
  }
  const m=document.querySelector('main'); if(m) m.scrollTop=0;
}

export function chooseDefaultTab(){
  if(S.defaultTabChosen || !S.appReady) return;
  S.defaultTabChosen = true;
  S.roosterMode = S.canEdit? 'standard' : 'week';
  if(!S.hashTabApplied) activateTab('myweek'); // Mijn week is the home page for everyone
  renderSchedule();
}

// Everything that has to happen once, at start-up, before init(): global listeners, theme, tab wiring,
// service worker. It lives in a function (not at the top of the file) so importing app.js — for tests —
// has no side effects and needs no browser.
export function bootstrap(){

  
  document.addEventListener('keydown', e=>{ if(e.key==='Escape') closeSheet(); });

  (function initTheme(){
    let pref='light'; try{ pref=localStorage.getItem('theme-pref')||'light'; }catch(e){}
    applyTheme(pref);
    const btn=document.getElementById('themeToggle');
    if(btn) btn.onclick=cycleTheme;
  })();

  document.addEventListener('visibilitychange', ()=>{ if(!document.hidden) checkWeekRollover(); });

  setInterval(checkWeekRollover, 60*1000);

  if('serviceWorker' in navigator){
    navigator.serviceWorker.register('https://mveen.github.io/AZ-Carpool/service-worker.js').catch(()=>{});
  }

  window.addEventListener('beforeinstallprompt', (e)=>{ e.preventDefault(); S.deferredInstallPrompt=e; renderProfile(); });

  window.addEventListener('appinstalled', ()=>{ S.appIsInstalled=true; S.deferredInstallPrompt=null; renderProfile(); });

  document.querySelectorAll('nav button[data-tab]').forEach(b=>b.addEventListener('click',()=>activateTab(b.dataset.tab)));

  (function applyInitialHashTab(){
    try{
      const hash=(location.hash||'').replace('#','');
      if(!/^[a-z]+$/i.test(hash)) return; // only ever expect plain tab names — anything else is ignored, not risked
      const btn=document.querySelector(`nav button[data-tab="${hash}"]`);
      if(btn){
        document.querySelectorAll('nav button[data-tab]').forEach(x=>x.classList.remove('active'));
        btn.classList.add('active');
        S.hashTabApplied = true;
      }
    }catch(e){ /* a malformed hash must never be able to break the rest of the app's startup */ }
  })();
}

export function startApp(){ bootstrap(); return init(); }
