// constants.js — generated by the modularisation of index.html; see README for what lives where.
import { t } from './i18n.js';


export const PH_PATHS = {
  calendar: `<rect x="40" y="40" width="176" height="176" rx="16" fill="none" stroke="currentColor" stroke-width="16"/><line x1="40" y1="100" x2="216" y2="100" stroke="currentColor" stroke-width="16"/><line x1="88" y1="24" x2="88" y2="56" stroke="currentColor" stroke-width="16" stroke-linecap="round"/><line x1="168" y1="24" x2="168" y2="56" stroke="currentColor" stroke-width="16" stroke-linecap="round"/>`,
  'calendar-fill': `<rect x="40" y="40" width="176" height="176" rx="16" fill="currentColor"/><rect x="40" y="88" width="176" height="20" fill="var(--card,#fff)"/><line x1="88" y1="24" x2="88" y2="56" stroke="currentColor" stroke-width="16" stroke-linecap="round"/><line x1="168" y1="24" x2="168" y2="56" stroke="currentColor" stroke-width="16" stroke-linecap="round"/>`,
  user: `<circle cx="128" cy="96" r="52" fill="none" stroke="currentColor" stroke-width="16"/><path d="M24 224c0-48 32-80 104-80s104 32 104 80" fill="none" stroke="currentColor" stroke-width="16" stroke-linecap="round"/>`,
  'user-fill': `<circle cx="128" cy="96" r="52" fill="currentColor"/><path d="M24 224c0-48 32-80 104-80s104 32 104 80Z" fill="currentColor"/>`,
  users: `<circle cx="88" cy="100" r="44" fill="none" stroke="currentColor" stroke-width="16"/><path d="M24 216c0-40 28-68 64-68s64 28 64 68" fill="none" stroke="currentColor" stroke-width="16" stroke-linecap="round"/><path d="M162 88a44 44 0 0 1 0 88" fill="none" stroke="currentColor" stroke-width="16" stroke-linecap="round"/><path d="M184 148c26 8 40 32 40 68" fill="none" stroke="currentColor" stroke-width="16" stroke-linecap="round"/>`,
  'users-fill': `<circle cx="88" cy="100" r="44" fill="currentColor"/><path d="M24 216c0-40 28-68 64-68s64 28 64 68Z" fill="currentColor"/><path d="M162 88a44 44 0 0 1 0 88 44 44 0 0 1-10-1.2 68 68 0 0 0 18-42.8 68 68 0 0 0-18-42.8A44 44 0 0 1 162 88Z" fill="currentColor"/><path d="M184 148c26 8 40 32 40 68h-40Z" fill="currentColor"/>`,
  lightning: `<path d="M167.84 17.09a8 8 0 0 0-8.85 1L47 121a8 8 0 0 0 3 13l57.63 21.61-14.66 73.33a8 8 0 0 0 13.69 7l112-120a8 8 0 0 0-6.98-13.34l-57.64-6.4 14.66-73.33a8 8 0 0 0-1.16-6.78Z" fill="none" stroke="currentColor" stroke-width="16" stroke-linejoin="round"/>`,
  'lightning-fill': `<path d="M167.84 17.09a8 8 0 0 0-8.85 1L47 121a8 8 0 0 0 3 13l57.63 21.61-14.66 73.33a8 8 0 0 0 13.69 7l112-120a8 8 0 0 0-6.98-13.34l-57.64-6.4 14.66-73.33a8 8 0 0 0-1.16-6.78Z" fill="currentColor"/>`,
  gear: (()=>{
    let teeth=''; for(let i=0;i<8;i++) teeth += `<line x1="128" y1="44" x2="128" y2="68" stroke="currentColor" stroke-width="18" stroke-linecap="round" transform="rotate(${i*45} 128 128)"/>`;
    return `<circle cx="128" cy="128" r="60" fill="none" stroke="currentColor" stroke-width="14"/>${teeth}<circle cx="128" cy="128" r="20" fill="none" stroke="currentColor" stroke-width="12"/>`;
  })(),
  'gear-fill': (()=>{
    let teeth=''; for(let i=0;i<8;i++) teeth += `<rect x="118" y="36" width="20" height="30" rx="6" fill="currentColor" transform="rotate(${i*45} 128 128)"/>`;
    const ring = `<path fill-rule="evenodd" fill="currentColor" d="M188,128 A60,60 0 1,0 68,128 A60,60 0 1,0 188,128 Z M148,128 A20,20 0 1,0 108,128 A20,20 0 1,0 148,128 Z"/>`;
    return ring + teeth;
  })(),
  warning: `<path d="M236 208H20a8 8 0 0 1-7-11.9L121 44.5a8 8 0 0 1 14 0l108 151.6a8 8 0 0 1-7 11.9Z" fill="none" stroke="currentColor" stroke-width="16" stroke-linejoin="round"/><line x1="128" y1="104" x2="128" y2="144" stroke="currentColor" stroke-width="16" stroke-linecap="round"/><circle cx="128" cy="172" r="10" fill="currentColor"/>`,
  check: `<polyline points="216,72 96,192 40,136" fill="none" stroke="currentColor" stroke-width="18" stroke-linecap="round" stroke-linejoin="round"/>`,
  'check-circle': `<circle cx="128" cy="128" r="96" fill="none" stroke="currentColor" stroke-width="16"/><polyline points="172,100 116,156 84,128" fill="none" stroke="currentColor" stroke-width="16" stroke-linecap="round" stroke-linejoin="round"/>`,
  car: `<path d="M48 176v16a8 8 0 0 0 8 8h16a8 8 0 0 0 8-8v-16h96v16a8 8 0 0 0 8 8h16a8 8 0 0 0 8-8v-16h8a8 8 0 0 0 8-8v-40a24 24 0 0 0-16.8-22.9l-9.6-32A24 24 0 0 0 178 56H78a24 24 0 0 0-23.6 17.1l-9.6 32A24 24 0 0 0 24 128v40a8 8 0 0 0 8 8Z" fill="none" stroke="currentColor" stroke-width="14" stroke-linejoin="round"/><circle cx="80" cy="152" r="12" fill="currentColor"/><circle cx="176" cy="152" r="12" fill="currentColor"/>`,
  trash: `<path d="M56 64h144l-12 144a8 8 0 0 1-8 8H76a8 8 0 0 1-8-8Z" fill="none" stroke="currentColor" stroke-width="16" stroke-linejoin="round"/><line x1="40" y1="64" x2="216" y2="64" stroke="currentColor" stroke-width="16" stroke-linecap="round"/><path d="M96 64V48a16 16 0 0 1 16-16h32a16 16 0 0 1 16 16v16" fill="none" stroke="currentColor" stroke-width="16"/>`,
  pencil: `<path d="M64 192 40 216l24-64L188 28a20 20 0 0 1 28 0l12 12a20 20 0 0 1 0 28Z" fill="none" stroke="currentColor" stroke-width="16" stroke-linejoin="round"/><line x1="160" y1="56" x2="200" y2="96" stroke="currentColor" stroke-width="16"/>`,
  dice: `<rect x="40" y="40" width="176" height="176" rx="24" fill="none" stroke="currentColor" stroke-width="16"/><circle cx="88" cy="88" r="12" fill="currentColor"/><circle cx="168" cy="88" r="12" fill="currentColor"/><circle cx="128" cy="128" r="12" fill="currentColor"/><circle cx="88" cy="168" r="12" fill="currentColor"/><circle cx="168" cy="168" r="12" fill="currentColor"/>`,
  refresh: `<path d="M60 108a72 72 0 0 1 122-42l14 14M196 148a72 72 0 0 1-122 42l-14-14" fill="none" stroke="currentColor" stroke-width="16" stroke-linecap="round"/><polyline points="180,50 182,80 152,80" fill="none" stroke="currentColor" stroke-width="16" stroke-linecap="round" stroke-linejoin="round"/><polyline points="76,206 74,176 104,176" fill="none" stroke="currentColor" stroke-width="16" stroke-linecap="round" stroke-linejoin="round"/>`,
  flask: `<path d="M100 32h56M108 32v64l-56 108a16 16 0 0 0 14 24h124a16 16 0 0 0 14-24l-56-108V32" fill="none" stroke="currentColor" stroke-width="16" stroke-linecap="round" stroke-linejoin="round"/><line x1="76" y1="168" x2="180" y2="168" stroke="currentColor" stroke-width="16"/>`,
  x: `<line x1="200" y1="56" x2="56" y2="200" stroke="currentColor" stroke-width="18" stroke-linecap="round"/><line x1="200" y1="200" x2="56" y2="56" stroke="currentColor" stroke-width="18" stroke-linecap="round"/>`,
  star: `<path d="M128 32l30 64 70 10-51 50 12 70-61-32-61 32 12-70-51-50 70-10Z" fill="none" stroke="currentColor" stroke-width="14" stroke-linejoin="round"/>`,
  'arrow-left': `<line x1="216" y1="128" x2="40" y2="128" stroke="currentColor" stroke-width="18" stroke-linecap="round"/><polyline points="104,64 40,128 104,192" fill="none" stroke="currentColor" stroke-width="18" stroke-linecap="round" stroke-linejoin="round"/>`,
  'arrow-up': `<line x1="128" y1="216" x2="128" y2="40" stroke="currentColor" stroke-width="18" stroke-linecap="round"/><polyline points="64,104 128,40 192,104" fill="none" stroke="currentColor" stroke-width="18" stroke-linecap="round" stroke-linejoin="round"/>`,
  'arrow-down': `<line x1="128" y1="40" x2="128" y2="216" stroke="currentColor" stroke-width="18" stroke-linecap="round"/><polyline points="64,152 128,216 192,152" fill="none" stroke="currentColor" stroke-width="18" stroke-linecap="round" stroke-linejoin="round"/>`,
  'arrow-right': `<line x1="40" y1="128" x2="216" y2="128" stroke="currentColor" stroke-width="18" stroke-linecap="round"/><polyline points="152,64 216,128 152,192" fill="none" stroke="currentColor" stroke-width="18" stroke-linecap="round" stroke-linejoin="round"/>`,
  sun: `<circle cx="128" cy="128" r="42" fill="none" stroke="currentColor" stroke-width="16"/><path d="M128 24v24M128 208v24M232 128h-24M48 128H24M197 59l-17 17M76 180l-17 17M197 197l-17-17M76 76 59 59" stroke="currentColor" stroke-width="16" stroke-linecap="round"/>`,
  moon: `<path d="M216 136A88 88 0 1 1 120 40a70 70 0 0 0 96 96Z" fill="none" stroke="currentColor" stroke-width="16" stroke-linejoin="round"/>`,
  home: `<path d="M32 128 128 48l96 80" fill="none" stroke="currentColor" stroke-width="16" stroke-linecap="round" stroke-linejoin="round"/><path d="M56 112v88a8 8 0 0 0 8 8h128a8 8 0 0 0 8-8v-88" fill="none" stroke="currentColor" stroke-width="16" stroke-linejoin="round"/>`,
  away: `<path d="M128 20c-44 0-80 36-80 80 0 60 80 136 80 136s80-76 80-136c0-44-36-80-80-80Z" fill="none" stroke="currentColor" stroke-width="14" stroke-linejoin="round"/><circle cx="128" cy="100" r="28" fill="none" stroke="currentColor" stroke-width="14"/>`,
  soccer: `<circle cx="128" cy="128" r="96" fill="none" stroke="currentColor" stroke-width="16"/><polygon points="128,92 162,117 149,157 107,157 94,117" fill="currentColor"/><path d="M128 92V32M162 117l57-19M149 157l35 49M107 157l-35 49M94 117 37 98" stroke="currentColor" stroke-width="14" stroke-linecap="round"/>`,
  eye: `<path d="M16 128 Q128 32 240 128 Q128 224 16 128 Z" fill="none" stroke="currentColor" stroke-width="16" stroke-linejoin="round"/><circle cx="128" cy="128" r="32" fill="none" stroke="currentColor" stroke-width="16"/>`,
};

export const DAYS=[["Ma","Maandag"],["Di","Dinsdag"],["Wo","Woensdag"],["Do","Donderdag"],["Vr","Vrijdag"]];

// One wording for the two directions, everywhere in the app.
export const DIR_TEXT = { heen:t('dir.heen'), terug:t('dir.terug') };

// Today's DAYS-key, if it's a weekday — used to default Rooster's day-carousel and to mark "today".
// True weekday-or-null: null on Sat/Sun means "no day is actually today" — used ONLY for
// real "is this today" indicators (green dot, VANDAAG badge). Never falls back to a weekday.
export const todayKey = (()=>{ const map=[null,"Ma","Di","Wo","Do","Vr",null]; return map[new Date().getDay()]; })();

// ---------- WhatsApp update button: opens a pre-filled draft, coordinator/parent still sends it ----------
export const APP_URL = "https://mveen.github.io/AZ-Carpool/";

export const WHATSAPP_SVG = `<svg width="18" height="18" viewBox="0 0 24 24" style="vertical-align:middle;margin-right:6px" aria-hidden="true"><circle cx="12" cy="12" r="12" fill="#25D366"/><path fill="#fff" d="M12 5.5a6.5 6.5 0 0 0-5.6 9.8L5.5 18.5l3.3-.9A6.5 6.5 0 1 0 12 5.5zm0 1.2a5.3 5.3 0 1 1 0 10.6 5.2 5.2 0 0 1-2.7-.7l-.2-.1-2 .5.5-1.9-.1-.2A5.3 5.3 0 0 1 12 6.7zm-2.8 2.6c-.1 0-.3 0-.4.2-.1.2-.6.6-.6 1.4s.6 1.6.7 1.7c.1.1 1.2 1.9 3 2.6 1.5.6 1.8.5 2.1.4.3 0 1-.4 1.1-.8.1-.4.1-.8.1-.9-.1-.1-.2-.1-.4-.2l-1.2-.6c-.2-.1-.3-.1-.4.1l-.5.6c-.1.1-.2.2-.4.1-.2-.1-.8-.3-1.5-.9-.6-.5-1-1.2-1.1-1.4-.1-.2 0-.3.1-.4l.3-.4c.1-.1.1-.2.2-.4 0-.1 0-.3 0-.4l-.5-1.3c-.1-.3-.3-.3-.4-.3h-.3z"/></svg>`;

// ---------- Seed from PDF ----------
export const PDF_SEED = [
  {girlName:"Evi",     schedule:{Ma:{heen:"10:15",terug:"18:00"},Di:{heen:"08:30",terug:"17:00"},Wo:{heen:"08:30",terug:"15:30"},Do:{heen:"09:15",terug:"17:30"},Vr:{heen:"08:00",terug:"15:30"}}},
  {girlName:"Jahaimy", schedule:{Ma:{heen:"08:30",terug:"16:45"},Di:{heen:"09:15",terug:"17:30"},Wo:{heen:"08:30",terug:"14:45"},Do:{heen:"08:30",terug:"17:30"},Vr:{heen:"09:15",terug:"16:45"}}},
  {girlName:"Anouk",   schedule:{Ma:{heen:"10:15",terug:"17:00"},Di:{heen:"08:15",terug:"13:45"},Wo:{heen:"10:15",terug:"13:00"},Do:{heen:"08:30",terug:"18:00"},Vr:{heen:"08:30",terug:"13:00"}}},
  {girlName:"Eline",   schedule:{Ma:{heen:"08:30",terug:"17:00"},Di:{heen:"08:15",terug:"14:45"},Wo:{heen:"10:15",terug:"15:30"},Do:{heen:"10:15",terug:"18:00"},Vr:{heen:"08:30",terug:"15:30"}}},
  {girlName:"Jet",     schedule:{Ma:{heen:"11:00",terug:"17:00"},Di:{heen:"08:15",terug:"14:45"},Wo:{heen:"13:00",terug:"15:30"},Do:{heen:"11:00",terug:"18:00"},Vr:{heen:"08:30",terug:"13:00"}}},
  {girlName:"Saar",    schedule:{Ma:{heen:"11:00",terug:"17:00"},Di:{heen:"08:15",terug:"14:45"},Wo:{heen:"13:00",terug:"15:30"},Do:{heen:"11:00",terug:"18:00"},Vr:{heen:"08:30",terug:"13:00"}}},
  {girlName:"Loïs",    schedule:{Ma:{heen:"10:15",terug:"17:00"},Di:{heen:"08:15",terug:"14:45"},Wo:{heen:"10:15",terug:"13:00"},Do:{heen:"08:30",terug:"18:00"},Vr:{heen:"08:30",terug:"13:00"}}},
  {girlName:"Robbin",  schedule:{Ma:{heen:"13:15",terug:"17:00"},Di:{heen:"08:15",terug:"12:00"},Wo:{heen:"",terug:""},Do:{heen:"13:15",terug:"18:00"},Vr:{heen:"08:30",terug:"10:45"}}}
];

export const WA_ICON_SMALL = `<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="12" fill="#25D366"/><path fill="#fff" d="M12 5.5a6.5 6.5 0 0 0-5.6 9.8L5.5 18.5l3.3-.9A6.5 6.5 0 1 0 12 5.5zm0 1.2a5.3 5.3 0 1 1 0 10.6 5.2 5.2 0 0 1-2.7-.7l-.2-.1-2 .5.5-1.9-.1-.2A5.3 5.3 0 0 1 12 6.7z"/></svg>`;
