// coordinator.js — generated by the modularisation of index.html; see README for what lives where.
import { t } from './i18n.js';
import { S } from './state.js';
import { fam } from './rides.js';
import { updateStatusLine } from './ui-common.js';

// Who's making this change right now, for the "laatst bijgewerkt door" footers.
export function myDisplayInfo(){
  const linked = !!(S.links[S.me] && S.links[S.me].familyId) || !!S.impersonateFamilyId;
  if(linked){
    const f = fam(myFamilyId());
    return { name: f.parentName||t('coordinator.onbekend'), phone: f.parentPhone1||f.parentPhone2||'' };
  }
  return { name: S.canEdit? t('coordinator.coordinator') : t('coordinator.onbekend'), phone: '' };
}

export function myFamilyId(){ return myFamilyIdFor(S); }

// ---------- pure rules (state passed in; no browser, no database) ----------
// Real coordinator rights, ignoring the "test as parent" view (which only changes what's SHOWN).
// state: { coordinatorConfig, me, links }
export function isRealCoordinatorFor(state){
  const { coordinatorConfig, me, links } = state;
  if(!coordinatorConfig || !me) return false;
  if(coordinatorConfig.uid && coordinatorConfig.uid===me) return true;
  return !!(coordinatorConfig.familyId && links[me] && links[me].familyId===coordinatorConfig.familyId);
}
// Coordinator status is either tied to the original claiming browser (uid), or — once the
// coordinator designates one in Beheer — to whichever family is linked as "coordinator gezin",
// so it survives clearing browser data as long as that family re-verifies through the gate.
// Testing as a parent always overrides real coordinator status.
export function canEditFor(state){
  if(state.impersonateFamilyId) return false;
  return isRealCoordinatorFor(state);
}
// Members may read/write data: the coordinator, or a browser linked to a family through the gate.
export function isMemberFor(state){ return isRealCoordinatorFor(state) || !!(state.links[state.me] && state.links[state.me].familyId); }
export function needsGateFor(state){ if(state.impersonateFamilyId) return false; return !!state.me && !state.canEdit && !(state.links[state.me] && state.links[state.me].familyId); }
export function myFamilyIdFor(state){ return state.impersonateFamilyId || (state.links[state.me] && state.links[state.me].familyId) || state.me; }

export function isValidInviteCode(c){ return /^[A-Za-z0-9-]{4,32}$/.test(c||''); }

// ---------- wrappers over the shared app state ----------
export function isRealCoordinator(){ return isRealCoordinatorFor(S); }
export function isMemberNow(){ return isMemberFor(S); }
export function recomputeCanEdit(){ S.canEdit = canEditFor(S); updateStatusLine(); }

// ---------- Access gate: phone + daughter + coordinator-issued code, before anything else shows ----------
// 10 random digits (crypto RNG): anyone can try looking up a code, so it must be too large
// to guess by brute force. Still digits only, so parents get the numeric keypad.
export function genCode(){
  const a=new Uint32Array(10); crypto.getRandomValues(a);
  return String(1+a[0]%9) + Array.from(a.slice(1), n=>n%10).join('');
}

export function needsGate(){ return needsGateFor(S); }

// Compares Dutch numbers regardless of 06.../ +316.../ 00316... formatting or stray spaces/dashes.
export function normalizePhone(p){
  let digits=(p||'').replace(/[^\d]/g,'');
  if(digits.startsWith('0031')) digits='0'+digits.slice(4);
  else if(digits.startsWith('31') && digits.length>=11) digits='0'+digits.slice(2);
  return digits;
}

export function slugify(s){ return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-'); }

// The logged-in parent's own family (null for a coordinator who isn't linked to a family).
export function myLinkedFamilyId(){ const linked = !!S.impersonateFamilyId || !!(S.links[S.me] && S.links[S.me].familyId); return linked? myFamilyId() : null; }

// ---------- Dagcoördinator (US-02): who handles change requests on a weekday ----------
// Beheer stores { Ma: familyId, Di: familyId, ... } in settings/dayCoordinators. The name and phone number are
// always read from the family, never stored or written into the code.
// state: { dayCoordinators, families }. Returns { familyId, name, phone } or null when none is set.
export function dayCoordinatorFor(state, day){
  const id = state.dayCoordinators && state.dayCoordinators[day];
  const f = id && state.families && state.families[id];
  if(!f) return null;
  return { familyId:id, name:f.parentName||'', phone:f.parentPhone1||f.parentPhone2||'' };
}
