// data.js — generated by the modularisation of index.html; see README for what lives where.
import { t, locale } from './i18n.js';
import { S } from './state.js';
import { deviationExpiryMs, deviationKey, getISOWeekKey, effectivePlanningDate, refreshWeekKey, weekKeyDayIso } from './dates.js';
import { isMemberNow, isRealCoordinator, isValidInviteCode, myDisplayInfo, myLinkedFamilyId, normalizePhone, recomputeCanEdit } from './coordinator.js';
import { notifyCoordinatorOfNewTimeChanges, renderBeheer } from './ui-beheer.js';
import { renderAll } from './app.js';
import { renderNoticeBanner } from './ui-notice.js';
import { normalizeNotice } from './notice.js';
import { renderMaintenance } from './ui-maintenance.js';
import { normalizeMaintenance } from './maintenance.js';
import { normalizeRitbeurs } from './ritbeurs.js';
import { checkRitbeurs } from './ritbeurs-data.js';
import { setStatus, showToast, updateStatusLine } from './ui-common.js';
import { renderSchedule } from './ui-schedule.js';
import { renderMyWeek } from './ui-myweek.js';
import { renderDeviationTab } from './ui-deviation.js';
import { renderMatchesTab } from './ui-matches.js';
import { calculateMatchDistances, currentMatchList, refreshMatchesIfStale } from './matches.js';
import { readFamilyForm } from './ui-profile.js';
import { computeDepartureTime, computeRideDeparture, effectiveCars, eligibleDrivers, groupsFor, isFlex, planPeriodRooster, planPeriodShift } from './rides.js';
import { applyOv, keepOv, ovIds } from './ov.js';
import { impactGate } from './impact.js';
import { newLogDocs, withCarRemoved } from './ride-log.js';
import { PERIOD_BACKUP_MAX, autoBackupId, backupId, backupsFor, buildPeriodBackup, countManual, planRestore, validBackup } from './period-backup.js';
import { deadlineMs, isValidIsoDate, isWorkday, mergePeriods, periodEntryId, periodEntryState, periodForDate, periodList, periodShiftId, periodWorkdays, storedPeriod, validateEntry, validatePeriod } from './period.js';

// ============================================================
// Firestore access. The app talks to `db` only; `db` delegates to whichever adapter
// initDb() was given: the real Firestore adapter in production (see index.html),
// or an in-memory fake in the tests (fake-db.js).
//   db.doc(path)            -> { get, set, update, delete, onSnapshot }
//   db.collection(path)     -> { get, onSnapshot, doc }
//   db.batch()              -> { set(path,data,opts), update(path,data), delete(path), commit() }
//   db.deleteField(), db.signIn(), db.calendarApiKey, db.setListenerSink(array|null)
// The OpenRouteService key is NOT here: it lives in the database (settings/apiKeys, members only) -> S.orsApiKey.
// ============================================================
export function createFirestoreDb({ sdk, firestoreDb, auth, calendarApiKey }){
  const { collection, doc, getDoc, getDocs, setDoc, updateDoc, deleteDoc, onSnapshot, writeBatch, deleteField, signInAnonymously } = sdk;
  function wrapDocSnap(s){ return { id:s.id, exists:s.exists(), data:()=>s.data(), pending:!!(s.metadata&&s.metadata.hasPendingWrites) }; }
  // While startDataListeners() runs, every onSnapshot() made through this adapter drops its
  // unsubscribe function in here, so all member-only listeners can be stopped together.
  let listenerSink = null;
  function track(unsub){ if(listenerSink) listenerSink.push(unsub); return unsub; }
  function wrapQuerySnap(s){ return { docs: s.docs.map(wrapDocSnap) }; }
  function docRef(path){
    const ref = doc(firestoreDb, ...path.split('/'));
    return {
      get: ()=>getDoc(ref).then(wrapDocSnap),
      set: (data,opts)=>setDoc(ref, data, opts),
      update: (data)=>updateDoc(ref, data),
      delete: ()=>deleteDoc(ref),
      onSnapshot: (onNext,onErr)=>track(onSnapshot(ref, s=>onNext(wrapDocSnap(s)), onErr))
    };
  }
  function collRef(path){
    const ref = collection(firestoreDb, path);
    return {
      get: ()=>getDocs(ref).then(wrapQuerySnap),
      onSnapshot: (onNext,onErr)=>track(onSnapshot(ref, s=>onNext(wrapQuerySnap(s)), onErr)),
      doc: (id)=>docRef(path+'/'+id)
    };
  }
  return {
    doc: docRef, collection: collRef,
    batch: ()=>{ const b=writeBatch(firestoreDb); const r=p=>doc(firestoreDb, ...p.split('/'));
      return { set:(p,d,o)=>b.set(r(p),d,o), update:(p,d)=>b.update(r(p),d), delete:(p)=>b.delete(r(p)), commit:()=>b.commit() }; },
    deleteField: ()=>deleteField(),
    signIn: ()=>signInAnonymously(auth),
    calendarApiKey,
    setListenerSink: (a)=>{ listenerSink = a; }
  };
}
let dbImpl = null;
export function initDb(impl){ dbImpl = impl; }
export const db = {
  doc: (p)=>dbImpl.doc(p),
  collection: (p)=>dbImpl.collection(p),
  batch: ()=>dbImpl.batch(),
  deleteField: ()=>dbImpl.deleteField(),
  signIn: ()=>dbImpl.signIn(),
  get calendarApiKey(){ return dbImpl.calendarApiKey; },
  setListenerSink: (a)=>dbImpl.setListenerSink(a)
};
// ============================================================



export async function purgeStaleMatchCarpools(){
  const cutoff = Date.now() - 24*60*60*1000; // 1 day grace period after the match
  for(const [slug,d] of Object.entries(S.matchCarpools)){
    if((d.startMs||0) < cutoff){ try{ await db.doc("matchCarpools/"+slug).delete(); }catch(e){} }
  }
}

// Rides that have taken place are logged for the solidarity overview in Beheer (see ride-log.js). Only the coordinator's app does it,
// and only once the log and the deviations have been read; it runs before old deviations are purged, so a one-off change is counted too.
export async function logPassedShifts(){
  if(!db || !S.rideLogLoaded || !S.deviationsLoaded || !isRealCoordinator()) return 0;
  refreshWeekKey();
  const planning = effectivePlanningDate(), lastWeek = new Date(planning); lastWeek.setDate(planning.getDate() - 7);
  const weekKeys = [getISOWeekKey(lastWeek), S.currentWeekKey];
  const docs = newLogDocs({
    weekKeys, families: S.families, logged: S.rideLog, nowMs: Date.now(), isoOf: weekKeyDayIso,
    carsOf: (weekKey, day, direction) => effectiveCars(day, direction, { ...S, currentWeekKey: weekKey }),
  });
  let n = 0;
  for(const [id, doc] of docs){
    try{ await db.doc("rideLog/"+id).set(doc); S.rideLog[id] = doc; n++; }catch(e){}
  }
  if(n) renderBeheer();
  return n;
}

// The coordinator removes one ride from the Gereden shifts overview (or puts it back). The ride stays in the log, marked `removed`, so
// logPassedShifts does not log that shift again; it only stops counting. Returns true when it was stored.
export async function setRideRemoved(id, index, familyId, removed){
  if(!db || !isRealCoordinator()) return false;
  const doc = withCarRemoved(S.rideLog[id], index, familyId, removed);
  if(!doc) return false;
  try{ await db.doc("rideLog/"+id).set(doc); }catch(e){ return false; }
  S.rideLog[id] = doc;
  renderBeheer();
  return true;
}

export async function purgeStaleDeviations(){
  refreshWeekKey();
  await logPassedShifts();
  const now = Date.now();
  for(const [key,dev] of Object.entries(S.deviations)){
    // Only ever purge an OLDER week (ISO keys like "2026-W39" sort correctly as strings) and
    // only once its own expiry has passed — never a newer week's deviation.
    const olderWeek = !dev.weekKey || dev.weekKey < S.currentWeekKey;
    const expired = typeof dev.expiresAt!=='number' || dev.expiresAt <= now;
    if(olderWeek && expired){
      try{ await db.doc("deviations/"+key).delete(); }catch(e){}
    }
  }
}

// Step 2 of "periode met andere tijden": a family hands in its times for the period (once per period; it can be changed until the
// deadline, and by the coordinator after it). `firstDay` = the period. `rawDays` = the form: { 'YYYY-MM-DD': { out, heen, terug } } for every workday.
// Nothing is stored unless the times are valid and the moment allows it. Returns true when stored.
export async function savePeriodEntry(familyId, firstDay, rawDays){
  if(!db){ showToast(t('data.geen_verbinding_met_opslag')); return false; }
  const period = S.periods[firstDay], f = S.families[familyId];
  if(!period || !f){ showToast(t('period.entry.err.noPeriod')); return false; }
  const id = periodEntryId(period, familyId);
  const st = periodEntryState(period, S.periodEntries[id], { hasFamily:true, isFlex:isFlex(f), canEdit:S.canEdit });
  if(!st.canEdit){ showToast(t('period.entry.err.closed')); return false; }
  const res = validateEntry(period, rawDays);
  if(!res.ok){
    const e = res.errors[0];
    const [y,m,d] = String(e.day).split('-').map(Number);
    const label = e.day? new Date(y,m-1,d).toLocaleDateString(locale(),{weekday:'long',day:'numeric',month:'short'}).replace('.','') : '';
    showToast(t(e.key,{p1:label}));
    return false;
  }
  const doc = { familyId, periodFirstDay:period.firstDay, days:res.days, submittedAt:Date.now(), by:myDisplayInfo().name };
  try{
    await db.doc("periodEntries/"+id).set(doc);
    S.periodEntries = {...S.periodEntries, [id]:doc};
    showToast(t('period.entry.saved'));
    return true;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

// ---------- Periode met andere tijden, step 4: the temporary rooster (coordinator) ----------
// One document per shift: periodCars/<firstDay>_<date>_<direction>. Where it exists it replaces the standard rooster for that date
// (rides.js periodShift); one-off changes in Wijzigen still go before it. Only the coordinator writes (firestore.rules).
const cleanPeriodCars = cars => (cars||[])
  .map(c=>({ driverFamilyId:c.driverFamilyId||'', girlIds:[...new Set((c.girlIds||[]).filter(id=>typeof id==='string' && id))], departureTime:c.departureTime||'' }))
  .filter(c=>c.girlIds.length);

function periodShiftDocOf(period, iso, direction, cars){
  return { periodFirstDay:period.firstDay, date:iso, direction, cars:cleanPeriodCars(cars), madeAt:Date.now(), by:myDisplayInfo().name };
}

// Only the coordinator changes a temporary rooster. Returns false (with the reason shown) when not allowed.
function periodRoosterGuard(){
  if(!db){ showToast(t('data.geen_verbinding_met_opslag')); return false; }
  if(!S.canEdit){ showToast(t('period.rooster.err.coordinator')); return false; }
  return true;
}
const noPeriodToast = () => showToast(t(periodList(S.periods).length? 'period.rooster.err.shift' : 'period.entry.err.noPeriod'));

// Stores the cars of ONE shift (a date of a period and a direction). The period is the one that date belongs to. Returns true when stored.
export async function savePeriodShift(iso, direction, cars){
  if(!periodRoosterGuard()) return false;
  const p = periodForDate(S.periods, iso);
  if(!p){ noPeriodToast(); return false; }
  if(!isWorkday(iso) || (direction!=='heen' && direction!=='terug')){ showToast(t('period.rooster.err.shift')); return false; }
  const doc = periodShiftDocOf(p, iso, direction, cars), id = periodShiftId(p, iso, direction);
  try{
    await db.doc("periodCars/"+id).set(doc);
    S.periodCars = {...S.periodCars, [id]:doc};
    return true;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

// "Tijdelijk rooster maken" / "Alles opnieuw indelen": plans every shift of ONE period with the handed-in times and stores them together.
export async function makePeriodRooster(firstDay){
  if(!periodRoosterGuard()) return false;
  const p = S.periods[firstDay];
  if(!p){ noPeriodToast(); return false; }
  const plan = planPeriodRooster(S, p);
  const batch = db.batch(), docs = {};
  plan.forEach(s=>{ const id = periodShiftId(p, s.iso, s.direction); docs[id] = periodShiftDocOf(p, s.iso, s.direction, s.cars); batch.set('periodCars/'+id, docs[id]); });
  try{
    await batch.commit();
    S.periodCars = {...S.periodCars, ...docs};
    showToast(t('period.rooster.made'));
    return true;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

// Plans one shift again ("Opnieuw indelen"): the proposal replaces the cars of that shift.
export async function replanPeriodShift(iso, direction){
  if(!periodRoosterGuard()) return false;
  const ok = await savePeriodShift(iso, direction, planPeriodShift(iso, direction).cars);
  if(ok) showToast(t('period.rooster.replanned'));
  return ok;
}

// The shifts of one period that have a temporary rooster.
export function periodShiftIds(period){
  return periodWorkdays(period.firstDay, period.lastDay).flatMap(iso=>['heen','terug'].map(d=>periodShiftId(period, iso, d))).filter(id=>S.periodCars[id] && S.periodCars[id].periodFirstDay===period.firstDay);
}

// Back to the standard rooster for the whole of one period: removes every shift of that period (the handed-in times stay).
export async function deletePeriodRooster(firstDay){
  if(!periodRoosterGuard()) return false;
  const p = S.periods[firstDay];
  if(!p){ noPeriodToast(); return false; }
  const ids = periodShiftIds(p);
  const batch = db.batch();
  ids.forEach(id=>batch.delete('periodCars/'+id));
  try{
    await batch.commit();
    const rest = {...S.periodCars}; ids.forEach(id=>delete rest[id]);
    S.periodCars = rest;
    showToast(t('period.rooster.removed'));
    return true;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

// ---------- The periods themselves (Beheer, coordinator) ----------
// periods/<firstDay>: name, first and last day, when filling in opens, the deadline and `deadlineAt` (the deadline as a moment, for firestore.rules).
// Periods never share a day. The first day is the id and the key of the handed-in times and the temporary rooster, so it cannot change
// once there is something stored for the period.
export function periodHasData(firstDay){
  const p = S.periods[firstDay];
  const entries = Object.values(S.periodEntries).filter(e => e && e.periodFirstDay===firstDay).length;
  return { entries, rooster: p? periodShiftIds(p).length : 0 };
}

// Validates and stores one period. `editing` = the first day of the period being edited ('' = a new one).
// -> { ok, errors, overlap }: nothing is stored unless ok.
export async function savePeriodDoc(raw, editing){
  if(!db){ showToast(t('data.geen_verbinding_met_opslag')); return { ok:false, errors:[] }; }
  const others = periodList(S.periods).filter(p => p.firstDay!==editing);
  const res = validatePeriod(raw, others);
  if(!res.ok) return res;
  const v = res.value;
  if(editing && editing!==v.firstDay){
    const d = periodHasData(editing);
    if(d.entries || d.rooster) return { ...res, ok:false, errors:['period.err.firstDayLocked'] };
  }
  try{
    await db.doc("periods/"+v.firstDay).set({ ...v, deadlineAt:deadlineMs(v) });   // deadlineAt: firestore.rules stop parents after it
    S.periodsColl = {...S.periodsColl, [v.firstDay]:v};
    if(editing && editing!==v.firstDay){
      await db.doc("periods/"+editing).delete();
      const rest = {...S.periodsColl}; delete rest[editing]; S.periodsColl = rest;
    }
    // A period that only lived in the old settings/period document moves over as soon as it is saved.
    if(S.legacyPeriod && (S.legacyPeriod.firstDay===editing || S.legacyPeriod.firstDay===v.firstDay)){ try{ await db.doc("settings/period").delete(); S.legacyPeriod = null; }catch(e){} }
    rebuildPeriods();
    return res;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return { ...res, ok:false, errors:[] }; }
}

// Removes a period AND what was handed in for it, so nothing invisible stays behind. Refused while a temporary rooster exists
// (remove that first, in Rooster). -> true when removed.
export async function deletePeriodCompletely(firstDay){
  if(!db){ showToast(t('data.geen_verbinding_met_opslag')); return false; }
  if(!S.canEdit){ showToast(t('period.rooster.err.coordinator')); return false; }
  const p = S.periods[firstDay];
  if(!p){ showToast(t('period.entry.err.noPeriod')); return false; }
  if(periodShiftIds(p).length){ showToast(t('period.err.deleteRooster')); return false; }
  const entryIds = Object.entries(S.periodEntries).filter(([,e])=>e && e.periodFirstDay===firstDay).map(([id])=>id);
  const batch = db.batch();
  const backupIds = backupsFor(S.periodBackups, firstDay).map(b=>b.id);
  batch.delete('periods/'+firstDay);
  entryIds.forEach(id=>batch.delete('periodEntries/'+id));
  backupIds.forEach(id=>batch.delete('periodBackups/'+id));
  if(S.legacyPeriod && S.legacyPeriod.firstDay===firstDay) batch.delete('settings/period');
  try{
    await batch.commit();
    const coll = {...S.periodsColl}; delete coll[firstDay]; S.periodsColl = coll;
    if(S.legacyPeriod && S.legacyPeriod.firstDay===firstDay) S.legacyPeriod = null;
    const ent = {...S.periodEntries}; entryIds.forEach(id=>delete ent[id]); S.periodEntries = ent;
    const bk = {...S.periodBackups}; backupIds.forEach(id=>delete bk[id]); S.periodBackups = bk;
    rebuildPeriods();
    showToast(t('period.deleted'));
    return true;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

// ---------- Back-ups of a period (Beheer, coordinator) ----------
// A back-up holds the period, the handed-in times and the temporary rooster of ONE period (periodBackups/<firstDay>_<ms>), so the coordinator
// can test and try things and then put everything back. Restoring is ONE batch (all or nothing) and first stores the current state as the
// automatic back-up periodBackups/<firstDay>_auto, so a restore can itself be undone.
export function periodBackupList(firstDay){ return backupsFor(S.periodBackups, firstDay); }

export async function createPeriodBackup(firstDay){
  if(!periodRoosterGuard()) return false;
  const p = S.periods[firstDay];
  if(!p){ noPeriodToast(); return false; }
  if(countManual(S.periodBackups, firstDay) >= PERIOD_BACKUP_MAX){ showToast(t('period.backup.err.full',{p1:PERIOD_BACKUP_MAX})); return false; }
  const now = Date.now(), id = backupId(firstDay, now);
  const doc = buildPeriodBackup(p, S.periodEntries, S.periodCars, { now, by:myDisplayInfo().name });
  try{
    await db.doc("periodBackups/"+id).set(doc);
    S.periodBackups = {...S.periodBackups, [id]:doc};
    showToast(t('period.backup.made'));
    return true;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

export async function deletePeriodBackup(id){
  if(!periodRoosterGuard()) return false;
  if(!S.periodBackups[id]) return false;
  try{
    await db.doc("periodBackups/"+id).delete();
    const rest = {...S.periodBackups}; delete rest[id]; S.periodBackups = rest;
    showToast(t('period.backup.deleted'));
    return true;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

// Puts the period back exactly as the back-up has it. Handed-in times and shifts made since are removed. Nothing is written when anything fails.
export async function restorePeriodBackup(id){
  if(!periodRoosterGuard()) return false;
  const b = validBackup(S.periodBackups[id]);
  if(!b){ showToast(t('period.backup.err.broken')); return false; }
  const first = b.periodFirstDay;
  const others = periodList(S.periods).filter(p => p.firstDay!==first);
  const plan = planRestore(b, others, S.periodEntries, S.periodCars);
  if(!plan.ok){ showToast(t(plan.error,{p1:plan.overlap? plan.overlap.name : ''})); return false; }
  const current = S.periods[first];
  const safetyId = autoBackupId(first);
  const safety = current? buildPeriodBackup(current, S.periodEntries, S.periodCars, { now:Date.now(), by:myDisplayInfo().name, auto:true }) : null;
  const batch = db.batch();
  if(safety) batch.set('periodBackups/'+safetyId, safety);
  plan.sets.forEach(([path, data])=>batch.set(path, data));
  plan.deletes.forEach(path=>batch.delete(path));
  try{
    await batch.commit();
    const pick = all => Object.fromEntries(Object.entries(all).filter(([, d])=>!(d && d.periodFirstDay===first)));
    const entries = pick(S.periodEntries), cars = pick(S.periodCars);
    plan.sets.forEach(([path, data])=>{
      const [coll, docId] = path.split('/');
      if(coll==='periodEntries') entries[docId] = data;
      else if(coll==='periodCars') cars[docId] = data;
    });
    S.periodEntries = entries; S.periodCars = cars;
    S.periodsColl = {...S.periodsColl, [first]:b.period};
    if(safety) S.periodBackups = {...S.periodBackups, [safetyId]:safety};
    rebuildPeriods();
    showToast(t('period.backup.restored'));
    return true;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

// S.periods = the collection plus the period of the first version of the app (settings/period), see mergePeriods.
export function rebuildPeriods(){
  S.periods = mergePeriods(S.periodsColl, S.legacyPeriod);
}

// The coordinator's app moves the old single period (settings/period) into the periods collection, once. The other apps read both meanwhile.
let migratingLegacy = false;
export async function migrateLegacyPeriod(){
  const p = S.legacyPeriod;
  if(migratingLegacy || !p || !db || !isRealCoordinator()) return false;
  migratingLegacy = true;
  try{
    if(!S.periodsColl[p.firstDay]) await db.doc("periods/"+p.firstDay).set({ ...p, deadlineAt:deadlineMs(p) });
    await db.doc("settings/period").delete();
    return true;
  }catch(e){ return false; }
  finally{ migratingLegacy = false; }
}

// Remembers when this (linked) browser last opened the app, for the coordinator's Beheer. At most once per
// 15 minutes per page load; never when the coordinator is only looking as another family. Best-effort.
let lastSessionWrite = 0;
export async function recordSession(now=Date.now()){
  if(!db || !S.me || S.impersonateFamilyId) return;
  const familyId = S.links[S.me] && S.links[S.me].familyId;
  if(!familyId || now-lastSessionWrite < 15*60*1000) return;
  lastSessionWrite = now;
  try{ await db.doc("sessions/"+S.me).set({familyId, at:now}); }catch(e){ lastSessionWrite = 0; }
}
export function resetSessionThrottle(){ lastSessionWrite = 0; }

export async function recordLastUpdate(kind){
  if(!db) return;
  try{
    const info=myDisplayInfo();
    // Name only — phone numbers are not shown to every parent.
    await db.doc("settings/lastUpdate"+kind).set({by:info.name, at:Date.now()});
  }catch(e){ /* best-effort only — never block the real action on this */ }
}

export function syncListeners(){
  if(!db || !S.me) return;
  const member = isMemberNow();
  if(member && !S.dataUnsubs.length) startDataListeners();
  if(!member && S.dataUnsubs.length) stopDataListeners();
  // Ritbeurs notifications: only the own family's inbox is listened to (families/<id>/notifications).
  const nf = member? (myLinkedFamilyId() || null) : null;
  if(S.notificationsFor !== nf){
    if(S.notificationsUnsub){ S.notificationsUnsub(); S.notificationsUnsub=null; }
    S.notifications = {}; S.notificationsFor = nf;
    if(nf){
      S.notificationsUnsub = db.collection("families/"+nf+"/notifications").onSnapshot(snap=>{
        S.notifications={}; snap.docs.forEach(d=>S.notifications[d.id]=d.data());
        renderDeviationTab();
      }, err=>{});
    }
  }
  const coord = isRealCoordinator();
  if(coord && !S.linksCollUnsub){
    S.linksCollUnsub = db.collection("links").onSnapshot(snap=>{
      const next={}; snap.docs.forEach(d=>next[d.id]=d.data());
      S.links = next;
      renderBeheer();
    }, err=>{});
  }
  if(coord && !S.sessionsUnsub){
    S.sessionsUnsub = db.collection("sessions").onSnapshot(snap=>{
      const next={}; snap.docs.forEach(d=>{ const {familyId,at}=d.data(); if(familyId && at>(next[familyId]||0)) next[familyId]=at; });
      S.lastSeenByFamily = next;
      renderBeheer();
    }, err=>{});
  }
  if(coord && !S.invitesUnsub){
    S.invitesUnsub = db.collection("invites").onSnapshot(snap=>{
      S.invitesByCode={}; S.inviteByFamily={};
      snap.docs.forEach(d=>{ const fid=d.data().familyId; if(fid){ S.invitesByCode[d.id]=fid; S.inviteByFamily[fid]=d.id; } });
      renderBeheer();
    }, err=>{});
  }
  if(coord && !S.periodBackupsUnsub){
    S.periodBackupsUnsub = db.collection("periodBackups").onSnapshot(snap=>{
      S.periodBackups={}; snap.docs.forEach(d=>S.periodBackups[d.id]=d.data());
      renderBeheer();
    }, err=>{});
  }
  if(coord && !S.rideLogUnsub){
    S.rideLogUnsub = db.collection("rideLog").onSnapshot(snap=>{
      S.rideLog={}; snap.docs.forEach(d=>S.rideLog[d.id]=d.data());
      const first = !S.rideLogLoaded; S.rideLogLoaded = true;
      if(first) logPassedShifts();
      renderBeheer();
    }, err=>{});
  }
  if(!coord){
    if(S.rideLogUnsub){ S.rideLogUnsub(); S.rideLogUnsub=null; S.rideLog={}; S.rideLogLoaded=false; }
    if(S.periodBackupsUnsub){ S.periodBackupsUnsub(); S.periodBackupsUnsub=null; S.periodBackups={}; }
    if(S.linksCollUnsub){ S.linksCollUnsub(); S.linksCollUnsub=null; const mine=S.links[S.me]; S.links={}; if(mine) S.links[S.me]=mine; }
    if(S.sessionsUnsub){ S.sessionsUnsub(); S.sessionsUnsub=null; S.lastSeenByFamily={}; }
    if(S.invitesUnsub){ S.invitesUnsub(); S.invitesUnsub=null; S.invitesByCode={}; S.inviteByFamily={}; }
  }
}

export function startDataListeners(){
  db.setListenerSink(S.dataUnsubs);
  try{
    db.collection("families").onSnapshot(snap=>{
        S.families={}; S.serverSchedules={};
        snap.docs.forEach(d=>{ S.families[d.id]=d.data(); S.serverSchedules[d.id]=JSON.parse(JSON.stringify(d.data().schedule||{})); });
        notifyCoordinatorOfNewTimeChanges();
        if(isRealCoordinator()) migrateLegacyFamilySecrets();
        renderAll(); },
      err=>{ setStatus(t('data.fout_bij_laden_gezinnen')+(err&&err.message||err), true); });
    db.collection("groups").onSnapshot(snap=>{ S.groups={}; snap.docs.forEach(d=>S.groups[d.id]=d.data()); renderSchedule(); renderMyWeek(); },
      err=>{ setStatus(t('data.fout_bij_laden_rooster')+(err&&err.message||err), true); });
    db.doc("settings/planning").onSnapshot(snap=>{ if(snap.exists) S.settings={...S.settings, ...snap.data()}; renderBeheer(); renderSchedule(); },
      err=>{ setStatus(t('data.fout_bij_laden_instellingen')+(err&&err.message||err), true); });
    db.doc("settings/dayCoordinators").onSnapshot(snap=>{ S.dayCoordinators = snap.exists? (snap.data()||{}) : {}; renderBeheer(); renderSchedule(); renderMyWeek(); renderDeviationTab(); },
      err=>{ setStatus(t('data.fout_bij_laden_instellingen')+(err&&err.message||err), true); });
    db.doc("settings/notice").onSnapshot(snap=>{ S.notice = snap.exists? normalizeNotice(snap.data()) : null; renderNoticeBanner(); renderBeheer(); },
      err=>{ setStatus(t('data.fout_bij_laden_instellingen')+(err&&err.message||err), true); });
    db.doc("settings/maintenance").onSnapshot(snap=>{ S.maintenance = snap.exists? normalizeMaintenance(snap.data()) : null; renderMaintenance(); renderBeheer(); },
      err=>{ setStatus(t('data.fout_bij_laden_instellingen')+(err&&err.message||err), true); });
    // Ritbeurs: the feature switch, the rides on offer and the "Ik kan inspringen" moments. Everyone reads them; the switch decides what is shown.
    db.doc("settings/ritbeurs").onSnapshot(snap=>{ S.ritbeurs = snap.exists? normalizeRitbeurs(snap.data()) : null; renderDeviationTab(); renderBeheer(); checkRitbeurs(); },
      err=>{ setStatus(t('data.fout_bij_laden_instellingen')+(err&&err.message||err), true); });
    db.collection("offers").onSnapshot(snap=>{ S.offers={}; snap.docs.forEach(d=>S.offers[d.id]=d.data()); renderDeviationTab(); checkRitbeurs(); },
      err=>{});
    db.collection("backupMoments").onSnapshot(snap=>{ S.moments={}; snap.docs.forEach(d=>S.moments[d.id]=d.data()); renderDeviationTab(); },
      err=>{});
    db.collection("periods").onSnapshot(snap=>{
      S.periodsColl={}; snap.docs.forEach(d=>{ const p = storedPeriod(d.data()); if(p && p.firstDay===d.id) S.periodsColl[d.id]=p; });
      rebuildPeriods(); renderBeheer(); renderDeviationTab(); renderSchedule(); renderMyWeek();
    }, err=>{ setStatus(t('data.fout_bij_laden_instellingen')+(err&&err.message||err), true); });
    // The first version stored ONE period in settings/period: still read, and moved into periods/ by the coordinator's app.
    db.doc("settings/period").onSnapshot(snap=>{
      S.legacyPeriod = snap.exists? storedPeriod(snap.data()) : null;
      rebuildPeriods(); migrateLegacyPeriod(); renderBeheer(); renderDeviationTab(); renderSchedule(); renderMyWeek();
    }, err=>{});
    db.collection("periodEntries").onSnapshot(snap=>{ S.periodEntries={}; snap.docs.forEach(d=>S.periodEntries[d.id]=d.data()); S.periodEntriesLoaded=true; renderDeviationTab(); renderBeheer(); },
      err=>{ setStatus(t('data.fout_bij_laden_instellingen')+(err&&err.message||err), true); });
    db.collection("periodCars").onSnapshot(snap=>{ S.periodCars={}; snap.docs.forEach(d=>S.periodCars[d.id]=d.data()); renderSchedule(); renderMyWeek(); renderDeviationTab(); },
      err=>{ setStatus(t('data.fout_bij_laden_instellingen')+(err&&err.message||err), true); });
    db.doc("settings/prefs").onSnapshot(snap=>{ S.prefs = snap.exists? (snap.data()||{rules:[]}) : {rules:[]}; if(!S.prefs.rules) S.prefs.rules=[]; renderBeheer(); renderSchedule(); },
      err=>{ setStatus(t('data.fout_bij_laden_voorkeuren')+(err&&err.message||err), true); });
    db.doc("settings/priority").onSnapshot(snap=>{ S.shiftPriority = snap.exists? (snap.data()||{}) : {}; renderBeheer(); renderSchedule(); },
      err=>{ setStatus(t('data.fout_bij_laden_prioriteit')+(err&&err.message||err), true); });
    db.collection("deviations").onSnapshot(snap=>{
      S.deviations={}; snap.docs.forEach(d=>S.deviations[d.id]=d.data());
      S.deviationsLoaded = true;
      purgeStaleDeviations();
      renderSchedule(); renderMyWeek(); renderDeviationTab();
    }, err=>{ setStatus(t('data.fout_bij_laden_wijzigingen')+(err&&err.message||err), true); });
    db.collection("matchCarpools").onSnapshot(snap=>{
      S.matchCarpools={}; snap.docs.forEach(d=>S.matchCarpools[d.id]=d.data());
      purgeStaleMatchCarpools();
      renderMatchesTab(); renderMyWeek();
    }, err=>{});
    db.doc("settings/lastUpdateRooster").onSnapshot(snap=>{ S.lastUpdateRooster = snap.exists? snap.data() : null; renderSchedule(); renderMyWeek(); },
      err=>{});
    db.doc("settings/lastUpdateDeviation").onSnapshot(snap=>{ S.lastUpdateDeviation = snap.exists? snap.data() : null; renderDeviationTab(); renderMyWeek(); },
      err=>{});
    db.doc("settings/matchFeeds").onSnapshot(snap=>{
      S.matchFeeds = (snap.exists && snap.data().feeds) || [];
      S.matchFeedsLoaded = true;
      refreshMatchesIfStale();   // first member of the day fetches; also when the calendars in Beheer changed
      renderBeheer(); renderMyWeek(); renderDeviationTab();
    }, err=>{});
    db.doc("settings/locations").onSnapshot(snap=>{ S.locationsDoc = snap.exists? snap.data() : null; renderBeheer(); renderSchedule(); renderMyWeek(); renderDeviationTab(); },
      err=>{});
    db.doc("settings/matchDistances").onSnapshot(snap=>{ S.matchDistances = snap.exists? (snap.data()||{}) : {}; S.matchDistancesLoaded = true; renderMyWeek(); renderMatchesTab(); calculateMatchDistances(currentMatchList()); },
      err=>{});
    db.doc("settings/matchCache").onSnapshot(snap=>{
      if(snap.exists){
        const d=snap.data();
        // Only entries with a calendar ID: older cache entries carried a possibly wrong team name.
        S.cachedMatches = (d.matches||[]).filter(e=>e.calendarId).map(e=>({calendarId:e.calendarId, eventId:e.eventId||'', teamLabel:e.teamLabel, summary:e.summary, location:e.location, start:new Date(e.startMs)}));
        S.cachedMatchesAt = d.fetchedAt||null;
        S.cachedMatchesFeedsSig = d.feedsSig||null;
        S.cachedMatchesPartial = !!d.partial;
      }
      S.matchCacheLoaded = true;
      renderMyWeek(); renderMatchesTab();
      refreshMatchesIfStale();
    }, err=>{ S.matchCacheLoaded = true; refreshMatchesIfStale(); });
    // API keys that must not sit in the public GitHub folder. Members only (Firestore rules); only the coordinator can change it.
    db.doc("settings/apiKeys").onSnapshot(snap=>{
      S.orsApiKey = snap.exists? String((snap.data()||{}).ors||'').trim() : '';
      renderBeheer(); renderMyWeek(); renderMatchesTab();
      calculateMatchDistances(currentMatchList());
    }, err=>{});
  }catch(e){ setStatus(t('app.kon_niet_live_verbinden')+(e&&e.message||e), true); }
  finally{ db.setListenerSink(null); }
}

export function stopDataListeners(){
  S.dataUnsubs.forEach(u=>{ try{ u(); }catch(e){} });
  S.dataUnsubs = [];
  S.families={}; S.serverSchedules={}; S.groups={}; S.deviations={}; S.matchCarpools={}; S.dayCoordinators={}; S.notice=null; S.noticeDraft=null; S.maintenance=null; S.maintenanceDraft=null; S.ritbeurs=null; S.offers={}; S.moments={}; S.rbConfirm=null; S.rbOffering=null; S.rbMomentDraft=null; S.periods={}; S.periodsColl={}; S.legacyPeriod=null; S.periodDraft=null; S.periodSel=null; S.periodEntries={}; S.periodEntriesLoaded=false; S.periodForm=null; S.periodView=null; S.periodCars={}; S.periodDay=null; S.locationsDoc=null; S.matchDistances={}; S.matchDistancesLoaded=false; S.matchCacheLoaded=false; S.orsApiKey='';
  S.lastPendingChangeCount = null;
  renderNoticeBanner();
  renderMaintenance();
  updateStatusLine();
}

export async function migrateLegacyFamilySecrets(){
  if(S.migratingSecrets || S.migrationFailed || !db) return;
  const todo = Object.entries(S.families).filter(([id,f])=> f && (('inviteCode' in f) || (!Array.isArray(f.phoneKeys) && (f.parentPhone1||f.parentPhone2))));
  if(!todo.length) return;
  S.migratingSecrets=true;
  try{
    const batch=db.batch();
    for(const [id,f] of todo){
      const upd={ phoneKeys:[f.parentPhone1,f.parentPhone2].map(normalizePhone).filter(Boolean) };
      if('inviteCode' in f){
        const code=String(f.inviteCode||'').trim();
        if(isValidInviteCode(code)) batch.set('invites/'+code, {familyId:id});
        upd.inviteCode = db.deleteField();
      }
      batch.update('families/'+id, upd);
    }
    await batch.commit();
    showToast(t('data.uitnodigingscodes_beveiligd'));
  }catch(e){
    S.migrationFailed=true;
    showToast(t('data.migratie_uitnodigingscodes_mislukt')+(e&&e.message||e));
  }finally{ S.migratingSecrets=false; }
}

// Strip baseGroupId (an internal marker effectiveCars() adds when falling back to the default
// schedule — it was never meant to be persisted into a deviation document) and any literal
// `undefined` field, which Firestore's SDK rejects outright with a thrown error.
export function cleanCars(cars){
  return cars.map(c=>{
    const {baseGroupId, ...rest} = c;
    Object.keys(rest).forEach(k=>{ if(rest[k]===undefined) delete rest[k]; });
    return rest;
  });
}

// This week's stored deviation of one shift (null when it belongs to another week).
export function currentDeviationDoc(day,direction){
  const dev = S.deviations[deviationKey(day,direction)];
  return dev && dev.weekKey===S.currentWeekKey ? dev : null;
}

async function writeDeviation(day,direction,cars,extra){
  refreshWeekKey();
  await db.doc("deviations/"+deviationKey(day,direction)).set({day,direction,weekKey:S.currentWeekKey,expiresAt:deviationExpiryMs(),cars:cleanCars(cars),...(extra||{})});
  S.lastDeviationEditDay = day;
  recordLastUpdate('Deviation');
}

// opts.skipGate: the impact preview (US-07) already looked at this change and the user confirmed it.
export async function saveDeviationCars(day,direction,cars,opts){
  if(!db){showToast(t('data.geen_verbinding_met_opslag'));return false;}
  if(!(opts&&opts.skipGate) && await impactGate(day,direction,cars, ()=>saveDeviationCars(day,direction,cars,{skipGate:true}), renderDeviationTab)) return false;
  try{
    refreshWeekKey();
    // "Rijdt niet mee" marks (US-06, both directions) live on the deviation and survive other edits, unless the girl is in a car again.
    const extra = keepOv(currentDeviationDoc(day,direction), cars);
    await writeDeviation(day,direction,cars,extra);
    return true;
  }catch(e){ showToast(t('data.opslaan_mislukt')+(e&&e.message||e)); return false; }
}

// US-06: a parent marks (or unmarks) that a daughter does not ride along on one shift (heen or terug).
// She leaves her car (departure time recalculated) and drops out of the planning for that ride.
export async function setReturnByPublicTransport(day,girlId,on,direction='terug'){
  if(!db){showToast(t('data.geen_verbinding_met_opslag'));return false;}
  try{
    refreshWeekKey();
    const cur = currentDeviationDoc(day,direction);
    const r = applyOv({cars:effectiveCars(day,direction), ovGirlIds:ovIds(cur), ovFrom:(cur&&cur.ovFrom)||{}}, girlId, on, ids=>computeRideDeparture(day,direction,ids));
    const extra = r.ovGirlIds.length? {ovGirlIds:r.ovGirlIds, ovFrom:r.ovFrom} : {};
    await writeDeviation(day,direction,r.cars,extra);
    return true;
  }catch(e){ showToast(t('data.opslaan_mislukt')+(e&&e.message||e)); return false; }
}

export async function doToggleCoord(id,isCurrently){
  try{
    if(isCurrently){
      const cfg={uid:S.me, claimedAt:Date.now()};
      await db.doc("config/coordinator").set(cfg);
      S.coordinatorConfig=cfg; S.coordinatorExists=true;
    } else {
      const cfg={familyId:id};
      await db.doc("config/coordinator").set(cfg);
      S.coordinatorConfig=cfg; S.coordinatorExists=true;
    }
    recomputeCanEdit();
    const navB=document.getElementById('navBeheer'); if(navB) navB.style.display=S.canEdit?'':'none';
    showToast(isCurrently? t('data.coordinator_rol_nu_alleen_via') : t('data.coordinator_ingesteld'));
    renderAll();
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
}

export async function saveCoordFamily(){
  if(!db){showToast(t('data.geen_verbinding_met_opslag'));return;}
  const data = readFamilyForm('coord');
  const codeEl=document.getElementById('coord_inviteCode');
  const newCode = codeEl? codeEl.value.trim() : '';
  if(S.coordEditId==null){
    const slug = (data.girlName||data.parentName||'gezin').toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,30) || 'gezin';
    S.coordEditId = 'manual-'+slug+'-'+Date.now().toString(36);
    const dupName=(data.girlName||'').trim().toLowerCase();
    const dup = dupName && Object.entries(S.families).some(([fid,fd])=> fid!==S.coordEditId && (fd.girlName||'').trim().toLowerCase()===dupName);
    if(dup) showToast(t('data.let_op_er_bestaat_al')+data.girlName+t('data.controleer_op_dubbelen'));
  }
  try{
    await db.doc("families/"+S.coordEditId).set(data,{merge:true});
    if(await saveInviteCode(S.coordEditId, newCode)) showToast(t('data.opgeslagen'));
  }
  catch(e){showToast(t('data.opslaan_mislukt')+(e&&e.message||e));}
}

// Back-up restore (Beheer → Back-up gezinnen): writes the planned families (family-backup.js planRestore) in ONE batch, so a restore is
// all-or-nothing. Fields that are not in the back-up (timeChanges, invite codes, links) stay untouched (merge). Returns true when stored.
export async function restoreFamilies(plan){
  if(!db){ showToast(t('data.geen_verbinding_met_opslag')); return false; }
  if(!S.canEdit){ showToast(t('backup.err.coordinator_only')); return false; }
  if(!plan || !plan.ok || !plan.items.length){ showToast(t('backup.err.nothing')); return false; }
  try{
    const batch = db.batch();
    plan.items.forEach(i=>batch.set('families/'+i.id, i.data, {merge:true}));
    if(plan.coordinatorFamilyId) batch.set('config/coordinator', {familyId:plan.coordinatorFamilyId});
    await batch.commit();
    if(plan.coordinatorFamilyId){
      S.coordinatorConfig = {familyId:plan.coordinatorFamilyId}; S.coordinatorExists = true;
      recomputeCanEdit();
    }
    showToast(t('backup.restored',{p1:plan.items.length}));
    return true;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

// Invite codes live in /invites/{code} (doc id = the code), not on the family doc, so linked
// parents can't read other families' codes. Returns false (with a toast) when refused.
export async function saveInviteCode(familyId, code){
  if(code===(S.inviteByFamily[familyId]||'')) return true;
  if(code && !isValidInviteCode(code)){ showToast(t('data.code_alleen_letters_cijfers_en')); return false; }
  if(code){
    const existing = await db.doc("invites/"+code).get();
    if(existing.exists && existing.data().familyId!==familyId){ showToast(t('data.deze_code_is_al_in')); return false; }
  }
  const batch = db.batch();
  if(code) batch.set('invites/'+code, {familyId});
  Object.entries(S.invitesByCode).forEach(([c,fid])=>{ if(fid===familyId && c!==code) batch.delete('invites/'+c); });
  await batch.commit();
  return true;
}

export async function markTimeChangesSeen(familyIds){
  if(!db) return;
  try{
    await Promise.all(familyIds.map(id=>db.doc("families/"+id).set({timeChanges:[]},{merge:true})));
    showToast(t('data.gemarkeerd_als_gezien'));
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
}

export async function createGroupWithDriver(day,direction,girlIds,driverId,extraExclude=[]){
  if(!db){showToast(t('data.geen_verbinding_met_opslag'));return;}
  const alreadyDriving = groupsFor(day,direction).map(([gid,g])=>g.driverFamilyId).filter(Boolean);
  const exclude = new Set([driverId, ...alreadyDriving, ...extraExclude]);
  const reserveIds = eligibleDrivers(day,direction,girlIds.length).map(([id])=>id).filter(id=>!exclude.has(id));
  const gid=`${day}_${direction}_${Date.now()}_${Math.random().toString(36).slice(2,6)}`;
  const departureTime=computeDepartureTime(day,direction,girlIds);
  try{ await db.doc("groups/"+gid).set({day,direction,girlIds,driverFamilyId:driverId||null,reserveFamilyIds:reserveIds,departureTime}); recordLastUpdate('Rooster'); }
  catch(e){showToast(t('data.kon_groep_niet_opslaan_alleen')+(e&&e.message||e));}
}

export async function useOption(day,direction,assignment){
  const usedDrivers = assignment.map(a=>a.driverId).filter(Boolean);
  for(const a of assignment){ await createGroupWithDriver(day,direction,a.girlIds,a.driverId, usedDrivers.filter(id=>id!==a.driverId)); }
}

export async function createGroupCustom(day,direction,ids){
  if(!ids.length){showToast(t('data.selecteer_minstens_1_dochter'));return;}
  const eligible=eligibleDrivers(day,direction,ids.length);
  await createGroupWithDriver(day,direction,ids, eligible[0]?eligible[0][0]:null);
}
