// data.js — generated by the modularisation of index.html; see README for what lives where.
import { t } from './i18n.js';
import { S } from './state.js';
import { deviationExpiryMs, deviationKey, refreshWeekKey } from './dates.js';
import { isMemberNow, isRealCoordinator, isValidInviteCode, myDisplayInfo, normalizePhone, recomputeCanEdit } from './coordinator.js';
import { notifyCoordinatorOfNewTimeChanges, renderBeheer } from './ui-beheer.js';
import { renderAll } from './app.js';
import { setStatus, showToast, updateStatusLine } from './ui-common.js';
import { renderSchedule } from './ui-schedule.js';
import { renderMyWeek } from './ui-myweek.js';
import { renderDeviationTab } from './ui-deviation.js';
import { renderMatchesTab } from './ui-matches.js';
import { calculateMatchDistances, currentMatchList, refreshMatchesIfStale } from './matches.js';
import { readFamilyForm } from './ui-profile.js';
import { computeDepartureTime, effectiveCars, eligibleDrivers, groupsFor } from './rides.js';
import { applyOv, keepOv, ovIds } from './ov.js';
import { impactGate } from './impact.js';
import { storedPeriod } from './period.js';

// ============================================================
// Firestore access. The app talks to `db` only; `db` delegates to whichever adapter
// initDb() was given: the real Firestore adapter in production (see index.html),
// or an in-memory fake in the tests (fake-db.js).
//   db.doc(path)            -> { get, set, update, delete, onSnapshot }
//   db.collection(path)     -> { get, onSnapshot, doc }
//   db.batch()              -> { set(path,data,opts), update(path,data), delete(path), commit() }
//   db.deleteField(), db.signIn(), db.calendarApiKey, db.setListenerSink(array|null)
// The OpenRouteService key is NOT here: it lives in the database (settings/apiKeys, members only) -> S.orsApiKey.
// ============================================================
export function createFirestoreDb({ sdk, firestoreDb, auth, calendarApiKey }){
  const { collection, doc, getDoc, getDocs, setDoc, updateDoc, deleteDoc, onSnapshot, writeBatch, deleteField, signInAnonymously } = sdk;
  function wrapDocSnap(s){ return { id:s.id, exists:s.exists(), data:()=>s.data(), pending:!!(s.metadata&&s.metadata.hasPendingWrites) }; }
  // While startDataListeners() runs, every onSnapshot() made through this adapter drops its
  // unsubscribe function in here, so all member-only listeners can be stopped together.
  let listenerSink = null;
  function track(unsub){ if(listenerSink) listenerSink.push(unsub); return unsub; }
  function wrapQuerySnap(s){ return { docs: s.docs.map(wrapDocSnap) }; }
  function docRef(path){
    const ref = doc(firestoreDb, ...path.split('/'));
    return {
      get: ()=>getDoc(ref).then(wrapDocSnap),
      set: (data,opts)=>setDoc(ref, data, opts),
      update: (data)=>updateDoc(ref, data),
      delete: ()=>deleteDoc(ref),
      onSnapshot: (onNext,onErr)=>track(onSnapshot(ref, s=>onNext(wrapDocSnap(s)), onErr))
    };
  }
  function collRef(path){
    const ref = collection(firestoreDb, path);
    return {
      get: ()=>getDocs(ref).then(wrapQuerySnap),
      onSnapshot: (onNext,onErr)=>track(onSnapshot(ref, s=>onNext(wrapQuerySnap(s)), onErr)),
      doc: (id)=>docRef(path+'/'+id)
    };
  }
  return {
    doc: docRef, collection: collRef,
    batch: ()=>{ const b=writeBatch(firestoreDb); const r=p=>doc(firestoreDb, ...p.split('/'));
      return { set:(p,d,o)=>b.set(r(p),d,o), update:(p,d)=>b.update(r(p),d), delete:(p)=>b.delete(r(p)), commit:()=>b.commit() }; },
    deleteField: ()=>deleteField(),
    signIn: ()=>signInAnonymously(auth),
    calendarApiKey,
    setListenerSink: (a)=>{ listenerSink = a; }
  };
}
let dbImpl = null;
export function initDb(impl){ dbImpl = impl; }
export const db = {
  doc: (p)=>dbImpl.doc(p),
  collection: (p)=>dbImpl.collection(p),
  batch: ()=>dbImpl.batch(),
  deleteField: ()=>dbImpl.deleteField(),
  signIn: ()=>dbImpl.signIn(),
  get calendarApiKey(){ return dbImpl.calendarApiKey; },
  setListenerSink: (a)=>dbImpl.setListenerSink(a)
};
// ============================================================



export async function purgeStaleMatchCarpools(){
  const cutoff = Date.now() - 24*60*60*1000; // 1 day grace period after the match
  for(const [slug,d] of Object.entries(S.matchCarpools)){
    if((d.startMs||0) < cutoff){ try{ await db.doc("matchCarpools/"+slug).delete(); }catch(e){} }
  }
}

export async function purgeStaleDeviations(){
  refreshWeekKey();
  const now = Date.now();
  for(const [key,dev] of Object.entries(S.deviations)){
    // Only ever purge an OLDER week (ISO keys like "2026-W39" sort correctly as strings) and
    // only once its own expiry has passed — never a newer week's deviation.
    const olderWeek = !dev.weekKey || dev.weekKey < S.currentWeekKey;
    const expired = typeof dev.expiresAt!=='number' || dev.expiresAt <= now;
    if(olderWeek && expired){
      try{ await db.doc("deviations/"+key).delete(); }catch(e){}
    }
  }
}

export async function recordLastUpdate(kind){
  if(!db) return;
  try{
    const info=myDisplayInfo();
    // Name only — phone numbers are not shown to every parent.
    await db.doc("settings/lastUpdate"+kind).set({by:info.name, at:Date.now()});
  }catch(e){ /* best-effort only — never block the real action on this */ }
}

export function syncListeners(){
  if(!db || !S.me) return;
  const member = isMemberNow();
  if(member && !S.dataUnsubs.length) startDataListeners();
  if(!member && S.dataUnsubs.length) stopDataListeners();
  const coord = isRealCoordinator();
  if(coord && !S.linksCollUnsub){
    S.linksCollUnsub = db.collection("links").onSnapshot(snap=>{
      const next={}; snap.docs.forEach(d=>next[d.id]=d.data());
      S.links = next;
      renderBeheer();
    }, err=>{});
  }
  if(coord && !S.invitesUnsub){
    S.invitesUnsub = db.collection("invites").onSnapshot(snap=>{
      S.invitesByCode={}; S.inviteByFamily={};
      snap.docs.forEach(d=>{ const fid=d.data().familyId; if(fid){ S.invitesByCode[d.id]=fid; S.inviteByFamily[fid]=d.id; } });
      renderBeheer();
    }, err=>{});
  }
  if(!coord){
    if(S.linksCollUnsub){ S.linksCollUnsub(); S.linksCollUnsub=null; const mine=S.links[S.me]; S.links={}; if(mine) S.links[S.me]=mine; }
    if(S.invitesUnsub){ S.invitesUnsub(); S.invitesUnsub=null; S.invitesByCode={}; S.inviteByFamily={}; }
  }
}

export function startDataListeners(){
  db.setListenerSink(S.dataUnsubs);
  try{
    db.collection("families").onSnapshot(snap=>{
        S.families={}; S.serverSchedules={};
        snap.docs.forEach(d=>{ S.families[d.id]=d.data(); S.serverSchedules[d.id]=JSON.parse(JSON.stringify(d.data().schedule||{})); });
        notifyCoordinatorOfNewTimeChanges();
        if(isRealCoordinator()) migrateLegacyFamilySecrets();
        renderAll(); },
      err=>{ setStatus(t('data.fout_bij_laden_gezinnen')+(err&&err.message||err), true); });
    db.collection("groups").onSnapshot(snap=>{ S.groups={}; snap.docs.forEach(d=>S.groups[d.id]=d.data()); renderSchedule(); renderMyWeek(); },
      err=>{ setStatus(t('data.fout_bij_laden_rooster')+(err&&err.message||err), true); });
    db.doc("settings/planning").onSnapshot(snap=>{ if(snap.exists) S.settings={...S.settings, ...snap.data()}; renderBeheer(); renderSchedule(); },
      err=>{ setStatus(t('data.fout_bij_laden_instellingen')+(err&&err.message||err), true); });
    db.doc("settings/dayCoordinators").onSnapshot(snap=>{ S.dayCoordinators = snap.exists? (snap.data()||{}) : {}; renderBeheer(); renderSchedule(); renderMyWeek(); renderDeviationTab(); },
      err=>{ setStatus(t('data.fout_bij_laden_instellingen')+(err&&err.message||err), true); });
    db.doc("settings/period").onSnapshot(snap=>{ S.period = snap.exists? storedPeriod(snap.data()) : null; renderBeheer(); },
      err=>{ setStatus(t('data.fout_bij_laden_instellingen')+(err&&err.message||err), true); });
    db.doc("settings/prefs").onSnapshot(snap=>{ S.prefs = snap.exists? (snap.data()||{rules:[]}) : {rules:[]}; if(!S.prefs.rules) S.prefs.rules=[]; renderBeheer(); renderSchedule(); },
      err=>{ setStatus(t('data.fout_bij_laden_voorkeuren')+(err&&err.message||err), true); });
    db.doc("settings/priority").onSnapshot(snap=>{ S.shiftPriority = snap.exists? (snap.data()||{}) : {}; renderBeheer(); renderSchedule(); },
      err=>{ setStatus(t('data.fout_bij_laden_prioriteit')+(err&&err.message||err), true); });
    db.collection("deviations").onSnapshot(snap=>{
      S.deviations={}; snap.docs.forEach(d=>S.deviations[d.id]=d.data());
      purgeStaleDeviations();
      renderSchedule(); renderMyWeek(); renderDeviationTab();
    }, err=>{ setStatus(t('data.fout_bij_laden_wijzigingen')+(err&&err.message||err), true); });
    db.collection("matchCarpools").onSnapshot(snap=>{
      S.matchCarpools={}; snap.docs.forEach(d=>S.matchCarpools[d.id]=d.data());
      purgeStaleMatchCarpools();
      renderMatchesTab(); renderMyWeek();
    }, err=>{});
    db.doc("settings/lastUpdateRooster").onSnapshot(snap=>{ S.lastUpdateRooster = snap.exists? snap.data() : null; renderSchedule(); renderMyWeek(); },
      err=>{});
    db.doc("settings/lastUpdateDeviation").onSnapshot(snap=>{ S.lastUpdateDeviation = snap.exists? snap.data() : null; renderDeviationTab(); renderMyWeek(); },
      err=>{});
    db.doc("settings/matchFeeds").onSnapshot(snap=>{
      S.matchFeeds = (snap.exists && snap.data().feeds) || [];
      S.matchFeedsLoaded = true;
      refreshMatchesIfStale();   // first member of the day fetches; also when the calendars in Beheer changed
      renderBeheer(); renderMyWeek(); renderDeviationTab();
    }, err=>{});
    db.doc("settings/locations").onSnapshot(snap=>{ S.locationsDoc = snap.exists? snap.data() : null; renderBeheer(); renderSchedule(); renderMyWeek(); renderDeviationTab(); },
      err=>{});
    db.doc("settings/matchDistances").onSnapshot(snap=>{ S.matchDistances = snap.exists? (snap.data()||{}) : {}; S.matchDistancesLoaded = true; renderMyWeek(); renderMatchesTab(); calculateMatchDistances(currentMatchList()); },
      err=>{});
    db.doc("settings/matchCache").onSnapshot(snap=>{
      if(snap.exists){
        const d=snap.data();
        // Only entries with a calendar ID: older cache entries carried a possibly wrong team name.
        S.cachedMatches = (d.matches||[]).filter(e=>e.calendarId).map(e=>({calendarId:e.calendarId, eventId:e.eventId||'', teamLabel:e.teamLabel, summary:e.summary, location:e.location, start:new Date(e.startMs)}));
        S.cachedMatchesAt = d.fetchedAt||null;
        S.cachedMatchesFeedsSig = d.feedsSig||null;
        S.cachedMatchesPartial = !!d.partial;
      }
      S.matchCacheLoaded = true;
      renderMyWeek(); renderMatchesTab();
      refreshMatchesIfStale();
    }, err=>{ S.matchCacheLoaded = true; refreshMatchesIfStale(); });
    // API keys that must not sit in the public GitHub folder. Members only (Firestore rules); only the coordinator can change it.
    db.doc("settings/apiKeys").onSnapshot(snap=>{
      S.orsApiKey = snap.exists? String((snap.data()||{}).ors||'').trim() : '';
      renderBeheer(); renderMyWeek(); renderMatchesTab();
      calculateMatchDistances(currentMatchList());
    }, err=>{});
  }catch(e){ setStatus(t('app.kon_niet_live_verbinden')+(e&&e.message||e), true); }
  finally{ db.setListenerSink(null); }
}

export function stopDataListeners(){
  S.dataUnsubs.forEach(u=>{ try{ u(); }catch(e){} });
  S.dataUnsubs = [];
  S.families={}; S.serverSchedules={}; S.groups={}; S.deviations={}; S.matchCarpools={}; S.dayCoordinators={}; S.period=null; S.periodDraft=null; S.locationsDoc=null; S.matchDistances={}; S.matchDistancesLoaded=false; S.matchCacheLoaded=false; S.orsApiKey='';
  S.lastPendingChangeCount = null;
  updateStatusLine();
}

export async function migrateLegacyFamilySecrets(){
  if(S.migratingSecrets || S.migrationFailed || !db) return;
  const todo = Object.entries(S.families).filter(([id,f])=> f && (('inviteCode' in f) || (!Array.isArray(f.phoneKeys) && (f.parentPhone1||f.parentPhone2))));
  if(!todo.length) return;
  S.migratingSecrets=true;
  try{
    const batch=db.batch();
    for(const [id,f] of todo){
      const upd={ phoneKeys:[f.parentPhone1,f.parentPhone2].map(normalizePhone).filter(Boolean) };
      if('inviteCode' in f){
        const code=String(f.inviteCode||'').trim();
        if(isValidInviteCode(code)) batch.set('invites/'+code, {familyId:id});
        upd.inviteCode = db.deleteField();
      }
      batch.update('families/'+id, upd);
    }
    await batch.commit();
    showToast(t('data.uitnodigingscodes_beveiligd'));
  }catch(e){
    S.migrationFailed=true;
    showToast(t('data.migratie_uitnodigingscodes_mislukt')+(e&&e.message||e));
  }finally{ S.migratingSecrets=false; }
}

// Strip baseGroupId (an internal marker effectiveCars() adds when falling back to the default
// schedule — it was never meant to be persisted into a deviation document) and any literal
// `undefined` field, which Firestore's SDK rejects outright with a thrown error.
function cleanCars(cars){
  return cars.map(c=>{
    const {baseGroupId, ...rest} = c;
    Object.keys(rest).forEach(k=>{ if(rest[k]===undefined) delete rest[k]; });
    return rest;
  });
}

// This week's stored deviation of one shift (null when it belongs to another week).
function currentDeviationDoc(day,direction){
  const dev = S.deviations[deviationKey(day,direction)];
  return dev && dev.weekKey===S.currentWeekKey ? dev : null;
}

async function writeDeviation(day,direction,cars,extra){
  refreshWeekKey();
  await db.doc("deviations/"+deviationKey(day,direction)).set({day,direction,weekKey:S.currentWeekKey,expiresAt:deviationExpiryMs(),cars:cleanCars(cars),...(extra||{})});
  S.lastDeviationEditDay = day;
  recordLastUpdate('Deviation');
}

// opts.skipGate: the impact preview (US-07) already looked at this change and the user confirmed it.
export async function saveDeviationCars(day,direction,cars,opts){
  if(!db){showToast(t('data.geen_verbinding_met_opslag'));return false;}
  if(!(opts&&opts.skipGate) && await impactGate(day,direction,cars, ()=>saveDeviationCars(day,direction,cars,{skipGate:true}), renderDeviationTab)) return false;
  try{
    refreshWeekKey();
    // "Terug met OV" marks (US-06) live on the terug deviation and survive other edits, unless the girl is in a car again.
    const extra = direction==='terug'? keepOv(currentDeviationDoc(day,direction), cars) : {};
    await writeDeviation(day,direction,cars,extra);
    return true;
  }catch(e){ showToast(t('data.opslaan_mislukt')+(e&&e.message||e)); return false; }
}

// US-06: a parent marks (or unmarks) that a daughter goes home by public transport on one day.
// She leaves her terug car (departure time recalculated) and drops out of the planning for that ride.
export async function setReturnByPublicTransport(day,girlId,on){
  if(!db){showToast(t('data.geen_verbinding_met_opslag'));return false;}
  try{
    refreshWeekKey();
    const cur = currentDeviationDoc(day,'terug');
    const r = applyOv({cars:effectiveCars(day,'terug'), ovGirlIds:ovIds(cur), ovFrom:(cur&&cur.ovFrom)||{}}, girlId, on, ids=>computeDepartureTime(day,'terug',ids));
    const extra = r.ovGirlIds.length? {ovGirlIds:r.ovGirlIds, ovFrom:r.ovFrom} : {};
    await writeDeviation(day,'terug',r.cars,extra);
    return true;
  }catch(e){ showToast(t('data.opslaan_mislukt')+(e&&e.message||e)); return false; }
}

export async function doToggleCoord(id,isCurrently){
  try{
    if(isCurrently){
      const cfg={uid:S.me, claimedAt:Date.now()};
      await db.doc("config/coordinator").set(cfg);
      S.coordinatorConfig=cfg; S.coordinatorExists=true;
    } else {
      const cfg={familyId:id};
      await db.doc("config/coordinator").set(cfg);
      S.coordinatorConfig=cfg; S.coordinatorExists=true;
    }
    recomputeCanEdit();
    const navB=document.getElementById('navBeheer'); if(navB) navB.style.display=S.canEdit?'':'none';
    showToast(isCurrently? t('data.coordinator_rol_nu_alleen_via') : t('data.coordinator_ingesteld'));
    renderAll();
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
}

export async function saveCoordFamily(){
  if(!db){showToast(t('data.geen_verbinding_met_opslag'));return;}
  const data = readFamilyForm('coord');
  const codeEl=document.getElementById('coord_inviteCode');
  const newCode = codeEl? codeEl.value.trim() : '';
  if(S.coordEditId==null){
    const slug = (data.girlName||data.parentName||'gezin').toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,30) || 'gezin';
    S.coordEditId = 'manual-'+slug+'-'+Date.now().toString(36);
    const dupName=(data.girlName||'').trim().toLowerCase();
    const dup = dupName && Object.entries(S.families).some(([fid,fd])=> fid!==S.coordEditId && (fd.girlName||'').trim().toLowerCase()===dupName);
    if(dup) showToast(t('data.let_op_er_bestaat_al')+data.girlName+t('data.controleer_op_dubbelen'));
  }
  try{
    await db.doc("families/"+S.coordEditId).set(data,{merge:true});
    if(await saveInviteCode(S.coordEditId, newCode)) showToast(t('data.opgeslagen'));
  }
  catch(e){showToast(t('data.opslaan_mislukt')+(e&&e.message||e));}
}

// Invite codes live in /invites/{code} (doc id = the code), not on the family doc, so linked
// parents can't read other families' codes. Returns false (with a toast) when refused.
export async function saveInviteCode(familyId, code){
  if(code===(S.inviteByFamily[familyId]||'')) return true;
  if(code && !isValidInviteCode(code)){ showToast(t('data.code_alleen_letters_cijfers_en')); return false; }
  if(code){
    const existing = await db.doc("invites/"+code).get();
    if(existing.exists && existing.data().familyId!==familyId){ showToast(t('data.deze_code_is_al_in')); return false; }
  }
  const batch = db.batch();
  if(code) batch.set('invites/'+code, {familyId});
  Object.entries(S.invitesByCode).forEach(([c,fid])=>{ if(fid===familyId && c!==code) batch.delete('invites/'+c); });
  await batch.commit();
  return true;
}

export async function markTimeChangesSeen(familyIds){
  if(!db) return;
  try{
    await Promise.all(familyIds.map(id=>db.doc("families/"+id).set({timeChanges:[]},{merge:true})));
    showToast(t('data.gemarkeerd_als_gezien'));
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
}

export async function createGroupWithDriver(day,direction,girlIds,driverId,extraExclude=[]){
  if(!db){showToast(t('data.geen_verbinding_met_opslag'));return;}
  const alreadyDriving = groupsFor(day,direction).map(([gid,g])=>g.driverFamilyId).filter(Boolean);
  const exclude = new Set([driverId, ...alreadyDriving, ...extraExclude]);
  const reserveIds = eligibleDrivers(day,direction,girlIds.length).map(([id])=>id).filter(id=>!exclude.has(id));
  const gid=`${day}_${direction}_${Date.now()}_${Math.random().toString(36).slice(2,6)}`;
  const departureTime=computeDepartureTime(day,direction,girlIds);
  try{ await db.doc("groups/"+gid).set({day,direction,girlIds,driverFamilyId:driverId||null,reserveFamilyIds:reserveIds,departureTime}); recordLastUpdate('Rooster'); }
  catch(e){showToast(t('data.kon_groep_niet_opslaan_alleen')+(e&&e.message||e));}
}

export async function useOption(day,direction,assignment){
  const usedDrivers = assignment.map(a=>a.driverId).filter(Boolean);
  for(const a of assignment){ await createGroupWithDriver(day,direction,a.girlIds,a.driverId, usedDrivers.filter(id=>id!==a.driverId)); }
}

export async function createGroupCustom(day,direction,ids){
  if(!ids.length){showToast(t('data.selecteer_minstens_1_dochter'));return;}
  const eligible=eligibleDrivers(day,direction,ids.length);
  await createGroupWithDriver(day,direction,ids, eligible[0]?eligible[0][0]:null);
}
