// dates.js — generated by the modularisation of index.html; see README for what lives where.
import { t } from './i18n.js';
import { locale } from './i18n.js';
import { DAYS } from './constants.js';
import { S } from './state.js';

export function dayUp(k){ return String(k||'').toUpperCase(); }

export function startOfWeek(d){ const day=(d.getDay()+6)%7; const s=new Date(d); s.setHours(0,0,0,0); s.setDate(d.getDate()-day); return s; }

// The week everything week-scoped (Dagafwijking, "wedstrijden deze week") is currently FOR:
// Monday-Friday of the actual current week on a weekday, but the UPCOMING week once the
// weekend starts. On a Saturday/Sunday, the outgoing week's Mon-Fri is already over and its
// deviations are meant to be purged — so "this week" should mean what's coming, not what just
// ended. This is deliberately separate from todayKey/scheduleDay, which stay about literal today.
export function effectivePlanningDate(){
  const now = new Date();
  const dow = now.getDay(); // 0=Sun, 6=Sat
  if(dow===0){ const d=new Date(now); d.setDate(now.getDate()+1); return d; } // Sun -> tomorrow's Monday
  if(dow===6){ const d=new Date(now); d.setDate(now.getDate()+2); return d; } // Sat -> the coming Monday
  return now;
}

// The actual calendar date for a given weekday key, within the CURRENT (or, on a weekend, the
// UPCOMING) real-world week — used so day-buttons/cards can show "28" or "28 sep" instead of
// just "Ma", helping distinguish which literal day is being edited, especially late in the week.
export function dateForWeekday(dayKey){
  const idx = DAYS.findIndex(([k])=>k===dayKey);
  const monday = startOfWeek(effectivePlanningDate());
  const d = new Date(monday); d.setDate(monday.getDate()+idx);
  return d;
}

// ISO week (e.g. "2026-W14") — deviations are tagged with this so they can never apply to
// any week but the one they were made for, regardless of when the app happens to be opened.
export function getISOWeekKey(date){
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dayNum = (d.getUTCDay()+6)%7;
  d.setUTCDate(d.getUTCDate()-dayNum+3);
  const firstThursday = new Date(Date.UTC(d.getUTCFullYear(),0,4));
  const weekNum = 1+Math.round(((d-firstThursday)/86400000-3+((firstThursday.getUTCDay()+6)%7))/7);
  return d.getUTCFullYear()+'-W'+String(weekNum).padStart(2,'0');
}

export function refreshWeekKey(){
  const k = getISOWeekKey(effectivePlanningDate());
  if(k===S.currentWeekKey) return false;
  S.currentWeekKey = k; return true;
}

// When a deviation for the current planning week stops mattering: Saturday 00:00 (local) of
// that week. Stored on the document as `expiresAt`; firestore.rules refuse deletes before it.
export function deviationExpiryMs(){
  const s = startOfWeek(effectivePlanningDate()); s.setDate(s.getDate()+5); return s.getTime();
}

export function deviationKey(day,direction){ return day+'_'+direction; }

// "Week 40 · 28 sep – 2 okt"
export function weekRangeLabel(){
  const mon=dateForWeekday('Ma'), fri=dateForWeekday('Vr');
  const f=d=>d.toLocaleDateString(locale(),{day:'numeric',month:'short'}).replace('.','');
  return t('dates.week', { p1: +S.currentWeekKey.split('-W')[1], p2: f(mon), p3: f(fri) });
}

// "maandag 28 september" for a weekday key in the current planning week.
export function waDayDate(day){ return dateForWeekday(day).toLocaleDateString(locale(),{weekday:'long', day:'numeric', month:'long'}); }
