// help-nl.js — the help text of the app (Help, behind your initials in the header): one article per question a parent may have.
// Rules for this file (a test enforces them):
//  - Plain, short Dutch for parents who are not technical. Name buttons and tabs exactly as they appear in the app.
//  - NEVER put a secret, API key, password, invite code, phone number, e-mail address or the name of a
//    parent or child in here. This file is public (GitHub Pages). It explains how the app works, nothing else.
//    (The developer's name in 'over-achtergrond' and 'over-privacy' is there on purpose.)
//  - Each article: id (unique), title (a question or a short topic), keywords (extra words people may type),
//    body (list of paragraphs; a paragraph that starts with "• " or "1. " is shown as its own line),
//    tab (optional: the tab where this happens; adds a "Ga naar ..." button, one of the data-tab values),
//    coordinatorOnly (optional: only shown to the coordinator),
//    group (optional: 'over' = listed under the heading "Over deze app", below the other topics).
import { TEST_COUNT } from './test-count.js';

export default [
  {
    id: 'wat-is',
    title: 'Wat kan ik met deze app?',
    keywords: 'uitleg introductie overzicht carpool rooster ritten chauffeur dochter',
    body: [
      'AZ Carpool regelt wie de meiden naar Alkmaar rijdt (heen) en weer terug naar Aalsmeer (terug).',
      'De onderste balk heeft de tabbladen: Mijn week (jouw overzicht), Rooster (alle ritten), Wijzigen (eenmalige aanpassing), Wedstrijden en, alleen voor de coördinator, Beheer. Mijn gezin (jouw gegevens), het thema en deze Help vind je rechtsboven achter je initialen.',
      'Kosten worden niet in deze app verrekend. Dat gaat via de Wie Betaalt Wat-app.',
    ],
    tab: 'myweek',
  },
  {
    id: 'inloggen',
    title: 'Hoe kom ik in de app? (telefoonnummer en code)',
    keywords: 'inloggen toegang code uitnodiging telefoonnummer gate aanmelden registreren nummer klopt niet',
    body: [
      'Bij de eerste keer vraagt de app om je telefoonnummer en een code. Die code krijg je van de coördinator, samen met de link naar de app.',
      '1. Vul het telefoonnummer in dat de coördinator van jou heeft. Een ander nummer werkt niet.',
      '2. Vul de code in en tik op Toegang aanvragen.',
      'Zegt de app "Code klopt niet"? Controleer of je de code precies hebt overgetypt. Zegt de app dat het telefoonnummer niet bij de code hoort, gebruik dan het nummer dat de coördinator van je heeft.',
      'Je hoeft dit maar één keer te doen op dit toestel.',
    ],
  },
  {
    id: 'melding-balk',
    title: 'Wat is de gele balk bovenaan de app?',
    keywords: 'melding balk geel mededeling bericht bovenaan waarschuwing nieuws',
    body: [
      'De coördinator kan een korte melding laten zien bovenaan de app, bijvoorbeeld dat een training niet doorgaat. Die melding staat in een dunne gele balk bovenaan, op elk tabblad.',
      'Je kunt de balk niet wegklikken. Hij verdwijnt vanzelf als de coördinator hem uitzet, of op het moment dat de coördinator heeft ingesteld.',
    ],
  },
  {
    id: 'dochter-koppelen',
    title: 'Hoe koppel ik mijn telefoon aan mijn gezin?',
    keywords: 'koppelen dochter gezin ontkoppelen code telefoonnummer toegang mijn gezin nieuwe telefoon',
    body: [
      'De coördinator voert je gezin in en geeft je een code. Vul bij Toegang aanvragen je telefoonnummer en die code in: je telefoon is dan gekoppeld aan je gezin. Een dochter kiezen hoeft niet.',
      'Twee ouders van hetzelfde gezin gebruiken dezelfde code, elk op de eigen telefoon.',
      'Nieuwe telefoon of ontkoppeld? Vraag de coördinator om de code en vul die opnieuw in.',
      'Wil je de telefoon loskoppelen? Tik in Mijn gezin op Ontkoppelen van deze dochter. Je moet twee keer tikken om het zeker te weten.',
    ],
    tab: 'profile',
  },
  {
    id: 'mijn-week',
    title: 'Waar zie ik wie mijn dochter rijdt?',
    keywords: 'mijn week overzicht wie rijdt vertrektijd heen terug chauffeur vandaag wanneer opgehaald',
    body: [
      'Op Mijn week zie je per dag de rit van je dochter: heen en terug, met de tijd en de chauffeur. Vandaag heeft een label VANDAAG.',
      'Rijd je zelf op een dag, dan staat er "Jouw rijbeurt om" met de tijd.',
      'Is er deze week iets aangepast, dan staat er "Wijziging actief" bij die dag.',
      'Mijn week is alleen om te lezen. Wil je iets veranderen, ga dan naar Wijzigen.',
      'Met de deel-knop rechtsboven stuur je het overzicht door.',
    ],
    tab: 'myweek',
  },
  {
    id: 'rit-ontbreekt',
    title: 'Mijn dochter heeft nog geen rit of staat op "niet ingepland"',
    keywords: 'niet ingepland niet ingedeeld geen rit geen chauffeur regelen ontbreekt',
    body: [
      'Dat betekent dat er voor die rit nog geen auto met een vrije plek is gevonden.',
      'Klopt de tijd van je dochter in Mijn gezin? Zonder aankomsttijd of klaartijd kan de app haar niet inplannen.',
      'Blijft het staan, laat het de coördinator weten. Die kan haar in het Rooster in een auto zetten.',
    ],
    tab: 'myweek',
  },
  {
    id: 'wijzigen',
    title: 'Mijn dochter is ziek of ik wil een rit ruilen (eenmalig wijzigen)',
    keywords: 'wijzigen ziek ruilen rit aanpassen eenmalig afmelden niet mee meerijden andere chauffeur tijd veranderen deze week',
    body: [
      'Ga naar Wijzigen. Daar pas je de ritten van alleen deze week aan. Het vaste rooster blijft zoals het was. Aan het weekend zijn alle wijzigingen vanzelf weer weg.',
      '1. Kies de dag bovenaan. Dagen met een wijziging hebben een stip.',
      '2. Elke rit is één regel: tijd, chauffeur en route, met daaronder de meisjes die meerijden. Tik op Wijzig om de rit open te klappen.',
      '3. Pas aan wat nodig is: vertrektijd, chauffeur, ophaalplek en aankomst (AFC \'34 of ATC). Bij Kinderen tik je op de drie puntjes om een meisje naar een andere auto te verplaatsen of uit de auto te halen. Een wijziging wordt meteen opgeslagen.',
      '4. Tik op Klaar om de rit weer dicht te klappen. Per ongeluk iets gewijzigd? Tik direct op Ongedaan.',
      'Wil je alles van die dag terugzetten? Tik op Terug naar standaard rooster. Tik twee keer om het zeker te weten.',
      'Stem een wijziging altijd eerst af met de chauffeur. Tik op de naam van de chauffeur en kies WhatsApp of Bellen.',
      'Onder de auto\'s staat Back-up: de chauffeurs die kunnen invallen, in de volgorde waarin je ze kunt vragen. Chauffeurs die die dag al rijden staan er niet bij. Tik op een naam om die chauffeur te vragen via WhatsApp of Bellen.',
    ],
    tab: 'deviation',
  },
  {
    id: 'dagcoordinator',
    title: 'Wat is een dagcoördinator?',
    keywords: 'dagcoordinator dagcoördinator coördinator morgen wie regelt',
    body: [
      'Elke dag heeft één ouder als dagcoördinator. Die regelt de wijzigingen voor die dag.',
      'Op Rooster en Mijn week staat wie dat morgen is. Op vrijdag staat er niets. In het weekend staat wie het maandag is.',
      'Staat er niemand, dan heeft de coördinator nog niemand ingesteld.',
    ],
  },
  {
    id: 'whatsapp-update',
    title: 'Hoe laat ik de anderen weten dat er iets verandert? (WhatsApp)',
    keywords: 'whatsapp delen bericht update conclusie appje versturen melden groep',
    body: [
      'Onderaan elke dag in Wijzigen staat het Dagbericht: een kant-en-klaar bericht met de wijzigingen en het schema van die dag. Tik op Deel in de groep en WhatsApp opent met de tekst al ingevuld.',
      'De app stuurt zelf nooit iets. Jij kiest in WhatsApp naar wie het gaat en tikt op versturen.',
    ],
    tab: 'deviation',
  },
  {
    id: 'terug-met-ov',
    title: 'Mijn dochter rijdt een rit niet mee',
    keywords: 'rijdt niet mee heen terug schakelaar afmelden ov openbaar vervoer zelf naar huis niet met de auto toch meerijden',
    body: [
      'Ga naar Mijn week, zoek de heen- of terugrit op de dag en zet de schakelaar rechts bij de rit uit. Je dochter gaat dan uit haar auto. De vertrektijd van de auto wordt opnieuw uitgerekend. Er hoeft geen reden bij.',
      'Ander plan? Zet de schakelaar weer aan om haar terug in de auto te zetten.',
    ],
    tab: 'myweek',
  },
  {
    id: 'rooster',
    title: 'Wat staat er in het Rooster?',
    keywords: 'rooster vast rooster deze week standaard alle ritten auto passagier verplaatsen tijdelijk rooster vakantie periode weekoverzicht pdf afdrukken printen',
    body: [
      'Het Rooster laat per dag alle auto\'s zien: wie rijdt en welke meiden erin zitten. Bij elke rit staat waar de auto ophaalt en heen gaat.',
      'Kies bovenaan Deze week (met eventuele wijzigingen) of Vast rooster (zoals het elke week is).',
      'Is er een periode met andere tijden (vakantie, proefwerkweek) en heeft de coördinator het tijdelijke rooster gemaakt? Dan staat er een derde knop met de naam van de periode. Daar zie je per dag de doorgegeven tijden en de auto\'s. Op die dagen laat Deze week het tijdelijke rooster zien in plaats van het vaste rooster.',
      'Tik op Weekoverzicht voor de hele week op één pagina, zoals de PDF die je eerder kreeg: alle ritten met chauffeur, passagiers, bezetting en reserves, hoe vaak elke chauffeur rijdt en de tijden van elke meid. Tik op Afdrukken / PDF om het af te drukken of als PDF te bewaren.',
      'Alleen de coördinator past het Rooster aan. Als ouder gebruik je daarvoor Wijzigen.',
    ],
    tab: 'schedule',
  },
  {
    id: 'weekschema',
    title: 'Wanneer kan ik rijden? Mijn vaste weekschema aanpassen',
    keywords: 'beschikbaar beschikbaarheid back-up backup rijden weekschema plekken zitplaatsen auto capaciteit aankomst klaar tijd vast',
    body: [
      'In Mijn gezin staat je vaste weekschema. Per dag geef je aan:',
      '• Kan jij deze dag rijden? Kies Beschikbaar of Back-up. Back-up betekent dat je alleen rijdt als het nodig is.',
      '• Heen: hoe laat je dochter in Alkmaar moet zijn.',
      '• Terug: hoe laat je dochter klaar is om opgehaald te worden.',
      '• Hoeveel plekken je auto heeft voor passagiers. Reken jezelf niet mee.',
      'Let op: een aanpassing hier geldt voor elke week, niet alleen voor deze week. De app waarschuwt je met "Je past je vaste weekschema aan" en slaat het pas op als je op Bevestigen: voor elke week tikt. Wil je maar één keer iets anders, tik dan op Eenmalig wijzigen. Je aanpassing wordt dan ongedaan gemaakt en je gaat naar Wijzigen, alleen voor deze week.',
    ],
    tab: 'profile',
  },
  {
    id: 'wedstrijden',
    title: 'Hoe regel ik een carpool voor een wedstrijd?',
    keywords: 'wedstrijd wedstrijden uitwedstrijd thuiswedstrijd competitie aftrap carpool regelen kalender agenda',
    body: [
      'Ga naar Wedstrijden. Daar staan alle wedstrijden van de komende 29 dagen.',
      'Een carpool kun je regelen voor wedstrijden van de komende 8 dagen. Bij latere wedstrijden staat vanaf welke dag het kan.',
      '1. Tik bij de wedstrijd op + Auto toevoegen.',
      '2. Kies de chauffeur, de meiden die meerijden en de vertrektijd.',
      '3. Sla op. Iedereen kan een wedstrijdcarpool opzetten en aanpassen.',
      'Onder de wedstrijd staat de afstand (enkele reis) en de carpoolkosten. Bij wedstrijden op AFC \'34 of het AZ Trainingscomplex is de afstand vast. Bij andere plekken is het een schatting en staat er een ± voor.',
      'De wedstrijden komen uit de agenda\'s van de teams. Ze worden één keer per dag bijgewerkt. Klopt er iets niet, laat het de coördinator weten.',
    ],
    tab: 'matches',
  },
  {
    id: 'route',
    title: 'Hoe kom ik bij het wedstrijdadres? (route)',
    keywords: 'route navigatie adres locatie maps kaart rijden naar veld',
    body: [
      'In Mijn week is de locatie van de wedstrijd een link. Tik erop en je kaartenapp opent met het adres. De route begint bij waar je op dat moment bent.',
    ],
    tab: 'myweek',
  },
  {
    id: 'periode-tijden',
    title: 'Ik moet tijden doorgeven voor de vakantie of proefwerkweek. Hoe doe ik dat?',
    keywords: 'periode vakantie proefwerkweek herfstvakantie tijden doorgeven deadline actie nodig rode stip andere tijden eerder later klaar rijdt niet mee',
    body: [
      'Als er een periode met andere tijden is, staat er bij Wijzigen een kaart Actie nodig met de deadline. Op het tabblad Wijzigen staat dan ook een rode 1. Lopen er twee perioden tegelijk, dan zijn het twee kaarten en staat er een 2. Vul elke periode apart in.',
      '1. Tik op Tijden doorgeven.',
      '2. Per dag staan de tijden van het vaste rooster al ingevuld. Pas alleen aan wat anders is. Aangepaste tijden krijgen een oranje kleur.',
      '3. Rijdt je dochter een dag niet mee? Zet de schakelaar op Rijdt niet mee.',
      '4. Tik op Doorgeven.',
      'Heen is de tijd dat je dochter in Alkmaar moet zijn. Terug is de tijd dat ze klaar is om opgehaald te worden. Een tijd invullen betekent dat ze meerijdt.',
      'Je vult dit één keer in voor de hele periode. Tot de deadline kun je het aanpassen met Tijden aanpassen. Daarna kan alleen de coördinator het nog aanpassen. Vul je niets in, dan geldt het vaste rooster.',
      'Je vaste weekschema in Mijn gezin verandert hierdoor niet.',
      'Daarna maakt de coördinator een tijdelijk rooster voor de periode. Dat zie je in Mijn week en bij Rooster. Alleen in die periode vervangt het tijdelijke rooster het vaste rooster. Wijzigen gaat altijd voor het tijdelijke rooster.',
    ],
    tab: 'deviation',
  },
  {
    id: 'ophaalplek',
    title: 'Waar wordt mijn dochter opgehaald?',
    keywords: 'ophaalplek ophalen afzetten plek busstation locatie waar adres',
    body: [
      'Bij elke rit staat de tijd en de plek, bijvoorbeeld "07:05 Busstation → AFC \'34".',
      'De vaste plek van elke auto staat in het Rooster (Vast rooster): tik op de plek van een auto om het vertrek en de aankomst van alleen die auto te kiezen. Voor één keer een andere plek kiezen kan in Wijzigen, bij de auto: kies een andere plek of kies Ander adres… en vul zelf een adres of plek in. Dat wordt niet als vaste plek bewaard en verdwijnt aan het eind van de week.',
    ],
    tab: 'deviation',
  },
  {
    id: 'flex',
    title: 'Ik ben een Flex-gezin. Hoe meld ik me aan voor een rit?',
    keywords: 'flex aanmelden inschrijven spelerchauffeur speelster meerijden zelf rijden afmelden',
    body: [
      'Flex-gezinnen staan niet in het vaste rooster. Je meldt je per dag en per richting aan in Wijzigen:',
      '• met een tijd,',
      '• als passagier in een auto met een vrije plek, of',
      '• als je zelf rijdt.',
      'Deze aanmelding verdwijnt aan het eind van de week, net als andere wijzigingen.',
    ],
    tab: 'deviation',
  },
  {
    id: 'installeren',
    title: 'Hoe zet ik de app op mijn telefoon?',
    keywords: 'installeren beginscherm icoon app telefoon iphone android safari chrome snelkoppeling',
    body: [
      'Je kunt AZ Carpool op je beginscherm zetten, dan opent hij als een gewone app.',
      '• Android: tik op Installeer app (te vinden in Mijn gezin).',
      '• iPhone: open de app in Safari, tik onderin op het deel-icoon en kies Zet op beginscherm.',
    ],
    tab: 'profile',
  },
  {
    id: 'donker',
    title: 'Hoe zet ik het donkere thema aan?',
    keywords: 'donker licht thema dark mode kleur scherm maan zon',
    body: [
      'Tik rechtsboven op je initialen en kies bij Thema Donker. Kies Licht om terug te gaan. De app onthoudt je keuze op dit toestel.',
    ],
  },
  {
    id: 'foutmelding',
    title: 'De app doet raar of zegt "Geen verbinding"',
    keywords: 'fout foutmelding geen verbinding niet verbonden werkt niet laden vastgelopen herladen internet storing opslaan mislukt',
    body: [
      '1. Controleer of je internet hebt (wifi of mobiele data).',
      '2. Sluit de app helemaal en open hem opnieuw. In de browser: laad de pagina opnieuw.',
      '3. Zie je oude gegevens? Open de app een keer met internet. Dan haalt hij de nieuwste versie op.',
      'Werkt het dan nog niet, laat het de coördinator weten en vertel welke melding je ziet.',
    ],
  },
  {
    id: 'coordinator-vragen',
    title: 'Waar kan ik terecht als ik er niet uitkom?',
    keywords: 'coordinator coördinator contact hulp vragen probleem bellen beheerder',
    body: [
      'Kom je er niet uit, vraag het dan aan de coördinator. Alleen de coördinator kan gezinnen toevoegen, het Rooster aanpassen, codes geven en de instellingen wijzigen.',
    ],
  },
  {
    id: 'beheer-gezinnen',
    title: 'Beheer: gezinnen toevoegen, codes en telefoonnummers',
    keywords: 'back-up backup terugzetten export import csv excel beheer gezin toevoegen code uitnodiging telefoonnummer coördinator maken testweergave ouder dubbel verwijderen oog',
    coordinatorOnly: true,
    body: [
      'Onder Beheer, bij Gezinnen beheren, voeg je gezinnen toe en pas je gegevens aan namens een ouder. Telefoonnummers en de uitnodigingscode staan onder Wijzig. Meerdere mensen kunnen dezelfde code gebruiken.',
      'Het oog-icoon toont de app zoals die ouder hem ziet. Met Stoppen ga je terug naar jouw eigen weergave.',
      'Bij Type gezin kies je Vast of Flex.',
      'Onder Back-up gezinnen maak je een bestand (CSV, te openen in Excel) van alle gezinnen, met tijden, beschikbaarheid, coördinator, autocapaciteit en telefoonnummers. Met Terugzetten uit bestand zet je een eerder gemaakt bestand terug: de gezinnen in het bestand worden overschreven, gezinnen die er niet in staan blijven staan. Het bestand wordt eerst gecontroleerd; bij een fout wordt er niets gewijzigd.',
      'Geef de code en de link alleen door aan de ouder zelf, niet in een openbare groep.',
    ],
    tab: 'beheer',
  },
  {
    id: 'beheer-instellingen',
    title: 'Beheer: planning, plekken en dagcoördinatoren',
    keywords: 'beheer instellingen planning plekken adres dagcoordinator dagcoördinator voorkeuren samen reizen volgorde standaard ophaalplek',
    coordinatorOnly: true,
    body: [
      '• Dagcoördinatoren: kies per weekdag één gezin.',
      '• Ophaal- en afzetplekken: maximaal 6 plekken met naam en adres. Met Plek toevoegen voeg je er een toe. Een adres mag gewoon een adres zijn of GPS-coördinaten. Het Busstation blijft altijd staan.',
      '• Planning-instellingen: regels voor hoe combinaties in het Rooster worden voorgesteld. Wijzigingen worden vanzelf opgeslagen.',
      '• Reisvoorkeuren: wie liever samen in één auto zit.',
      '• Selectievolgorde per shift: de volgorde van de beschikbare chauffeurs (ook Flex-gezinnen die als chauffeur beschikbaar zijn). Een hogere plek wordt eerder gekozen. Staat er "back-up" achter, dan rijdt dat gezin alleen mee als de standaardchauffeurs de shift niet kunnen dekken.',
      '• Zo plant de app: eerst moet iedereen mee binnen de maximale wachttijd (en passen de plekken). Daarna zo min mogelijk back-upchauffeurs, dan zo min mogelijk auto\'s, dan de hoogste plekken in de Selectievolgorde, dan de kortste wachttijd. Daarna tellen de wensen: samen reizen, dan de eigen ouder, dan de voorkeur. Een grotere auto krijgt nooit voorrang op tijd.',
      '• Meldingen bij gewijzigde tijden: zie je bovenaan het Rooster. Zet ook browsermeldingen aan voor een seintje.',
    ],
    tab: 'beheer',
  },
  {
    id: 'ritbeurs',
    title: 'Een rit aanbieden of overnemen (Ritbeurs)',
    keywords: 'ritbeurs aanbieden overnemen ruilen rit kan niet rijden inspringen back-up melding markt vervanger',
    body: [
      'Kun je een rit niet rijden? Ga naar Wijzigen en tik bovenaan op Ritbeurs. Bij Jouw rijbeurten tik je op Aanbieden bij de rit die je niet kunt rijden. Je kunt er een kort bericht bij zetten.',
      'Eerst horen de back-ups het die zich voor dat tijdstip hebben gemeld. Alle andere gezinnen zien de rit in de Ritbeurs. Het getal achter Ritbeurs en op het tabblad Wijzigen laat zien hoeveel ritten open staan.',
      'Wil je een rit overnemen? Tik op Ik neem deze rit over en bevestig. Wie als eerste bevestigt, rijdt de rit. Ben je te laat, dan zie je dat meteen. Passen er te weinig kinderen in jouw auto, of rijd je al rond die tijd, dan krijg je een waarschuwing. Je mag de rit dan toch overnemen.',
      'Overgenomen is van jou, ook als je later toch niet kunt. Dan bied je hem zelf opnieuw aan. De aanbieder kan zijn aanbod intrekken zolang niemand de rit heeft.',
      'Heb je tijd en wil je kunnen inspringen? Meld bij Ik kan inspringen een tijdvak. Chauffeurs met een rit in dat tijdvak krijgen een bericht. Met Alleen als ik niet al rijd krijg je alleen aanbiedingen op momenten dat je niet zelf rijdt. Een tijdvak verwijder je met de prullenbak.',
      'Staat een aangeboden rit om 18:00 de dag ervoor nog open, dan krijgen de aanbieder en de dagcoördinator een melding.',
      'Meldingen staan onderaan in de Ritbeurs. Dit zijn meldingen in de app: je ziet ze als je de app opent. Stille uren (standaard 22:00 tot 06:00) kun je daar zelf instellen. Meldingen die in de stille uren binnenkomen, verschijnen daarna.',
      'Zie je geen Ritbeurs? Dan heeft de coördinator hem uitgezet.',
    ],
    tab: 'deviation',
  },
  {
    id: 'beheer-ritbeurs',
    title: 'Beheer: de Ritbeurs aan- of uitzetten',
    keywords: 'ritbeurs uitzetten aanzetten schakelaar feature meldingen stoppen',
    body: [
      'In Beheer, bij Berichten, staat de kaart Ritbeurs met één schakelaar. De schakelaar slaat direct op.',
      'Uit betekent: de Ritbeurs verdwijnt bij iedereen, er kan niets meer worden aangeboden of overgenomen en er worden direct geen meldingen meer gemaakt. Ook niet door een app die nog open staat: de database weigert het.',
      'Wat al is overgenomen blijft gewoon in het rooster staan. Aanbiedingen en tijdvakken blijven bewaard en komen terug als je de Ritbeurs weer aanzet.',
    ],
    tab: 'beheer',
    coordinatorOnly: true,
  },
  {
    id: 'beheer-onderhoud',
    title: 'Beheer: de app tijdelijk dichtzetten (onderhoudsmodus)',
    keywords: 'onderhoud onderhoudsmodus dicht sluiten niet beschikbaar offline storing pagina aan uit zetten',
    coordinatorOnly: true,
    body: [
      'Onder Beheer, bij Onderhoudsmodus, zet je de app tijdelijk dicht. Alle gebruikers zien dan een scherm dat de app even niet beschikbaar is. Jij blijft alles zien en kunnen doen.',
      '1. Typ eventueel eerst een eigen tekst, bijvoorbeeld wanneer de app weer open is (maximaal 150 tekens). Onder Zo zien gebruikers het zie je het resultaat.',
      '2. Zet Onderhoudsmodus aan.',
      'Er is geen Opslaan-knop: de schakelaar wordt meteen opgeslagen, een eigen tekst zodra je het veld verlaat. Binnen enkele seconden zien de gebruikers het scherm. Bovenaan zie jij een gele balk als herinnering.',
      'Weer openzetten doe je door Onderhoudsmodus uit te zetten. Het scherm van de gebruikers verdwijnt dan vanzelf, zonder dat zij iets hoeven te doen. In de testweergave als ouder zie je de onderhoudspagina niet.',
    ],
    tab: 'beheer',
  },
  {
    id: 'beheer-melding',
    title: 'Beheer: een melding voor iedereen aan- en uitzetten',
    keywords: 'melding balk geel mededeling bericht aan uit zetten automatisch uit datum tijd iedereen',
    coordinatorOnly: true,
    body: [
      'Onder Beheer, bij Melding voor iedereen, zet je een korte melding aan. Alle gebruikers zien hem als dunne gele balk bovenaan de app.',
      '1. Zet Melding tonen aan.',
      '2. Typ de tekst (maximaal 100 tekens). Onder Zo ziet iedereen het zie je het resultaat.',
      '3. Kies eventueel Automatisch uit op: een datum én een tijd. Laat je dit leeg, dan blijft de melding aan tot jij hem uitzet.',
      '4. Tik op Opslaan.',
      'Uitzetten doe je door Melding tonen uit te zetten en op Opslaan te tikken. De tekst blijft bewaard, dus je kunt hem later weer aanzetten. Gebruikers kunnen de balk zelf niet wegklikken.',
    ],
    tab: 'beheer',
  },
  {
    id: 'beheer-periode',
    title: 'Beheer: een periode met andere tijden instellen (vakantie, proefwerkweek)',
    keywords: 'periode vakantie proefwerkweek herfstvakantie andere tijden deadline invullen tijdelijk rooster eerste dag laatste dag',
    coordinatorOnly: true,
    body: [
      'Onder Perioden met andere tijden staat een lijst met alle perioden. Tik op + Periode toevoegen om ouders andere tijden te laten doorgeven voor een vakantie of proefwerkweek. Het vaste rooster blijft staan.',
      '• Naam: bijvoorbeeld Herfstvakantie.',
      '• Eerste dag en Laatste dag: allebei een werkdag, samen maximaal 10 werkdagen.',
      '• Invullen open vanaf: vanaf die dag kunnen ouders hun tijden doorgeven.',
      '• Deadline: dag en tijd, vóór de eerste dag van de periode.',
      'Tik op Opslaan. Met Annuleren gooi je je wijzigingen weg. Met het potlood-icoon wijzig je een periode; het formulier verschijnt dan op de plek van die periode. De eerste dag kun je niet meer wijzigen zodra er tijden of een tijdelijk rooster zijn.',
      'Je kunt meerdere perioden tegelijk hebben. Ouders kunnen dus al tijden doorgeven voor de toetsweek terwijl de herfstvakantie nog loopt. Twee perioden mogen alleen geen dag delen: de app meldt het als ze overlappen.',
      'Bij elke periode waarvoor invullen is geopend zie je een voortgangsbalk (bijvoorbeeld 6 van 8 gezinnen). Tik op Wie heeft ingevuld? om te zien wie al heeft doorgegeven en wie nog niet. Onder de titel staan alvast de eerste gezinnen die nog moeten.',
      'Met het prullenbak-icoon verwijder je een periode (tik twee keer). De tijden die gezinnen voor die periode hebben doorgegeven, worden ook verwijderd. De app zegt hoeveel gezinnen dat zijn. Heeft de periode een tijdelijk rooster, verwijder dat dan eerst bij Rooster.',
      'Vanaf de dag dat invullen opent, zien alle ouders bij Wijzigen een kaart Actie nodig en een rode 1 op het tabblad. Jij ziet die kaart ook, voor je eigen gezin.',
      'Onder Namens een ouder invullen zie je wie al heeft doorgegeven en wie nog niet. Tik bij een gezin op Invullen om de tijden namens de ouder in te vullen. Bij een gezin dat al heeft doorgegeven, tik je op Bekijk en daarna op Tijden aanpassen. Hetzelfde aantal staat in Beheer bij de periode.',
      'Na de deadline kunnen ouders niets meer aanpassen. Jij kunt tot het einde van de periode nog tijden invullen en aanpassen, voor jezelf en namens een ouder.',
      'Een ouder die niets invult, houdt het vaste rooster voor die dagen.',
    ],
    tab: 'beheer',
  },
  {
    id: 'periode-backup',
    title: 'Beheer: een back-up maken van een periode, om veilig te testen',
    keywords: 'back-up backup periode testen uitproberen terugzetten herstellen tijden doorgegeven tijdelijk rooster veilig overschrijven',
    coordinatorOnly: true,
    body: [
      'Wil je iets uitproberen in een periode met andere tijden? Maak dan eerst een back-up. Zo overschrijf je niet wat ouders hebben doorgegeven.',
      'Bij Perioden met andere tijden staat onder elke periode een regel Back-ups. Tik erop en daarna op Back-up maken. De back-up bewaart drie dingen: de periode zelf (naam, dagen, deadline), alles wat gezinnen hebben doorgegeven en het tijdelijke rooster. Je kunt tot 10 back-ups per periode hebben.',
      'Bij elke back-up staat het moment en hoeveel gezinnen en ritten erin zitten. Eronder staat wat er sindsdien is veranderd.',
      'Terugzetten: tik op het pijltje-icoon en tik nog een keer. Alles gaat dan terug naar het moment van de back-up. Heeft een ouder sindsdien iets doorgegeven of aangepast, dan gaat dat verloren. De app zegt hoeveel gezinnen dat zijn voordat je bevestigt.',
      'Vlak voor het terugzetten maakt de app zelf een back-up van de stand van dat moment (Automatisch). Zet je per ongeluk de verkeerde terug, dan zet je die automatische back-up terug. Er is per periode één automatische back-up. Een nieuwe vervangt de vorige.',
      'Met het prullenbak-icoon verwijder je een back-up. Verwijder je een hele periode, dan gaan de back-ups van die periode ook weg.',
      'Tip: laat ouders niet invullen terwijl je test, of sluit de deadline eerst. Dan verlies je bij het terugzetten niets.',
    ],
    tab: 'beheer',
  },
  {
    id: 'periode-rooster',
    title: 'Rooster: het tijdelijke rooster voor een periode maken',
    keywords: 'tijdelijk rooster periode vakantie proefwerkweek auto indeling opnieuw indelen chauffeur verplaatsen niet ingedeeld doorgegeven',
    coordinatorOnly: true,
    body: [
      'Bij Rooster staat bovenaan een kaart per periode: hoeveel gezinnen hebben doorgegeven, wie nog niet, en per dag hoeveel tijden anders zijn dan het vaste rooster.',
      '1. Tik op Tijdelijk rooster maken. De app deelt alle dagen van de periode in met de doorgegeven tijden, op dezelfde manier als bij het vaste rooster. Wie niets heeft doorgegeven, houdt de vaste tijd.',
      '2. Tik op de derde knop (de naam van de periode) en kies een dag. Zijn er twee perioden, kies dan eerst boven in het veld Periode welke je wilt zien.',
      '3. Pas aan wat niet klopt: kies een andere chauffeur, verplaats een meisje naar een andere auto of naar Niet ingedeeld, of zet een meisje in een nieuwe auto. Elke wijziging wordt meteen opgeslagen.',
      '4. Met Opnieuw indelen deel je één richting van een dag opnieuw in. Met Alles opnieuw indelen doe je dat voor de hele periode. Handmatige aanpassingen zijn dan weg. Tik twee keer om het zeker te weten.',
      'Met het prullenbak-icoon bij de kaart van een periode verwijder je alleen het tijdelijke rooster van die periode. Dan geldt weer het vaste rooster. De doorgegeven tijden blijven bewaard.',
      'Het tijdelijke rooster vervangt het vaste rooster alleen in de periode. Wijzigingen in Wijzigen gaan altijd voor het tijdelijke rooster.',
    ],
    tab: 'schedule',
  },
  {
    id: 'beheer-kalenders',
    title: 'Beheer: wedstrijdkalenders en afstanden',
    keywords: 'beheer wedstrijdkalender kalender agenda google openbaar verversen afstand kilometers wedstrijden ontbreken',
    coordinatorOnly: true,
    body: [
      'Onder Wedstrijdkalenders (Google Calendar) voer je per team een naam en een Calendar ID in. Elke agenda moet openbaar staan in Google Calendar.',
      'Met Nu verversen haal je de wedstrijden meteen op. Anders gebeurt dat één keer per dag, door de eerste ouder die de app opent.',
      'Gebruik altijd de teamnaam zoals je die hier invult, en verander die niet los ergens anders.',
      'Ontbreken de afstanden bij uitwedstrijden, dan is er nog geen routeservice-sleutel ingesteld. Die stel je in onder Beheer, bij API-sleutels. Zet die sleutel nooit in een bericht of in dit hulpvenster.',
    ],
    tab: 'beheer',
  },
  // ---- Over deze app (shown under its own heading below the topics; text comes from the coordinator's document) ----
  {
    id: 'over-achtergrond',
    group: 'over',
    title: 'Over deze app: achtergrond en kwaliteit',
    keywords: 'over app gemaakt ontwikkeld bouwer wie claude ai gemini lumo tests testen kwaliteit wcag toegankelijkheid contrast ontwerp gebruiksgemak stabiel betrouwbaar',
    body: [
      'De app is ontwikkeld door Michiel Veen met Claude (AI), aangevuld met Gemini en Lumo. De app zelf gebruikt geen AI. De eisen, de keuzes en de controle liggen bij de ontwikkelaar.',
      'Bij elke wijziging worden tests geschreven. Vóór livegang draaien alle bestaande tests opnieuw en moeten ze allemaal slagen. Het gaat om ' + TEST_COUNT.toLocaleString('nl-NL') + ' automatische tests.',
      'Ontwerp en gebruiksgemak zijn meerdere keren getoetst, onder meer aan de WCAG-richtlijnen. Getoetst is op contrast, bruikbaarheid op een telefoon en een consistent gebruik van knoppen en kleuren.',
    ],
  },
  {
    id: 'over-privacy',
    group: 'over',
    title: 'Over deze app: privacy en AVG (GDPR)',
    keywords: 'privacy avg gdpr gegevens opgeslagen persoonsgegevens cookies tracking analytics meting ip adres veilig veiligheid security beveiliging verwijderen wissen cookiebanner toegang verantwoordelijke toestemming rechten inzage kopie bewaartermijn bewaren klacht autoriteit persoonsgegevens europa eu firebase telefoonnummer zichtbaar',
    body: [
      'De app houdt zich aan de Algemene verordening gegevensbescherming (AVG, in het Engels GDPR). De app bewaart zo weinig mogelijk gegevens.',
      'Verantwoordelijk voor de gegevens is Michiel Veen, ontwikkelaar van de app en coördinator. De app is een initiatief van ouders voor ouders en is geen onderdeel van de club.',
      'Welke gegevens worden bewaard:',
      '• Ouders: het telefoonnummer (of de telefoonnummers) en de naam die je zelf invult. De naam is niet verplicht.',
      '• Dochters: alleen de voornaam, tenzij de ouder die zelf aanpast.',
      '• Verder: rijtijden en beschikbaarheid, het rooster en wijzigingen, voor zover nodig voor de carpool.',
      'Er worden geen woonadressen, geboortedata of e-mailadressen opgeslagen. De adressen in de app zijn openbare plaatsen, zoals voetbalvelden.',
      'Naam en telefoonnummer zijn zichtbaar voor alle gebruikers. Dat is bewust: carpoolers moeten elkaar kunnen bereiken, bijvoorbeeld bij een wijziging of vertraging. De app is alleen bedoeld voor de carpoolgroep en niet openbaar.',
      'De gegevens worden alleen gebruikt om de carpool te organiseren en elkaar daarover te bereiken. Ze worden niet verkocht en niet voor reclame of andere doelen gebruikt. De grondslag is jouw toestemming: je vult de gegevens zelf in en doet vrijwillig mee. Je kunt die toestemming altijd intrekken.',
      'De gegevens staan in een database van Google Firebase op servers in de Europese Unie. De app wordt gehost op GitHub Pages.',
      'Toegang is alleen mogelijk met telefoonnummer en code. De database weigert toegang voor niet-leden, ook buiten de app om.',
      'De app gebruikt geen cookies en heeft geen tracking of meting (geen Google Analytics, Sentry of Hotjar, geen advertenties). Het toestel bewaart alleen wat nodig is voor de werking: een anonieme inlogcode en de themakeuze. Er is daarom geen cookiebanner.',
      'Naar externe diensten gaan geen persoonsgegevens. Het IP-adres is wel zichtbaar voor de partijen die de app laden: GitHub (hosting), Google (database, agenda-opvraging) en OpenRouteService (routes). Dat geldt voor elke website. OpenRouteService ontvangt alleen de adressen van de voetbalvelden en Google Agenda alleen het agenda-ID.',
      'Na elke grote wijziging wordt de app gecontroleerd op security- en privacy-risico\'s.',
      'Gegevens blijven bewaard tot je de carpool verlaat of om verwijdering vraagt. De coördinator verwijdert de gegevens als iemand stopt, of aan het einde van het seizoen.',
      'Je mag je gegevens inzien, laten aanpassen of laten verwijderen. Je naam kun je zelf wijzigen in de app. Voor inzage, een kopie of verwijdering vraag je het aan de coördinator. Dan worden ook de gegevens van je dochter(s) verwijderd, waarna je niet meer in de app kunt. Je krijgt meestal binnen 3 dagen antwoord, uiterlijk binnen een maand.',
      'Neem bij vragen over privacy contact op met de coördinator. Je kunt ook een klacht indienen bij de Autoriteit Persoonsgegevens.',
    ],
  },
  {
    id: 'over-diensten',
    group: 'over',
    title: 'Over deze app: gebruikte diensten',
    keywords: 'diensten koppelingen integraties routes openrouteservice navigatie maps waze tomtom here wego google agenda kalender whatsapp firebase github hosting opslag database afstand',
    body: [
      '• Routes: OpenRouteService, een Europese open-sourcedienst op basis van OpenStreetMap-gegevens. Gebruikt voor afstand en kosten van uitwedstrijden.',
      '• Navigatie: op Android is de navigatie-app vrij te kiezen (bijvoorbeeld TomTom, HERE WeGo, Waze, Google Maps). Op iPhone en andere apparaten opent Google Maps.',
      '• Wedstrijden: uit een apart Google-agenda met de wedstrijdkalenders van de teams. Wordt één keer per dag bijgewerkt.',
      '• Berichten: via WhatsApp. De app verstuurt zelf geen berichten.',
      '• Opslag en hosting: Google Firebase (database) en GitHub Pages (hosting).',
    ],
  },
  {
    id: 'over-beheer',
    group: 'over',
    title: 'Over deze app: beheer en onderhoud',
    keywords: 'beheer onderhoud verbeteren verbetering ontwikkelaar developer contributor meewerken hulp vragen zonder afhankelijk seizoen kalender leeg coordinator rol roosters standaardschema',
    body: [
      'Verbeteringen verlopen uitsluitend via de ontwikkelaar. Een developer die wil meewerken kan contributor worden.',
      'Deze helpfunctie bevat de kennis over de app. Zoek hier eerst een antwoord op je vraag, daarna pas de coördinator benaderen. Bij elke aanpassing van de app wordt de helpfunctie mee aangepast.',
      'De app werkt zonder tussenkomst van de ontwikkelaar. Enige afhankelijkheid: elk seizoen wordt een nieuwe wedstrijdkalender gebruikt, die in Beheer moet worden toegevoegd. Zonder die stap blijven de wedstrijden leeg.',
      'De coördinatorrol blijft bij dezelfde persoon. Roosters en standaardschema\'s worden door de coördinator samengesteld.',
    ],
  },
];
