// matches.js — generated by the modularisation of index.html; see README for what lives where.
import { t } from './i18n.js';
import { S } from './state.js';
import { effectivePlanningDate, startOfWeek } from './dates.js';
import { db } from './data.js';
import { renderMyWeek } from './ui-myweek.js';
import { renderMatchesTab } from './ui-matches.js';
import { fam, seats } from './rides.js';
import { ensureDistances, hasApiKey, fetchWithTimeout } from './distance.js';
import { normalizeLocations } from './locations.js';
import { isMemberNow } from './coordinator.js';

export function activeMatchFeeds(){ return S.matchFeeds; }

// Team name for a calendar, always looked up live from the Beheer settings (by calendar ID),
// so renaming a team in Beheer immediately shows everywhere — also for stored carpools.
function feedLabel(calendarId){
  const f = calendarId && S.matchFeeds.find(x=>x.calendarId===calendarId);
  return f? (f.label||'') : '';
}

export function matchLabel(m){ return feedLabel(m && m.calendarId) || (m && m.teamLabel) || ''; }

// "TeamA-TeamB" — but team names can themselves contain a hyphen (e.g. "NFC O15-1",
// "AZ MO17-1" is a common Dutch youth-team numbering convention), so the real separator is
// specifically the hyphen immediately followed by a LETTER (the start of the next team's
// name) — a same-team numbering hyphen is always followed by a digit, never a letter.
export function analyzeMatch(summary){
  const sep = summary.match(/-(?=[A-Za-z])/);
  if(!sep) return {opponent:summary, isHome:null, home:summary, away:''};
  const home = summary.slice(0, sep.index).trim();
  const away = summary.slice(sep.index+1).trim();
  const homeIsAZ = /az/i.test(home), awayIsAZ = /az/i.test(away);
  if(homeIsAZ && !awayIsAZ) return {opponent:away, isHome:true, home, away};
  if(!homeIsAZ && awayIsAZ) return {opponent:home, isHome:false, home, away};
  return {opponent: awayIsAZ? home : away, isHome:homeIsAZ, home, away};
}

function idPart(s){ return String(s||'').replace(/[^A-Za-z0-9_-]/g,'_'); }

// Firestore document ID for a match's carpool: calendar ID + Google Calendar event ID.
export function matchSlug(m){
  if(m.calendarId && m.eventId) return 'ev_'+idPart(m.calendarId)+'__'+idPart(m.eventId);
  return legacyMatchSlug(m, matchLabel(m));
}

// Old documents (before IDs were used) were keyed on "teamname_starttime".
function legacyMatchSlug(m, label){ return (label+'_'+m.start.getTime()).toLowerCase().replace(/[^a-z0-9_]/g,''); }

// The stored carpool for a match: by ID first, then an old name-keyed document as fallback.
export function carpoolFor(m){
  const id = matchSlug(m);
  if(S.matchCarpools[id]) return {id, doc:S.matchCarpools[id]};
  // Same calendar + same kick-off, but a different event ID (Google can re-issue IDs when it
  // re-imports a calendar feed): still the same match.
  if(m.calendarId){
    const sameCal = Object.entries(S.matchCarpools).find(([,d])=>d && d.calendarId===m.calendarId && d.startMs===m.start.getTime());
    if(sameCal) return {id:sameCal[0], doc:sameCal[1]};
  }
  const candidates = [matchLabel(m), m.teamLabel].filter(Boolean);
  for(const label of candidates){
    const lid = legacyMatchSlug(m, label);
    const d = S.matchCarpools[lid];
    if(d && !d.eventId) return {id:lid, doc:d, legacy:true};
  }
  // Old document saved under a different (e.g. wrong) team name: accept it only when it is the
  // single old-style document with exactly this kick-off time, so it can't be mixed up.
  const sameTime = Object.entries(S.matchCarpools).filter(([,d])=>d && !d.eventId && d.startMs===m.start.getTime());
  if(sameTime.length===1) return {id:sameTime[0][0], doc:sameTime[0][1], legacy:true};
  return {id, doc:null};
}

export function matchesThisWeek(list){ const now=new Date(); const s=startOfWeek(effectivePlanningDate()); const e=new Date(s); e.setDate(s.getDate()+7); return list.filter(m=>m.start>=now && m.start<e).sort((a,b)=>a.start-b.start); }

// Wedstrijden tab: every match of the next 29 days is shown, but a carpool can be set up only for the
// first 8 days. Both windows are rolling (today through N-1 days out, inclusive) and deliberately NOT
// bound to calendar Sat/Sun, so "next Saturday" is always visible whatever day it is today.
export const MATCH_HORIZON_DAYS = 29;   // shown
export const MATCH_PLAN_DAYS = 8;       // a carpool can be set up

function matchesWithin(list, days){
  const now=new Date();
  const start=new Date(now); start.setHours(0,0,0,0);
  const end=new Date(start); end.setDate(start.getDate()+days);
  return list.filter(m=>m.start>=now && m.start<end).sort((a,b)=>a.start-b.start);
}
export function matchesNext8Days(list){ return matchesWithin(list, MATCH_PLAN_DAYS); }
export function matchesNext29Days(list){ return matchesWithin(list, MATCH_HORIZON_DAYS); }
// True when a carpool may be set up for this match (it is within the first 8 days).
export function isMatchPlannable(m){ return matchesNext8Days([m]).length===1; }
// The first day on which a carpool can be set up for a match that is still too far away.
export function plannableFrom(m){ const d=new Date(m.start); d.setHours(0,0,0,0); d.setDate(d.getDate()-(MATCH_PLAN_DAYS-1)); return d; }

async function fetchTeamMatches(feed){
  try{
    if(!db.calendarApiKey) throw new Error(t('matches.geen_api_key'));
    const timeMin = new Date(); timeMin.setDate(timeMin.getDate()-1);
    const timeMax = new Date(); timeMax.setDate(timeMax.getDate()+MATCH_HORIZON_DAYS+1);   // the Wedstrijden tab shows 29 days
    const url = `https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(feed.calendarId)}/events`
      + `?key=${encodeURIComponent(db.calendarApiKey)}&singleEvents=true&orderBy=startTime`
      + `&timeMin=${encodeURIComponent(timeMin.toISOString())}&timeMax=${encodeURIComponent(timeMax.toISOString())}&maxResults=50`;
    const res = await fetchWithTimeout(fetch, url);
    if(!res.ok){
      let detail='';
      try{ const body=await res.json(); detail = body && body.error && body.error.message ? ' — '+body.error.message : ''; }catch(e){}
      throw new Error(t('matches.http')+res.status+detail);
    }
    const data = await res.json();
    const events = (data.items||[]).map(ev=>{
      const startStr = ev.start && (ev.start.dateTime || ev.start.date);
      if(!startStr || !ev.summary) return null;
      // Google returns an ISO timestamp with its own explicit UTC offset already included
      // (the calendar's own Europe/Amsterdam timezone), so this is unambiguous regardless
      // of what timezone the viewing browser happens to be in.
      return { calendarId: feed.calendarId, eventId: ev.id||'', teamLabel: feed.label, summary: ev.summary, location: ev.location||'', start: new Date(startStr) };
    }).filter(Boolean);
    return { ok:true, events };
  }catch(e){ return { ok:false, error: (e&&e.message)||String(e) }; }
}

// ---------- Daily refresh ----------
// The team calendars are fetched from Google once per day: the first member who opens the app that day does it
// and stores the result in settings/matchCache. Everyone else reads that cache. A fetch also happens when the
// set of calendars changed (Beheer) or when the last fetch was partial (one team failed).
export const MATCH_RETRY_MS = 15*60*1000;   // after an automatic attempt: wait this long before trying again

// The calendar IDs as one comparable text. Renaming a team does not change it.
export function feedsSignature(feeds){ return (feeds||[]).map(f=>f && f.calendarId).filter(Boolean).sort().join(','); }

function sameLocalDay(a, b){ return new Date(a).toDateString()===new Date(b).toDateString(); }

// PURE. fetchedAt: ms of the last complete fetch (or null)   feedsSig / partial: what that fetch was for / whether a team failed
//       feeds: the calendars now in Beheer   lastAttempt: {at, sig} of the last automatic attempt in this session (or null)   now: ms
export function matchesNeedRefresh({ fetchedAt, feedsSig, partial, feeds, lastAttempt, now }){
  const sig = feedsSignature(feeds);
  const stale = !fetchedAt || !!partial || (feedsSig||'')!==sig || !sameLocalDay(fetchedAt, now);
  if(!stale) return false;
  // A failed fetch must not repeat every minute: same calendars + recent attempt = wait.
  if(lastAttempt && lastAttempt.sig===sig && now-lastAttempt.at<MATCH_RETRY_MS) return false;
  return true;
}

// The newest of: this session's own fetch, and what the database cache says.
function currentFreshness(){
  if(S.matchesFetchedAt && S.matchesFetchedAt>=(S.cachedMatchesAt||0))
    return { fetchedAt:S.matchesFetchedAt, feedsSig:S.matchesFeedsSig, partial:S.matchFetchFailedTeams.length>0 };
  return { fetchedAt:S.cachedMatchesAt, feedsSig:S.cachedMatchesFeedsSig, partial:S.cachedMatchesPartial };
}

// Called when the calendars or the cache arrive, when the app comes to the foreground, and once a minute
// (like checkWeekRollover). Fetches only when the data is not from today. Returns true when a fetch was started.
export function refreshMatchesIfStale(now=Date.now()){
  if(!S.matchFeedsLoaded || !S.matchCacheLoaded || !isMemberNow()) return false;   // wait until the coordinator's calendars and the cache are known
  const feeds = activeMatchFeeds();
  if(!matchesNeedRefresh({ ...currentFreshness(), feeds, lastAttempt:S.matchLastAttempt, now })) return false;
  S.matchLastAttempt = { at:now, sig:feedsSignature(feeds) };
  loadAllMatches();
  return true;
}

export async function loadAllMatches(){
  if(!S.matchFeedsLoaded) return; // wait for the coordinator's calendars; the snapshot calls this
  const seq = ++S.matchLoadSeq;
  const feeds = activeMatchFeeds().filter(f=>f.calendarId);
  const results = await Promise.all(feeds.map(fetchTeamMatches));
  if(seq!==S.matchLoadSeq) return; // a newer load was started meanwhile
  const failed = [];
  let combined = [];
  results.forEach((r,i)=>{ if(!r.ok) failed.push({label:feeds[i].label, error:r.error}); else combined = combined.concat(r.events); });
  if(combined.length || !S.matchFetchFailedTeams.length){
    S.matches = combined; S.matchesSource='live'; S.matchesFetchedAt=Date.now(); S.matchesFeedsSig=feedsSignature(feeds); S.matchFetchFailedTeams=failed;
    if(db){ try{ await db.doc("settings/matchCache").set({fetchedAt:Date.now(), feedsSig:feedsSignature(feeds), partial:failed.length>0, matches:combined.map(e=>({calendarId:e.calendarId,eventId:e.eventId,teamLabel:e.teamLabel,summary:e.summary,location:e.location,startMs:e.start.getTime()}))}); }catch(e){} }
  }
  renderMyWeek(); renderMatchesTab();
  calculateMatchDistances(combined);
}

export function currentMatchList(){
  if(S.matches.length || S.matchesSource==='live') return S.matches;
  return S.cachedMatches;
}

// ---------- Shared match-carpool rendering (Afwijking, Mijn week, Dagafwijking) ----------
// A stored matchCarpools doc carries its own denormalized match info — turn it back into the
// same shape as a fetched match so matchInfoHtml() can render both identically.
export function docToMatch(d){ return {calendarId:d.calendarId||'', eventId:d.eventId||'', teamLabel:d.teamLabel||'', summary:d.summary||'', location:d.location||'', start:new Date(d.startMs)}; }

// Stored match carpools (with at least one car) whose match is on the given calendar date.
export function matchCarpoolsOnDate(date){
  const key = date.toDateString();
  return Object.entries(S.matchCarpools)
    .filter(([,d])=>d && d.startMs && d.cars && d.cars.length && new Date(d.startMs).toDateString()===key)
    .sort((a,b)=>a[1].startMs-b[1].startMs);
}

// Every match-carpool car this family is involved in (as driver and/or via the daughter),
// from the start of today up to the end of the current planning week.
export function myMatchRides(myId){
  const from = new Date(); from.setHours(0,0,0,0);
  const to = startOfWeek(effectivePlanningDate()); to.setDate(to.getDate()+7);
  const out = [];
  Object.entries(S.matchCarpools).forEach(([slug,d])=>{
    if(!d || !d.startMs || d.startMs<from.getTime() || d.startMs>=to.getTime()) return;
    (d.cars||[]).forEach(c=>{
      const driving = c.driverFamilyId===myId;
      const daughter = (c.girlIds||[]).includes(myId);
      if(driving || daughter) out.push({slug, doc:d, car:c, driving, daughter});
    });
  });
  return out.sort((a,b)=>a.doc.startMs-b.doc.startMs || (a.car.departureTime||'').localeCompare(b.car.departureTime||''));
}

export function suggestedMatchDeparture(matchDate){
  const t = new Date(matchDate.getTime() - 210*60000); // 3.5 hours before
  return String(t.getHours()).padStart(2,'0')+':'+String(t.getMinutes()).padStart(2,'0');
}

// Capacity check for the "add car" form: compares the chosen passengers with the driver's
// passenger seats (capacity minus the driver). Only a warning — saving stays possible.
export function matchCarCapacityState(slug){
  const driverSel=document.getElementById('matchCarDriver_'+slug);
  const n=document.querySelectorAll('.matchCarGirlPick:checked').length;
  const driverId = driverSel && driverSel.value;
  const cap = driverId? seats(fam(driverId)) : null;
  return {n, cap, driverId, over: cap!=null && n>cap};
}

// US-21: calculates the projected distance of matches that do not have one yet (once per match, stored for everyone).
// Waits until the stored distances are loaded, so nothing is calculated twice. Returns the number of routes requested.
export async function calculateMatchDistances(list){
  if(!hasApiKey(S.orsApiKey) || !S.matchDistancesLoaded || !isMemberNow() || !list || !list.length) return 0;
  const cfg = normalizeLocations(S.locationsDoc);
  const bus = cfg.places.find(p=>p.id==='busstation');
  const originText = (bus && bus.address) || 'Busstation Aalsmeer, Aalsmeer, Nederland';
  const matches = list.map(m=>({ key:matchSlug(m), isHome:analyzeMatch(m.summary).isHome, location:m.location }));
  try{
    return await ensureDistances({
      matches, storedByKey:S.matchDistances, fixedKm:cfg.fixedKm, apiKey:S.orsApiKey, originText,
      fetchFn:(url,opts)=>fetch(url,opts),
      store: async (key,val)=>{
        S.matchDistances = {...S.matchDistances, [key]:val};
        try{ await db.doc("settings/matchDistances").set({[key]:val},{merge:true}); }catch(e){ /* not stored: it is calculated again next session */ }
        renderMyWeek(); renderMatchesTab();
      }
    });
  }catch(e){ return 0; }
}
