// rides.js — generated by the modularisation of index.html; see README for what lives where.
import { t } from './i18n.js';
import { S } from './state.js';
import { deviationKey, weekKeyDayIso } from './dates.js';
import { periodDayKey, periodEntryId, periodForDate, periodShiftId, periodWorkdays } from './period.js';
import { ovIds } from './ov.js';
import { esc } from './ui-common.js';
import { computeDepartureTime as pureComputeDepartureTime, minutesToTime as pureMinutesToTime, planAlternativeAssignments, planClusters as pureplanClusters, planPartialAssignment, planPrimaryAssignment, timeToMinutes as pureTimeToMinutes } from './planning.js';

// Day labels are always shown in capitals ("MA"); the keys themselves ("Ma") stay as stored data.
// A family's time for one day+direction; '' when the family, its schedule or that day is missing
// (e.g. a car that still lists a family that was deleted).
export function famTime(id,day,direction, st=S){ const sc=fam(id, st).schedule; return (sc && sc[day] && sc[day][direction]) || ''; }

export function activeDeviation(day,direction, st=S){
  const dev = st.deviations[deviationKey(day,direction)];
  return (dev && dev.weekKey===st.currentWeekKey && dev.cars && dev.cars.length) ? dev : null;
}

// The single source of truth for "what cars actually run today" — the default Rooster groups,
// unless a still-current-week deviation overrides them. Used by Mijn week, the Wijzigen editor
// and Rooster's "Deze week" view. Rooster's "Standaardrooster" view shows the default groups,
// and deviations never touch those.
export function effectiveCars(day,direction, st=S){
  const dev = activeDeviation(day,direction, st);
  if(dev) return dev.cars.map(c=>({...c}));
  const ps = periodShift(day,direction, st);
  if(ps) return ps.doc.cars.map(c=>({...c, girlIds:[...(c.girlIds||[])]}));
  return groupsFor(day,direction, st).map(([gid,g])=>({...g, baseGroupId:gid}));
}

// What a one-off change is compared with: the temporary rooster on a date where it applies, else the standard rooster.
export function baseCars(day,direction, st=S){
  const ps = periodShift(day,direction, st);
  return ps? ps.doc.cars : groupsFor(day,direction, st).map(([,g])=>g);
}

// ---------- Periode met andere tijden: the temporary rooster (see period.js) ----------
// The temporary rooster of one shift of the current planning week: only where the coordinator made it, and only for a date inside the
// period. Everything else (other dates, other weeks, no rooster made) runs on the standard rooster, exactly as before.
export function periodShift(day,direction, st=S){
  if(!st.periodCars) return null;
  const iso = weekKeyDayIso(st.currentWeekKey, day);
  const p = iso && periodForDate(st.periods, iso);   // the period that date belongs to: periods never share a day
  if(!p) return null;
  const id = periodShiftId(p, iso, direction), doc = st.periodCars[id];
  return doc && doc.periodFirstDay===p.firstDay && Array.isArray(doc.cars)? { id, iso, doc } : null;
}

// The time a family handed in for a date of the period ('' = does not ride that way). A family that handed in nothing keeps its standard time.
export function periodTimeFor(id, iso, direction, st=S){
  const p = periodForDate(st.periods, iso), entry = p && st.periodEntries && st.periodEntries[periodEntryId(p,id)];
  const d = entry && entry.days && entry.days[iso];
  if(d) return d.out? '' : (d[direction]||'');
  return famTime(id, periodDayKey(iso), direction, st);
}

// The time that counts for a shift of the current planning week: the handed-in time where the temporary rooster applies, else the standard one.
export function rideTime(id, day, direction, st=S){
  const ps = periodShift(day,direction, st);
  return ps? periodTimeFor(id, ps.iso, direction, st) : famTime(id, day, direction, st);
}

// Who needs a ride on a shift of the current planning week (Flex families never do).
export function girlsForRide(day,direction, st=S){
  return Object.entries(st.families).filter(([id,f])=>!isFlex(f) && rideTime(id,day,direction, st));
}

export function computeRideDeparture(day,direction,girlIds, st=S){
  const minutesList = girlIds.map(id=>pureTimeToMinutes(rideTime(id,day,direction, st)));
  return pureComputeDepartureTime(direction, minutesList, st.settings.travelLeadMinutes||60);
}

export function fam(id, st=S){return st.families[id]||{parentName:"?",girlName:"?",capacity:4,schedule:{},availability:{}};}

// "capacity" as entered/stored is the TOTAL car capacity including the driver's own seat.
// Every scheduling/display calculation needs the PASSENGER seat count, which is one less.
export function seats(f){ return Math.max(0, (f.capacity||0) - 1); }

export function girlName(id, st=S){ return esc(fam(id, st).girlName||fam(id, st).parentName||id); }
// Passengers are always listed A-Z. Drivers are NOT sorted with this: their order is the selection order.
const byNameNl = (a,b)=>a.localeCompare(b,'nl',{sensitivity:'base'});
export function sortGirlIds(ids, st=S){
  return [...(ids||[])].map(id=>[id, fam(id, st).girlName||fam(id, st).parentName||id]).sort((a,b)=>byNameNl(a[1],b[1])).map(x=>x[0]);
}
// Same for [id, family] entries (Beheer lists, checkbox rows).
export function sortFamEntriesByGirl(entries){
  return [...entries].sort((a,b)=>byNameNl(a[1].girlName||a[1].parentName||a[0], b[1].girlName||b[1].parentName||b[0]));
}

function shiftKeyOf(day,direction){ return day+'_'+direction; }

function shiftPriorityOf(day,direction,id, st=S){
  const map = st.shiftPriority[shiftKeyOf(day,direction)] || {};
  return map[id]!=null? map[id] : 999;
}

export function sortByShiftPriority(day,direction,entries, st=S){
  return [...entries].sort((a,b)=>shiftPriorityOf(day,direction,a[0], st)-shiftPriorityOf(day,direction,b[0], st));
}

// Standaard-beschikbaar drivers are preferred as a whole GROUP over back-up-only drivers when
// actually filling a shift — Selectievolgorde rank only decides order WITHIN each tier. This is
// deliberately separate from the reserve-list display, which stays pure Selectievolgorde order
// regardless of standaard/back-up (that distinction doesn't matter for "who could step in").
function sortByAvailabilityTier(day,direction,entries, st=S){
  return [...entries].sort((a,b)=>{
    const aTier = isStandaardAvailable(a[1],day,direction)? 0 : 1;
    const bTier = isStandaardAvailable(b[1],day,direction)? 0 : 1;
    if(aTier!==bTier) return aTier-bTier;
    return shiftPriorityOf(day,direction,a[0], st)-shiftPriorityOf(day,direction,b[0], st);
  });
}

function backupField(direction){ return direction==='heen' ? 'backupHeen' : 'backupTerug'; }

function isStandaardAvailable(f,day,direction){
  const a=(f.availability&&f.availability[day])||{};
  return !!a[direction];
}

export function isAvailable(f,day,direction){
  const a=(f.availability&&f.availability[day])||{};
  return !!(a[direction] || a[backupField(direction)]);
}

export function plainGirlName(id, st=S){ const f=fam(id, st); return f.girlName||f.parentName||id; }

// Flex families ride only on days they sign up for: never auto-planned, not as passenger and not as driver.
export function isFlex(f){ return !!f && f.familyType==='flex'; }

// A Flex driver is a player who drives herself: marked "speelster-chauffeur" wherever her name shows.
export function plainDriverName(id, st=S){
  if(!id) return t('driver.none');
  const f = fam(id, st);
  return (f.parentName||'?') + (isFlex(f)? ' ('+t('flex.speelsterChauffeur')+')' : '');
}
// Same, as HTML: escaped name plus a small badge for a Flex driver.
export function driverNameHtml(id, st=S){
  if(!id) return esc(t('driver.none'));
  const f = fam(id, st);
  return esc(f.parentName||'?') + (isFlex(f)? ` <span class="badge flexBadge">${esc(t('flex.speelsterChauffeur'))}</span>` : '');
}

// ---------- Rooster tab ----------
export function girlsFor(day,direction, st=S){
  return Object.entries(st.families).filter(([id,f])=>!isFlex(f) && f.schedule && f.schedule[day] && f.schedule[day][direction]);
}

export function groupsFor(day,direction, st=S){
  return Object.entries(st.groups).filter(([id,g])=>g.day===day && g.direction===direction);
}

export function alreadyGrouped(day,direction, st=S){
  const ids=new Set();
  groupsFor(day,direction, st).forEach(([id,g])=>g.girlIds.forEach(gid=>ids.add(gid)));
  return ids;
}

export function eligibleDrivers(day,direction,count, st=S){
  return sortByShiftPriority(day,direction, Object.entries(st.families).filter(([id,f])=>
    !isFlex(f) && isAvailable(f,day,direction) && seats(f)>=count
  ), st);
}

export function availableDrivers(day,direction, st=S){
  return Object.entries(st.families).filter(([id,f])=> !isFlex(f) && isAvailable(f,day,direction));
}

// timeToMinutes/minutesToTime/computeDepartureTime/planClusters/planPrimaryOption/planOptions
// are now thin wrappers around the tested, standalone planning.js module (see that file's
// own test suite — planning.test.js — for the actual algorithm's correctness guarantees).
export function timeToMinutes(t){ return pureTimeToMinutes(t); }

function minutesToTime(min){ return pureMinutesToTime(min); }

export function computeDepartureTime(day,direction,girlIds, st=S){
  const minutesList = girlIds.map(id=>pureTimeToMinutes(famTime(id,day,direction, st)));
  return pureComputeDepartureTime(direction, minutesList, st.settings.travelLeadMinutes||60);
}

// timeOf (optional): where a girl's time comes from; the standard schedule unless the temporary rooster is being planned.
function planClusters(day,direction,list, st=S, timeOf){
  const girlsInput = list.map(([id,f])=>({id, min: pureTimeToMinutes(timeOf? timeOf(id) : f.schedule[day][direction])}));
  const driverSeats = availableDrivers(day,direction, st).map(([id,f])=>seats(f));
  const togetherRules = (st.prefs.rules||[]).filter(r=>r.type==='together');
  const preferRules = (st.prefs.rules||[]).filter(r=>r.type==='prefer');
  const gapLimitMinutes = (st.settings.gapThresholdHours||3)*60;
  const prefWindowMinutes = st.settings.prefWindowMinutes!=null? st.settings.prefWindowMinutes : 30;
  return pureplanClusters({ girls: girlsInput, driverSeats, gapLimitMinutes, togetherRules, preferRules, prefWindowMinutes });
}

function planPrimaryOption(day,direction,list, st=S){
  const clusters = planClusters(day,direction,list, st);
  if(!clusters.length) return null;
  const priorityDrivers = sortByAvailabilityTier(day,direction, availableDrivers(day,direction, st), st)
    .map(([id,f])=>({id, seats: seats(f)}));
  const assignment = planPrimaryAssignment(clusters, priorityDrivers);
  if(!assignment) return null;
  const label = assignment.map(a=>esc(fam(a.driverId, st).parentName)).join(' &amp; ');
  return {label, assignment};
}

export function planOptions(day,direction,list, st=S){
  const clusters = planClusters(day,direction,list, st);
  const availForAlts = availableDrivers(day,direction, st).map(([id,f])=>({id, seats: seats(f)}));
  const rawAlts = planAlternativeAssignments(clusters, availForAlts);
  let opts = rawAlts.map(assignment=>({
    label: assignment.map(a=>esc(fam(a.driverId, st).parentName)).join(' &amp; '),
    assignment
  }));
  opts.sort((a,b)=>{
    const pa=a.assignment.reduce((s,x)=>s+shiftPriorityOf(day,direction,x.driverId, st),0);
    const pb=b.assignment.reduce((s,x)=>s+shiftPriorityOf(day,direction,x.driverId, st),0);
    return pa-pb;
  });
  const primary = planPrimaryOption(day,direction,list, st);
  if(primary){
    const key=a=>a.assignment.map(x=>x.driverId).sort().join('+');
    opts = opts.filter(o=>key(o)!==key(primary));
    opts.unshift(primary);
  }
  return opts;
}

// Girls with a time on this day/direction who are in no car. mode 'week' = this week's real
// rides (Wijzigingen applied); 'standard' = the standard schedule.
export function unplacedFor(day,direction,mode, st=S){
  const cars = mode==='week'? effectiveCars(day,direction, st) : groupsFor(day,direction, st).map(([,g])=>g);
  const riders = mode==='week'? girlsForRide(day,direction, st) : girlsFor(day,direction, st);
  const placed = new Set(cars.flatMap(c=>c.girlIds||[]));
  // A girl marked "Rijdt niet mee" is out of the planning for that ride.
  const ov = mode==='week'? new Set(ovGirlsFor(day, st, direction)) : new Set();
  return riders.filter(([id])=>!placed.has(id) && !ov.has(id));
}

// Girls marked "Rijdt niet mee" on this shift of the current week (US-06). direction defaults to 'terug'.
export function ovGirlsFor(day, st=S, direction='terug'){
  const dev = st.deviations[deviationKey(day,direction)];
  return dev && dev.weekKey===st.currentWeekKey ? ovIds(dev) : [];
}

export function carsCountFor(day,mode, st=S){
  return ['heen','terug'].reduce((n,d)=> n + (mode==='week'
    ? effectiveCars(day,d, st).filter(c=>(c.girlIds||[]).length).length
    : groupsFor(day,d, st).length), 0);
}

// Reserve drivers are a TRIP-wide backup pool, shown once per trip: everyone available for this
// trip (standaard or back-up) who isn't already driving it and has room for at least the
// SMALLEST car of the trip, so they could take over at least one of the rides.
// (Previously the LARGEST car's size was required, which hid every reserve on trips with one
// big car — e.g. a 5- or 6-passenger car — even when 4-seat back-ups could cover the other car.)
export function tripReserveIds(day,direction,cars, st=S){
  const sizes = cars.map(c=>(c.girlIds||[]).length).filter(n=>n>0);
  if(!sizes.length) return [];
  const smallest = Math.min(...sizes);
  const assigned = new Set(cars.map(c=>c.driverFamilyId).filter(Boolean));
  return eligibleDrivers(day,direction,smallest, st).map(([id])=>id).filter(id=>!assigned.has(id));
}

// ---------- The temporary rooster by date (Rooster, third view): independent of the current planning week ----------
// Who needs a ride on a date of the period, and at what time: the handed-in time, else the standard time.
export function periodRidersFor(iso,direction, st=S){
  return Object.entries(st.families).filter(([id,f])=>!isFlex(f) && periodTimeFor(id,iso,direction, st));
}

// The cars of one made shift, or null while that shift has no temporary rooster yet.
export function periodCarsFor(iso,direction, st=S){
  const p = periodForDate(st.periods, iso), doc = p && st.periodCars && st.periodCars[periodShiftId(p,iso,direction)];
  return doc && doc.periodFirstDay===p.firstDay && Array.isArray(doc.cars)? doc.cars : null;
}

// Riders of a made shift that are in no car (a shift that is not made has nobody "unplaced").
export function periodUnplacedFor(iso,direction, st=S){
  const cars = periodCarsFor(iso,direction, st);
  if(!cars) return [];
  const placed = new Set(cars.flatMap(c=>c.girlIds||[]));
  return periodRidersFor(iso,direction, st).filter(([id])=>!placed.has(id));
}

export function periodDeparture(iso,direction,girlIds, st=S){
  return pureComputeDepartureTime(direction, girlIds.map(id=>pureTimeToMinutes(periodTimeFor(id,iso,direction, st))), st.settings.travelLeadMinutes||60);
}

// Drivers who could drive `count` passengers on a date of the period: the standard availability of that weekday, as everywhere.
export function periodEligibleDrivers(iso,direction,count, st=S){
  const day = periodDayKey(iso);
  return day? eligibleDrivers(day,direction,count, st) : [];
}

// The automatic proposal for one shift ("auto-indeling"): the same planning as the standard rooster, with the handed-in times.
// -> { cars: [{ driverFamilyId, girlIds, departureTime }], unplaced: [girlId] }; riders no driver can take are handed back as unplaced.
export function planPeriodShift(iso,direction, st=S){
  const day = periodDayKey(iso);
  const list = day? periodRidersFor(iso,direction, st) : [];
  if(!list.length) return { cars:[], unplaced:[] };
  const timeOf = id => periodTimeFor(id,iso,direction, st);
  const clusters = planClusters(day,direction,list, st, timeOf);
  const drivers = sortByAvailabilityTier(day,direction, availableDrivers(day,direction, st), st).map(([id,f])=>({id, seats:seats(f)}));
  const r = planPartialAssignment(clusters, drivers);
  return {
    cars: r.assigned.map(a=>({ driverFamilyId:a.driverId, girlIds:a.girlIds, departureTime:periodDeparture(iso,direction,a.girlIds, st) })),
    unplaced: r.unassigned.flat(),
  };
}

// Every shift of one period, planned: [{ iso, direction, cars, unplaced }] for each workday of the period, heen and terug.
export function planPeriodRooster(st=S, p){
  if(!p) return [];
  return periodWorkdays(p.firstDay, p.lastDay).flatMap(iso => ['heen','terug'].map(direction => ({ iso, direction, ...planPeriodShift(iso,direction, st) })));
}

// The families as the planning must see them for one shift of the current planning week: with the handed-in times where the temporary
// rooster applies (the impact preview plans with family.schedule), else the families themselves.
export function shiftFamilies(day,direction, st=S){
  const ps = periodShift(day,direction, st);
  if(!ps) return st.families;
  return Object.fromEntries(Object.entries(st.families).map(([id,f])=>{
    const time = periodTimeFor(id, ps.iso, direction, st);
    const schedule = {...(f.schedule||{}), [day]: {...((f.schedule||{})[day]||{}), [direction]: time}};
    return [id, {...f, schedule}];
  }));
}
