// state.js — all shared mutable app state lives on S (one object, so every module sees the same values).
export const S = {
  scheduleDay: null,
  roosterMode: 'week',
  pendingSwapRequest: null,
  me: null,
  canEdit: false,
  coordinatorExists: false,
  coordinatorConfig: null,
  appReady: false,
  impersonateFamilyId: null,
  families: {},
  groups: {},
  links: {},
  deviations: {},
  linksLoaded: false,
  invitesByCode: {},
  inviteByFamily: {},
  lastUpdateRooster: null,
  lastUpdateDeviation: null,
  serverSchedules: {},
  lastPendingChangeCount: null,
  matchFeeds: [],
  matchFeedsLoaded: false,
  matchFeedsSig: null,
  matchLoadSeq: 0,
  matches: [],
  matchesSource: null,
  matchesFetchedAt: null,
  matchFetchFailedTeams: [],
  cachedMatches: [],
  cachedMatchesAt: null,
  matchCarpools: {},
  weekendMatchBySlug: {},
  openMatchCarpoolForm: null,
  currentWeekKey: null,
  settings: {gapThresholdHours:3, travelLeadMinutes:60, prefWindowMinutes:30, parentPrefWindowMinutes:60},
  prefs: {rules:[]},
  shiftPriority: {},
  deferredInstallPrompt: null,
  appIsInstalled: false,
  dataUnsubs: [],
  linksCollUnsub: null,
  invitesUnsub: null,
  migratingSecrets: false,
  migrationFailed: false,
  hashTabApplied: false,
  defaultTabChosen: false,
  formSelectedDay: {me:'Ma', coord:'Ma'},
  deviationDay: null,
  weekschemaWarn: false,
  lastDeviationEditDay: null,
  coordEditId: undefined,
  selectedShiftKey: 'Ma_heen',
};
