// texts-nl.js — every piece of Dutch text the app shows. Keys are grouped by area (wa = WhatsApp messages,
// dir = travel directions, toast = short pop-up messages, ...). Values may contain {placeholders}.
export default {
  'meta.locale': 'nl-NL',

  // Travel directions (one wording everywhere in the app)
  'dir.heen': 'Heen · Aalsmeer → Alkmaar',
  'dir.terug': 'Terug · Alkmaar → Aalsmeer',

  // Names
  'driver.none': 'nog geen chauffeur',
  'ask.unknownTime': '?',

  // WhatsApp — generic update
  'wa.generic': 'Het schema is bijgewerkt voor {days}. Zie Mijn week voor de impact: {url}',
  'wa.thisWeek': 'deze week',
  'wa.and': ' en ',

  // WhatsApp — Mijn week (one line per day for one family's daughter)
  'wa.my.header': 'Carpool deze week – {name}:',
  'wa.my.line': '{day}{changed} — heen: {heen} | terug: {terug}',
  'wa.my.changed': ' (gewijzigd)',
  'wa.my.notPlanned': '{time} (nog niet ingepland)',
  'wa.my.with': '{time} met {driver}',
  'wa.my.none': 'Geen ritten ingesteld deze week.',
  'wa.my.match': '{day} — wedstrijd {team} vs {opponent}: vertrek {time} met {driver}',

  // WhatsApp — one day's full schedule (Wijzigen)
  'wa.day.title': 'Aangepast schema {dayLabel} {date}:',
  'wa.day.adapted': ' (aangepast)',
  'wa.day.noRides': '• geen ritten',
  'wa.day.car': '• {time} – {driver}: {girls}',

  // WhatsApp — "can you drive / you are driving" asks from the Rooster
  'wa.ask.reserve': 'Hi! Zou jij de rit {direction} van {date} om {time} kunnen doen?',
  'wa.ask.reserve.heen': 'heen',
  'wa.ask.reserve.terug': 'terug',
  'wa.ask.driver': 'Hi! Je rijdt de rit van {date} om {time}. ',
  // ---- Texts extracted from the original screens (generated once; edit freely) ----
  // app
  "app.niet_verbonden": "Niet verbonden.",
  "app.fout_bij_laden_koppeling": "Fout bij laden koppeling: ",
  "app.kon_niet_live_verbinden": "Kon niet live verbinden: ",
  // beheer
  "beheer.nog_geen_gezinnen": "Nog geen gezinnen.",
  "beheer.ouder": "Ouder",
  "beheer.span_class_muted_span": "<span class=\"muted\">–</span>",
  "beheer.groen_vlak_standaard_beschikbaar": "groen vlak = standaard beschikbaar.",
  "beheer.grijs_cijfer_back_up_indien": "grijs cijfer = back-up (indien nodig). Cijfer = plek voor passagiers (niet de totale autocapaciteit). H = heen, T = terug.",
  "beheer.of": " of ",
  "beheer.voorkeur_verwijderen": "Voorkeur verwijderen",
  "beheer.verwijder": "Verwijder",
  "beheer.nog_geen_voorkeuren": "Nog geen voorkeuren.",
  "beheer.samen_reizen": "Samen reizen",
  "beheer.moeten_altijd_samen_in_1": "(moeten altijd samen in 1 auto als het even kan):",
  "beheer.toevoegen": "+ Toevoegen",
  "beheer.voorkeur": "Voorkeur",
  "beheer.moet_met_minstens_een_van": "(moet met minstens één van de gekozen meiden):",
  "beheer.wie": "Wie",
  "beheer.bij_voorkeur_met_kies_een": "Bij voorkeur met (kies één of meer)",
  "beheer.span_class_muted_nog_geen": "<span class=\"muted\">Nog geen meiden.</span>",
  "beheer.heen": " – Heen",
  "beheer.terug": " – Terug",
  "beheer.bepaal_per_shift_in_welke": "Bepaal per shift in welke volgorde beschikbare chauffeurs worden voorgesteld.",
  "beheer.shift": "Shift",
  "beheer.geen_beschikbare_chauffeurs_voor_deze": "Geen beschikbare chauffeurs voor deze shift.",
  "beheer.pl": "pl.)",
  "beheer.pl_back_up": "pl., back-up)",
  "beheer.volgorde_opgeslagen": "Volgorde opgeslagen ✓",
  "beheer.deze_pagina_is_alleen_voor": "Deze pagina is alleen voor de coördinator.",
  "beheer.mogelijk_dubbele_gezinnen_controleer_en": "Mogelijk dubbele gezinnen — controleer en verwijder de onjuiste:",
  "beheer.wijzig": "Wijzig",
  "beheer.testweergave_als_deze_ouder": "Testweergave als deze ouder",
  "beheer.span_class_badge_gekoppeld_span": "<span class=\"badge\">gekoppeld</span>",
  "beheer.span_class_badge_rec_coordinator": "<span class=\"badge rec\">COÖRDINATOR</span>",
  "beheer.geen": "Geen",
  "beheer.en": " en ",
  "beheer.deze_ouder": "deze ouder",
  "beheer.nog_geen_gezinnen_toegevoegd": "Nog geen gezinnen toegevoegd.",
  "beheer.onderdelen": "Onderdelen",
  "beheer.chip_gezinnen": "Gezinnen",
  "beheer.chip_periodes": "Periodes",
  "beheer.chip_berichten": "Berichten",
  "beheer.chip_koppelingen": "Koppelingen",
  "beheer.sec_gezinnen": "Gezinnen en rooster",
  "beheer.sec_periodes": "Periodes en planning",
  "beheer.sec_berichten": "Berichten",
  "beheer.sec_koppelingen": "Koppelingen en data",
  "ridelog.title": "Gereden shifts",
  "ridelog.intro": "Hoe vaak elk gezin heeft gereden. Een shift telt pas mee als hij is geweest; elke auto telt apart (heen en terug). De telling begint bij de eerste keer dat deze functie draaide.",
  "ridelog.empty": "Er is nog niets vastgelegd. Shifts komen hier te staan zodra ze zijn geweest en jij de app opent.",
  "ridelog.per_month": "Per maand",
  "ridelog.per_year": "Per jaar",
  "ridelog.prev": "Vorige",
  "ridelog.next": "Volgende",
  "ridelog.pick_year": "Kies een jaar",
  "ridelog.col_family": "Gezin",
  "ridelog.col_heen": "Heen",
  "ridelog.col_terug": "Terug",
  "ridelog.col_total": "Totaal",
  "ridelog.col_year": "Jaar",
  "ridelog.summary": "{p1} shifts gereden · gemiddeld {p2} per gezin · minst {p3}, meest {p4}",
  "ridelog.idle": "{p1} gezinnen nog niet gereden",
  "ridelog.export_year": "Export {p1} (CSV)",
  "ridelog.export_all": "Export alle ritten (CSV)",
  "ridelog.exported": "Bestand gemaakt",
  "ridelog.hint": "Tik op een gezin om te zien welke shifts zijn gereden.",
  "ridelog.open_family": "Toon shifts van {p1}",
  "ridelog.all_button": "Alle shifts bekijken",
  "ridelog.all_title": "Alle shifts",
  "ridelog.all_summary": "{p1} shifts · nieuwste eerst",
  "ridelog.family_summary": "{p1} shifts · {p2} heen · {p3} terug",
  "ridelog.list_head": "Gereden shifts (nieuwste eerst)",
  "ridelog.none_in_period": "Geen shifts in deze periode.",
  "ridelog.dir_heen": "heen",
  "ridelog.dir_terug": "terug",
  "ridelog.girls": "{p1} meiden",
  "ridelog.girls_one": "1 meid",
  "ridelog.logged": "gelogd {p1}",
  "ridelog.remove": "Verwijder shift",
  "ridelog.remove_label": "Verwijder shift {p1}, {p2}, {p3}",
  "ridelog.remove_title": "Deze shift verwijderen?",
  "ridelog.remove_text": "{p1} gaat daarna van {p2} naar {p3} shifts in {p4}. De shift telt niet meer mee en komt niet vanzelf terug in de telling. Je kunt hem altijd terugzetten.",
  "ridelog.removed_head": "Verwijderd ({p1})",
  "ridelog.removed_note": "telt niet mee",
  "ridelog.restore": "Terugzetten",
  "ridelog.removed_toast": "Shift verwijderd",
  "ridelog.restored_toast": "Shift teruggezet",
  "ridelog.save_failed": "Opslaan mislukt. Probeer het opnieuw.",
  "beheer.attn_titel": "Om te checken ({p1})",
  "beheer.attn_zonder_code": "Zonder code: {p1}",
  "beheer.attn_zonder_telefoon": "Zonder telefoonnummer: {p1}",
  "beheer.attn_dubbel": "Dubbel gezin: {p1} ({p2}×)",
  "beheer.attn_kalender_mislukt": "Kalender mislukt: {p1}",
  "beheer.gezinnen_beheren": "Gezinnen beheren",
  "beheer.vul_of_wijzig_gegevens_namens": "Vul of wijzig gegevens namens een andere ouder. Telefoonnummers en uitnodigingscode staan onder \"Wijzig\", net als de coördinator-koppeling. Het oog-icoon toont de app zoals deze ouder hem ziet.",
  "beheer.nieuw_gezin_toevoegen": "+ Nieuw gezin toevoegen",
  "beheer.selectievolgorde_per_shift": "Selectievolgorde per shift",
  "beheer.reisvoorkeuren": "Reisvoorkeuren",
  "beheer.wie_er_logistiek_het_beste": "Wie er logistiek het beste samen in 1 auto kan; wordt meegewogen bij het opsplitsen in auto's.",
  "beheer.beschikbaarheid_chauffeurs_weekoverzicht": "Beschikbaarheid chauffeurs (weekoverzicht)",
  "beheer.planning_instellingen": "Planning-instellingen",
  "beheer.deze_regels_bepalen_hoe_combinaties": "Deze regels bepalen hoe combinaties in het Rooster worden voorgesteld. Wijzigingen worden automatisch opgeslagen.",
  "beheer.max_tijdsverschil_voor_1_auto": "Max. tijdsverschil voor 1 auto (uur)",
  "beheer.rijtijd_aalsmeer_alkmaar_min_vertrektijd": "Rijtijd Aalsmeer→Alkmaar (min, vertrektijd heen)",
  "beheer.marge_reisvookeuren_min": "Marge reisvookeuren (min)",
  "beheer.max_wachttijd_om_met_eigen": "Max. wachttijd om met eigen ouder te rijden (min)",
  "beheer.wedstrijdkalenders_google_calendar": "Wedstrijdkalenders (Google Calendar)",
  "beheer.deze_agenda_s_voeden_wedstrijden": "Deze agenda's voeden \"Wedstrijden deze week\" (Mijn week) en het tabblad Wedstrijden (29 dagen vooruit). Elke agenda moet openbaar (\"Make available to public\") staan — Google Calendar → tandwiel bij de agenda → Instellingen en delen → Toegangsrechten.",
  "beheer.nieuwe_kalender_toevoegen": "+ Nieuwe kalender toevoegen",
  "beheer.nu_verversen": "Nu verversen",
  "beheer.meldingen_bij_gewijzigde_tijden": "Meldingen bij gewijzigde tijden",
  "beheer.als_een_ouder_de_aankomst": "Als een ouder de aankomst- of ophaaltijd van een dochter aanpast, zie je dat bovenaan het Rooster (met een teller op het Rooster-tabje). Zet hieronder ook meldingen van je browser aan om een seintje te krijgen terwijl de app open staat op de achtergrond.",
  "beheer.naam": "Naam",
  "beheer.calendar_id": "Calendar ID",
  "beheer.xxxx_group_v_calendar_google": "xxxx@group.v.calendar.google.com",
  "beheer.verwijder_kalender": "Verwijder kalender",
  "beheer.laatst_opgehaald": "Laatst opgehaald:",
  "beheer.mislukt": " — mislukt: ",
  "beheer.browsermeldingen_staan_aan_op_dit": "Browsermeldingen staan aan op dit apparaat.",
  "beheer.browsermeldingen_zijn_geblokkeerd_zet_ze": "Browsermeldingen zijn geblokkeerd — zet ze aan in de instellingen van je browser.",
  "beheer.browsermeldingen_aanzetten": "Browsermeldingen aanzetten",
  "beheer.deze_browser_ondersteunt_geen_meldingen": "Deze browser ondersteunt geen meldingen.",
  "beheer.kies_minstens_2_meiden": "Kies minstens 2 meiden.",
  "beheer.toegevoegd": "Toegevoegd ✓",
  "beheer.kies_een_meisje_en_minstens": "Kies een meisje en minstens 1 voorkeur.",
  "beheer.verwijderen_mislukt": "Verwijderen mislukt: ",
  "beheer.zeker_nogmaals_klikken": "Zeker? Nogmaals klikken",
  "beheer.verwijderd": "Verwijderd ✓",
  "beheer.wedstrijden_verversen": "Wedstrijden verversen…",
  "beheer.fout_bij_koppelen_knoppen": "Fout bij koppelen knoppen: ",
  "beheer.span_class_muted_nog_geen_2": "<span class=\"muted\">Nog geen coördinator</span>",
  "beheer.coordinator_intrekken": "Coördinator intrekken",
  "beheer.maak_coordinator": "Maak coördinator",
  "beheer.maak_coordinator_2": " Maak coördinator",
  "beheer.uitnodigingscode_meerdere_mensen_kunnen_dezelfde": "Uitnodigingscode (meerdere mensen kunnen dezelfde code gebruiken)",
  "beheer.nieuwe_code": "Nieuwe code",
  "beheer.sluiten": "Sluiten",
  "beheer.wijzigingen_worden_automatisch_opgeslagen": "Wijzigingen worden automatisch opgeslagen.",
  "beheer.nieuw_gezin_toevoegen_2": "Nieuw gezin toevoegen",
  "beheer.bewerken": "Bewerken: ",
  "beheer.let_op_jij_bent_hier": "Let op: jij bent hier zelf niet aan gekoppeld — klik nogmaals om toch door te gaan",
  "beheer.zeker_de_coordinator_rol_gaat": "Zeker? De coördinator-rol gaat dan alleen nog via dit apparaat",
  "beheer.gezien": "Gezien",
  "beheer.door": "door ",
  "beheer.gewijzigde_tijden": "Gewijzigde tijden (",
  "beheer.deze_ouders_hebben_hun_aankomst": "Deze ouders hebben hun aankomst- of ophaaltijden aangepast. Controleer het rooster en markeer ze daarna als gezien.",
  "beheer.alles_gezien": "Alles gezien",
  "beheer.zeker_klik_nogmaals": "Zeker? Klik nogmaals",
  "beheer.van": " van ",
  "beheer.az_carpool": "AZ Carpool",
  // common
  "common.annuleren": "Annuleren",
  "common.laatst_bijgewerkt_door": "Laatst bijgewerkt door:",
  "common.licht_thema_aanzetten": "Licht thema aanzetten",
  "common.donker_thema_aanzetten": "Donker thema aanzetten",
  "common.installeer_de_app": "Installeer de app",
  "common.zet_az_carpool_op_je": "Zet AZ Carpool op je beginscherm voor snelle toegang, net als een echte app.",
  "common.installeer_app": "Installeer app",
  "common.zet_az_carpool_op_je_2": "Zet AZ Carpool op je beginscherm: tik onderin Safari op het deel-icoon, kies daarna",
  "common.zet_op_beginscherm": "\"Zet op beginscherm\"",
  "common.geen_verbinding": "Geen verbinding",
  "common.kan_geen_verbinding_maken_met": "Kan geen verbinding maken met de database. Dit betekent meestal dat het Firebase-configuratieblok bovenaan het bestand nog niet is ingevuld, of dat er geen internetverbinding is.",
  "common.foutmelding": "Foutmelding:",
  "common.coordinator": " (Coördinator)",
  "common.nog_niet_gekoppeld_ga_naar": "Nog niet gekoppeld — vul je telefoonnummer en code in",
  // coordinator
  "coordinator.coordinator": "Coördinator",
  // data
  "data.fout_bij_laden_gezinnen": "Fout bij laden gezinnen: ",
  "data.fout_bij_laden_rooster": "Fout bij laden rooster: ",
  "data.fout_bij_laden_instellingen": "Fout bij laden instellingen: ",
  "data.fout_bij_laden_voorkeuren": "Fout bij laden voorkeuren: ",
  "data.fout_bij_laden_prioriteit": "Fout bij laden prioriteit: ",
  "data.fout_bij_laden_wijzigingen": "Fout bij laden wijzigingen: ",
  "data.uitnodigingscodes_beveiligd": "Uitnodigingscodes beveiligd ✓",
  "data.migratie_uitnodigingscodes_mislukt": "Migratie uitnodigingscodes mislukt: ",
  "data.geen_verbinding_met_opslag": "Geen verbinding met opslag.",
  "data.opslaan_mislukt": "Opslaan mislukt: ",
  "data.coordinator_rol_nu_alleen_via": "Coördinator-rol nu alleen via dit apparaat",
  "data.coordinator_ingesteld": "Coördinator ingesteld ✓",
  "data.mislukt": "Mislukt: ",
  "data.let_op_er_bestaat_al": "Let op: er bestaat al een gezin met de naam '",
  "data.controleer_op_dubbelen": "' — controleer op dubbelen.",
  "data.opgeslagen": "Opgeslagen ✓",
  "data.code_alleen_letters_cijfers_en": "Code: alleen letters, cijfers en '-', 4–32 tekens.",
  "data.deze_code_is_al_in": "Deze code is al in gebruik bij een ander gezin — kies een andere.",
  "data.gemarkeerd_als_gezien": "Gemarkeerd als gezien ✓",
  "data.kon_groep_niet_opslaan_alleen": "Kon groep niet opslaan (alleen coördinator kan bewerken): ",
  "data.selecteer_minstens_1_dochter": "Selecteer minstens 1 dochter.",
  // deviation
  "deviation.nog_geen_chauffeur": "nog geen chauffeur",
  "deviation.meer_passagiers_dan_plekken": "Meer passagiers dan plekken",
  "deviation.verwijder_carpool": "Verwijder carpool",
  "deviation.geen_passagiers": "geen passagiers",
  "deviation.p_class_muted_style_font": "<p class=\"muted\" style=\"font-size:12px;margin:4px 0 0\">Nog geen carpool ingesteld.</p>",
  "deviation.chauffeur": "Chauffeur",
  "deviation.kies": "-- kies --",
  "deviation.welke_passagiers": "Welke passagiers?",
  "deviation.vertrektijd": "Vertrektijd",
  "deviation.opslaan": "Opslaan",
  "deviation.auto_toevoegen": "+ Auto toevoegen",
  "deviation.zet_een_carpool_op_voor": "Zet een carpool op voor een wedstrijd. Iedereen kan dit doen en aanpassen",
  "deviation.kies_een_chauffeur": "Kies een chauffeur.",
  "deviation.kies_minstens_1_dochter": "Kies minstens 1 dochter.",
  "deviation.toch_opslaan": "Toch opslaan",
  "deviation.kon_deze_wedstrijd_niet_vinden": "Kon deze wedstrijd niet vinden — herlaad de pagina.",
  "deviation.carpool_toegevoegd": "Carpool toegevoegd ✓",
  "deviation.deel_update_via_whatsapp": "Deel update via WhatsApp",
  "deviation.wijzigen": "Wijzigen",
  "deviation.kon_je_account_niet_herkennen": "Kon je account niet herkennen. Herlaad de pagina.",
  "deviation.wijzigingen": "Wijzigingen ·",
  "deviation.eenmalige_ritaanpassing_voor_deze_week": "Eenmalige ritaanpassing voor deze week (ziek, rijbeurt ruilen, etc). Het standaardrooster blijft intact; wijzigingen worden elk weekend automatisch gewist.",
  "deviation.kies_een_dag": "Kies een dag",
  "deviation.gewijzigd": ", gewijzigd",
  "deviation.wedstrijdcarpool": ", wedstrijdcarpool",
  "deviation.span_class_devdaydot_aria_hidden": "<span class=\"devDayDot\" aria-hidden=\"true\"></span>",
  "deviation.wedstrijdcarpool_op_deze_dag": "Wedstrijdcarpool op deze dag",
  "deviation.deze_week_gewijzigd": "= deze week gewijzigd",
  "deviation.wijziging": "Wijziging —",
  "deviation.andere_dag": "Andere dag",
  "deviation.wijzigingen_hier_gelden_alleen_voor": "Wijzigingen hier gelden alleen voor",
  "deviation.deze_week_en_verdwijnen_dit": "deze week en verdwijnen dit weekend vanzelf.",
  "deviation.wedstrijdcarpool_2": "Wedstrijdcarpool",
  "deviation.alleen_lezen": "Alleen lezen",
  "deviation.extra_ritten_naar_een_wedstrijd": "Extra ritten naar een wedstrijd op deze dag.",
  "deviation.wedstrijdcarpool_aanpassen": "Wedstrijdcarpool aanpassen",
  "deviation.geen_chauffeur": "-- geen chauffeur --",
  "deviation.geen_beschikbaarheid": " (geen beschikbaarheid)",
  "deviation.verplaats_naar": "Verplaats naar…",
  "deviation.auto": "Auto:",
  "deviation.verwijder_uit_auto": "Verwijder uit auto",
  "deviation.p_class_muted_geen_passagiers": "<p class=\"muted\">Geen passagiers meer in deze auto.</p>",
  "deviation.vertrek": "Vertrek",
  "deviation.deze_ouder_heeft_voor_dit": "Deze ouder heeft voor dit moment geen beschikbaarheid opgegeven — controleer of dit echt klopt.",
  "deviation.geen_ritten_gepland_in_het": "Geen ritten gepland in het standaard Rooster voor dit moment.",
  "deviation.voeg_toe_aan_auto": "Voeg toe aan auto…",
  "deviation.andere_meiden": "Andere meiden",
  "deviation.ook_meiden_die_niet_standaard": "Ook meiden die niet standaard meerijden, kun je hier alsnog aan een auto toevoegen.",
  "deviation.span_class_muted_nog_geen": "<span class=\"muted\">Nog geen auto</span>",
  "deviation.terug_naar_standaard_rooster": "Terug naar standaard rooster",
  "deviation.verwijderd_uit_deze_auto": " verwijderd uit deze auto.",
  "deviation.verplaatst": " verplaatst.",
  "deviation.toegevoegd": " toegevoegd.",
  "deviation.zeker_terug_naar_standaard_rooster": "Zeker? Terug naar standaard rooster",
  "deviation.teruggezet_naar_standaard": "Teruggezet naar standaard ✓",
  // matches
  "matches.http": "HTTP ",
  // myweek
  "myweek.thuis": " (Thuis)",
  "myweek.uit": " (Uit)",
  "myweek.vs": "vs",
  "myweek.mijn_week": "Mijn week",
  "myweek.koppel_eerst_je_dochter_via": "Je hebt geen eigen gezin. Bekijk een gezin via Beheer (Testweergave als deze ouder) om hier een weekoverzicht te zien.",
  "myweek.jouw_rijbeurt_om": "Jouw rijbeurt om",
  "myweek.wijziging_actief": "Wijziging actief",
  "myweek.wedstrijd": "Wedstrijd:",
  "myweek.aftrap": "Aftrap",
  "myweek.wedstrijd_2": "Wedstrijd",
  "myweek.span_class_todaytag_vandaag_span": "<span class=\"todayTag\">VANDAAG</span>",
  "myweek.geen_dagen_met_een_tijd": "Geen dagen met een tijd ingesteld deze week.",
  "myweek.kon_niet_ophalen": "Kon niet ophalen:",
  "myweek.p_class_muted_geen_wedstrijden": "<p class=\"muted\">Geen wedstrijden gevonden.</p>",
  "myweek.wedstrijden_deze_week": "Wedstrijden deze week",
  "myweek.carpool_regelen": "Carpool regelen",
  "myweek.niet_ingepland": "): niet ingepland",
  "myweek.regelen": "Regelen",
  "myweek.heeft_nog_geen_rit": "heeft nog geen rit",
  "myweek.je_dochter": "Je dochter",
  "myweek.ouder": "Ouder:",
  "myweek.passagiersplekken": "passagiersplekken",
  "myweek.deel_mijn_week_via_whatsapp": "Deel mijn week via WhatsApp",
  "myweek.deel_via_whatsapp": "Deel via WhatsApp",
  "myweek.rit_dochter": "Rit dochter",
  "myweek.jouw_rijbeurt": "Jouw rijbeurt",
  "myweek.wijziging": "Wijziging",
  "myweek.wedstrijdrit": "Wedstrijdrit",
  // profile
  "profile.testweergave_als": "Testweergave als:",
  "profile.stop_testen": "Stop testen",
  "profile.testweergave_gestart": "Testweergave gestart ✓",
  "profile.terug_naar_coordinatorweergave": "Terug naar coördinatorweergave ✓",
  "profile.heen_aankomst_alkmaar_nodig": "Heen: aankomst Alkmaar nodig",
  "profile.terug_klaar_om_op_te": "Terug: klaar om op te halen",
  "profile.kan_jij_deze_dag_rijden": "Kan jij deze dag rijden?",
  "profile.beschikbaar": "Beschikbaar",
  "profile.back_up": "Back-up",
  "profile.aankomst": "Aankomst: ",
  "profile.klaar": "Klaar: ",
  "profile.naam_ouder": "Naam ouder",
  "profile.coordinator_zonder_gezin": "Je bent coördinator en hebt geen eigen gezin. Gezinnen voeg je toe en beheer je bij Beheer.",
  "profile.naam_dochter": "Naam dochter",
  "profile.tel_nr_1": "Tel.nr. 1",
  "profile.tel_nr_1_wa": "Tel.nr. 1 (ontvangt WhatsApp-berichtjes)",
  "profile.tel_nr_2": "Tel.nr. 2",
  "profile.totale_autocapaciteit_incl_bestuurder": "Totale autocapaciteit (incl. bestuurder)",
  "profile.zitplaatsen_totaal": "zitplaatsen totaal",
  "profile.plek_voor": "Plek voor",
  "profile.passagiers": "passagiers",
  "profile.minder_zitplaatsen": "Minder zitplaatsen",
  "profile.meer_zitplaatsen": "Meer zitplaatsen",
  "profile.weekschema_waarschuwing_titel": "Je past je vaste weekschema aan",
  "profile.weekschema_waarschuwing_tekst": "Deze aanpassing is nog niet opgeslagen. Ze werkt door in de standaardplanning van elke week, niet alleen deze week.",
  "profile.weekschema_bevestigen": "Bevestigen: voor elke week",
  "profile.weekschema_naar_wijzigen": "Eenmalig wijzigen",
  "profile.weekschema_eenmalig_uitleg": "Eenmalig wijzigen maakt deze aanpassing ongedaan en opent Wijzigen voor alleen deze week.",
  "profile.weekschema_bevestigd": "Weekschema opgeslagen voor elke week",
  "weekschema.tijd": "{p1} {p2}: tijd {p3} → {p4}",
  "weekschema.geen_tijd": "geen tijd",
  "weekschema.rijdt_aan": "{p1} {p2}: je rijdt",
  "weekschema.rijdt_uit": "{p1} {p2}: je rijdt niet",
  "weekschema.backup_aan": "{p1} {p2}: je bent back-up",
  "weekschema.backup_uit": "{p1} {p2}: geen back-up meer",
  "deviation.intent_titel": "Dit wilde je eenmalig wijzigen",
  "deviation.intent_hint": "Pas hieronder de ritten van deze week aan. Je vaste weekschema is niet veranderd.",
  "deviation.intent_sluiten": "Sluiten",
  "profile.weekschema_beschikbaarheid_per_dag": "Weekschema &amp; beschikbaarheid per dag",
  "profile.zitplaatsen_totaal_2": " zitplaatsen totaal",
  "profile.welkom_bij_az_carpool": "Welkom bij AZ Carpool",
  "profile.er_is_nog_geen_coordinator": "Er is nog geen coördinator ingesteld voor deze app. Ben jij dat?",
  "profile.ik_ben_de_coordinator": "Ik ben de coördinator",
  "profile.ben_je_een_ouder_en": "Ben je een ouder en geen coördinator? Wacht tot de coördinator dit heeft ingesteld en de link met een uitnodigingscode met je deelt.",
  "profile.je_bent_nu_coordinator": "Je bent nu coördinator ✓",
  "profile.mislukt_mogelijk_had_iemand_anders": "Mislukt (mogelijk had iemand anders je net voor): ",
  "profile.laden": "Laden…",
  "profile.toegang_tot_az_carpool": "Toegang tot AZ Carpool",
  "profile.vul_je_telefoonnummer_en_de": "Vul je telefoonnummer en de code in die je van de coördinator hebt gekregen.",
  "profile.telefoonnummer": "Telefoonnummer",
  "profile.code": "Code",
  "profile.toegang_aanvragen": "Toegang aanvragen",
  "profile.code_van_de_coordinator": "Code van de coördinator",
  "profile.geen_verbinding_herlaad_de_pagina": "Geen verbinding. Herlaad de pagina.",
  "profile.vul_alle_velden_in": "Vul alle velden in.",
  "profile.code_klopt_niet_controleer_en": "Code klopt niet. Controleer en probeer opnieuw.",
  "profile.toegang_verleend": "Toegang verleend ✓",
  "profile.dit_telefoonnummer_hoort_niet_bij": "Dit telefoonnummer hoort niet bij deze code. Gebruik het nummer dat de coördinator van je heeft.",
  "profile.mijn_gezin": "Mijn gezin",
  "profile.ontkoppelen_van_deze_dochter": "Ontkoppelen van deze dochter",
  "profile.contactgegevens_autocapaciteit": "Contactgegevens &amp; autocapaciteit",
  "profile.gekoppeld_aan": "Gekoppeld aan:",
  "profile.zeker_tik_nogmaals_om_te": "Zeker? Tik nogmaals om te ontkoppelen",
  "profile.ontkoppeld": "Ontkoppeld ✓",
  "profile.geen_verbinding_met_opslag_herlaad": "Geen verbinding met opslag. Herlaad de pagina en probeer opnieuw.",
  "profile.je_account_kon_niet_herkend": "Je account kon niet herkend worden. Herlaad de pagina.",
  "profile.opgeslagen_de_coordinator_ziet_je": "Opgeslagen ✓ — de coördinator ziet je gewijzigde tijden",
  // schedule
  "schedule.rit": "rit",
  "schedule.span_class_daypilltoday_aria_hidden": "<span class=\"daypillToday\" aria-hidden=\"true\"></span>",
  "schedule.welk_rooster": "Welk rooster",
  "schedule.deze_week": "Deze week",
  "schedule.standaardrooster": "Vast rooster",
  "schedule.tik_op_een_naam_om": " Tik op een naam om haar te verplaatsen.",
  "schedule.niet_ingedeeld": "niet ingedeeld",
  "schedule.voorstellen": "Voorstellen",
  "schedule.reserve": "Reserve:",
  "schedule.geen_chauffeur": "Geen chauffeur",
  "schedule.jij_rijdt": "Jij rijdt",
  "schedule.chauffeur": "Chauffeur:",
  "schedule.minedriving": " mineDriving",
  "schedule.plekken": "plekken",
  "schedule.geen_ritten": "Geen ritten.",
  "schedule.gewijzigd": "gewijzigd",
  "schedule.kies_chauffeur": "-- kies chauffeur --",
  "schedule.verwijder_auto": "Verwijder auto",
  "schedule.geen_plek_meer_in_deze": "Geen plek meer in deze auto (",
  "schedule.bezet_wil_je": "bezet). Wil je",
  "schedule.wisselen_met_een_andere_passagier": "wisselen met een andere passagier?",
  "schedule.wissel_met_welke_passagier": "Wissel met welke passagier",
  "schedule.wissel": "Wissel",
  "schedule.nog_geen_ritten_ingepland": "Nog geen ritten ingepland.",
  "schedule.voorstellen_2": "Voorstellen:",
  "schedule.optie": "Optie",
  "schedule.gebruik_deze_optie": "Gebruik deze optie",
  "schedule.primary": " primary",
  "schedule.span_class_badge_rec_aanbevolen": "<span class=\"badge rec\">AANBEVOLEN</span> ",
  "schedule.secondary": " secondary",
  "schedule.geen_enkele_chauffeur_scombinatie_heeft": "Geen enkele chauffeur(scombinatie) heeft genoeg plek voor",
  "schedule.deze_meid": "deze meid",
  "schedule.aangepaste_combinatie": "Aangepaste combinatie",
  "schedule.nieuwe_auto_met_deze_meiden": "Nieuwe auto met deze meiden",
  "schedule.iedereen_is_ingedeeld": "Iedereen is ingedeeld.",
  "schedule.zie_deze_week": "Zie 'Deze week'",
  "schedule.deze_week_gewijzigd": "deze week gewijzigd",
  "schedule.verplaatst": " verplaatst ✓",
  "schedule.verplaatsen_mislukt": "Verplaatsen mislukt: ",
  "schedule.geen_chauffeur_2": "geen chauffeur",
  "schedule.vol_je_kunt_wisselen": " · vol, je kunt wisselen",
  "schedule.een_van_de_auto_s": "Een van de auto's bestaat niet meer.",
  "schedule.toevoegen_mislukt": "Toevoegen mislukt: ",
  "schedule.chauffeur_gewisseld_dubbele_boeking_automatisch": "Chauffeur gewisseld — dubbele boeking automatisch opgelost ✓",
  "schedule.chauffeur_gewisseld": "Chauffeur gewisseld ✓",
  "schedule.wisselen_mislukt": "Wisselen mislukt: ",
  "schedule.aanpassen_mislukt": "Aanpassen mislukt: ",
  "schedule.kies_wie_je_wilt_wisselen": "Kies wie je wilt wisselen.",
  "schedule.gewisseld": "Gewisseld ✓",
  "schedule.fout_bij_koppelen_roosterknoppen": "Fout bij koppelen roosterknoppen: ",
  // ---- added by hand ----
  "app.verbinden": "Verbinden…",
  "coordinator.onbekend": "Onbekend",
  "common.ouder": "Ouder",
  "deviation.opslaan": "Opslaan",
  "myweek.vandaag": "Vandaag",
  "matches.geen_api_key": "Geen Google Calendar API-key ingesteld in firebase-config.js.",
  // ---- Static page texts (index.html data-i18n attributes) ----
  "app.title": "AZ Carpool",
  "app.route": "Aalsmeer – Alkmaar ·",
  "app.loading": "Laden…",
  "nav.main": "Hoofdnavigatie",
  "nav.rooster": "Rooster",
  "nav.myweek": "Mijn week",
  "nav.deviation": "Wijzigen",
  "nav.profile": "Mijn gezin",
  "nav.matches": "Wedstrijden",
  "nav.beheer": "Beheer",
  "matches.titel": "Wedstrijden komende 4 weken",
  "matches.nog_niet_te_plannen": "Carpool nog niet te plannen. Dit kan vanaf {date}.",
  // ---- Messages with placeholders (from the original text; {p1}, {p2}... are filled in by the code) ----
  "dates.week": "Week {p1} · {p2} – {p3}",
  "beheer.samen_reizen_2": "Samen reizen: {p1}",
  "beheer.nieuwe_tijdswijziging_zie_rooster": "Nieuwe tijdswijziging{p1} — zie Rooster",
  "deviation.heeft_maar_je_hebt_passagiers": "{p1} {p2} heeft {p3} {p4}, maar je hebt {p5} passagiers gekozen.",
  "deviation.te_veel_passagiers_tik_nogmaals": "Te veel passagiers ({p1}/{p2}). Tik nogmaals op \"Toch opslaan\" om door te gaan.",
  "deviation.deze_auto_zit_nu_vol": "Deze auto zit nu vol ({p1}/{p2}) — verplaatsing is wel doorgevoerd.",
  "deviation.deze_auto_zit_nu_vol_2": "Deze auto zit nu vol ({p1}/{p2}) — toevoeging is wel doorgevoerd.",
  "myweek.jij_rijdt": "{p1}{p2} Jij rijdt{p3}",
  "myweek.rijdt_mee_met": "{p1} Rijdt mee met: {p2}",
  "myweek.niet_ingepland_2": "{p1} niet ingepland",
  "schedule.niet_ingedeeld_2": ", {p1} niet ingedeeld",
  "schedule.het_standaardrooster_met_de_wijzigingen": "{p1} · met wijzigingen.",
  "schedule.het_vaste_rooster_elke_week": "Het vaste rooster, elke week gelijk.{p1}",
  "schedule.aankomst_alkmaar_nodig": "Aankomst Alkmaar nodig: {p1}",
  "schedule.klaar_om_op_te_halen": "Klaar om op te halen: {p1}",
  "schedule.nog_niet_ingedeeld": "Nog niet ingedeeld: {p1}.",
  "schedule.nog_niet_ingedeeld_2": "Nog niet ingedeeld ({p1}): {p2}.",
  "schedule.toevoegen_aan_auto": "Toevoegen aan auto {p1} ({p2})",
  "schedule.toevoegen_aan_bestaande_auto_s": "Toevoegen aan bestaande auto's",
  "schedule.nieuwe_auto": "Nieuwe auto: {p1}",
  "schedule.vertrek": "Vertrek {p1}{p2}{p3}",
  "schedule.plekken_2": " · {p1}/{p2} plekken",
  "schedule.kies_een_andere_auto": "{p1} · {p2} — kies een andere auto:",
  // ---- added by hand (2) ----
  "common.plek": "plek",
  "common.plekken": "plekken",
  "dir.heenShort": "Heen",
  "dir.terugShort": "Terug",
  "deviation.gekozen": "{n} gekozen",
  "schedule.verplaats": "Verplaats {p1}",
  "schedule.auto_regel": "Auto {p1}: {p2} ({p3}/{p4} pl., vertrek {p5})",
  "schedule.deze_n_meiden": "deze {p1} meiden",
  "schedule.auto_label": "Auto {p1} · {p2}",
  "beheer.voorkeur_met": "Voorkeur: {p1} met {p2}",
  "common.onbekend": "onbekend",
  // ---- US-02..05: dagcoördinator, conclusie-appje, 1-op-1 afstemmen, Flex ----
  "dayCoord.label": "Dagcoördinator {when}: {name}",
  "dayCoord.you": "Jij bent dagcoördinator {when}",
  "dayCoord.waLabel": "Stuur {name} een WhatsApp-bericht",
  "dayCoord.waText": "Hi! Een vraag over de carpool van {when}: ",
  "dayCoord.beheerTitle": "Dagcoördinatoren",
  "dayCoord.beheerIntro": "Kies per weekdag welke ouder wijzigingen in de carpool afhandelt. Ouders zien deze naam in Rooster en Mijn week, met een WhatsApp-knop.",
  "dayCoord.tomorrow": "morgen",
  "dayCoord.monday": "maandag",
  "dayCoord.none": "-- niemand --",
  "dayCoord.saved": "Dagcoördinator opgeslagen",
  "conclusie.title": "Conclusie-appje {dayLabel}",
  "conclusie.intro": "Controleer de tekst en verstuur hem zelf in de groepsapp.",
  "conclusie.forYou": "Jij bent dagcoördinator op {day}. Deel het besluit met de groep.",
  "conclusie.button": "Open in WhatsApp",
  "conclusie.previewLabel": "Voorbeeldtekst",
  "wa.conclusie.out": "Rijdt niet mee {direction}: {names}",
  "wa.conclusie.changed": "Gewijzigde chauffeur/tijd: {entries}",
  "wa.conclusie.changedEntry": "{direction} {driver} {time}",
  "wa.conclusie.extra": "Rijdt ook mee {direction}: {names}",
  "wa.conclusie.title": "Aangepast schema {day} {date}",
  "wa.conclusie.onSchedule": "{dayLabel}: volgens schema. Zie Mijn week: {url}",
  "wa.dir.heen": "heen",
  "wa.dir.terug": "terug",
  // ---- Weekoverzicht (Rooster): the PDF layout, on screen and for print ----
  "overview.open": "Weekoverzicht",
  "overview.title": "Carpooloverzicht AZ, regio Aalsmeer",
  "overview.versie": "Versie:",
  "overview.vertrektijden": "Vertrektijden heen: {heen}, terug: {terug}",
  "overview.standaardrit": "Standaardrit = {km} km ({eur}); heen & weer = {km2} km ({eur2}) ({ct}ct/km)",
  "overview.coordinator": "Coördinator:",
  "overview.dag": "Dag",
  "overview.rit": "Rit",
  "overview.tijdstip": "Tijdstip",
  "overview.auto": "Auto",
  "overview.chauffeur": "Chauffeur",
  "overview.passagiers": "Passagiers",
  "overview.bezetting": "Bezetting",
  "overview.reserve": "Reserve (volgorde van vragen)",
  "overview.rijfrequentie": "Rijfrequentie",
  "overview.speelster": "Speelster",
  "overview.aankomstShort": "aank.",
  "overview.klaarShort": "klaar",
  "overview.geenChauffeur": "geen chauffeur",
  "overview.geenRitten": "Geen ritten",
  "overview.gewijzigd": "Deze week aangepast ten opzichte van het vaste rooster.",
  "overview.print": "Afdrukken / PDF",
  "overview.sluiten": "Sluiten",
  "oneOnOne.label": "Stem 1-op-1 af, de dagcoördinator deelt het besluit.",
  "oneOnOne.button": "Stem af met chauffeur {name}",
  "deviation.backup": "Back-up:",
  "oneOnOne.aria": "Stem af met chauffeur {name} via WhatsApp",
  "wa.oneOnOne": "Hi! Over de rit {direction} van {date}: kunnen we even afstemmen? ",
  "flex.speelsterChauffeur": "speelster-chauffeur",
  "flex.title": "Flex: aanmelden voor deze dag",
  "flex.intro": "Flex-leden rijden alleen mee op dagen dat ze zich aanmelden.",
  "flex.timeHeen": "Aankomst in Alkmaar",
  "flex.timeTerug": "Klaar om op te halen",
  "flex.chooseCar": "Kies auto…",
  "flex.rideAlong": "Rij mee",
  "flex.drive": "Ik rijd zelf",
  "flex.noCarToDrive": "Geen auto beschikbaar om zelf te rijden.",
  "flex.noFreeSeat": "Geen auto met een vrije plek.",
  "flex.signedUp": "Aangemeld",
  "flex.signOff": "Afmelden",
  "flex.chooseTime": "Vul eerst een tijd in.",
  "flex.chooseCarToast": "Kies een auto om in mee te rijden.",
  "flex.joined": "{p1} rijdt mee",
  "flex.driving": "{p1} rijdt zelf",
  "flex.removed": "{p1} is afgemeld",
  "flex.badge": "Flex",
  "profile.gezinstype": "Type gezin",
  "profile.gezinstype.vast": "Vast: rijdt volgens het schema",
  "profile.gezinstype.flex": "Flex: rijdt alleen op aangemelde dagen, wordt nooit automatisch ingepland",
  // ---- API-sleutels (Beheer) ----
  "apikeys.titel": "API-sleutels",
  "apikeys.uitleg": "De sleutel voor OpenRouteService (afstand van uitwedstrijden) staat hier in de database, niet in de publieke GitHub-map. Alleen leden kunnen hem lezen; alleen de coördinator kan hem wijzigen.",
  "apikeys.ors_label": "OpenRouteService-sleutel",
  "apikeys.ors_placeholder": "Nieuwe sleutel plakken",
  "apikeys.ors_ingesteld": "OpenRouteService-sleutel is ingesteld (eindigt op {p1}).",
  "apikeys.ors_niet_ingesteld": "Nog geen OpenRouteService-sleutel: de afstand van uitwedstrijden wordt niet berekend.",
  "apikeys.opslaan": "Sleutel opslaan",
  "apikeys.verwijderen": "Sleutel verwijderen",
  "apikeys.opgeslagen": "Sleutel opgeslagen",
  "apikeys.verwijderd": "Sleutel verwijderd",
  "apikeys.leeg": "Plak eerst een sleutel",
  "apikeys.spaties": "Een sleutel bevat geen spaties",
  "profile.wa_intro_label": "Stuur inlogbericht via WhatsApp",
  "profile.wa_intro_text": "Hi! Je kunt inloggen op de AZ Carpool-app via {url} \nGebruik dit telefoonnummer en de code: {code}",
  "profile.wa_intro_text_nocode": "Hi! Je kunt inloggen op de AZ Carpool-app via {url} \nGebruik dit telefoonnummer en de code die je van de coördinator krijgt.",
  "notice.title": "Melding voor iedereen",
  "notice.intro": "Een korte melding als dunne gele balk bovenaan de app, zichtbaar voor alle gebruikers. Jij zet hem aan en uit.",
  "notice.show": "Melding tonen",
  "notice.text": "Tekst",
  "notice.placeholder": "Bijvoorbeeld: Zaterdag geen training.",
  "notice.off.label": "Automatisch uit op (niet verplicht)",
  "notice.off.date": "Datum waarop de melding uitgaat",
  "notice.off.time": "Tijd waarop de melding uitgaat",
  "notice.off.hint": "Laat leeg om de melding aan te laten tot je hem zelf uitzet.",
  "notice.preview": "Zo ziet iedereen het",
  "notice.preview.empty": "Nog geen tekst.",
  "notice.status.on": "Zichtbaar voor iedereen",
  "notice.status.off": "Uit, niet zichtbaar",
  "notice.status.ended": "Automatisch uitgegaan",
  "notice.save": "Opslaan",
  "notice.saved.on": "Melding staat aan",
  "notice.saved.off": "Melding staat uit",
  "notice.err.noText": "Vul eerst een tekst in",
  "notice.err.offBoth": "Vul bij automatisch uit zowel datum als tijd in",
  "notice.err.invalidOff": "Datum of tijd voor automatisch uit klopt niet",
  "notice.err.offPast": "Het moment voor automatisch uit ligt in het verleden",
  "maint.title": "Onderhoudsmodus",
  "maint.intro": "Zet de app tijdelijk dicht voor alle gebruikers. Jij kunt gewoon alles blijven doen. Anderen zien een scherm dat de app even niet beschikbaar is.",
  "maint.show": "Onderhoudsmodus aan",
  "maint.text": "Eigen tekst voor gebruikers (niet verplicht)",
  "maint.placeholder": "Bijvoorbeeld: We zijn weer terug rond 20:00.",
  "maint.preview": "Zo zien gebruikers het",
  "maint.status.on": "Aan, gebruikers zien de onderhoudspagina",
  "maint.status.off": "Uit, de app is gewoon open",
  "maint.autosave": "Wijzigingen worden meteen opgeslagen.",
  "maint.saved.on": "Onderhoudsmodus staat aan",
  "maint.saved.off": "Onderhoudsmodus staat uit",
  "maint.err.coordinatorOnly": "Alleen de coördinator kan de onderhoudsmodus wijzigen",
  "maint.banner": "Onderhoudsmodus staat aan. Gebruikers zien dat de app niet beschikbaar is.",
  "maint.page.title": "De app is even niet beschikbaar",
  "maint.page.default": "We doen onderhoud aan de app. Probeer het over een tijdje opnieuw.",
  "maint.page.auto": "Dit scherm verdwijnt vanzelf zodra de app weer open is.",
  // ---- US-15, US-06, US-21, US-07, US-22 ----
  "loc.beheerTitle": "Ophaal- en afzetplekken",
  "loc.beheerIntro": "Ouders halen hun dochter op of zetten haar af op één van deze plekken (maximaal {p1}). Vul een adres in, of GPS-coördinaten: decimale graden (52.2589, 4.7673) of graden-minuten-seconden (52°15'32.3\"N 4°46'02.3\"E). Per rit kan de plek eenmalig worden gewijzigd in Wijzigen.",
  "loc.placeName": "Naam in het rooster",
  "loc.placeAddress": "Exact adres",
  "loc.destination": "Bestemming in Alkmaar",
  "loc.defaultHeen": "Standaard ophaalplek (heen)",
  "loc.defaultTerug": "Standaard afzetplek (terug)",
  "loc.fixedAFC": "AFC '34, Alkmaar",
  "loc.fixedATC": "AZ Trainingscomplex, Wijdewormer",
  "loc.fixedTitle": "Vaste afstand (km, enkele reis)",
  "loc.fixedHint": "Wedstrijden op AFC of ATC gebruiken deze vaste afstand. Er wordt niets berekend.",
  "loc.saved": "Plekken opgeslagen",
  "loc.override": "Plek (eenmalig)",
  "loc.useDefault": "Standaard: {name}",
  "loc.changedTag": "eenmalig gewijzigd",
  "loc.addressPlaceholder": "Adres of GPS-coördinaten",
  "loc.gpsRecognized": "GPS herkend: {p1}",
  "loc.addPlace": "Plek toevoegen",
  "loc.maxPlaces": "Maximaal {p1} plekken.",
  "loc.newPlaceName": "Nieuwe plek",
  "loc.remove": "Verwijder",
  "loc.removePlace": "Verwijder plek {name}",
  "loc.shiftHint": "In het Rooster (Standaardrooster) kun je op de plek van een auto klikken om die auto een eigen standaard vertrek- en aankomstplek te geven.",
  "loc.shiftChange": "Andere plek voor deze auto",
  "loc.shiftTitle": "Standaardplek van deze auto",
  "loc.shiftSub": "{p1} {p2}: geldt alleen voor deze auto, elke week. Kies het vertrek en de aankomst.",
  "loc.arrivalItem": "Aankomst: {name}",
  "loc.shiftSaved": "Standaardplek van de auto opgeslagen",
  "loc.freeLabel": "Of vrij invoeren (adres of plek)",
  "loc.freePlaceholder": "Bijv. Hoofdweg 12, Hoofddorp of Tankstation Shell",
  "loc.freeOption": "Ander adres…",
  "loc.freeHint": "Alleen voor deze rit, wordt niet als standaardadres bewaard.",
  "ov.switchLabel": "Rijdt mee {p1} {p2}",
  "ov.status": "{p1} Rijdt niet mee",
  "ov.on": "{p1} rijdt niet mee",
  "ov.off": "{p1} rijdt weer mee",
  "ov.toastUndo": "Ongedaan maken",
  "myweek.plekken": "plekken",
  "wa.my.ov": "rijdt niet mee",
  "dist.km": "± {km} km enkele reis",
  "dist.cost": "± € {eur} carpoolkosten",
  "dist.kmFixed": "{km} km enkele reis",
  "dist.costFixed": "€ {eur} carpoolkosten",
  "dist.unknown": "locatie onbekend",
  "dist.pending": "afstand wordt berekend…",
  "dist.fixedMissing": "vaste afstand {venue} nog niet ingesteld",
  "geo.route": "Route plannen naar {place}",
  "impact.saves": "Scheelt een auto",
  "impact.none": "Geen effect",
  "impact.needSeat": "Extra plek nodig → voorstel: {name}",
  "impact.noSolution": "Geen oplossing → back-up {name}",
  "impact.noSolutionNoBackup": "Geen oplossing en geen back-up beschikbaar",
  "impact.title": "Effect van deze wijziging",
  "impact.save": "Opslaan",
  "impact.beheerTitle": "Impact-preview (pilot)",
  "impact.beheerIntro": "Pilot van 2 à 3 weken met de dagcoördinatoren. Aan: vóór het opslaan van een wijziging toont de app wat het effect is op het rooster. Er wordt niets van de preview opgeslagen. Uit: alles werkt zoals altijd, en er blijft geen data achter.",
  "impact.beheerToggle": "Impact-preview aan",
  "impact.on": "Impact-preview staat aan",
  "impact.off": "Impact-preview staat uit",
  // ---- Help ("?" in the header) ----
  "help.title": "Hulp",
  "help.open": "Hulp openen",
  "help.close": "Sluiten",
  "help.search_label": "Zoek in de hulp",
  "help.search_placeholder": "Waar kunnen we je mee helpen?",
  "help.topics": "Alle onderwerpen",
  "help.about": "Over deze app",
  "help.results": "Resultaten",
  // ---- Periode met andere tijden (vakantie, proefwerkweek): Beheer ----
  "period.title": "Perioden met andere tijden",
  "period.intro": "Ouders geven voor een periode één keer hun tijden door. Het vaste rooster blijft staan. Je kunt meerdere perioden hebben, ook als de ene nog loopt terwijl je de volgende al uitzet. Perioden mogen geen dag delen.",
  "period.add": "+ Periode toevoegen",
  "period.list.edit": "Wijzig {p1}",
  "period.list.roosterMade": "Tijdelijk rooster gemaakt",
  "period.form.addTitle": "Periode toevoegen",
  "period.form.editTitle": "Periode wijzigen",
  "period.firstDayLockedHint": "De eerste dag kan niet meer worden gewijzigd: er zijn al tijden of een tijdelijk rooster voor deze periode.",
  "period.delete.confirmData": "Zeker? {p1} gezinnen verliezen hun tijden",
  "period.delete.confirmBackups": "Zeker? {p1} back-ups van deze periode gaan ook weg",
  "period.delete.confirmDataBackups": "Zeker? {p1} gezinnen verliezen hun tijden en {p2} back-ups gaan weg",
  "period.backup.title": "Back-ups ({p1})",
  "period.backup.intro": "Een back-up bewaart de periode, de doorgegeven tijden en het tijdelijke rooster. Zo kun je veilig testen en daarna alles terugzetten.",
  "period.backup.make": "Back-up maken",
  "period.backup.auto": "automatisch, vlak voor terugzetten",
  "period.backup.what": "{p1} gezinnen doorgegeven · {p2} ritten in het tijdelijke rooster",
  "period.backup.since": "Sindsdien anders: {p1} gezinnen, {p2} ritten",
  "period.backup.sincePeriod": "Sindsdien anders: de instellingen van de periode",
  "period.backup.same": "Sindsdien niets veranderd",
  "period.backup.restore": "Zet deze back-up terug",
  "period.backup.delete": "Verwijder back-up",
  "period.backup.restoreConfirm": "Zeker? Alles gaat terug naar deze back-up",
  "period.backup.restoreConfirmLost": "Zeker? {p1} gezinnen verliezen wat ze sindsdien doorgaven",
  "period.backup.made": "Back-up gemaakt",
  "period.backup.deleted": "Back-up verwijderd",
  "period.backup.restored": "Back-up teruggezet",
  "period.backup.err.full": "Je hebt al {p1} back-ups van deze periode. Verwijder er eerst een.",
  "period.backup.err.broken": "Deze back-up is niet compleet en kan niet worden teruggezet.",
  "period.err.overlap": "Deze periode overlapt met {p1}. Perioden mogen geen dag delen.",
  "period.err.firstDayLocked": "De eerste dag kan niet meer worden gewijzigd: er zijn al tijden of een tijdelijk rooster voor deze periode.",
  "period.err.deleteRooster": "Verwijder eerst het tijdelijke rooster van deze periode (bij Rooster).",
  "period.view.pick": "Periode",
  "period.name": "Naam",
  "period.namePlaceholder": "Bijvoorbeeld Herfstvakantie",
  "period.firstDay": "Eerste dag",
  "period.lastDay": "Laatste dag",
  "period.maxHint": "Periode is maximaal {p1} werkdagen (2 weken).",
  "period.opensOn": "Invullen open vanaf",
  "period.opensHint": "Vanaf dan krijgt iedereen de melding op Wijzigen.",
  "period.deadline": "Deadline",
  "period.deadlineDate": "Deadline (datum)",
  "period.deadlineTime": "Deadline (tijd)",
  "period.deadlineHint": "Staat in de melding voor ouders.",
  "period.save": "Opslaan",
  "period.cancel": "Annuleren",
  "period.delete": "Verwijder periode",
  "period.saved": "Periode opgeslagen",
  "period.deleted": "Periode verwijderd",
  "period.phase.none": "Nog geen periode ingesteld.",
  "period.phase.waiting": "Invullen opent op {p1}.",
  "period.phase.open": "Invullen is open tot de deadline: {p1}.",
  "period.phase.closed": "De deadline is voorbij ({p1}). Alleen de coördinator kan nog tijden aanpassen.",
  "period.phase.over": "Deze periode is voorbij. Stel een nieuwe periode in als dat nodig is.",
  "period.err.name": "Vul een naam in.",
  "period.err.nameLong": "De naam is te lang (maximaal 40 tekens).",
  "period.err.days": "Vul de eerste en de laatste dag in.",
  "period.err.weekend": "De eerste en de laatste dag moeten een werkdag zijn (maandag t/m vrijdag).",
  "period.err.order": "De laatste dag ligt vóór de eerste dag.",
  "period.err.tooLong": "Een periode is maximaal {p1} werkdagen.",
  "period.err.opens": "Vul in vanaf welke dag invullen open is.",
  "period.err.deadline": "Vul de deadline in (datum en tijd).",
  "period.err.deadlineBeforeOpen": "De deadline ligt vóór de dag waarop invullen opent.",
  "period.err.deadlineAfterStart": "De deadline moet vóór de eerste dag van de periode liggen.",
  // ---- Periode met andere tijden: ouders geven tijden door (Wijzigen) ----
  "period.task.title": "Actie nodig: geef tijden door",
  "period.task.body": "{p1} · {p2}. Geef door hoe laat {p3} heen en terug moet, of dat ze niet meerijdt.",
  "period.task.deadline": "Deadline: {p1}",
  "period.task.deadlinePassed": "De deadline is voorbij. Alleen jij kunt als coördinator de tijden nog invullen.",
  "period.task.standardStays": "Het vaste rooster blijft staan voor andere weken.",
  "period.task.button": "Tijden doorgeven",
  "period.task.bodyCoord": "{p1} · {p2}. Geef je eigen tijden door. Als coördinator kun je ook invullen namens een ouder.",
  "period.coord.title": "Namens een ouder invullen",
  "period.coord.intro": "{p1} · {p2}. Als coördinator kun je invullen namens een ouder.",
  "period.coord.progress": "{p1} van {p2} doorgegeven. Nog {p3} te gaan.",
  "period.coord.allDone": "Alle {p2} gezinnen hebben doorgegeven.",
  "period.coord.notYet": "Nog niet",
  "period.coord.done": "Doorgegeven",
  "period.coord.fill": "Invullen",
  "period.coord.view": "Bekijk",
  "period.coord.hide": "Sluiten",
  "period.form.onBehalf": "Je vult in namens {p1} ({p2}).",
  "period.status.label": "Doorgegeven",
  "period.status.value": "{p1} van {p2} gezinnen",
  "period.pill.waiting": "Gepland",
  "period.pill.open": "Open",
  "period.pill.closed": "Deadline voorbij",
  "period.pill.over": "Afgelopen",
  "period.who.title": "Wie heeft ingevuld?",
  "period.who.missing": "Nog niet: {p1}",
  "period.who.more": "+{p1}",
  "period.who.allDone": "Iedereen heeft doorgegeven",
  "period.who.todo": "Nog niet doorgegeven ({p1})",
  "period.who.done": "Doorgegeven ({p1})",
  "period.who.stateTodo": "Nog niet",
  "period.who.stateDone": "Doorgegeven",
  "period.form.groupFill": "Invullen door ouders",
  "period.badge.aria": "Actie nodig: tijden doorgeven",
  "period.done.title": "Tijden doorgegeven",
  "period.done.body": "{p1} · {p2}. Wijzigen kan tot {p3}.",
  "period.done.locked": "{p1} · {p2}. De deadline is voorbij. Tijden aanpassen kan alleen nog via de coördinator.",
  "period.done.yours": "Jouw tijden · {p1}",
  "period.done.out": "rijdt niet mee",
  "period.done.heen": "heen {p1}",
  "period.done.terug": "terug {p1}",
  "period.done.noHeen": "niet heen",
  "period.done.noTerug": "niet terug",
  "period.done.edit": "Tijden aanpassen",
  "period.form.title": "Tijden {p1}",
  "period.form.sub": "{p1} · {p2} · deadline {p3}",
  "period.form.hint": "Ingevuld is het vaste rooster. Pas aan wat anders is. Een tijd invullen = meerijden.",
  "period.form.heen": "Heen: aankomst Alkmaar",
  "period.form.terug": "Terug: klaar om op te halen",
  "period.form.rides": "Rijdt mee",
  "period.form.notRides": "Rijdt niet mee",
  "period.form.notRidesDay": "{p1} rijdt deze dag niet mee.",
  "period.form.cancel": "Annuleren",
  "period.form.submit": "Doorgeven",
  "period.entry.saved": "Tijden doorgegeven ✓",
  "period.entry.err.noPeriod": "Er is geen periode ingesteld.",
  "period.entry.err.closed": "De deadline is voorbij. Alleen de coördinator kan de tijden nog aanpassen.",
  "period.entry.err.missing": "Vul alle dagen in.",
  "period.entry.err.time": "{p1}: vul een geldige tijd in.",
  "period.entry.err.noTime": "{p1}: vul een tijd in, of kies Rijdt niet mee.",
  "period.entry.err.order": "{p1}: Terug moet later zijn dan Heen.",
  // ---- Periode met andere tijden, step 4: Rooster (overview and temporary rooster) ----
  "period.ov.title": "{p1} · {p2}",
  "period.ov.handed": "Doorgegeven",
  "period.ov.handedValue": "{p1} van {p2}",
  "period.ov.deadlineOpen": "Deadline {p1} · nog niet: {p2}",
  "period.ov.deadlineOpenAll": "Deadline {p1} · iedereen heeft doorgegeven",
  "period.ov.deadlineClosed": "Deadline voorbij · nog niet: {p2}",
  "period.ov.deadlineClosedAll": "Deadline voorbij · iedereen heeft doorgegeven",
  "period.ov.dayChanges": "{p1} wijz.",
  "period.ov.noChanges": "geen wijz.",
  "period.ov.dayTitle": "{p1}: {p2} wijzigingen, {p3} rijden niet mee",
  "period.ov.make": "Tijdelijk rooster maken",
  "period.ov.remake": "Alles opnieuw indelen",
  "period.ov.remove": "Verwijder tijdelijk rooster",
  "period.ov.explain": "Het tijdelijke rooster vervangt het vaste rooster alleen in deze periode. Daarna geldt weer het vaste rooster.",
  "period.view.parentInfo": "Tijdelijk rooster {p1} ({p2}). Wijzigingen in Wijzigen gaan altijd voor het tijdelijke rooster.",
  "period.view.coordInfo": "Tijdelijk rooster {p1} ({p2}). Iedereen kan in Wijzigen blijven wijzigen. Dat gaat altijd voor het tijdelijke rooster.",
  "period.view.notMade": "Voor deze dag is nog geen tijdelijk rooster: het vaste rooster geldt.",
  "period.view.times": "Doorgegeven tijden",
  "period.view.notRiding": "rijdt niet mee",
  "period.view.nobody": "Niemand rijdt mee.",
  "period.view.noCars": "Geen ritten.",
  "period.view.car": "Auto {p1}",
  "period.view.replan": "Opnieuw indelen",
  "period.view.driver": "Chauffeur",
  "period.view.noDriver": "-- geen chauffeur --",
  "period.view.move": "Verplaats naar…",
  "period.view.moveTo": "Auto {p1} · {p2}",
  "period.view.notPlaced": "Niet ingedeeld",
  "period.view.place": "Zet in…",
  "period.view.newCar": "Nieuwe auto: {p1}",
  "period.view.unplaced": "{p1} niet ingedeeld",
  "period.rooster.made": "Tijdelijk rooster gemaakt ✓",
  "period.rooster.replanned": "Opnieuw ingedeeld ✓",
  "period.rooster.removed": "Tijdelijk rooster verwijderd",
  "period.rooster.saved": "Opgeslagen ✓",
  "period.rooster.err.coordinator": "Alleen de coördinator kan het tijdelijke rooster aanpassen.",
  "period.rooster.err.shift": "Deze dag hoort niet bij de periode.",
  "period.rooster.err.full": "Auto vol: {p1} van {p2} plekken.",
  "period.rooster.err.driverBusy": "Deze chauffeur rijdt al in een andere auto.",
  "period.rooster.err.unknown": "Kon deze wijziging niet uitvoeren.",
  // Back-up en terugzetten van gezinnen (Beheer)
  "backup.title": "Back-up gezinnen",
  "backup.intro": "Sla alle gezinnen op in één bestand (CSV, te openen in Excel) of zet een eerder bestand terug. Het bestand bevat per gezin: ouder, dochter, type, coördinator (j/n), autocapaciteit, telefoonnummers, de heen- en terugtijden en de beschikbaarheid (beschikbaar of back-up) per dag. Uitnodigingscodes en koppelingen staan er bewust niet in.",
  "backup.make": "Back-up maken",
  "backup.restore": "Terugzetten uit bestand…",
  "backup.made": "Back-up gemaakt: {p1} gezinnen",
  "backup.read_error": "Bestand kon niet gelezen worden",
  "backup.preview_title": "Controle van {p1}",
  "backup.preview_summary": "{p1} gezinnen worden overschreven, {p2} nieuw.",
  "backup.preview_untouched": "{p1} gezinnen die niet in het bestand staan blijven ongewijzigd.",
  "backup.preview_coordinator": "Let op: de coördinator wordt {p1}. Ben jij dat niet zelf, dan verlies je de toegang tot Beheer.",
  "backup.confirm": "Overschrijven",
  "backup.confirm_again": "Zeker? Klik nogmaals",
  "backup.cancel": "Annuleren",
  "backup.errors_title": "Het bestand is niet teruggezet: er is niets gewijzigd. Dit moet eerst kloppen:",
  "backup.errors_more": "… en nog {p1} andere meldingen",
  "backup.line": "Regel {p1}: {p2}",
  "backup.restored": "Teruggezet: {p1} gezinnen ✓",
  "backup.err.empty": "Het bestand bevat geen gezinnen.",
  "backup.err.columns": "Kolommen ontbreken: {p1}. Gebruik een bestand dat met Back-up maken is gemaakt.",
  "backup.err.noName": "Ouder en dochter zijn allebei leeg.",
  "backup.err.type": "Type gezin \"{p1}\" is onbekend (vast of flex).",
  "backup.err.coordinator": "Coördinator \"{p1}\" is onbekend (j of n).",
  "backup.err.capacity": "Autocapaciteit \"{p1}\" klopt niet (een getal van 1 tot 9).",
  "backup.err.time": "Kolom \"{p1}\": \"{p2}\" is geen tijd (uu:mm).",
  "backup.err.avail": "Kolom \"{p1}\": \"{p2}\" is onbekend (beschikbaar, back-up of leeg).",
  "backup.err.id": "Id \"{p1}\" is niet toegestaan.",
  "backup.err.dupId": "Id \"{p1}\" staat meer dan één keer in het bestand.",
  "backup.err.sameFamily": "{p1} staat meer dan één keer in het bestand.",
  "backup.err.manyCoord": "Er staat bij meer dan één gezin \"j\" bij Coördinator. Er mag er maar één zijn.",
  "backup.err.coordinator_only": "Alleen de coördinator kan terugzetten.",
  "backup.err.nothing": "Er is niets om terug te zetten.",
  "help.no_results": "Niets gevonden. Probeer een ander woord, of vraag het aan de coördinator.",
  "help.back": "Terug naar de lijst",
  "help.goto": "Ga naar {tab}",
  "help.contact": "Kom je er niet uit? Vraag het aan de coördinator.",
  "dir.heenTo": "Heen · Aalsmeer → {city}",
  "dir.terugFrom": "Terug · {city} → Aalsmeer",
  "deviation.wijzig": "Wijzig",
  "deviation.klaar": "Klaar",
  "deviation.ophalen": "Ophalen (alleen deze rit)",
  "deviation.aankomst": "Aankomst",
  "deviation.kinderen": "Kinderen",
  "deviation.opties": "Opties",
  "deviation.naar_auto": "Naar {name}",
  "deviation.verwijder": "Verwijder",
  "deviation.ongedaan": "Ongedaan",
};
