// texts-nl.js — every piece of Dutch text the app shows. Keys are grouped by area (wa = WhatsApp messages,
// dir = travel directions, toast = short pop-up messages, ...). Values may contain {placeholders}.
export default {
  'meta.locale': 'nl-NL',

  // Travel directions (one wording everywhere in the app)
  'dir.heen': 'Heen · Aalsmeer → Alkmaar',
  'dir.terug': 'Terug · Alkmaar → Aalsmeer',

  // Names
  'driver.none': 'nog geen chauffeur',
  'ask.unknownTime': '?',

  // WhatsApp — generic update
  'wa.generic': 'Het schema is bijgewerkt voor {days}. Zie Mijn week voor de impact: {url}',
  'wa.thisWeek': 'deze week',
  'wa.and': ' en ',

  // WhatsApp — Mijn week (one line per day for one family's daughter)
  'wa.my.header': 'Carpool deze week – {name}:',
  'wa.my.line': '{day}{changed} — heen: {heen} | terug: {terug}',
  'wa.my.changed': ' (gewijzigd)',
  'wa.my.notPlanned': '{time} (nog niet ingepland)',
  'wa.my.with': '{time} met {driver}',
  'wa.my.none': 'Geen ritten ingesteld deze week.',
  'wa.my.match': '{day} — wedstrijd {team} vs {opponent}: vertrek {time} met {driver}',

  // WhatsApp — one day's full schedule (Wijzigen)
  'wa.day.title': 'Aangepast schema {dayLabel} {date}:',
  'wa.day.adapted': ' (aangepast)',
  'wa.day.noRides': '• geen ritten',
  'wa.day.car': '• {time} – {driver}: {girls}',

  // WhatsApp — "can you drive / you are driving" asks from the Rooster
  'wa.ask.reserve': 'Hi! Zou jij de rit {direction} van {date} om {time} kunnen doen?',
  'wa.ask.reserve.heen': 'heen',
  'wa.ask.reserve.terug': 'terug',
  'wa.ask.driver': 'Hi! Je rijdt de rit van {date} om {time}. ',
  // ---- Texts extracted from the original screens (generated once; edit freely) ----
  // app
  "app.niet_verbonden": "Niet verbonden.",
  "app.fout_bij_laden_koppeling": "Fout bij laden koppeling: ",
  "app.kon_niet_live_verbinden": "Kon niet live verbinden: ",
  // beheer
  "beheer.nog_geen_gezinnen": "Nog geen gezinnen.",
  "beheer.ouder": "Ouder",
  "beheer.span_class_muted_span": "<span class=\"muted\">–</span>",
  "beheer.groen_vlak_standaard_beschikbaar": "groen vlak = standaard beschikbaar.",
  "beheer.grijs_cijfer_back_up_indien": "grijs cijfer = back-up (indien nodig). Cijfer = plek voor passagiers (niet de totale autocapaciteit). H = heen, T = terug.",
  "beheer.of": " of ",
  "beheer.voorkeur_verwijderen": "Voorkeur verwijderen",
  "beheer.verwijder": "Verwijder",
  "beheer.nog_geen_voorkeuren": "Nog geen voorkeuren.",
  "beheer.samen_reizen": "Samen reizen",
  "beheer.moeten_altijd_samen_in_1": "(moeten altijd samen in 1 auto als het even kan):",
  "beheer.toevoegen": "+ Toevoegen",
  "beheer.voorkeur": "Voorkeur",
  "beheer.moet_met_minstens_een_van": "(moet met minstens één van de gekozen meiden):",
  "beheer.wie": "Wie",
  "beheer.bij_voorkeur_met_kies_een": "Bij voorkeur met (kies één of meer)",
  "beheer.span_class_muted_nog_geen": "<span class=\"muted\">Nog geen meiden.</span>",
  "beheer.heen": " – Heen",
  "beheer.terug": " – Terug",
  "beheer.bepaal_per_shift_in_welke": "Bepaal per shift in welke volgorde beschikbare chauffeurs worden voorgesteld.",
  "beheer.shift": "Shift",
  "beheer.geen_beschikbare_chauffeurs_voor_deze": "Geen beschikbare chauffeurs voor deze shift.",
  "beheer.pl": "pl.)",
  "beheer.volgorde_opgeslagen": "Volgorde opgeslagen ✓",
  "beheer.deze_pagina_is_alleen_voor": "Deze pagina is alleen voor de coördinator.",
  "beheer.mogelijk_dubbele_gezinnen_controleer_en": "Mogelijk dubbele gezinnen — controleer en verwijder de onjuiste:",
  "beheer.wijzig": "Wijzig",
  "beheer.testweergave_als_deze_ouder": "Testweergave als deze ouder",
  "beheer.span_class_badge_gekoppeld_span": "<span class=\"badge\">gekoppeld</span>",
  "beheer.span_class_badge_rec_coordinator": "<span class=\"badge rec\">COÖRDINATOR</span>",
  "beheer.geen": "Geen",
  "beheer.en": " en ",
  "beheer.deze_ouder": "deze ouder",
  "beheer.nog_geen_gezinnen_toegevoegd": "Nog geen gezinnen toegevoegd.",
  "beheer.gezinnen_beheren": "Gezinnen beheren",
  "beheer.vul_of_wijzig_gegevens_namens": "Vul of wijzig gegevens namens een andere ouder. Telefoonnummers en uitnodigingscode staan onder \"Wijzig\", net als de coördinator-koppeling. Het oog-icoon toont de app zoals deze ouder hem ziet.",
  "beheer.nieuw_gezin_toevoegen": "+ Nieuw gezin toevoegen",
  "beheer.selectievolgorde_per_shift": "Selectievolgorde per shift",
  "beheer.reisvoorkeuren": "Reisvoorkeuren",
  "beheer.wie_er_logistiek_het_beste": "Wie er logistiek het beste samen in 1 auto kan; wordt meegewogen bij het opsplitsen in auto's.",
  "beheer.beschikbaarheid_chauffeurs_weekoverzicht": "Beschikbaarheid chauffeurs (weekoverzicht)",
  "beheer.planning_instellingen": "Planning-instellingen",
  "beheer.deze_regels_bepalen_hoe_combinaties": "Deze regels bepalen hoe combinaties in het Rooster worden voorgesteld. Wijzigingen worden automatisch opgeslagen.",
  "beheer.max_tijdsverschil_voor_1_auto": "Max. tijdsverschil voor 1 auto (uur)",
  "beheer.rijtijd_aalsmeer_alkmaar_min_vertrektijd": "Rijtijd Aalsmeer→Alkmaar (min, vertrektijd heen)",
  "beheer.marge_reisvookeuren_min": "Marge reisvookeuren (min)",
  "beheer.max_wachttijd_om_met_eigen": "Max. wachttijd om met eigen ouder te rijden (min)",
  "beheer.wedstrijdkalenders_google_calendar": "Wedstrijdkalenders (Google Calendar)",
  "beheer.deze_agenda_s_voeden_wedstrijden": "Deze agenda's voeden \"Wedstrijden deze week\" (Mijn week) en \"Wedstrijdcarpool komende dagen\" (Wijzigen). Elke agenda moet openbaar (\"Make available to public\") staan — Google Calendar → tandwiel bij de agenda → Instellingen en delen → Toegangsrechten.",
  "beheer.nieuwe_kalender_toevoegen": "+ Nieuwe kalender toevoegen",
  "beheer.nu_verversen": "Nu verversen",
  "beheer.meldingen_bij_gewijzigde_tijden": "Meldingen bij gewijzigde tijden",
  "beheer.als_een_ouder_de_aankomst": "Als een ouder de aankomst- of ophaaltijd van een dochter aanpast, zie je dat bovenaan het Rooster (met een teller op het Rooster-tabje). Zet hieronder ook meldingen van je browser aan om een seintje te krijgen terwijl de app open staat op de achtergrond.",
  "beheer.beheerderstools": "Beheerderstools",
  "beheer.alles_wissen_pdf_gegevens_laden": "Alles wissen &amp; PDF-gegevens laden",
  "beheer.naam": "Naam",
  "beheer.calendar_id": "Calendar ID",
  "beheer.xxxx_group_v_calendar_google": "xxxx@group.v.calendar.google.com",
  "beheer.verwijder_kalender": "Verwijder kalender",
  "beheer.laatst_opgehaald": "Laatst opgehaald:",
  "beheer.mislukt": " — mislukt: ",
  "beheer.browsermeldingen_staan_aan_op_dit": "Browsermeldingen staan aan op dit apparaat.",
  "beheer.browsermeldingen_zijn_geblokkeerd_zet_ze": "Browsermeldingen zijn geblokkeerd — zet ze aan in de instellingen van je browser.",
  "beheer.browsermeldingen_aanzetten": "Browsermeldingen aanzetten",
  "beheer.deze_browser_ondersteunt_geen_meldingen": "Deze browser ondersteunt geen meldingen.",
  "beheer.kies_minstens_2_meiden": "Kies minstens 2 meiden.",
  "beheer.toegevoegd": "Toegevoegd ✓",
  "beheer.kies_een_meisje_en_minstens": "Kies een meisje en minstens 1 voorkeur.",
  "beheer.verwijderen_mislukt": "Verwijderen mislukt: ",
  "beheer.zeker_nogmaals_klikken": "Zeker? Nogmaals klikken",
  "beheer.verwijderd": "Verwijderd ✓",
  "beheer.wedstrijden_verversen": "Wedstrijden verversen…",
  "beheer.zeker_alles_wordt_gewist_klik": "Zeker?! Alles wordt gewist — klik nogmaals",
  "beheer.fout_bij_koppelen_knoppen": "Fout bij koppelen knoppen: ",
  "beheer.span_class_muted_nog_geen_2": "<span class=\"muted\">Nog geen coördinator</span>",
  "beheer.coordinator_intrekken": "Coördinator intrekken",
  "beheer.maak_coordinator": "Maak coördinator",
  "beheer.maak_coordinator_2": " Maak coördinator",
  "beheer.uitnodigingscode_meerdere_mensen_kunnen_dezelfde": "Uitnodigingscode (meerdere mensen kunnen dezelfde code gebruiken)",
  "beheer.nieuwe_code": "Nieuwe code",
  "beheer.sluiten": "Sluiten",
  "beheer.wijzigingen_worden_automatisch_opgeslagen": "Wijzigingen worden automatisch opgeslagen.",
  "beheer.nieuw_gezin_toevoegen_2": "Nieuw gezin toevoegen",
  "beheer.bewerken": "Bewerken: ",
  "beheer.let_op_jij_bent_hier": "Let op: jij bent hier zelf niet aan gekoppeld — klik nogmaals om toch door te gaan",
  "beheer.zeker_de_coordinator_rol_gaat": "Zeker? De coördinator-rol gaat dan alleen nog via dit apparaat",
  "beheer.bezig_met_wissen": "Bezig met wissen…",
  "beheer.bezig_met_invullen": "Bezig met invullen…",
  "beheer.ouder_van": "Ouder van ",
  "beheer.had_wel_een_tijd_onverwacht": " had wel een tijd (onverwacht)",
  "beheer.mist_een_tijd": " mist een tijd",
  "beheer.fout_tijdens_laden": "Fout tijdens laden: ",
  "beheer.gezien": "Gezien",
  "beheer.door": "door ",
  "beheer.gewijzigde_tijden": "Gewijzigde tijden (",
  "beheer.deze_ouders_hebben_hun_aankomst": "Deze ouders hebben hun aankomst- of ophaaltijden aangepast. Controleer het rooster en markeer ze daarna als gezien.",
  "beheer.alles_gezien": "Alles gezien",
  "beheer.zeker_klik_nogmaals": "Zeker? Klik nogmaals",
  "beheer.van": " van ",
  "beheer.az_carpool": "AZ Carpool",
  // common
  "common.annuleren": "Annuleren",
  "common.laatst_bijgewerkt_door": "Laatst bijgewerkt door:",
  "common.licht_thema_aanzetten": "Licht thema aanzetten",
  "common.donker_thema_aanzetten": "Donker thema aanzetten",
  "common.installeer_de_app": "Installeer de app",
  "common.zet_az_carpool_op_je": "Zet AZ Carpool op je beginscherm voor snelle toegang, net als een echte app.",
  "common.installeer_app": "Installeer app",
  "common.zet_az_carpool_op_je_2": "Zet AZ Carpool op je beginscherm: tik onderin Safari op het deel-icoon, kies daarna",
  "common.zet_op_beginscherm": "\"Zet op beginscherm\"",
  "common.geen_verbinding": "Geen verbinding",
  "common.kan_geen_verbinding_maken_met": "Kan geen verbinding maken met de database. Dit betekent meestal dat het Firebase-configuratieblok bovenaan het bestand nog niet is ingevuld, of dat er geen internetverbinding is.",
  "common.foutmelding": "Foutmelding:",
  "common.coordinator": " (Coördinator)",
  "common.nog_niet_gekoppeld_ga_naar": "Nog niet gekoppeld — ga naar Mijn gezin",
  // coordinator
  "coordinator.coordinator": "Coördinator",
  // data
  "data.fout_bij_laden_gezinnen": "Fout bij laden gezinnen: ",
  "data.fout_bij_laden_rooster": "Fout bij laden rooster: ",
  "data.fout_bij_laden_instellingen": "Fout bij laden instellingen: ",
  "data.fout_bij_laden_voorkeuren": "Fout bij laden voorkeuren: ",
  "data.fout_bij_laden_prioriteit": "Fout bij laden prioriteit: ",
  "data.fout_bij_laden_wijzigingen": "Fout bij laden wijzigingen: ",
  "data.uitnodigingscodes_beveiligd": "Uitnodigingscodes beveiligd ✓",
  "data.migratie_uitnodigingscodes_mislukt": "Migratie uitnodigingscodes mislukt: ",
  "data.geen_verbinding_met_opslag": "Geen verbinding met opslag.",
  "data.opslaan_mislukt": "Opslaan mislukt: ",
  "data.coordinator_rol_nu_alleen_via": "Coördinator-rol nu alleen via dit apparaat",
  "data.coordinator_ingesteld": "Coördinator ingesteld ✓",
  "data.mislukt": "Mislukt: ",
  "data.let_op_er_bestaat_al": "Let op: er bestaat al een gezin met de naam '",
  "data.controleer_op_dubbelen": "' — controleer op dubbelen.",
  "data.opgeslagen": "Opgeslagen ✓",
  "data.code_alleen_letters_cijfers_en": "Code: alleen letters, cijfers en '-', 4–32 tekens.",
  "data.deze_code_is_al_in": "Deze code is al in gebruik bij een ander gezin — kies een andere.",
  "data.gemarkeerd_als_gezien": "Gemarkeerd als gezien ✓",
  "data.kon_groep_niet_opslaan_alleen": "Kon groep niet opslaan (alleen coördinator kan bewerken): ",
  "data.selecteer_minstens_1_dochter": "Selecteer minstens 1 dochter.",
  // deviation
  "deviation.nog_geen_chauffeur": "nog geen chauffeur",
  "deviation.meer_passagiers_dan_plekken": "Meer passagiers dan plekken",
  "deviation.verwijder_carpool": "Verwijder carpool",
  "deviation.geen_passagiers": "geen passagiers",
  "deviation.wedstrijdcarpool_komende_dagen": "Wedstrijdcarpool komende dagen",
  "deviation.geen_wedstrijden_gevonden": "Geen wedstrijden gevonden.",
  "deviation.p_class_muted_style_font": "<p class=\"muted\" style=\"font-size:12px;margin:4px 0 0\">Nog geen carpool ingesteld.</p>",
  "deviation.chauffeur": "Chauffeur",
  "deviation.kies": "-- kies --",
  "deviation.welke_passagiers": "Welke passagiers?",
  "deviation.vertrektijd": "Vertrektijd",
  "deviation.opslaan": "Opslaan",
  "deviation.auto_toevoegen": "+ Auto toevoegen",
  "deviation.zet_een_carpool_op_voor": "Zet een carpool op voor een wedstrijd. Iedereen kan dit doen en aanpassen",
  "deviation.kies_een_chauffeur": "Kies een chauffeur.",
  "deviation.kies_minstens_1_dochter": "Kies minstens 1 dochter.",
  "deviation.toch_opslaan": "Toch opslaan",
  "deviation.kon_deze_wedstrijd_niet_vinden": "Kon deze wedstrijd niet vinden — herlaad de pagina.",
  "deviation.carpool_toegevoegd": "Carpool toegevoegd ✓",
  "deviation.deel_update_via_whatsapp": "Deel update via WhatsApp",
  "deviation.wijzigen": "Wijzigen",
  "deviation.kon_je_account_niet_herkennen": "Kon je account niet herkennen. Herlaad de pagina.",
  "deviation.wijzigingen": "Wijzigingen ·",
  "deviation.eenmalige_ritaanpassing_voor_deze_week": "Eenmalige ritaanpassing voor deze week (ziek, rijbeurt ruilen, etc). Het standaardrooster blijft intact; wijzigingen worden elk weekend automatisch gewist.",
  "deviation.kies_een_dag": "Kies een dag",
  "deviation.gewijzigd": ", gewijzigd",
  "deviation.wedstrijdcarpool": ", wedstrijdcarpool",
  "deviation.span_class_devdaydot_aria_hidden": "<span class=\"devDayDot\" aria-hidden=\"true\"></span>",
  "deviation.wedstrijdcarpool_op_deze_dag": "Wedstrijdcarpool op deze dag",
  "deviation.deze_week_gewijzigd": "= deze week gewijzigd",
  "deviation.wijziging": "Wijziging —",
  "deviation.andere_dag": "Andere dag",
  "deviation.wijzigingen_hier_gelden_alleen_voor": "Wijzigingen hier gelden alleen voor",
  "deviation.deze_week_en_verdwijnen_dit": "deze week en verdwijnen dit weekend vanzelf.",
  "deviation.wedstrijdcarpool_2": "Wedstrijdcarpool",
  "deviation.alleen_lezen": "Alleen lezen",
  "deviation.extra_ritten_naar_een_wedstrijd": "Extra ritten naar een wedstrijd op deze dag.",
  "deviation.wedstrijdcarpool_aanpassen": "Wedstrijdcarpool aanpassen",
  "deviation.geen_chauffeur": "-- geen chauffeur --",
  "deviation.geen_beschikbaarheid": " (geen beschikbaarheid)",
  "deviation.verplaats_naar": "Verplaats naar…",
  "deviation.auto": "Auto:",
  "deviation.verwijder_uit_auto": "Verwijder uit auto",
  "deviation.p_class_muted_geen_passagiers": "<p class=\"muted\">Geen passagiers meer in deze auto.</p>",
  "deviation.vertrek": "Vertrek",
  "deviation.deze_ouder_heeft_voor_dit": "Deze ouder heeft voor dit moment geen beschikbaarheid opgegeven — controleer of dit echt klopt.",
  "deviation.geen_ritten_gepland_in_het": "Geen ritten gepland in het standaard Rooster voor dit moment.",
  "deviation.voeg_toe_aan_auto": "Voeg toe aan auto…",
  "deviation.andere_meiden": "Andere meiden",
  "deviation.ook_meiden_die_niet_standaard": "Ook meiden die niet standaard meerijden, kun je hier alsnog aan een auto toevoegen.",
  "deviation.span_class_muted_nog_geen": "<span class=\"muted\">Nog geen auto</span>",
  "deviation.terug_naar_standaard_rooster": "Terug naar standaard rooster",
  "deviation.verwijderd_uit_deze_auto": " verwijderd uit deze auto.",
  "deviation.verplaatst": " verplaatst.",
  "deviation.toegevoegd": " toegevoegd.",
  "deviation.zeker_terug_naar_standaard_rooster": "Zeker? Terug naar standaard rooster",
  "deviation.teruggezet_naar_standaard": "Teruggezet naar standaard ✓",
  // matches
  "matches.http": "HTTP ",
  // myweek
  "myweek.thuis": " (Thuis)",
  "myweek.uit": " (Uit)",
  "myweek.vs": "vs",
  "myweek.mijn_week": "Mijn week",
  "myweek.koppel_eerst_je_dochter_via": "Koppel eerst je dochter via 'Mijn gezin' om hier je weekoverzicht te zien.",
  "myweek.jouw_rijbeurt_om": "Jouw rijbeurt om",
  "myweek.wijziging_actief": "Wijziging actief",
  "myweek.wedstrijd": "Wedstrijd:",
  "myweek.aftrap": "Aftrap",
  "myweek.wedstrijd_2": "Wedstrijd",
  "myweek.span_class_todaytag_vandaag_span": "<span class=\"todayTag\">VANDAAG</span>",
  "myweek.geen_dagen_met_een_tijd": "Geen dagen met een tijd ingesteld deze week.",
  "myweek.kon_niet_ophalen": "Kon niet ophalen:",
  "myweek.p_class_muted_geen_wedstrijden": "<p class=\"muted\">Geen wedstrijden gevonden.</p>",
  "myweek.wedstrijden_deze_week": "Wedstrijden deze week",
  "myweek.carpool_regelen": "Carpool regelen",
  "myweek.niet_ingepland": "): niet ingepland",
  "myweek.regelen": "Regelen",
  "myweek.heeft_nog_geen_rit": "heeft nog geen rit",
  "myweek.je_dochter": "Je dochter",
  "myweek.ouder": "Ouder:",
  "myweek.passagiersplekken": "passagiersplekken",
  "myweek.deel_mijn_week_via_whatsapp": "Deel mijn week via WhatsApp",
  "myweek.deel_via_whatsapp": "Deel via WhatsApp",
  "myweek.rit_dochter": "Rit dochter",
  "myweek.jouw_rijbeurt": "Jouw rijbeurt",
  "myweek.wijziging": "Wijziging",
  "myweek.wedstrijdrit": "Wedstrijdrit",
  // profile
  "profile.testweergave_als": "Testweergave als:",
  "profile.stop_testen": "Stop testen",
  "profile.testweergave_gestart": "Testweergave gestart ✓",
  "profile.terug_naar_coordinatorweergave": "Terug naar coördinatorweergave ✓",
  "profile.heen_aankomst_alkmaar_nodig": "Heen: aankomst Alkmaar nodig",
  "profile.terug_klaar_om_op_te": "Terug: klaar om op te halen",
  "profile.kan_jij_deze_dag_rijden": "Kan jij deze dag rijden?",
  "profile.beschikbaar": "Beschikbaar",
  "profile.back_up": "Back-up",
  "profile.aankomst": "Aankomst: ",
  "profile.klaar": "Klaar: ",
  "profile.naam_ouder": "Naam ouder",
  "profile.naam_dochter": "Naam dochter",
  "profile.tel_nr_1": "Tel.nr. 1",
  "profile.tel_nr_2": "Tel.nr. 2",
  "profile.totale_autocapaciteit_incl_bestuurder": "Totale autocapaciteit (incl. bestuurder)",
  "profile.zitplaatsen_totaal": "zitplaatsen totaal",
  "profile.plek_voor": "Plek voor",
  "profile.passagiers": "passagiers",
  "profile.minder_zitplaatsen": "Minder zitplaatsen",
  "profile.meer_zitplaatsen": "Meer zitplaatsen",
  "profile.weekschema_beschikbaarheid_per_dag": "Weekschema &amp; beschikbaarheid per dag",
  "profile.zitplaatsen_totaal_2": " zitplaatsen totaal",
  "profile.welkom_bij_az_carpool": "Welkom bij AZ Carpool",
  "profile.er_is_nog_geen_coordinator": "Er is nog geen coördinator ingesteld voor deze app. Ben jij dat?",
  "profile.ik_ben_de_coordinator": "Ik ben de coördinator",
  "profile.ben_je_een_ouder_en": "Ben je een ouder en geen coördinator? Wacht tot de coördinator dit heeft ingesteld en de link met een uitnodigingscode met je deelt.",
  "profile.je_bent_nu_coordinator": "Je bent nu coördinator ✓",
  "profile.mislukt_mogelijk_had_iemand_anders": "Mislukt (mogelijk had iemand anders je net voor): ",
  "profile.laden": "Laden…",
  "profile.toegang_tot_az_carpool": "Toegang tot AZ Carpool",
  "profile.vul_je_telefoonnummer_en_de": "Vul je telefoonnummer en de code in die je van de coördinator hebt gekregen.",
  "profile.telefoonnummer": "Telefoonnummer",
  "profile.code": "Code",
  "profile.toegang_aanvragen": "Toegang aanvragen",
  "profile.code_van_de_coordinator": "Code van de coördinator",
  "profile.geen_verbinding_herlaad_de_pagina": "Geen verbinding. Herlaad de pagina.",
  "profile.vul_alle_velden_in": "Vul alle velden in.",
  "profile.code_klopt_niet_controleer_en": "Code klopt niet. Controleer en probeer opnieuw.",
  "profile.toegang_verleend": "Toegang verleend ✓",
  "profile.dit_telefoonnummer_hoort_niet_bij": "Dit telefoonnummer hoort niet bij deze code. Gebruik het nummer dat de coördinator van je heeft.",
  "profile.mijn_gezin": "Mijn gezin",
  "profile.ontkoppelen_van_deze_dochter": "Ontkoppelen van deze dochter",
  "profile.contactgegevens_autocapaciteit": "Contactgegevens &amp; autocapaciteit",
  "profile.gekoppeld_aan": "Gekoppeld aan:",
  "profile.welkom_selecteer_je_dochter_om": "Welkom! Selecteer je dochter om haar gegevens te bekijken en bij te werken. (Alleen de coördinator kan nieuwe gezinnen toevoegen; twee ouders kunnen dezelfde dochter selecteren.)",
  "profile.mijn_dochter": "Mijn dochter",
  "profile.dit_is_mijn_dochter": "Dit is mijn dochter",
  "profile.er_zijn_nog_geen_gezinnen": "Er zijn nog geen gezinnen toegevoegd door de coördinator.",
  "profile.zeker_tik_nogmaals_om_te": "Zeker? Tik nogmaals om te ontkoppelen",
  "profile.ontkoppeld": "Ontkoppeld ✓",
  "profile.gekoppeld": "Gekoppeld ✓",
  "profile.koppelen_mislukt": "Koppelen mislukt: ",
  "profile.geen_verbinding_met_opslag_herlaad": "Geen verbinding met opslag. Herlaad de pagina en probeer opnieuw.",
  "profile.je_account_kon_niet_herkend": "Je account kon niet herkend worden. Herlaad de pagina.",
  "profile.opgeslagen_de_coordinator_ziet_je": "Opgeslagen ✓ — de coördinator ziet je gewijzigde tijden",
  // schedule
  "schedule.rit": "rit",
  "schedule.span_class_daypilltoday_aria_hidden": "<span class=\"daypillToday\" aria-hidden=\"true\"></span>",
  "schedule.welk_rooster": "Welk rooster",
  "schedule.deze_week": "Deze week",
  "schedule.standaardrooster": "Standaardrooster",
  "schedule.tik_op_een_naam_om": " Tik op een naam om haar te verplaatsen.",
  "schedule.niet_ingedeeld": "niet ingedeeld",
  "schedule.voorstellen": "Voorstellen",
  "schedule.reserve": "Reserve:",
  "schedule.geen_chauffeur": "Geen chauffeur",
  "schedule.jij_rijdt": "Jij rijdt",
  "schedule.chauffeur": "Chauffeur:",
  "schedule.minedriving": " mineDriving",
  "schedule.plekken": "plekken",
  "schedule.geen_ritten": "Geen ritten.",
  "schedule.gewijzigd": "gewijzigd",
  "schedule.kies_chauffeur": "-- kies chauffeur --",
  "schedule.verwijder_auto": "Verwijder auto",
  "schedule.geen_plek_meer_in_deze": "Geen plek meer in deze auto (",
  "schedule.bezet_wil_je": "bezet). Wil je",
  "schedule.wisselen_met_een_andere_passagier": "wisselen met een andere passagier?",
  "schedule.wissel_met_welke_passagier": "Wissel met welke passagier",
  "schedule.wissel": "Wissel",
  "schedule.nog_geen_ritten_ingepland": "Nog geen ritten ingepland.",
  "schedule.voorstellen_2": "Voorstellen:",
  "schedule.optie": "Optie",
  "schedule.gebruik_deze_optie": "Gebruik deze optie",
  "schedule.primary": " primary",
  "schedule.span_class_badge_rec_aanbevolen": "<span class=\"badge rec\">AANBEVOLEN</span> ",
  "schedule.secondary": " secondary",
  "schedule.geen_enkele_chauffeur_scombinatie_heeft": "Geen enkele chauffeur(scombinatie) heeft genoeg plek voor",
  "schedule.deze_meid": "deze meid",
  "schedule.aangepaste_combinatie": "Aangepaste combinatie",
  "schedule.nieuwe_auto_met_deze_meiden": "Nieuwe auto met deze meiden",
  "schedule.iedereen_is_ingedeeld": "Iedereen is ingedeeld.",
  "schedule.zie_deze_week": "Zie 'Deze week'",
  "schedule.deze_week_gewijzigd": "deze week gewijzigd",
  "schedule.verplaatst": " verplaatst ✓",
  "schedule.verplaatsen_mislukt": "Verplaatsen mislukt: ",
  "schedule.geen_chauffeur_2": "geen chauffeur",
  "schedule.vol_je_kunt_wisselen": " · vol, je kunt wisselen",
  "schedule.een_van_de_auto_s": "Een van de auto's bestaat niet meer.",
  "schedule.toevoegen_mislukt": "Toevoegen mislukt: ",
  "schedule.chauffeur_gewisseld_dubbele_boeking_automatisch": "Chauffeur gewisseld — dubbele boeking automatisch opgelost ✓",
  "schedule.chauffeur_gewisseld": "Chauffeur gewisseld ✓",
  "schedule.wisselen_mislukt": "Wisselen mislukt: ",
  "schedule.aanpassen_mislukt": "Aanpassen mislukt: ",
  "schedule.kies_wie_je_wilt_wisselen": "Kies wie je wilt wisselen.",
  "schedule.gewisseld": "Gewisseld ✓",
  "schedule.fout_bij_koppelen_roosterknoppen": "Fout bij koppelen roosterknoppen: ",
  // ---- added by hand ----
  "app.verbinden": "Verbinden…",
  "coordinator.onbekend": "Onbekend",
  "common.ouder": "Ouder",
  "deviation.opslaan": "Opslaan",
  "myweek.vandaag": "Vandaag",
  "matches.geen_api_key": "Geen Google Calendar API-key ingesteld in firebase-config.js.",
  // ---- Static page texts (index.html data-i18n attributes) ----
  "app.title": "AZ Carpool",
  "app.route": "Aalsmeer – Alkmaar ·",
  "app.loading": "Laden…",
  "nav.main": "Hoofdnavigatie",
  "nav.rooster": "Rooster",
  "nav.myweek": "Mijn week",
  "nav.deviation": "Wijzigen",
  "nav.profile": "Mijn gezin",
  "nav.beheer": "Beheer",
  // ---- Messages with placeholders (from the original text; {p1}, {p2}... are filled in by the code) ----
  "dates.week": "Week {p1} · {p2} – {p3}",
  "beheer.samen_reizen_2": "Samen reizen: {p1}",
  "beheer.klaar_gezinnen_aangemaakt_alle_dagen": "{p1} Klaar: {p2} gezinnen aangemaakt, alle dagen ingevuld behalve Robbin/Woensdag (zoals verwacht).",
  "beheer.gezinnen_aangemaakt_maar_validatie_vond": "{p1} {p2} gezinnen aangemaakt, maar validatie vond afwijkingen: {p3}",
  "beheer.nieuwe_tijdswijziging_zie_rooster": "Nieuwe tijdswijziging{p1} — zie Rooster",
  "deviation.heeft_maar_je_hebt_passagiers": "{p1} {p2} heeft {p3} {p4}, maar je hebt {p5} passagiers gekozen.",
  "deviation.te_veel_passagiers_tik_nogmaals": "Te veel passagiers ({p1}/{p2}). Tik nogmaals op \"Toch opslaan\" om door te gaan.",
  "deviation.deze_auto_zit_nu_vol": "Deze auto zit nu vol ({p1}/{p2}) — verplaatsing is wel doorgevoerd.",
  "deviation.deze_auto_zit_nu_vol_2": "Deze auto zit nu vol ({p1}/{p2}) — toevoeging is wel doorgevoerd.",
  "myweek.jij_rijdt": "{p1}{p2} Jij rijdt{p3}",
  "myweek.rijdt_mee_met": "{p1} Rijdt mee met: {p2}",
  "myweek.niet_ingepland_2": "{p1} niet ingepland",
  "schedule.niet_ingedeeld_2": ", {p1} niet ingedeeld",
  "schedule.het_standaardrooster_met_de_wijzigingen": "{p1} — het standaardrooster mét de wijzigingen van deze week.",
  "schedule.het_vaste_rooster_elke_week": "Het vaste rooster, elke week gelijk.{p1}",
  "schedule.aankomst_alkmaar_nodig": "Aankomst Alkmaar nodig: {p1}",
  "schedule.klaar_om_op_te_halen": "Klaar om op te halen: {p1}",
  "schedule.nog_niet_ingedeeld": "Nog niet ingedeeld: {p1}.",
  "schedule.nog_niet_ingedeeld_2": "Nog niet ingedeeld ({p1}): {p2}.",
  "schedule.toevoegen_aan_auto": "Toevoegen aan auto {p1} ({p2})",
  "schedule.toevoegen_aan_bestaande_auto_s": "Toevoegen aan bestaande auto's",
  "schedule.nieuwe_auto": "Nieuwe auto: {p1}",
  "schedule.vertrek": "Vertrek {p1}{p2}{p3}",
  "schedule.plekken_2": " · {p1}/{p2} plekken",
  "schedule.kies_een_andere_auto": "{p1} · {p2} — kies een andere auto:",
  // ---- added by hand (2) ----
  "common.plek": "plek",
  "common.plekken": "plekken",
  "dir.heenShort": "Heen",
  "dir.terugShort": "Terug",
  "deviation.gekozen": "{n} gekozen",
  "schedule.verplaats": "Verplaats {p1}",
  "schedule.auto_regel": "Auto {p1}: {p2} ({p3}/{p4} pl., vertrek {p5})",
  "schedule.deze_n_meiden": "deze {p1} meiden",
  "schedule.auto_label": "Auto {p1} · {p2}",
  "beheer.voorkeur_met": "Voorkeur: {p1} met {p2}",
  "common.onbekend": "onbekend",
};
