// ui-beheer.js — generated by the modularisation of index.html; see README for what lives where.
import { t, locale } from './i18n.js';
import { S } from './state.js';
import { DAYS, PDF_SEED } from './constants.js';
import { dayUp } from './dates.js';
import { availableDrivers, fam, girlName, seats, sortByShiftPriority } from './rides.js';
import { esc, hapticTap, phIcon, showToast, twoStepConfirm } from './ui-common.js';
import { db, doToggleCoord, markTimeChangesSeen, saveCoordFamily } from './data.js';
import { activeMatchFeeds, loadAllMatches } from './matches.js';
import { familyFormHtml, startImpersonate, wireExclusiveAvailability, wireFamilyFormExtras } from './ui-profile.js';
import { genCode, slugify } from './coordinator.js';
import { collectPendingChanges, countPendingChanges, describeChange } from './schedule-changes.js';
import { renderSchedule } from './ui-schedule.js';

export function renderAvailabilityTable(){
  const rows = Object.entries(S.families).sort((a,b)=>(a[1].parentName||'').localeCompare(b[1].parentName||''));
  if(!rows.length) return `<p class="muted">${t('beheer.nog_geen_gezinnen')}</p>`;
  const head = `<tr><th style="text-align:left">${t('beheer.ouder')}</th>${DAYS.map(([k])=>`<th colspan="2">${dayUp(k)}</th>`).join('')}</tr>
    <tr><th></th>${DAYS.map(()=>`<th style="font-size:11px;color:var(--muted)">H</th><th style="font-size:11px;color:var(--muted)">T</th>`).join('')}</tr>`;
  const body = rows.map(([id,f])=>{
    const cells = DAYS.map(([k])=>{
      const a=(f.availability&&f.availability[k])||{};
      // Standaard = solid green cell; back-up = plain grey number.
      const cellFor = (isDefault,isBackup) => isDefault
        ? `<span class="availStd">${seats(f)}</span>`
        : isBackup ? `<span style="color:var(--backup);font-weight:500">${seats(f)}</span>` : t('beheer.span_class_muted_span');
      return `<td style="text-align:center">${cellFor(a.heen,a.backupHeen)}</td><td style="text-align:center">${cellFor(a.terug,a.backupTerug)}</td>`;
    }).join('');
    return `<tr style="border-top:1px solid var(--border)"><td>${esc(f.parentName||'?')}</td>${cells}</tr>`;
  }).join('');
  return `<div style="overflow-x:auto"><table class="avail">${head}${body}</table></div>
    <p class="muted" style="margin-top:6px"><span class="availStd">4</span> ${t('beheer.groen_vlak_standaard_beschikbaar')} <span style="color:var(--backup);font-weight:500">4</span> ${t('beheer.grijs_cijfer_back_up_indien')}</p>`;
}

export function renderPrefsCard(){
  const girls = Object.entries(S.families).filter(([id,f])=>f.girlName);
  const ruleRows = (S.prefs.rules||[]).map((r,i)=>{
    const label = r.type==='together'
      ? t('beheer.samen_reizen_2', { p1: (r.ids||[]).map(id=>girlName(id)).join(' &amp; ') })
      : t('beheer.voorkeur_met',{p1:girlName(r.girlId),p2:(r.withAny||[]).map(id=>girlName(id)).join(t('beheer.of'))});
    return `<div class="rowflex" style="padding:6px 0;border-bottom:1px solid var(--border)"><span style="font-size:13px">${label}</span><button type="button" class="iconbtn danger" data-delpref="${i}" aria-label="${t('beheer.voorkeur_verwijderen')}" title="${t('beheer.verwijder')}">${phIcon('trash')}</button></div>`;
  }).join('') || `<p class="muted">${t('beheer.nog_geen_voorkeuren')}</p>`;
  const togetherChecks = girls.map(([id,f])=>`<label class="chip"><input type="checkbox" class="prefTogetherPick" value="${id}">${esc(f.girlName)}</label>`).join('');
  const preferSelect = `<select id="preferGirlSelect">${girls.map(([id,f])=>`<option value="${id}">${esc(f.girlName)}</option>`).join('')}</select>`;
  const preferChecks = girls.map(([id,f])=>`<label class="chip"><input type="checkbox" class="prefWithPick" value="${id}">${esc(f.girlName)}</label>`).join('');
  return `${ruleRows}
    <hr style="border:none;border-top:1px solid var(--border);margin:12px 0">
    <p class="muted"><strong>${t('beheer.samen_reizen')}</strong> ${t('beheer.moeten_altijd_samen_in_1')}</p>
    <div>${togetherChecks || t('beheer.span_class_muted_nog_geen')}</div>
    <button type="button" class="btn small secondary" id="addTogetherPref">${t('beheer.toevoegen')}</button>
    <p class="muted" style="margin-top:14px"><strong>${t('beheer.voorkeur')}</strong> ${t('beheer.moet_met_minstens_een_van')}</p>
    <label>${t('beheer.wie')}</label>${preferSelect}
    <label>${t('beheer.bij_voorkeur_met_kies_een')}</label><div>${preferChecks || t('beheer.span_class_muted_nog_geen')}</div>
    <button type="button" class="btn small secondary" id="addPreferPref">${t('beheer.toevoegen')}</button>`;
}

export function renderPriorityCard(){
  const shifts=[];
  DAYS.forEach(([k,label])=>{ shifts.push([k+'_heen', label+t('beheer.heen')]); shifts.push([k+'_terug', label+t('beheer.terug')]); });
  const options = shifts.map(([key,label])=>`<option value="${key}" ${key===S.selectedShiftKey?'selected':''}>${label}</option>`).join('');
  return `<p class="muted">${t('beheer.bepaal_per_shift_in_welke')}</p>
    <label>${t('beheer.shift')}</label><select id="shiftPrioritySelect">${options}</select>
    <div id="shiftPriorityRows" style="margin-top:8px"></div>`;
}

export function renderShiftPriorityRows(shiftKeyVal){
  const div=document.getElementById('shiftPriorityRows');
  if(!div) return;
  const [day,direction]=shiftKeyVal.split('_');
  const rows = sortByShiftPriority(day,direction, availableDrivers(day,direction));
  if(!rows.length){ div.innerHTML=`<p class="muted">${t('beheer.geen_beschikbare_chauffeurs_voor_deze')}</p>`; return; }
  div.innerHTML = rows.map(([id,f],i)=>`
    <div class="rowflex" style="padding:8px 6px;border-bottom:1px solid var(--border)">
      <span>${i+1}. ${esc(f.parentName||'?')} <span class="muted">(${esc(f.girlName||'')}, ${seats(f)} ${t('beheer.pl')}</span></span>
      <span style="display:flex;gap:4px">
        <button type="button" class="iconbtn" data-prioup="${id}" aria-label="${esc(f.parentName||'chauffeur')} hoger in prioriteit" ${i===0?'disabled':''}>${phIcon('arrow-up')}</button>
        <button type="button" class="iconbtn" data-priodown="${id}" aria-label="${esc(f.parentName||'chauffeur')} lager in prioriteit" ${i===rows.length-1?'disabled':''}>${phIcon('arrow-down')}</button>
      </span>
    </div>`).join('');
  const ids=rows.map(([id])=>id);
  div.querySelectorAll('[data-prioup]').forEach(btn=>btn.onclick=()=>movePriority(shiftKeyVal,ids,btn.dataset.prioup,-1));
  div.querySelectorAll('[data-priodown]').forEach(btn=>btn.onclick=()=>movePriority(shiftKeyVal,ids,btn.dataset.priodown,1));
}

export async function movePriority(shiftKeyVal,ids,id,delta){
  const idx=ids.indexOf(id);
  const newIdx=idx+delta;
  if(newIdx<0||newIdx>=ids.length) return;
  const newIds=[...ids];
  [newIds[idx],newIds[newIdx]]=[newIds[newIdx],newIds[idx]];
  const map={}; newIds.forEach((gid,i)=>map[gid]=i+1);
  if(!db){showToast(t('data.geen_verbinding_met_opslag'));return;}
  try{ await db.doc("settings/priority").set({...S.shiftPriority,[shiftKeyVal]:map}); showToast(t('beheer.volgorde_opgeslagen')); }
  catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
}

// US-02: one family per weekday who handles change requests. Stored as familyIds in settings/dayCoordinators;
// names are read from the families, so renaming a parent in Beheer updates every screen.
export function dayCoordinatorsCardHtml(){
  const fams = Object.entries(S.families).sort((a,b)=>(a[1].parentName||'').localeCompare(b[1].parentName||'', locale()));
  const rows = DAYS.map(([k,label])=>{
    const cur = S.dayCoordinators[k]||'';
    return `<div class="rowflex" style="align-items:center;gap:8px;margin-top:6px">
      <label style="margin:0;width:96px" for="dayCoord_${k}">${label}</label>
      <select id="dayCoord_${k}" class="dayCoordSel" data-coordday="${k}" style="flex:1">
        <option value="">${t('dayCoord.none')}</option>
        ${fams.map(([id,f])=>`<option value="${id}" ${id===cur?'selected':''}>${esc(f.parentName||id)} (${esc(f.girlName||'?')})</option>`).join('')}
      </select>
    </div>`;
  }).join('');
  return `<div class="card" id="dayCoordCard">
      <h2>${t('dayCoord.beheerTitle')}</h2>
      <p class="muted">${t('dayCoord.beheerIntro')}</p>
      ${rows}
    </div>`;
}

export async function saveDayCoordinator(day, familyId){
  if(!db){ showToast(t('data.geen_verbinding_met_opslag')); return false; }
  const next = {...S.dayCoordinators};
  if(familyId) next[day]=familyId; else delete next[day];
  try{
    await db.doc("settings/dayCoordinators").set(next);
    S.dayCoordinators = next;
    showToast(t('dayCoord.saved'));
    return true;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

export function renderBeheer(){
  const box=document.getElementById('tab-beheer');
  if(!box) return;
  if(!S.canEdit){ box.innerHTML = `<div class="card"><p class="muted">${t('beheer.deze_pagina_is_alleen_voor')}</p></div>`; return; }

  const claimed = {}; Object.entries(S.links).forEach(([uid,l])=>claimed[l.familyId]=true);
  const byName={};
  Object.entries(S.families).forEach(([id,fd])=>{
    const key=(fd.girlName||'').trim().toLowerCase();
    if(key) (byName[key]=byName[key]||[]).push([id,fd]);
  });
  const dupGroups = Object.values(byName).filter(list=>list.length>1);
  const dupWarning = dupGroups.length? `<div class="group warning" style="margin-bottom:10px">
      <div class="fitbad">${phIcon('warning')} ${t('beheer.mogelijk_dubbele_gezinnen_controleer_en')}</div>
      ${dupGroups.map(list=>`<div style="margin-top:6px"><strong>${esc(list[0][1].girlName)}</strong> (${list.length}x):<br>${list.map(([id,fd])=>`<span class="pill">${esc(fd.parentName||id)} <button type="button" class="iconbtn danger" data-coorddel="${id}" style="margin-left:4px;min-width:30px;min-height:30px" aria-label="${t('beheer.verwijder')}" title="${t('beheer.verwijder')}">${phIcon('trash')}</button></span>`).join(' ')}</div>`).join('')}
    </div>` : '';
  const rows = Object.entries(S.families).map(([id,fd])=>{
    const isCoord = S.coordinatorConfig && S.coordinatorConfig.familyId===id;
    // Phone numbers and invite codes are only shown inside "Wijzig"; the list only flags what's missing.
    const missing = [!fd.parentPhone1&&!fd.parentPhone2? 'telefoonnummer' : '', !S.inviteByFamily[id]? 'code' : ''].filter(Boolean);
    return `
    <div class="rowflex" style="padding:10px 0;border-bottom:1px solid var(--border);gap:8px">
      <div style="flex:1;min-width:0">
        <div style="font-size:15px;font-weight:800">${esc(fd.girlName||'(naam?)')}</div>
        <div class="muted">${esc(fd.parentName||'(ouder?)')} ${claimed[id]?t('beheer.span_class_badge_gekoppeld_span'):''} ${isCoord?t('beheer.span_class_badge_rec_coordinator'):''}${fd.familyType==='flex'? ` <span class="badge flexBadge">${t('flex.badge')}</span>` : ''}</div>
        ${missing.length? `<div class="fitbad" style="font-size:11px;margin-top:2px">${phIcon('warning')} ${t('beheer.geen')} ${missing.join(t('beheer.en'))}</div>` : ''}
      </div>
      <span style="display:flex;gap:6px;flex-shrink:0">
        <button type="button" class="btn small secondary" data-coordedit="${id}">${t('beheer.wijzig')}</button>
        <button type="button" class="iconbtn" data-imptest="${id}" aria-label="Test de app als ${esc(fd.parentName||t('beheer.deze_ouder'))}" title="${t('beheer.testweergave_als_deze_ouder')}">${phIcon('eye')}</button>
        <button type="button" class="iconbtn danger" data-coorddel="${id}" aria-label="Verwijder ${esc(fd.girlName||'gezin')}" title="${t('beheer.verwijder')}">${phIcon('trash')}</button>
      </span>
    </div>`;
  }).join('') || `<p class="muted">${t('beheer.nog_geen_gezinnen_toegevoegd')}</p>`;

  box.innerHTML = `
    <div class="card">
      <h2>${t('beheer.gezinnen_beheren')}</h2>
      <p class="muted">${t('beheer.vul_of_wijzig_gegevens_namens')}</p>
      ${dupWarning}
      ${rows}
      <button type="button" class="btn secondary" id="coordNew">${t('beheer.nieuw_gezin_toevoegen')}</button>
      <div id="coordEditArea"></div>
    </div>
    <div class="card">
      <h2>${t('beheer.selectievolgorde_per_shift')}</h2>
      ${renderPriorityCard()}
    </div>
    <div class="card">
      <h2>${t('beheer.reisvoorkeuren')}</h2>
      <p class="muted">${t('beheer.wie_er_logistiek_het_beste')}</p>
      ${renderPrefsCard()}
    </div>
    ${dayCoordinatorsCardHtml()}
    <div class="card">
      <h2>${t('beheer.beschikbaarheid_chauffeurs_weekoverzicht')}</h2>
      ${renderAvailabilityTable()}
    </div>
    <div class="card">
      <h2>${t('beheer.planning_instellingen')}</h2>
      <p class="muted">${t('beheer.deze_regels_bepalen_hoe_combinaties')}</p>
      <div class="grid4">
        <div><label>${t('beheer.max_tijdsverschil_voor_1_auto')}</label><input type="number" id="setGap" min="0.5" step="0.5" value="${S.settings.gapThresholdHours}"></div>
        <div><label>${t('beheer.rijtijd_aalsmeer_alkmaar_min_vertrektijd')}</label><input type="number" id="setLead" min="0" step="5" value="${S.settings.travelLeadMinutes}"></div>
        <div><label>${t('beheer.marge_reisvookeuren_min')}</label><input type="number" id="setPrefWindow" min="0" step="5" value="${S.settings.prefWindowMinutes}"></div>
        <div><label>${t('beheer.max_wachttijd_om_met_eigen')}</label><input type="number" id="setParentPrefWindow" min="0" step="5" value="${S.settings.parentPrefWindowMinutes}"></div>
      </div>
    </div>
    <div class="card">
      <h2>${t('beheer.wedstrijdkalenders_google_calendar')}</h2>
      <p class="muted">${t('beheer.deze_agenda_s_voeden_wedstrijden')}</p>
      ${activeMatchFeeds().map((f,i)=>`
        <div class="rowflex" style="margin-top:6px;align-items:flex-end;gap:6px">
          <div class="grid2" style="flex:1">
            <div><label style="margin-top:0">${t('beheer.naam')}</label><input type="text" class="matchFeedLabel" data-feedidx="${i}" value="${esc(f.label)}"></div>
            <div><label style="margin-top:0">${t('beheer.calendar_id')}</label><input type="text" class="matchFeedCalId" data-feedidx="${i}" value="${esc(f.calendarId)}" placeholder="${t('beheer.xxxx_group_v_calendar_google')}"></div>
          </div>
          <button type="button" class="iconbtn danger" data-delfeed="${i}" aria-label="${t('beheer.verwijder_kalender')}" title="${t('beheer.verwijder_kalender')}">${phIcon('trash')}</button>
        </div>`).join('')}
      <button type="button" class="btn small secondary" id="addMatchFeedBtn" style="margin-top:8px">${t('beheer.nieuwe_kalender_toevoegen')}</button>
      <button type="button" class="btn small secondary" id="refreshMatchesBtn" style="margin-top:8px">${phIcon('refresh')} ${t('beheer.nu_verversen')}</button>
      ${S.matchesFetchedAt? `<p class="muted" style="font-size:11px;margin-top:6px">${t('beheer.laatst_opgehaald')} ${new Date(S.matchesFetchedAt).toLocaleString(locale())}${S.matchFetchFailedTeams.length? t('beheer.mislukt')+esc(S.matchFetchFailedTeams.map(f=>f.label+' ('+f.error+')').join('; ')) : ''}</p>` : ''}
    </div>
    <div class="card">
      <h2>${t('beheer.meldingen_bij_gewijzigde_tijden')}</h2>
      <p class="muted">${t('beheer.als_een_ouder_de_aankomst')}</p>
      ${('Notification' in window)
        ? (Notification.permission==='granted'
            ? `<p class="fitok">${phIcon('check')} ${t('beheer.browsermeldingen_staan_aan_op_dit')}</p>`
            : Notification.permission==='denied'
              ? `<p class="fitbad">${t('beheer.browsermeldingen_zijn_geblokkeerd_zet_ze')}</p>`
              : `<button type="button" class="btn small secondary" id="enableNotifBtn">${t('beheer.browsermeldingen_aanzetten')}</button>`)
        : `<p class="muted">${t('beheer.deze_browser_ondersteunt_geen_meldingen')}</p>`}
    </div>
    <div class="card">
      <h2>${t('beheer.beheerderstools')}</h2>
      <button type="button" class="btn danger" id="seedPdf">${phIcon('trash')} ${t('beheer.alles_wissen_pdf_gegevens_laden')}</button>
      <p id="seedMsg" class="muted" style="margin-top:8px"></p>
    </div>`;

  try{
    const saveSettingsAuto = async ()=>{
      if(!db){showToast(t('data.geen_verbinding_met_opslag'));return;}
      const gapThresholdHours = parseFloat(document.getElementById('setGap').value)||3;
      const travelLeadMinutes = parseInt(document.getElementById('setLead').value)||60;
      const prefWindowMinutes = parseInt(document.getElementById('setPrefWindow').value);
      const parentPrefWindowMinutes = parseInt(document.getElementById('setParentPrefWindow').value);
      try{ await db.doc("settings/planning").set({gapThresholdHours,travelLeadMinutes,prefWindowMinutes: isNaN(prefWindowMinutes)?30:prefWindowMinutes, parentPrefWindowMinutes: isNaN(parentPrefWindowMinutes)?60:parentPrefWindowMinutes}); showToast(t('data.opgeslagen')); }
      catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
    };
    const setGapEl=document.getElementById('setGap'); if(setGapEl) setGapEl.onchange=saveSettingsAuto;
    const setLeadEl=document.getElementById('setLead'); if(setLeadEl) setLeadEl.onchange=saveSettingsAuto;
    const setPrefWindowEl=document.getElementById('setPrefWindow'); if(setPrefWindowEl) setPrefWindowEl.onchange=saveSettingsAuto;
    const setParentPrefWindowEl=document.getElementById('setParentPrefWindow'); if(setParentPrefWindowEl) setParentPrefWindowEl.onchange=saveSettingsAuto;
    document.querySelectorAll('.dayCoordSel').forEach(sel=>sel.onchange=()=>saveDayCoordinator(sel.dataset.coordday, sel.value));
    const atp=document.getElementById('addTogetherPref');
    if(atp) atp.onclick=async ()=>{
      const ids=[...document.querySelectorAll('.prefTogetherPick:checked')].map(c=>c.value);
      if(ids.length<2){showToast(t('beheer.kies_minstens_2_meiden'));return;}
      try{ await db.doc("settings/prefs").set({rules:[...(S.prefs.rules||[]), {type:'together', ids}]}); showToast(t('beheer.toegevoegd')); }
      catch(e){showToast(t('data.mislukt')+(e&&e.message||e));}
    };
    const app_=document.getElementById('addPreferPref');
    if(app_) app_.onclick=async ()=>{
      const girlSel=document.getElementById('preferGirlSelect');
      const girlId=girlSel? girlSel.value : null;
      const withAny=[...document.querySelectorAll('.prefWithPick:checked')].map(c=>c.value).filter(id=>id!==girlId);
      if(!girlId||!withAny.length){showToast(t('beheer.kies_een_meisje_en_minstens'));return;}
      try{ await db.doc("settings/prefs").set({rules:[...(S.prefs.rules||[]), {type:'prefer', girlId, withAny}]}); showToast(t('beheer.toegevoegd')); }
      catch(e){showToast(t('data.mislukt')+(e&&e.message||e));}
    };
    document.querySelectorAll('[data-delpref]').forEach(b=>b.onclick=async ()=>{
      const idx=+b.dataset.delpref;
      const rules=(S.prefs.rules||[]).filter((_,i)=>i!==idx);
      try{ await db.doc("settings/prefs").set({rules}); }catch(e){showToast(t('beheer.verwijderen_mislukt')+(e&&e.message||e));}
    });
    document.querySelectorAll('[data-imptest]').forEach(b=>b.onclick=()=>startImpersonate(b.dataset.imptest));
    const shiftSel=document.getElementById('shiftPrioritySelect');
    if(shiftSel){
      shiftSel.onchange = ()=>{ S.selectedShiftKey=shiftSel.value; renderShiftPriorityRows(S.selectedShiftKey); };
      renderShiftPriorityRows(S.selectedShiftKey);
    }
    const cn=document.getElementById('coordNew');
    if(cn) cn.onclick = ()=>{ S.coordEditId=null; renderCoordEditor(); };
    document.querySelectorAll('[data-coordedit]').forEach(b=>b.onclick=()=>{ S.coordEditId=b.dataset.coordedit; renderCoordEditor(); });
    document.querySelectorAll('[data-coorddel]').forEach(b=>b.onclick=()=>twoStepConfirm(b,t('beheer.zeker_nogmaals_klikken'),async ()=>{
      try{
        const fid=b.dataset.coorddel;
        const batch=db.batch();
        batch.delete('families/'+fid);
        Object.entries(S.invitesByCode).forEach(([c,f])=>{ if(f===fid) batch.delete('invites/'+c); });
        Object.entries(S.groups).forEach(([gid,g])=>{
          const inCar=(g.girlIds||[]).includes(fid), drives=g.driverFamilyId===fid;
          if(inCar||drives) batch.update('groups/'+gid, {girlIds:(g.girlIds||[]).filter(x=>x!==fid), ...(drives?{driverFamilyId:null}:{})});
        });
        await batch.commit();
      }catch(e){showToast(t('beheer.verwijderen_mislukt')+(e&&e.message||e));}
    }));
    if(S.coordEditId!==undefined) renderCoordEditor();
    const saveMatchFeeds = async ()=>{
      const labels=[...document.querySelectorAll('.matchFeedLabel')];
      const calIds=[...document.querySelectorAll('.matchFeedCalId')];
      const feeds = labels.map((el,i)=>({label:el.value.trim(), calendarId:(calIds[i]&&calIds[i].value.trim())||''})).filter(f=>f.calendarId);
      try{ await db.doc("settings/matchFeeds").set({feeds}); showToast(t('data.opgeslagen')); }
      catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
    };
    document.querySelectorAll('.matchFeedLabel,.matchFeedCalId').forEach(el=>el.onchange=saveMatchFeeds);
    const addFeedBtn=document.getElementById('addMatchFeedBtn');
    if(addFeedBtn) addFeedBtn.onclick=()=>{ S.matchFeeds=[...activeMatchFeeds(), {label:'', calendarId:''}]; renderBeheer(); };
    document.querySelectorAll('[data-delfeed]').forEach(b=>b.onclick=async ()=>{
      const idx=+b.dataset.delfeed;
      const feeds = activeMatchFeeds().filter((_,i)=>i!==idx);
      try{ await db.doc("settings/matchFeeds").set({feeds}); showToast(t('beheer.verwijderd')); }
      catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
    });
    const refreshBtn=document.getElementById('refreshMatchesBtn');
    if(refreshBtn) refreshBtn.onclick=()=>{ showToast(t('beheer.wedstrijden_verversen')); loadAllMatches(); };
    const enb=document.getElementById('enableNotifBtn');
    if(enb) enb.onclick=async ()=>{ try{ await Notification.requestPermission(); }catch(e){} renderBeheer(); };
    const sd=document.getElementById('seedPdf');
    if(sd) sd.onclick = ()=>twoStepConfirm(sd,t('beheer.zeker_alles_wordt_gewist_klik'),seedFromPdf);
  }catch(e){ showToast(t('beheer.fout_bij_koppelen_knoppen')+(e&&e.message||e)); }
}

export function renderCoordEditor(){
  const area=document.getElementById('coordEditArea');
  if(!area)return;
  if(S.coordEditId===undefined){area.innerHTML='';return;}
  const isNew = S.coordEditId===null;
  const f = isNew? null : fam(S.coordEditId);
  const currentCode = f? (S.inviteByFamily[S.coordEditId]||'') : genCode();
  const isCoordThis = !isNew && S.coordinatorConfig && S.coordinatorConfig.familyId===S.coordEditId;
  const selfLinkedThis = !isNew && !!(S.links[S.me] && S.links[S.me].familyId===S.coordEditId);
  const coordToggleHtml = isNew? '' : `
    <div class="rowflex" style="margin:10px 0;padding:10px;border:1px solid var(--border);border-radius:var(--radius-md);background:var(--bg)">
      <span style="font-size:13px">${isCoordThis? t('beheer.span_class_badge_rec_coordinator') : t('beheer.span_class_muted_nog_geen_2')}</span>
      <button type="button" class="btn small secondary" id="coordToggleBtn">${isCoordThis? t('beheer.coordinator_intrekken') : (selfLinkedThis? t('beheer.maak_coordinator') : phIcon('warning')+t('beheer.maak_coordinator_2'))}</button>
    </div>`;
  area.innerHTML = `<div class="card" style="margin-top:10px;border-color:var(--accent)">
    <h2>${isNew? t('beheer.nieuw_gezin_toevoegen_2') : t('beheer.bewerken')+esc((f.girlName||f.parentName)||'')}</h2>
    ${coordToggleHtml}
    <label>${t('beheer.uitnodigingscode_meerdere_mensen_kunnen_dezelfde')}</label>
    <div class="rowflex" style="gap:6px">
      <input type="text" id="coord_inviteCode" value="${esc(currentCode)}" style="flex:1">
      <button type="button" class="btn small secondary" id="genCodeBtn">${phIcon('dice')} ${t('beheer.nieuwe_code')}</button>
    </div>
    ${familyFormHtml('coord', f)}
    <button type="button" class="btn secondary" id="coordCancel">${t('beheer.sluiten')}</button>
    <p class="muted" style="margin-top:8px">${t('beheer.wijzigingen_worden_automatisch_opgeslagen')}</p>
  </div>`;
  const card=area.querySelector('.card');
  if(card) card.addEventListener('change', ()=>saveCoordFamily());
  wireExclusiveAvailability('coord');
  wireFamilyFormExtras('coord', renderCoordEditor);
  const ctb=document.getElementById('coordToggleBtn');
  if(ctb) ctb.onclick=()=>{
    const isCurrently = S.coordinatorConfig && S.coordinatorConfig.familyId===S.coordEditId;
    const selfLinked = !!(S.links[S.me] && S.links[S.me].familyId===S.coordEditId);
    if(!isCurrently && !selfLinked){
      twoStepConfirm(ctb, t('beheer.let_op_jij_bent_hier'), ()=>doToggleCoord(S.coordEditId,isCurrently));
    } else if(isCurrently){
      twoStepConfirm(ctb, t('beheer.zeker_de_coordinator_rol_gaat'), ()=>doToggleCoord(S.coordEditId,isCurrently));
    } else {
      doToggleCoord(S.coordEditId,isCurrently);
    }
  };
  document.getElementById('coordCancel').onclick = ()=>{ S.coordEditId=undefined; renderBeheer(); };
  const genBtn=document.getElementById('genCodeBtn');
  if(genBtn) genBtn.onclick=()=>{ document.getElementById('coord_inviteCode').value=genCode(); saveCoordFamily(); };
}

export async function seedFromPdf(){
  if(!db){showToast(t('data.geen_verbinding_met_opslag'));return;}
  const msg=document.getElementById('seedMsg');
  if(msg) msg.textContent=t('beheer.bezig_met_wissen');
  try{
    const famSnap = await db.collection("families").get();
    await Promise.all(famSnap.docs.map(d=>db.doc("families/"+d.id).delete()));
    const invSnap = await db.collection("invites").get();
    await Promise.all(invSnap.docs.map(d=>db.doc("invites/"+d.id).delete()));
    const grpSnap = await db.collection("groups").get();
    await Promise.all(grpSnap.docs.map(d=>db.doc("groups/"+d.id).delete()));
    if(msg) msg.textContent=t('beheer.bezig_met_invullen');
    const emptyAvail={heen:false,terug:false,backupHeen:false,backupTerug:false};
    await Promise.all(PDF_SEED.map(g=>{
      const availability={}; DAYS.forEach(([k])=>availability[k]={...emptyAvail});
      return db.doc("families/"+slugify(g.girlName)).set({
        parentName:t('beheer.ouder_van')+g.girlName, girlName:g.girlName, capacity:4, schedule:g.schedule, availability
      });
    }));
    const check = await db.collection("families").get();
    const docs = check.docs.map(d=>d.data());
    let ok = docs.length===8; let details=[];
    docs.forEach(f=>{
      DAYS.forEach(([k])=>{
        const has = f.schedule && f.schedule[k] && f.schedule[k].heen && f.schedule[k].terug;
        const expectMissing = (f.girlName==='Robbin' && k==='Wo');
        if(expectMissing && has) {ok=false; details.push(f.girlName+" "+k+t('beheer.had_wel_een_tijd_onverwacht'));}
        if(!expectMissing && !has){ok=false; details.push(f.girlName+" "+k+t('beheer.mist_een_tijd'));}
      });
    });
    if(msg) msg.innerHTML = ok
      ? t('beheer.klaar_gezinnen_aangemaakt_alle_dagen', { p1: phIcon('check-circle'), p2: docs.length })
      : t('beheer.gezinnen_aangemaakt_maar_validatie_vond', { p1: phIcon('warning'), p2: docs.length, p3: esc(details.join('; ')) });
  }catch(e){ if(msg) msg.textContent=t('beheer.fout_tijdens_laden')+(e&&e.message||e); }
}

// ---------- Tijdswijzigingen: coordinator sees which passengers changed their times ----------
export function timeChangesCardHtml(){
  if(!S.canEdit) return '';
  const pending = collectPendingChanges(S.families);
  if(!pending.length) return '';
  const total = pending.reduce((n,f)=>n+f.changes.length,0);
  const famHtml = pending.map(f=>{
    const lines = f.changes.map(c=>`<div class="timeChangeLine"><button type="button" class="btn small secondary" data-tcday="${esc(c.day)}" style="padding:2px 8px;min-height:26px;margin-right:6px">${esc(dayUp(c.day))}</button>${esc(describeChange(c).replace(/^\S+ · /,''))}</div>`).join('');
    const when = f.latestAt? new Date(f.latestAt).toLocaleString(locale(),{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}) : '';
    const by = f.changes.find(c=>c.by)?.by || '';
    return `<div class="timeChangeFam">
      <div class="rowflex" style="align-items:flex-start">
        <div><strong>${esc(f.girlName||f.parentName||f.familyId)}</strong>
          <div class="muted" style="font-size:11px">${by? t('beheer.door')+esc(by)+' · ' : ''}${when}</div></div>
        <button type="button" class="btn small secondary" data-tcseen="${esc(f.familyId)}">${phIcon('check')} ${t('beheer.gezien')}</button>
      </div>
      ${lines}
    </div>`;
  }).join('');
  return `<div class="card timeChangeCard">
    <div class="rowflex" style="align-items:baseline">
      <h2 style="margin:0">${phIcon('warning')} ${t('beheer.gewijzigde_tijden')}${total})</h2>
      ${pending.length>1? `<button type="button" class="btn small secondary" id="tcSeenAll">${t('beheer.alles_gezien')}</button>` : ''}
    </div>
    <p class="muted" style="margin:4px 0 6px">${t('beheer.deze_ouders_hebben_hun_aankomst')}</p>
    ${famHtml}
  </div>`;
}

export function wireTimeChangesCard(){
  document.querySelectorAll('[data-tcseen]').forEach(b=>b.onclick=()=>markTimeChangesSeen([b.dataset.tcseen]));
  const all=document.getElementById('tcSeenAll');
  if(all) all.onclick=()=>twoStepConfirm(all,t('beheer.zeker_klik_nogmaals'),()=>markTimeChangesSeen(collectPendingChanges(S.families).map(f=>f.familyId)));
  document.querySelectorAll('[data-tcday]').forEach(b=>b.onclick=()=>{ S.scheduleDay=b.dataset.tcday; hapticTap(); renderSchedule(); });
}

export function updateTimeChangesBadge(){
  const badge=document.getElementById('navRoosterBadge');
  if(!badge) return;
  const n = S.canEdit? countPendingChanges(S.families) : 0;
  badge.textContent = n>9? '9+' : String(n);
  badge.style.display = n? '' : 'none';
}

// Called on every families snapshot: when a NEW change arrives while the coordinator has the
// app open, show a toast (and, if the browser allowed it, a system notification).
export function notifyCoordinatorOfNewTimeChanges(){
  const n = countPendingChanges(S.families);
  const prev = S.lastPendingChangeCount;
  S.lastPendingChangeCount = n;
  if(prev===null || !S.canEdit || n<=prev) return;
  const newest = collectPendingChanges(S.families)[0];
  const who = newest? (newest.girlName||newest.parentName) : '';
  const msg = t('beheer.nieuwe_tijdswijziging_zie_rooster', { p1: who? t('beheer.van')+who : '' });
  showToast(msg);
  try{
    if('Notification' in window && Notification.permission==='granted' && document.visibilityState!=='visible'){
      new Notification(t('beheer.az_carpool'), {body: msg, icon: './icon-192.png'});
    }
  }catch(e){ /* notifications are a bonus; never break the app over them */ }
}
