// ui-beheer.js — generated by the modularisation of index.html; see README for what lives where.
import { t, locale } from './i18n.js';
import { S } from './state.js';
import { DAYS, PDF_SEED } from './constants.js';
import { dayUp, isoDayLabel, isoRangeLabel } from './dates.js';
import { availableDrivers, fam, girlName, seats, sortByShiftPriority } from './rides.js';
import { noticeCardHtml, wireNoticeCard } from './ui-notice.js';
import { esc, foldCards, hapticTap, locationsCfg, phIcon, showToast, twoStepConfirm } from './ui-common.js';
import { impactCardHtml, wireImpactCard } from './impact.js';
import { BUSSTATION_ID, MAX_PLACES, newPlace, normalizeLocations, parseCoordinates } from './locations.js';
import { hasApiKey } from './distance.js';
import { db, deletePeriodCompletely, doToggleCoord, markTimeChangesSeen, periodHasData, recordLastUpdate, saveCoordFamily, savePeriodDoc } from './data.js';
import { activeMatchFeeds, loadAllMatches } from './matches.js';
import { familyFormHtml, startImpersonate, wireExclusiveAvailability, wireFamilyFormExtras } from './ui-profile.js';
import { genCode, slugify } from './coordinator.js';
import { PERIOD_MAX_WORKDAYS, PERIOD_NAME_MAX, normalizePeriod, periodList, periodPhase, periodProgress } from './period.js';
import { collectPendingChanges, countPendingChanges, describeChange } from './schedule-changes.js';
import { renderSchedule } from './ui-schedule.js';
import { renderMyWeek } from './ui-myweek.js';
import { renderDeviationTab } from './ui-deviation.js';

export function renderAvailabilityTable(){
  const rows = Object.entries(S.families).sort((a,b)=>(a[1].parentName||'').localeCompare(b[1].parentName||''));
  if(!rows.length) return `<p class="muted">${t('beheer.nog_geen_gezinnen')}</p>`;
  const head = `<tr><th style="text-align:left">${t('beheer.ouder')}</th>${DAYS.map(([k])=>`<th colspan="2">${dayUp(k)}</th>`).join('')}</tr>
    <tr><th></th>${DAYS.map(()=>`<th style="font-size:12px;color:var(--muted)">H</th><th style="font-size:12px;color:var(--muted)">T</th>`).join('')}</tr>`;
  const body = rows.map(([id,f])=>{
    const cells = DAYS.map(([k])=>{
      const a=(f.availability&&f.availability[k])||{};
      // Standaard = solid green cell; back-up = plain grey number.
      const cellFor = (isDefault,isBackup) => isDefault
        ? `<span class="availStd">${seats(f)}</span>`
        : isBackup ? `<span style="color:var(--backup);font-weight:500">${seats(f)}</span>` : t('beheer.span_class_muted_span');
      return `<td style="text-align:center">${cellFor(a.heen,a.backupHeen)}</td><td style="text-align:center">${cellFor(a.terug,a.backupTerug)}</td>`;
    }).join('');
    return `<tr style="border-top:1px solid var(--border)"><td>${esc(f.parentName||'?')}</td>${cells}</tr>`;
  }).join('');
  return `<div style="overflow-x:auto"><table class="avail">${head}${body}</table></div>
    <p class="muted" style="margin-top:6px"><span class="availStd">4</span> ${t('beheer.groen_vlak_standaard_beschikbaar')} <span style="color:var(--backup);font-weight:500">4</span> ${t('beheer.grijs_cijfer_back_up_indien')}</p>`;
}

export function renderPrefsCard(){
  const girls = Object.entries(S.families).filter(([id,f])=>f.girlName);
  const ruleRows = (S.prefs.rules||[]).map((r,i)=>{
    const label = r.type==='together'
      ? t('beheer.samen_reizen_2', { p1: (r.ids||[]).map(id=>girlName(id)).join(' &amp; ') })
      : t('beheer.voorkeur_met',{p1:girlName(r.girlId),p2:(r.withAny||[]).map(id=>girlName(id)).join(t('beheer.of'))});
    return `<div class="rowflex" style="padding:6px 0;border-bottom:1px solid var(--border)"><span style="font-size:14px">${label}</span><button type="button" class="iconbtn danger" data-delpref="${i}" aria-label="${t('beheer.voorkeur_verwijderen')}" title="${t('beheer.verwijder')}">${phIcon('trash')}</button></div>`;
  }).join('') || `<p class="muted">${t('beheer.nog_geen_voorkeuren')}</p>`;
  const togetherChecks = girls.map(([id,f])=>`<label class="chip"><input type="checkbox" class="prefTogetherPick" value="${id}">${esc(f.girlName)}</label>`).join('');
  const preferSelect = `<select id="preferGirlSelect">${girls.map(([id,f])=>`<option value="${id}">${esc(f.girlName)}</option>`).join('')}</select>`;
  const preferChecks = girls.map(([id,f])=>`<label class="chip"><input type="checkbox" class="prefWithPick" value="${id}">${esc(f.girlName)}</label>`).join('');
  return `${ruleRows}
    <hr style="border:none;border-top:1px solid var(--border);margin:12px 0">
    <p class="muted"><strong>${t('beheer.samen_reizen')}</strong> ${t('beheer.moeten_altijd_samen_in_1')}</p>
    <div>${togetherChecks || t('beheer.span_class_muted_nog_geen')}</div>
    <button type="button" class="btn small secondary" id="addTogetherPref">${t('beheer.toevoegen')}</button>
    <p class="muted" style="margin-top:14px"><strong>${t('beheer.voorkeur')}</strong> ${t('beheer.moet_met_minstens_een_van')}</p>
    <label>${t('beheer.wie')}</label>${preferSelect}
    <label>${t('beheer.bij_voorkeur_met_kies_een')}</label><div>${preferChecks || t('beheer.span_class_muted_nog_geen')}</div>
    <button type="button" class="btn small secondary" id="addPreferPref">${t('beheer.toevoegen')}</button>`;
}

export function renderPriorityCard(){
  const shifts=[];
  DAYS.forEach(([k,label])=>{ shifts.push([k+'_heen', label+t('beheer.heen')]); shifts.push([k+'_terug', label+t('beheer.terug')]); });
  const options = shifts.map(([key,label])=>`<option value="${key}" ${key===S.selectedShiftKey?'selected':''}>${label}</option>`).join('');
  return `<p class="muted">${t('beheer.bepaal_per_shift_in_welke')}</p>
    <label>${t('beheer.shift')}</label><select id="shiftPrioritySelect">${options}</select>
    <div id="shiftPriorityRows" style="margin-top:8px"></div>`;
}

export function renderShiftPriorityRows(shiftKeyVal){
  const div=document.getElementById('shiftPriorityRows');
  if(!div) return;
  const [day,direction]=shiftKeyVal.split('_');
  const rows = sortByShiftPriority(day,direction, availableDrivers(day,direction));
  if(!rows.length){ div.innerHTML=`<p class="muted">${t('beheer.geen_beschikbare_chauffeurs_voor_deze')}</p>`; return; }
  div.innerHTML = rows.map(([id,f],i)=>`
    <div class="rowflex" style="padding:8px 6px;border-bottom:1px solid var(--border)">
      <span>${i+1}. ${esc(f.parentName||'?')} <span class="muted">(${esc(f.girlName||'')}, ${seats(f)} ${t('beheer.pl')}</span></span>
      <span style="display:flex;gap:4px">
        <button type="button" class="iconbtn" data-prioup="${id}" aria-label="${esc(f.parentName||'chauffeur')} hoger in prioriteit" ${i===0?'disabled':''}>${phIcon('arrow-up')}</button>
        <button type="button" class="iconbtn" data-priodown="${id}" aria-label="${esc(f.parentName||'chauffeur')} lager in prioriteit" ${i===rows.length-1?'disabled':''}>${phIcon('arrow-down')}</button>
      </span>
    </div>`).join('');
  const ids=rows.map(([id])=>id);
  div.querySelectorAll('[data-prioup]').forEach(btn=>btn.onclick=()=>movePriority(shiftKeyVal,ids,btn.dataset.prioup,-1));
  div.querySelectorAll('[data-priodown]').forEach(btn=>btn.onclick=()=>movePriority(shiftKeyVal,ids,btn.dataset.priodown,1));
}

export async function movePriority(shiftKeyVal,ids,id,delta){
  const idx=ids.indexOf(id);
  const newIdx=idx+delta;
  if(newIdx<0||newIdx>=ids.length) return;
  const newIds=[...ids];
  [newIds[idx],newIds[newIdx]]=[newIds[newIdx],newIds[idx]];
  const map={}; newIds.forEach((gid,i)=>map[gid]=i+1);
  if(!db){showToast(t('data.geen_verbinding_met_opslag'));return;}
  try{ await db.doc("settings/priority").set({...S.shiftPriority,[shiftKeyVal]:map}); showToast(t('beheer.volgorde_opgeslagen')); }
  catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
}

// US-02: one family per weekday who handles change requests. Stored as familyIds in settings/dayCoordinators;
// names are read from the families, so renaming a parent in Beheer updates every screen.
export function dayCoordinatorsCardHtml(){
  const fams = Object.entries(S.families).sort((a,b)=>(a[1].parentName||'').localeCompare(b[1].parentName||'', locale()));
  const rows = DAYS.map(([k,label])=>{
    const cur = S.dayCoordinators[k]||'';
    return `<div class="rowflex" style="align-items:center;gap:8px;margin-top:6px">
      <label style="margin:0;width:96px" for="dayCoord_${k}">${label}</label>
      <select id="dayCoord_${k}" class="dayCoordSel" data-coordday="${k}" style="flex:1">
        <option value="">${t('dayCoord.none')}</option>
        ${fams.map(([id,f])=>`<option value="${id}" ${id===cur?'selected':''}>${esc(f.parentName||id)} (${esc(f.girlName||'?')})</option>`).join('')}
      </select>
    </div>`;
  }).join('');
  return `<div class="card" id="dayCoordCard">
      <h2>${t('dayCoord.beheerTitle')}</h2>
      <p class="muted">${t('dayCoord.beheerIntro')}</p>
      ${rows}
    </div>`;
}

export async function saveDayCoordinator(day, familyId){
  if(!db){ showToast(t('data.geen_verbinding_met_opslag')); return false; }
  const next = {...S.dayCoordinators};
  if(familyId) next[day]=familyId; else delete next[day];
  try{
    await db.doc("settings/dayCoordinators").set(next);
    S.dayCoordinators = next;
    showToast(t('dayCoord.saved'));
    return true;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

// Periodes met andere tijden (vakantie, proefwerkweek): the coordinator keeps a LIST of periods, each with a name, first and last day
// (max 10 workdays), when filling in opens and a deadline. Periods never share a day; the filling-in windows may overlap, so the next
// period can be collected while the current one is running. One document per period: periods/<firstDay>. Edits of the form stay in
// S.periodDraft until Opslaan, so a live update from the database cannot wipe what is being typed.
const fmtDay = iso => isoDayLabel(iso);
const fmtDeadline = p => fmtDay(p.deadlineDate)+' '+p.deadlineTime;

export function periodPhaseText(p, nowMs){
  const phase = periodPhase(p, nowMs);
  if(phase==='none') return t('period.phase.none');
  const v = normalizePeriod(p);
  if(phase==='waiting') return t('period.phase.waiting',{p1:fmtDay(v.opensOn)});
  if(phase==='open') return t('period.phase.open',{p1:fmtDeadline(v)});
  if(phase==='closed') return t('period.phase.closed',{p1:fmtDeadline(v)});
  return t('period.phase.over');
}

// "Doorgegeven: 9 van 14 gezinnen" (Flex families are not counted): only once filling in has opened and the entries are loaded.
export function periodStatusHtml(p, nowMs){
  if(!p || !S.periodEntriesLoaded) return '';
  const phase = periodPhase(p, nowMs);
  if(phase!=='open' && phase!=='closed' && phase!=='over') return '';
  const pr = periodProgress(p, S.families, S.periodEntries);
  return `<div class="rowflex periodStatus" style="margin-top:4px"><span class="muted">${t('period.status.label')}</span><b>${esc(t('period.status.value',{p1:pr.done, p2:pr.total}))}</b></div>`;
}

// The label of the delete button when it asks "sure?": says how many families lose what they handed in.
export function periodDeleteConfirmLabel(p){
  const n = periodHasData(p.firstDay).entries;
  return n? t('period.delete.confirmData',{p1:n}) : t('beheer.zeker_nogmaals_klikken');
}

function periodRowHtml(p, nowMs){
  const v = normalizePeriod(p), d = periodHasData(v.firstDay);
  const info = [periodPhaseText(v, nowMs), d.rooster? t('period.list.roosterMade') : ''].filter(Boolean).join(' · ');
  return `<div class="periodListRow" data-periodlist="${v.firstDay}">
      <div style="flex:1;min-width:0">
        <div><strong>${esc(v.name)}</strong> <span class="muted">${esc(isoRangeLabel(v.firstDay, v.lastDay))}</span></div>
        <div class="muted" style="font-size:12px">${esc(info)}</div>
        ${periodStatusHtml(v, nowMs)}
      </div>
      <button type="button" class="iconbtn" data-plistedit="${v.firstDay}" aria-label="${esc(t('period.list.edit',{p1:v.name}))}" title="${esc(t('period.list.edit',{p1:v.name}))}">${phIcon('pencil')}</button>
      <button type="button" class="iconbtn danger" data-plistdelete="${v.firstDay}" aria-label="${esc(t('period.delete'))}: ${esc(v.name)}" title="${esc(t('period.delete'))}: ${esc(v.name)}">${phIcon('trash')}</button>
    </div>`;
}

function periodFormCardHtml(){
  const dr = S.periodDraft, v = normalizePeriod(dr.value);
  const locked = !!dr.editing && (periodHasData(dr.editing).entries>0 || periodHasData(dr.editing).rooster>0);
  const field = (id,labelKey,type,val,extra='') => `<div style="margin-top:10px;flex:1"><label for="${id}" style="margin-top:0">${t(labelKey)}</label><input type="${type}" id="${id}" class="periodInput" value="${esc(val)}" ${extra}></div>`;
  return `<div class="periodFormCard" id="periodDraftForm">
      <h3 style="margin:12px 0 0;font-size:15px">${t(dr.editing? 'period.form.editTitle' : 'period.form.addTitle')}</h3>
      ${field('periodName','period.name','text',v.name,`maxlength="${PERIOD_NAME_MAX}" placeholder="${esc(t('period.namePlaceholder'))}"`)}
      <div class="rowflex" style="gap:8px">
        ${field('periodFirst','period.firstDay','date',v.firstDay, locked? 'disabled' : '')}
        ${field('periodLast','period.lastDay','date',v.lastDay)}
      </div>
      <p class="muted" style="margin-top:3px">${t('period.maxHint',{p1:PERIOD_MAX_WORKDAYS})}${locked? ' '+t('period.firstDayLockedHint') : ''}</p>
      ${field('periodOpens','period.opensOn','date',v.opensOn)}
      <p class="muted" style="margin-top:3px">${t('period.opensHint')}</p>
      <div class="rowflex" style="gap:8px">
        ${field('periodDlDate','period.deadlineDate','date',v.deadlineDate)}
        ${field('periodDlTime','period.deadlineTime','time',v.deadlineTime)}
      </div>
      <p class="muted" style="margin-top:3px">${t('period.deadlineHint')}</p>
      <div class="rowflex" style="gap:6px;margin-top:8px">
        <button type="button" class="btn small" id="periodDraftSave">${t('period.save')}</button>
        <button type="button" class="btn small secondary" id="periodDraftCancel">${t('period.cancel')}</button>
      </div>
    </div>`;
}

export function periodsCardHtml(nowMs){
  const list = periodList(S.periods);
  return `<div class="card" id="periodCard">
      <h2>${t('period.title')}</h2>
      <p class="muted">${t('period.intro')}</p>
      ${list.length? list.map(p => periodRowHtml(p, nowMs)).join('') : (S.periodDraft? '' : `<p class="muted" id="periodPhase">${t('period.phase.none')}</p>`)}
      ${S.periodDraft? periodFormCardHtml() : `<button type="button" class="btn small secondary" id="periodAdd" data-plistadd style="margin-top:10px">${t('period.add')}</button>`}
    </div>`;
}

const periodField = id => { const el = document.getElementById(id); return el? el.value : ''; };
function readPeriodForm(){
  return normalizePeriod({ name:periodField('periodName'), firstDay:periodField('periodFirst'), lastDay:periodField('periodLast'),
    opensOn:periodField('periodOpens'), deadlineDate:periodField('periodDlDate'), deadlineTime:periodField('periodDlTime') });
}

// Opens the form for a new period (no argument) or to edit one.
export function startPeriodEdit(firstDay){
  S.periodDraft = { editing: firstDay||'', value: firstDay && S.periods[firstDay]? normalizePeriod(S.periods[firstDay]) : normalizePeriod({}) };
  renderBeheer();
}

// Keeps what is typed while the form is open (see the note above).
export function rememberPeriodDraft(){ if(S.periodDraft) S.periodDraft = { editing:S.periodDraft.editing, value:readPeriodForm() }; }

export async function savePeriod(){
  if(!S.periodDraft) return false;
  const editing = S.periodDraft.editing;
  const res = await savePeriodDoc(readPeriodForm(), editing);
  if(!res.ok){
    S.periodDraft = { editing, value:res.value || readPeriodForm() };
    if(res.errors && res.errors.length) showToast(t(res.errors[0],{p1:res.overlap? res.overlap.name : PERIOD_MAX_WORKDAYS}));
    return false;
  }
  S.periodDraft = null;
  showToast(t('period.saved'));
  renderBeheer();
  return true;
}

export function cancelPeriodEdit(){ S.periodDraft = null; renderBeheer(); }

export async function deletePeriod(firstDay){
  const ok = await deletePeriodCompletely(firstDay);
  if(ok && S.periodDraft && S.periodDraft.editing===firstDay) S.periodDraft = null;
  renderBeheer();
  return ok;
}

// US-15 / US-21: the pickup and drop-off places (up to 6) with names and addresses, the destination in Alkmaar,
// the default place per direction and the fixed distances for AFC and ATC. One document: settings/locations.
// An address is a logical address, GPS in decimal degrees, or GPS in degrees-minutes-seconds.
export function locationsCardHtml(){
  const cfg = locationsCfg();
  const placeRows = cfg.places.map(p=>{
    const gps = parseCoordinates(p.address);
    const hint = gps? `<p class="addrHint">${t('loc.gpsRecognized',{p1:gps.lat+', '+gps.lon})}</p>` : '';
    const remove = p.id===BUSSTATION_ID? '' : `<button type="button" class="iconbtn danger locRemove" data-locremove="${p.id}" aria-label="${esc(t('loc.removePlace',{name:p.name}))}" title="${esc(t('loc.removePlace',{name:p.name}))}">${phIcon('trash')}</button>`;
    return `<div class="grid2" style="margin-top:6px">
      <div><label style="margin-top:0" for="locName_${p.id}">${t('loc.placeName')}</label><input type="text" class="locInput" id="locName_${p.id}" value="${esc(p.name)}"></div>
      <div><label style="margin-top:0" for="locAddr_${p.id}">${t('loc.placeAddress')}</label>
        <div class="rowflex" style="gap:6px"><input type="text" class="locInput" id="locAddr_${p.id}" value="${esc(p.address)}" placeholder="${esc(t('loc.addressPlaceholder'))}" style="flex:1;min-width:0">${remove}</div>${hint}</div>
    </div>`;
  }).join('');
  const opts = sel => cfg.places.map(p=>`<option value="${p.id}" ${p.id===sel?'selected':''}>${esc(p.name)}</option>`).join('');
  const add = cfg.places.length<MAX_PLACES
    ? `<button type="button" class="btn small secondary" id="locAdd" style="margin-top:10px">+ ${t('loc.addPlace')}</button>`
    : `<p class="muted" style="margin-top:10px">${t('loc.maxPlaces',{p1:MAX_PLACES})}</p>`;
  return `<div class="card" id="locationsCard">
      <h2>${t('loc.beheerTitle')}</h2>
      <p class="muted">${t('loc.beheerIntro',{p1:MAX_PLACES})}</p>
      ${placeRows}
      ${add}
      <div class="grid2" style="margin-top:10px">
        <div><label style="margin-top:0" for="locDestName">${t('loc.destination')}</label><input type="text" class="locInput" id="locDestName" value="${esc(cfg.destination.name)}"></div>
        <div><label style="margin-top:0" for="locDestAddr">${t('loc.placeAddress')}</label><input type="text" class="locInput" id="locDestAddr" value="${esc(cfg.destination.address)}" placeholder="Straat 1, Alkmaar"></div>
      </div>
      <div class="grid2" style="margin-top:10px">
        <div><label style="margin-top:0" for="locDefHeen">${t('loc.defaultHeen')}</label><select class="locInput" id="locDefHeen">${opts(cfg.defaults.heen)}</select></div>
        <div><label style="margin-top:0" for="locDefTerug">${t('loc.defaultTerug')}</label><select class="locInput" id="locDefTerug">${opts(cfg.defaults.terug)}</select></div>
      </div>
      <p class="muted" style="margin-top:10px">${t('loc.shiftHint')}</p>
      <p class="muted" style="margin-top:10px"><strong>${t('loc.fixedTitle')}</strong> ${t('loc.fixedHint')}</p>
      <div class="grid2">
        <div><label style="margin-top:0" for="locFixAFC">${t('loc.fixedAFC')}</label><input type="number" class="locInput" id="locFixAFC" min="0" step="0.1" value="${cfg.fixedKm.AFC==null?'':cfg.fixedKm.AFC}"></div>
        <div><label style="margin-top:0" for="locFixATC">${t('loc.fixedATC')}</label><input type="number" class="locInput" id="locFixATC" min="0" step="0.1" value="${cfg.fixedKm.ATC==null?'':cfg.fixedKm.ATC}"></div>
      </div>
    </div>`;
}

// API keys that may not sit in the public GitHub folder. Now only the OpenRouteService key (distance of away matches).
// Stored in settings/apiKeys: members can read it (the app needs it), only the coordinator can change it (Firestore rules).
// The key itself is never shown again after saving, only the last 4 characters.
export function apiKeysCardHtml(){
  const has = hasApiKey(S.orsApiKey);
  const status = has
    ? `<p class="fitok">${phIcon('check')} ${t('apikeys.ors_ingesteld',{p1:esc(String(S.orsApiKey).slice(-4))})}</p>`
    : `<p class="muted">${t('apikeys.ors_niet_ingesteld')}</p>`;
  return `<div class="card" id="apiKeysCard">
      <h2>${t('apikeys.titel')}</h2>
      <p class="muted">${t('apikeys.uitleg')}</p>
      ${status}
      <label style="margin-top:0" for="apiKeyOrs">${t('apikeys.ors_label')}</label>
      <input type="password" id="apiKeyOrs" autocomplete="off" spellcheck="false" placeholder="${esc(t('apikeys.ors_placeholder'))}">
      <div class="rowflex" style="gap:6px;margin-top:8px">
        <button type="button" class="btn small secondary" id="apiKeyOrsSave">${t('apikeys.opslaan')}</button>
        ${has? `<button type="button" class="btn small danger" id="apiKeyOrsClear">${t('apikeys.verwijderen')}</button>` : ''}
      </div>
    </div>`;
}

// Saves (or, with value '', removes) the OpenRouteService key. Without an argument it reads the input field.
export async function saveOrsApiKey(value){
  if(!db){ showToast(t('data.geen_verbinding_met_opslag')); return false; }
  const el = document.getElementById('apiKeyOrs');
  const key = String(value!==undefined? value : (el? el.value : '')).trim();
  if(value===undefined && !key){ showToast(t('apikeys.leeg')); return false; }
  if(/\s/.test(key)){ showToast(t('apikeys.spaties')); return false; }
  try{
    await db.doc("settings/apiKeys").set({ ors:key }, { merge:true });
    S.orsApiKey = key;
    if(el) el.value = '';
    showToast(t(key? 'apikeys.opgeslagen' : 'apikeys.verwijderd'));
    renderBeheer(); renderMyWeek();
    return true;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

// One write of settings/locations (normalised). Every locations save goes through here.
async function writeLocations(raw, toastKey){
  if(!db){ showToast(t('data.geen_verbinding_met_opslag')); return false; }
  const doc = normalizeLocations(raw);
  try{ await db.doc("settings/locations").set(doc); S.locationsDoc = doc; if(toastKey) showToast(t(toastKey)); return true; }
  catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

export async function saveLocations(){
  if(!db){ showToast(t('data.geen_verbinding_met_opslag')); return false; }
  const val = (id,fb)=>{ const el=document.getElementById(id); return el? el.value : (fb==null?'':fb); };
  const cur = locationsCfg();
  return writeLocations({
    places: cur.places.map(p=>({ id:p.id, name:val('locName_'+p.id,p.name), address:val('locAddr_'+p.id,p.address) })),
    destination: { name:val('locDestName'), address:val('locDestAddr') },
    defaults: { heen:val('locDefHeen',cur.defaults.heen), terug:val('locDefTerug',cur.defaults.terug) },
    shifts: cur.shifts,
    fixedKm: { AFC:val('locFixAFC'), ATC:val('locFixATC') },
  }, 'loc.saved');
}

// Adds an empty place (max 6). The coordinator then types its name and address.
export async function addLocationPlace(){
  const cur = locationsCfg();
  if(cur.places.length>=MAX_PLACES){ showToast(t('loc.maxPlaces',{p1:MAX_PLACES})); return false; }
  return writeLocations({ ...cur, places:[...cur.places, newPlace(cur.places, t('loc.newPlaceName'))] }, 'loc.saved');
}

// Removes a place. Rides that still point at it fall back to the standard place; Busstation cannot be removed.
export async function removeLocationPlace(id){
  const cur = locationsCfg();
  if(id===BUSSTATION_ID || !cur.places.some(p=>p.id===id)) return false;
  return writeLocations({ ...cur, places:cur.places.filter(p=>p.id!==id) }, 'loc.saved');
}

// Standaardrooster: another standard place for one shift (day + direction). placeId '' = follow the heen/terug default.
export async function saveShiftLocation(day,direction,placeId){
  const cur = locationsCfg();
  const shifts = {...cur.shifts};
  if(placeId) shifts[day+'_'+direction]=placeId; else delete shifts[day+'_'+direction];
  const ok = await writeLocations({ ...cur, shifts }, 'loc.shiftSaved');
  if(ok){ recordLastUpdate('Rooster'); renderSchedule(); renderMyWeek(); renderDeviationTab(); }
  return ok;
}

export function renderBeheer(){
  const box=document.getElementById('tab-beheer');
  if(!box) return;
  if(!S.canEdit){ box.innerHTML = `<div class="card"><p class="muted">${t('beheer.deze_pagina_is_alleen_voor')}</p></div>`; return; }

  const claimed = {}; Object.entries(S.links).forEach(([uid,l])=>claimed[l.familyId]=true);
  const byName={};
  Object.entries(S.families).forEach(([id,fd])=>{
    const key=(fd.girlName||'').trim().toLowerCase();
    if(key) (byName[key]=byName[key]||[]).push([id,fd]);
  });
  const dupGroups = Object.values(byName).filter(list=>list.length>1);
  const dupWarning = dupGroups.length? `<div class="group warning" style="margin-bottom:10px">
      <div class="fitbad">${phIcon('warning')} ${t('beheer.mogelijk_dubbele_gezinnen_controleer_en')}</div>
      ${dupGroups.map(list=>`<div style="margin-top:6px"><strong>${esc(list[0][1].girlName)}</strong> (${list.length}x):<br>${list.map(([id,fd])=>`<span class="pill">${esc(fd.parentName||id)} <button type="button" class="iconbtn danger" data-coorddel="${id}" style="margin-left:4px;min-width:30px;min-height:30px" aria-label="${t('beheer.verwijder')}" title="${t('beheer.verwijder')}">${phIcon('trash')}</button></span>`).join(' ')}</div>`).join('')}
    </div>` : '';
  const rows = Object.entries(S.families).map(([id,fd])=>{
    const isCoord = S.coordinatorConfig && S.coordinatorConfig.familyId===id;
    // Phone numbers and invite codes are only shown inside "Wijzig"; the list only flags what's missing.
    const missing = [!fd.parentPhone1&&!fd.parentPhone2? 'telefoonnummer' : '', !S.inviteByFamily[id]? 'code' : ''].filter(Boolean);
    return `
    <div class="rowflex" style="padding:10px 0;border-bottom:1px solid var(--border);gap:8px">
      <div style="flex:1;min-width:0">
        <div style="font-size:16px;font-weight:800">${esc(fd.girlName||'(naam?)')}</div>
        <div class="muted">${esc(fd.parentName||'(ouder?)')} ${claimed[id]?t('beheer.span_class_badge_gekoppeld_span'):''} ${isCoord?t('beheer.span_class_badge_rec_coordinator'):''}${fd.familyType==='flex'? ` <span class="badge flexBadge">${t('flex.badge')}</span>` : ''}</div>
        ${missing.length? `<div class="fitbad" style="font-size:12px;margin-top:2px">${phIcon('warning')} ${t('beheer.geen')} ${missing.join(t('beheer.en'))}</div>` : ''}
      </div>
      <span style="display:flex;gap:6px;flex-shrink:0">
        <button type="button" class="btn small secondary" data-coordedit="${id}">${t('beheer.wijzig')}</button>
        <button type="button" class="iconbtn" data-imptest="${id}" aria-label="Test de app als ${esc(fd.parentName||t('beheer.deze_ouder'))}" title="${t('beheer.testweergave_als_deze_ouder')}">${phIcon('eye')}</button>
        <button type="button" class="iconbtn danger" data-coorddel="${id}" aria-label="Verwijder ${esc(fd.girlName||'gezin')}" title="${t('beheer.verwijder')}">${phIcon('trash')}</button>
      </span>
    </div>`;
  }).join('') || `<p class="muted">${t('beheer.nog_geen_gezinnen_toegevoegd')}</p>`;

  box.innerHTML = `
    <div class="card">
      <h2>${t('beheer.gezinnen_beheren')}</h2>
      <p class="muted">${t('beheer.vul_of_wijzig_gegevens_namens')}</p>
      ${dupWarning}
      ${rows}
      <button type="button" class="btn secondary" id="coordNew">${t('beheer.nieuw_gezin_toevoegen')}</button>
      <div id="coordEditArea"></div>
    </div>
    <div class="card">
      <h2>${t('beheer.selectievolgorde_per_shift')}</h2>
      ${renderPriorityCard()}
    </div>
    <div class="card">
      <h2>${t('beheer.reisvoorkeuren')}</h2>
      <p class="muted">${t('beheer.wie_er_logistiek_het_beste')}</p>
      ${renderPrefsCard()}
    </div>
    ${dayCoordinatorsCardHtml()}
    ${noticeCardHtml()}
    ${periodsCardHtml()}
    ${locationsCardHtml()}
    ${apiKeysCardHtml()}
    ${impactCardHtml()}
    <div class="card">
      <h2>${t('beheer.beschikbaarheid_chauffeurs_weekoverzicht')}</h2>
      ${renderAvailabilityTable()}
    </div>
    <div class="card">
      <h2>${t('beheer.planning_instellingen')}</h2>
      <p class="muted">${t('beheer.deze_regels_bepalen_hoe_combinaties')}</p>
      <div class="grid4">
        <div><label>${t('beheer.max_tijdsverschil_voor_1_auto')}</label><input type="number" id="setGap" min="0.5" step="0.5" value="${S.settings.gapThresholdHours}"></div>
        <div><label>${t('beheer.rijtijd_aalsmeer_alkmaar_min_vertrektijd')}</label><input type="number" id="setLead" min="0" step="5" value="${S.settings.travelLeadMinutes}"></div>
        <div><label>${t('beheer.marge_reisvookeuren_min')}</label><input type="number" id="setPrefWindow" min="0" step="5" value="${S.settings.prefWindowMinutes}"></div>
        <div><label>${t('beheer.max_wachttijd_om_met_eigen')}</label><input type="number" id="setParentPrefWindow" min="0" step="5" value="${S.settings.parentPrefWindowMinutes}"></div>
      </div>
    </div>
    <div class="card">
      <h2>${t('beheer.wedstrijdkalenders_google_calendar')}</h2>
      <p class="muted">${t('beheer.deze_agenda_s_voeden_wedstrijden')}</p>
      ${activeMatchFeeds().map((f,i)=>`
        <div class="rowflex" style="margin-top:6px;align-items:flex-end;gap:6px">
          <div class="grid2" style="flex:1">
            <div><label style="margin-top:0">${t('beheer.naam')}</label><input type="text" class="matchFeedLabel" data-feedidx="${i}" value="${esc(f.label)}"></div>
            <div><label style="margin-top:0">${t('beheer.calendar_id')}</label><input type="text" class="matchFeedCalId" data-feedidx="${i}" value="${esc(f.calendarId)}" placeholder="${t('beheer.xxxx_group_v_calendar_google')}"></div>
          </div>
          <button type="button" class="iconbtn danger" data-delfeed="${i}" aria-label="${t('beheer.verwijder_kalender')}" title="${t('beheer.verwijder_kalender')}">${phIcon('trash')}</button>
        </div>`).join('')}
      <button type="button" class="btn small secondary" id="addMatchFeedBtn" style="margin-top:8px">${t('beheer.nieuwe_kalender_toevoegen')}</button>
      <button type="button" class="btn small secondary" id="refreshMatchesBtn" style="margin-top:8px">${phIcon('refresh')} ${t('beheer.nu_verversen')}</button>
      ${(S.matchesFetchedAt||S.cachedMatchesAt)? `<p class="muted" style="font-size:12px;margin-top:6px">${t('beheer.laatst_opgehaald')} ${new Date(Math.max(S.matchesFetchedAt||0, S.cachedMatchesAt||0)).toLocaleString(locale())}${S.matchFetchFailedTeams.length? t('beheer.mislukt')+esc(S.matchFetchFailedTeams.map(f=>f.label+' ('+f.error+')').join('; ')) : ''}</p>` : ''}
    </div>
    <div class="card">
      <h2>${t('beheer.meldingen_bij_gewijzigde_tijden')}</h2>
      <p class="muted">${t('beheer.als_een_ouder_de_aankomst')}</p>
      ${('Notification' in window)
        ? (Notification.permission==='granted'
            ? `<p class="fitok">${phIcon('check')} ${t('beheer.browsermeldingen_staan_aan_op_dit')}</p>`
            : Notification.permission==='denied'
              ? `<p class="fitbad">${t('beheer.browsermeldingen_zijn_geblokkeerd_zet_ze')}</p>`
              : `<button type="button" class="btn small secondary" id="enableNotifBtn">${t('beheer.browsermeldingen_aanzetten')}</button>`)
        : `<p class="muted">${t('beheer.deze_browser_ondersteunt_geen_meldingen')}</p>`}
    </div>
    <div class="card">
      <h2>${t('beheer.beheerderstools')}</h2>
      <button type="button" class="btn danger" id="seedPdf">${phIcon('trash')} ${t('beheer.alles_wissen_pdf_gegevens_laden')}</button>
      <p id="seedMsg" class="muted" style="margin-top:8px"></p>
    </div>`;

  foldCards(box);

  try{
    const saveSettingsAuto = async ()=>{
      if(!db){showToast(t('data.geen_verbinding_met_opslag'));return;}
      const gapThresholdHours = parseFloat(document.getElementById('setGap').value)||3;
      const travelLeadMinutes = parseInt(document.getElementById('setLead').value)||60;
      const prefWindowMinutes = parseInt(document.getElementById('setPrefWindow').value);
      const parentPrefWindowMinutes = parseInt(document.getElementById('setParentPrefWindow').value);
      try{ await db.doc("settings/planning").set({gapThresholdHours,travelLeadMinutes,prefWindowMinutes: isNaN(prefWindowMinutes)?30:prefWindowMinutes, parentPrefWindowMinutes: isNaN(parentPrefWindowMinutes)?60:parentPrefWindowMinutes}); showToast(t('data.opgeslagen')); }
      catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
    };
    const setGapEl=document.getElementById('setGap'); if(setGapEl) setGapEl.onchange=saveSettingsAuto;
    const setLeadEl=document.getElementById('setLead'); if(setLeadEl) setLeadEl.onchange=saveSettingsAuto;
    const setPrefWindowEl=document.getElementById('setPrefWindow'); if(setPrefWindowEl) setPrefWindowEl.onchange=saveSettingsAuto;
    const setParentPrefWindowEl=document.getElementById('setParentPrefWindow'); if(setParentPrefWindowEl) setParentPrefWindowEl.onchange=saveSettingsAuto;
    document.querySelectorAll('.dayCoordSel').forEach(sel=>sel.onchange=()=>saveDayCoordinator(sel.dataset.coordday, sel.value));
    wireNoticeCard();
    document.querySelectorAll('.periodInput').forEach(el=>el.oninput=rememberPeriodDraft);
    const perSave=document.getElementById('periodDraftSave'); if(perSave) perSave.onclick=()=>{ hapticTap(); return savePeriod(); };
    const perCancel=document.getElementById('periodDraftCancel'); if(perCancel) perCancel.onclick=()=>cancelPeriodEdit();
    document.querySelectorAll('[data-plistadd]').forEach(b=>b.onclick=()=>{ hapticTap(); startPeriodEdit(); });
    document.querySelectorAll('[data-plistedit]').forEach(b=>b.onclick=()=>{ hapticTap(); startPeriodEdit(b.dataset.plistedit); });
    document.querySelectorAll('[data-plistdelete]').forEach(b=>b.onclick=()=>{ const p=S.periods[b.dataset.plistdelete]; if(p) twoStepConfirm(b, periodDeleteConfirmLabel(p), ()=>deletePeriod(b.dataset.plistdelete)); });
    document.querySelectorAll('.locInput').forEach(el=>el.onchange=()=>saveLocations());
    const orsSave=document.getElementById('apiKeyOrsSave'); if(orsSave) orsSave.onclick=()=>{ hapticTap(); saveOrsApiKey(); };
    const orsClear=document.getElementById('apiKeyOrsClear'); if(orsClear) orsClear.onclick=()=>twoStepConfirm(orsClear, t('beheer.zeker_nogmaals_klikken'), ()=>saveOrsApiKey(''));
    const locAdd=document.getElementById('locAdd'); if(locAdd) locAdd.onclick=()=>{ hapticTap(); addLocationPlace(); };
    document.querySelectorAll('[data-locremove]').forEach(btn=>btn.onclick=()=>twoStepConfirm(btn, t('beheer.zeker_nogmaals_klikken'), ()=>removeLocationPlace(btn.dataset.locremove)));
    wireImpactCard(renderBeheer);
    const atp=document.getElementById('addTogetherPref');
    if(atp) atp.onclick=async ()=>{
      const ids=[...document.querySelectorAll('.prefTogetherPick:checked')].map(c=>c.value);
      if(ids.length<2){showToast(t('beheer.kies_minstens_2_meiden'));return;}
      try{ await db.doc("settings/prefs").set({rules:[...(S.prefs.rules||[]), {type:'together', ids}]}); showToast(t('beheer.toegevoegd')); }
      catch(e){showToast(t('data.mislukt')+(e&&e.message||e));}
    };
    const app_=document.getElementById('addPreferPref');
    if(app_) app_.onclick=async ()=>{
      const girlSel=document.getElementById('preferGirlSelect');
      const girlId=girlSel? girlSel.value : null;
      const withAny=[...document.querySelectorAll('.prefWithPick:checked')].map(c=>c.value).filter(id=>id!==girlId);
      if(!girlId||!withAny.length){showToast(t('beheer.kies_een_meisje_en_minstens'));return;}
      try{ await db.doc("settings/prefs").set({rules:[...(S.prefs.rules||[]), {type:'prefer', girlId, withAny}]}); showToast(t('beheer.toegevoegd')); }
      catch(e){showToast(t('data.mislukt')+(e&&e.message||e));}
    };
    document.querySelectorAll('[data-delpref]').forEach(b=>b.onclick=async ()=>{
      const idx=+b.dataset.delpref;
      const rules=(S.prefs.rules||[]).filter((_,i)=>i!==idx);
      try{ await db.doc("settings/prefs").set({rules}); }catch(e){showToast(t('beheer.verwijderen_mislukt')+(e&&e.message||e));}
    });
    document.querySelectorAll('[data-imptest]').forEach(b=>b.onclick=()=>startImpersonate(b.dataset.imptest));
    const shiftSel=document.getElementById('shiftPrioritySelect');
    if(shiftSel){
      shiftSel.onchange = ()=>{ S.selectedShiftKey=shiftSel.value; renderShiftPriorityRows(S.selectedShiftKey); };
      renderShiftPriorityRows(S.selectedShiftKey);
    }
    const cn=document.getElementById('coordNew');
    if(cn) cn.onclick = ()=>{ S.coordEditId=null; renderCoordEditor(); };
    document.querySelectorAll('[data-coordedit]').forEach(b=>b.onclick=()=>{ S.coordEditId=b.dataset.coordedit; renderCoordEditor(); });
    document.querySelectorAll('[data-coorddel]').forEach(b=>b.onclick=()=>twoStepConfirm(b,t('beheer.zeker_nogmaals_klikken'),async ()=>{
      try{
        const fid=b.dataset.coorddel;
        const batch=db.batch();
        batch.delete('families/'+fid);
        Object.entries(S.invitesByCode).forEach(([c,f])=>{ if(f===fid) batch.delete('invites/'+c); });
        Object.entries(S.groups).forEach(([gid,g])=>{
          const inCar=(g.girlIds||[]).includes(fid), drives=g.driverFamilyId===fid;
          if(inCar||drives) batch.update('groups/'+gid, {girlIds:(g.girlIds||[]).filter(x=>x!==fid), ...(drives?{driverFamilyId:null}:{})});
        });
        await batch.commit();
      }catch(e){showToast(t('beheer.verwijderen_mislukt')+(e&&e.message||e));}
    }));
    if(S.coordEditId!==undefined) renderCoordEditor();
    const saveMatchFeeds = async ()=>{
      const labels=[...document.querySelectorAll('.matchFeedLabel')];
      const calIds=[...document.querySelectorAll('.matchFeedCalId')];
      const feeds = labels.map((el,i)=>({label:el.value.trim(), calendarId:(calIds[i]&&calIds[i].value.trim())||''})).filter(f=>f.calendarId);
      try{ await db.doc("settings/matchFeeds").set({feeds}); showToast(t('data.opgeslagen')); }
      catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
    };
    document.querySelectorAll('.matchFeedLabel,.matchFeedCalId').forEach(el=>el.onchange=saveMatchFeeds);
    const addFeedBtn=document.getElementById('addMatchFeedBtn');
    if(addFeedBtn) addFeedBtn.onclick=()=>{ S.matchFeeds=[...activeMatchFeeds(), {label:'', calendarId:''}]; renderBeheer(); };
    document.querySelectorAll('[data-delfeed]').forEach(b=>b.onclick=async ()=>{
      const idx=+b.dataset.delfeed;
      const feeds = activeMatchFeeds().filter((_,i)=>i!==idx);
      try{ await db.doc("settings/matchFeeds").set({feeds}); showToast(t('beheer.verwijderd')); }
      catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
    });
    const refreshBtn=document.getElementById('refreshMatchesBtn');
    if(refreshBtn) refreshBtn.onclick=()=>{ showToast(t('beheer.wedstrijden_verversen')); loadAllMatches(); };
    const enb=document.getElementById('enableNotifBtn');
    if(enb) enb.onclick=async ()=>{ try{ await Notification.requestPermission(); }catch(e){} renderBeheer(); };
    const sd=document.getElementById('seedPdf');
    if(sd) sd.onclick = ()=>twoStepConfirm(sd,t('beheer.zeker_alles_wordt_gewist_klik'),seedFromPdf);
  }catch(e){ showToast(t('beheer.fout_bij_koppelen_knoppen')+(e&&e.message||e)); }
}

export function renderCoordEditor(){
  const area=document.getElementById('coordEditArea');
  if(!area)return;
  if(S.coordEditId===undefined){area.innerHTML='';return;}
  const isNew = S.coordEditId===null;
  const f = isNew? null : fam(S.coordEditId);
  const currentCode = f? (S.inviteByFamily[S.coordEditId]||'') : genCode();
  const isCoordThis = !isNew && S.coordinatorConfig && S.coordinatorConfig.familyId===S.coordEditId;
  const selfLinkedThis = !isNew && !!(S.links[S.me] && S.links[S.me].familyId===S.coordEditId);
  const coordToggleHtml = isNew? '' : `
    <div class="rowflex" style="margin:10px 0;padding:10px;border:1px solid var(--border);border-radius:var(--radius-md);background:var(--bg)">
      <span style="font-size:14px">${isCoordThis? t('beheer.span_class_badge_rec_coordinator') : t('beheer.span_class_muted_nog_geen_2')}</span>
      <button type="button" class="btn small secondary" id="coordToggleBtn">${isCoordThis? t('beheer.coordinator_intrekken') : (selfLinkedThis? t('beheer.maak_coordinator') : phIcon('warning')+t('beheer.maak_coordinator_2'))}</button>
    </div>`;
  area.innerHTML = `<div class="card" style="margin-top:10px;border-color:var(--accent)">
    <h2>${isNew? t('beheer.nieuw_gezin_toevoegen_2') : t('beheer.bewerken')+esc((f.girlName||f.parentName)||'')}</h2>
    ${coordToggleHtml}
    <label>${t('beheer.uitnodigingscode_meerdere_mensen_kunnen_dezelfde')}</label>
    <div class="rowflex" style="gap:6px">
      <input type="text" id="coord_inviteCode" value="${esc(currentCode)}" style="flex:1">
      <button type="button" class="btn small secondary" id="genCodeBtn">${phIcon('dice')} ${t('beheer.nieuwe_code')}</button>
    </div>
    ${familyFormHtml('coord', f)}
    <button type="button" class="btn secondary" id="coordCancel">${t('beheer.sluiten')}</button>
    <p class="muted" style="margin-top:8px">${t('beheer.wijzigingen_worden_automatisch_opgeslagen')}</p>
  </div>`;
  const card=area.querySelector('.card');
  if(card) card.addEventListener('change', ()=>saveCoordFamily());
  wireExclusiveAvailability('coord');
  wireFamilyFormExtras('coord', renderCoordEditor);
  const ctb=document.getElementById('coordToggleBtn');
  if(ctb) ctb.onclick=()=>{
    const isCurrently = S.coordinatorConfig && S.coordinatorConfig.familyId===S.coordEditId;
    const selfLinked = !!(S.links[S.me] && S.links[S.me].familyId===S.coordEditId);
    if(!isCurrently && !selfLinked){
      twoStepConfirm(ctb, t('beheer.let_op_jij_bent_hier'), ()=>doToggleCoord(S.coordEditId,isCurrently));
    } else if(isCurrently){
      twoStepConfirm(ctb, t('beheer.zeker_de_coordinator_rol_gaat'), ()=>doToggleCoord(S.coordEditId,isCurrently));
    } else {
      doToggleCoord(S.coordEditId,isCurrently);
    }
  };
  document.getElementById('coordCancel').onclick = ()=>{ S.coordEditId=undefined; renderBeheer(); };
  const genBtn=document.getElementById('genCodeBtn');
  if(genBtn) genBtn.onclick=()=>{ document.getElementById('coord_inviteCode').value=genCode(); saveCoordFamily(); };
}

export async function seedFromPdf(){
  if(!db){showToast(t('data.geen_verbinding_met_opslag'));return;}
  const msg=document.getElementById('seedMsg');
  if(msg) msg.textContent=t('beheer.bezig_met_wissen');
  try{
    const famSnap = await db.collection("families").get();
    await Promise.all(famSnap.docs.map(d=>db.doc("families/"+d.id).delete()));
    const invSnap = await db.collection("invites").get();
    await Promise.all(invSnap.docs.map(d=>db.doc("invites/"+d.id).delete()));
    const grpSnap = await db.collection("groups").get();
    await Promise.all(grpSnap.docs.map(d=>db.doc("groups/"+d.id).delete()));
    if(msg) msg.textContent=t('beheer.bezig_met_invullen');
    const emptyAvail={heen:false,terug:false,backupHeen:false,backupTerug:false};
    await Promise.all(PDF_SEED.map(g=>{
      const availability={}; DAYS.forEach(([k])=>availability[k]={...emptyAvail});
      return db.doc("families/"+slugify(g.girlName)).set({
        parentName:t('beheer.ouder_van')+g.girlName, girlName:g.girlName, capacity:4, schedule:g.schedule, availability
      });
    }));
    const check = await db.collection("families").get();
    const docs = check.docs.map(d=>d.data());
    let ok = docs.length===8; let details=[];
    docs.forEach(f=>{
      DAYS.forEach(([k])=>{
        const has = f.schedule && f.schedule[k] && f.schedule[k].heen && f.schedule[k].terug;
        const expectMissing = (f.girlName==='Robbin' && k==='Wo');
        if(expectMissing && has) {ok=false; details.push(f.girlName+" "+k+t('beheer.had_wel_een_tijd_onverwacht'));}
        if(!expectMissing && !has){ok=false; details.push(f.girlName+" "+k+t('beheer.mist_een_tijd'));}
      });
    });
    if(msg) msg.innerHTML = ok
      ? t('beheer.klaar_gezinnen_aangemaakt_alle_dagen', { p1: phIcon('check-circle'), p2: docs.length })
      : t('beheer.gezinnen_aangemaakt_maar_validatie_vond', { p1: phIcon('warning'), p2: docs.length, p3: esc(details.join('; ')) });
  }catch(e){ if(msg) msg.textContent=t('beheer.fout_tijdens_laden')+(e&&e.message||e); }
}

// ---------- Tijdswijzigingen: coordinator sees which passengers changed their times ----------
export function timeChangesCardHtml(){
  if(!S.canEdit) return '';
  const pending = collectPendingChanges(S.families);
  if(!pending.length) return '';
  const total = pending.reduce((n,f)=>n+f.changes.length,0);
  const famHtml = pending.map(f=>{
    const lines = f.changes.map(c=>`<div class="timeChangeLine"><button type="button" class="btn small secondary" data-tcday="${esc(c.day)}" style="padding:2px 8px;min-height:26px;margin-right:6px">${esc(dayUp(c.day))}</button>${esc(describeChange(c).replace(/^\S+ · /,''))}</div>`).join('');
    const when = f.latestAt? new Date(f.latestAt).toLocaleString(locale(),{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}) : '';
    const by = f.changes.find(c=>c.by)?.by || '';
    return `<div class="timeChangeFam">
      <div class="rowflex" style="align-items:flex-start">
        <div><strong>${esc(f.girlName||f.parentName||f.familyId)}</strong>
          <div class="muted" style="font-size:12px">${by? t('beheer.door')+esc(by)+' · ' : ''}${when}</div></div>
        <button type="button" class="btn small secondary" data-tcseen="${esc(f.familyId)}">${phIcon('check')} ${t('beheer.gezien')}</button>
      </div>
      ${lines}
    </div>`;
  }).join('');
  return `<div class="card timeChangeCard">
    <div class="rowflex" style="align-items:baseline">
      <h2 style="margin:0">${phIcon('warning')} ${t('beheer.gewijzigde_tijden')}${total})</h2>
      ${pending.length>1? `<button type="button" class="btn small secondary" id="tcSeenAll">${t('beheer.alles_gezien')}</button>` : ''}
    </div>
    <p class="muted" style="margin:4px 0 6px">${t('beheer.deze_ouders_hebben_hun_aankomst')}</p>
    ${famHtml}
  </div>`;
}

export function wireTimeChangesCard(){
  document.querySelectorAll('[data-tcseen]').forEach(b=>b.onclick=()=>markTimeChangesSeen([b.dataset.tcseen]));
  const all=document.getElementById('tcSeenAll');
  if(all) all.onclick=()=>twoStepConfirm(all,t('beheer.zeker_klik_nogmaals'),()=>markTimeChangesSeen(collectPendingChanges(S.families).map(f=>f.familyId)));
  document.querySelectorAll('[data-tcday]').forEach(b=>b.onclick=()=>{ S.scheduleDay=b.dataset.tcday; hapticTap(); renderSchedule(); });
}

export function updateTimeChangesBadge(){
  const badge=document.getElementById('navRoosterBadge');
  if(!badge) return;
  const n = S.canEdit? countPendingChanges(S.families) : 0;
  badge.textContent = n>9? '9+' : String(n);
  badge.style.display = n? '' : 'none';
}

// Called on every families snapshot: when a NEW change arrives while the coordinator has the
// app open, show a toast (and, if the browser allowed it, a system notification).
export function notifyCoordinatorOfNewTimeChanges(){
  const n = countPendingChanges(S.families);
  const prev = S.lastPendingChangeCount;
  S.lastPendingChangeCount = n;
  if(prev===null || !S.canEdit || n<=prev) return;
  const newest = collectPendingChanges(S.families)[0];
  const who = newest? (newest.girlName||newest.parentName) : '';
  const msg = t('beheer.nieuwe_tijdswijziging_zie_rooster', { p1: who? t('beheer.van')+who : '' });
  showToast(msg);
  try{
    if('Notification' in window && Notification.permission==='granted' && document.visibilityState!=='visible'){
      new Notification(t('beheer.az_carpool'), {body: msg, icon: './icon-192.png'});
    }
  }catch(e){ /* notifications are a bonus; never break the app over them */ }
}
