// ui-beheer.js — generated by the modularisation of index.html; see README for what lives where.
import { t, locale } from './i18n.js';
import { S } from './state.js';
import { DAYS } from './constants.js';
import { dayUp, isoDayLabel, isoRangeLabel } from './dates.js';
import { availableDrivers, driverNameHtml, isStandaardDriver, fam, girlName, seats, sortByShiftPriority, sortFamEntriesByGirl } from './rides.js';
import { noticeCardHtml, wireNoticeCard } from './ui-notice.js';
import { maintenanceCardHtml, wireMaintenanceCard } from './ui-maintenance.js';
import { ritbeursCardHtml, wireRitbeursCard } from './ui-ritbeurs.js';
import { rideLogCardHtml, wireRideLogCard } from './ui-ride-log.js';
import { PERIOD_BACKUP_MAX, changesSince } from './period-backup.js';
import { esc, foldCards, foldHtml, hapticTap, locationsCfg, phIcon, showToast, twoStepConfirm } from './ui-common.js';
import { impactCardHtml, wireImpactCard } from './impact.js';
import { BUSSTATION_ID, MAX_PLACES, newPlace, normalizeLocations, parseCoordinates } from './locations.js';
import { hasApiKey } from './distance.js';
import { createPeriodBackup, db, deletePeriodBackup, deletePeriodCompletely, doToggleCoord, markTimeChangesSeen, periodBackupList, periodHasData, recordLastUpdate, restorePeriodBackup, restoreFamilies, saveCoordFamily, savePeriodDoc } from './data.js';
import { backupFileName, buildBackupCsv, parseBackup, planRestore } from './family-backup.js';
import { activeMatchFeeds, loadAllMatches } from './matches.js';
import { familyFormHtml, startImpersonate, wireIntroWa, wireExclusiveAvailability, wireFamilyFormExtras } from './ui-profile.js';
import { genCode } from './coordinator.js';
import { PERIOD_MAX_WORKDAYS, PERIOD_NAME_MAX, normalizePeriod, periodList, periodPhase, periodProgress } from './period.js';
import { collectPendingChanges, countPendingChanges, describeChange } from './schedule-changes.js';
import { renderSchedule } from './ui-schedule.js';
import { renderMyWeek } from './ui-myweek.js';
import { renderDeviationTab } from './ui-deviation.js';

export function renderAvailabilityTable(){
  const rows = Object.entries(S.families).sort((a,b)=>(a[1].parentName||'').localeCompare(b[1].parentName||''));
  if(!rows.length) return `<p class="muted">${t('beheer.nog_geen_gezinnen')}</p>`;
  const head = `<tr><th style="text-align:left">${t('beheer.ouder')}</th>${DAYS.map(([k])=>`<th colspan="2">${dayUp(k)}</th>`).join('')}</tr>
    <tr><th></th>${DAYS.map(()=>`<th style="font-size:12px;color:var(--muted)">H</th><th style="font-size:12px;color:var(--muted)">T</th>`).join('')}</tr>`;
  const body = rows.map(([id,f])=>{
    const cells = DAYS.map(([k])=>{
      const a=(f.availability&&f.availability[k])||{};
      // Standaard = solid green cell; back-up = plain grey number.
      const cellFor = (isDefault,isBackup) => isDefault
        ? `<span class="availStd">${seats(f)}</span>`
        : isBackup ? `<span style="color:var(--backup);font-weight:500">${seats(f)}</span>` : t('beheer.span_class_muted_span');
      return `<td style="text-align:center">${cellFor(a.heen,a.backupHeen)}</td><td style="text-align:center">${cellFor(a.terug,a.backupTerug)}</td>`;
    }).join('');
    return `<tr style="border-top:1px solid var(--border)"><td>${esc(f.parentName||'?')}</td>${cells}</tr>`;
  }).join('');
  return `<div style="overflow-x:auto"><table class="avail">${head}${body}</table></div>
    <p class="muted" style="margin-top:6px"><span class="availStd">4</span> ${t('beheer.groen_vlak_standaard_beschikbaar')} <span style="color:var(--backup);font-weight:500">4</span> ${t('beheer.grijs_cijfer_back_up_indien')}</p>`;
}

export function renderPrefsCard(){
  const girls = sortFamEntriesByGirl(Object.entries(S.families).filter(([id,f])=>f.girlName));
  const ruleRows = (S.prefs.rules||[]).map((r,i)=>{
    const label = r.type==='together'
      ? t('beheer.samen_reizen_2', { p1: (r.ids||[]).map(id=>girlName(id)).join(' &amp; ') })
      : t('beheer.voorkeur_met',{p1:girlName(r.girlId),p2:(r.withAny||[]).map(id=>girlName(id)).join(t('beheer.of'))});
    return `<div class="rowflex" style="padding:6px 0;border-bottom:1px solid var(--border)"><span style="font-size:14px">${label}</span><button type="button" class="iconbtn danger" data-delpref="${i}" aria-label="${t('beheer.voorkeur_verwijderen')}" title="${t('beheer.verwijder')}">${phIcon('trash')}</button></div>`;
  }).join('') || `<p class="muted">${t('beheer.nog_geen_voorkeuren')}</p>`;
  const togetherChecks = girls.map(([id,f])=>`<label class="chip"><input type="checkbox" class="prefTogetherPick" value="${id}">${esc(f.girlName)}</label>`).join('');
  const preferSelect = `<select id="preferGirlSelect">${girls.map(([id,f])=>`<option value="${id}">${esc(f.girlName)}</option>`).join('')}</select>`;
  const preferChecks = girls.map(([id,f])=>`<label class="chip"><input type="checkbox" class="prefWithPick" value="${id}">${esc(f.girlName)}</label>`).join('');
  return `${ruleRows}
    <hr style="border:none;border-top:1px solid var(--border);margin:12px 0">
    <p class="muted"><strong>${t('beheer.samen_reizen')}</strong> ${t('beheer.moeten_altijd_samen_in_1')}</p>
    <div>${togetherChecks || t('beheer.span_class_muted_nog_geen')}</div>
    <button type="button" class="btn small secondary" id="addTogetherPref">${t('beheer.toevoegen')}</button>
    <p class="muted" style="margin-top:14px"><strong>${t('beheer.voorkeur')}</strong> ${t('beheer.moet_met_minstens_een_van')}</p>
    <label>${t('beheer.wie')}</label>${preferSelect}
    <label>${t('beheer.bij_voorkeur_met_kies_een')}</label><div>${preferChecks || t('beheer.span_class_muted_nog_geen')}</div>
    <button type="button" class="btn small secondary" id="addPreferPref">${t('beheer.toevoegen')}</button>`;
}

export function renderPriorityCard(){
  const shifts=[];
  DAYS.forEach(([k,label])=>{ shifts.push([k+'_heen', label+t('beheer.heen')]); shifts.push([k+'_terug', label+t('beheer.terug')]); });
  const options = shifts.map(([key,label])=>`<option value="${key}" ${key===S.selectedShiftKey?'selected':''}>${label}</option>`).join('');
  return `<p class="muted">${t('beheer.bepaal_per_shift_in_welke')}</p>
    <label>${t('beheer.shift')}</label><select id="shiftPrioritySelect">${options}</select>
    <div id="shiftPriorityRows" style="margin-top:8px"></div>`;
}

export function renderShiftPriorityRows(shiftKeyVal){
  const div=document.getElementById('shiftPriorityRows');
  if(!div) return;
  const [day,direction]=shiftKeyVal.split('_');
  const rows = sortByShiftPriority(day,direction, availableDrivers(day,direction));
  if(!rows.length){ div.innerHTML=`<p class="muted">${t('beheer.geen_beschikbare_chauffeurs_voor_deze')}</p>`; return; }
  div.innerHTML = rows.map(([id,f],i)=>`
    <div class="rowflex" style="padding:8px 6px;border-bottom:1px solid var(--border)">
      <span>${i+1}. ${driverNameHtml(id)} <span class="muted">(${esc(f.girlName||'')}, ${seats(f)} ${t(isStandaardDriver(f,day,direction)?'beheer.pl':'beheer.pl_back_up')}</span></span>
      <span style="display:flex;gap:4px">
        <button type="button" class="iconbtn" data-prioup="${id}" aria-label="${esc(f.parentName||'chauffeur')} hoger in prioriteit" ${i===0?'disabled':''}>${phIcon('arrow-up')}</button>
        <button type="button" class="iconbtn" data-priodown="${id}" aria-label="${esc(f.parentName||'chauffeur')} lager in prioriteit" ${i===rows.length-1?'disabled':''}>${phIcon('arrow-down')}</button>
      </span>
    </div>`).join('');
  const ids=rows.map(([id])=>id);
  div.querySelectorAll('[data-prioup]').forEach(btn=>btn.onclick=()=>movePriority(shiftKeyVal,ids,btn.dataset.prioup,-1));
  div.querySelectorAll('[data-priodown]').forEach(btn=>btn.onclick=()=>movePriority(shiftKeyVal,ids,btn.dataset.priodown,1));
}

export async function movePriority(shiftKeyVal,ids,id,delta){
  const idx=ids.indexOf(id);
  const newIdx=idx+delta;
  if(newIdx<0||newIdx>=ids.length) return;
  const newIds=[...ids];
  [newIds[idx],newIds[newIdx]]=[newIds[newIdx],newIds[idx]];
  const map={}; newIds.forEach((gid,i)=>map[gid]=i+1);
  if(!db){showToast(t('data.geen_verbinding_met_opslag'));return;}
  try{ await db.doc("settings/priority").set({...S.shiftPriority,[shiftKeyVal]:map}); showToast(t('beheer.volgorde_opgeslagen')); }
  catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
}

// Back-up gezinnen: download all families as one CSV, or restore (overwrite) from such a file. The file is checked completely first;
// what was read waits in `pendingBackup` (module variable, so a live update of the Beheer tab does not lose it) until the coordinator confirms.
let pendingBackup = null;
const MAX_SHOWN_ERRORS = 8;

export function familyBackupCardHtml(){
  let pending = '';
  if(pendingBackup && pendingBackup.errors){
    const shown = pendingBackup.errors.slice(0, MAX_SHOWN_ERRORS).map(e=>`<li>${esc(e.line? t('backup.line',{p1:e.line,p2:t(e.key,e.params)}) : t(e.key,e.params))}</li>`).join('');
    const more = pendingBackup.errors.length - MAX_SHOWN_ERRORS;
    pending = `<div class="group warning" id="backupPending" style="margin-top:10px">
      <div class="fitbad">${phIcon('warning')} ${t('backup.errors_title')}</div>
      <ul style="margin:6px 0 8px 18px;padding:0;font-size:14px">${shown}${more>0? `<li>${t('backup.errors_more',{p1:more})}</li>` : ''}</ul>
      <button type="button" class="btn small secondary" id="backupCancel">${t('backup.cancel')}</button>
    </div>`;
  } else if(pendingBackup){
    const plan = pendingBackup.plan;
    const fresh = plan.items.filter(i=>i.isNew).length;
    const coordName = plan.coordinatorFamilyId && plan.items.find(i=>i.id===plan.coordinatorFamilyId);
    pending = `<div class="group" id="backupPending" style="margin-top:10px">
      <div><strong>${t('backup.preview_title',{p1:esc(pendingBackup.fileName)})}</strong></div>
      <p style="margin:6px 0">${t('backup.preview_summary',{p1:plan.items.length-fresh,p2:fresh})}${plan.untouched.length? ' '+t('backup.preview_untouched',{p1:plan.untouched.length}) : ''}</p>
      ${coordName? `<p class="fitbad" style="margin:6px 0">${phIcon('warning')} ${t('backup.preview_coordinator',{p1:esc(coordName.data.parentName||coordName.data.girlName)})}</p>` : ''}
      <div class="rowflex" style="gap:8px;justify-content:flex-start">
        <button type="button" class="btn small" id="backupConfirm">${t('backup.confirm')}</button>
        <button type="button" class="btn small secondary" id="backupCancel">${t('backup.cancel')}</button>
      </div>
    </div>`;
  }
  return `<div class="card" id="backupCard">
      <h2>${t('backup.title')}</h2>
      <p class="muted">${t('backup.intro')}</p>
      <div class="rowflex" style="gap:8px;justify-content:flex-start;flex-wrap:wrap">
        <button type="button" class="btn secondary" id="backupMake">${t('backup.make')}</button>
        <button type="button" class="btn secondary" id="backupRestore">${t('backup.restore')}</button>
        <input type="file" id="backupFile" accept=".csv,text/csv,text/plain" style="display:none">
      </div>
      ${pending}
    </div>`;
}

export function downloadBackup(){
  const coordId = S.coordinatorConfig && S.coordinatorConfig.familyId;
  const blob = new Blob([buildBackupCsv(S.families, coordId)], {type:'text/csv;charset=utf-8'});
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = backupFileName(); document.body.appendChild(a); a.click(); a.remove();
  setTimeout(()=>URL.revokeObjectURL(url), 1000);
  showToast(t('backup.made',{p1:Object.keys(S.families).length}));
}

// Reads the chosen file's text, checks it and shows either the problems or the preview. Nothing is written yet.
export function prepareRestore(fileName, text){
  const res = parseBackup(text);
  if(!res.ok){ pendingBackup = { fileName, errors:res.errors }; return; }
  const plan = planRestore(res.rows, S.families, S.coordinatorConfig && S.coordinatorConfig.familyId, d=>{
    const slug = (d.girlName||d.parentName||'gezin').toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,30) || 'gezin';
    return 'manual-'+slug+'-'+Date.now().toString(36)+Math.random().toString(36).slice(2,5);
  });
  pendingBackup = plan.ok? { fileName, plan } : { fileName, errors:plan.errors };
}

export async function confirmRestore(){
  const plan = pendingBackup && pendingBackup.plan;
  if(!plan) return false;
  const ok = await restoreFamilies(plan);
  if(ok) pendingBackup = null;
  renderBeheer();
  return ok;
}

export function cancelRestore(){ pendingBackup = null; renderBeheer(); }

export function wireFamilyBackupCard(){
  const mk=document.getElementById('backupMake'); if(mk) mk.onclick=downloadBackup;
  const rs=document.getElementById('backupRestore'), file=document.getElementById('backupFile');
  if(rs && file) rs.onclick=()=>{ file.value=''; file.click(); };
  if(file) file.onchange=async ()=>{
    const f = file.files && file.files[0];
    if(!f) return;
    try{ prepareRestore(f.name, await f.text()); }
    catch(e){ pendingBackup = null; showToast(t('backup.read_error')); }
    renderBeheer();
  };
  const ok=document.getElementById('backupConfirm');
  if(ok) ok.onclick=()=>twoStepConfirm(ok, t('backup.confirm_again'), confirmRestore);
  const cn=document.getElementById('backupCancel'); if(cn) cn.onclick=cancelRestore;
}

// US-02: one family per weekday who handles change requests. Stored as familyIds in settings/dayCoordinators;
// names are read from the families, so renaming a parent in Beheer updates every screen.
export function dayCoordinatorsCardHtml(){
  const fams = Object.entries(S.families).sort((a,b)=>(a[1].parentName||'').localeCompare(b[1].parentName||'', locale()));
  const rows = DAYS.map(([k,label])=>{
    const cur = S.dayCoordinators[k]||'';
    return `<div class="rowflex" style="align-items:center;gap:8px;margin-top:6px">
      <label style="margin:0;width:96px" for="dayCoord_${k}">${label}</label>
      <select id="dayCoord_${k}" class="dayCoordSel" data-coordday="${k}" style="flex:1">
        <option value="">${t('dayCoord.none')}</option>
        ${fams.map(([id,f])=>`<option value="${id}" ${id===cur?'selected':''}>${esc(f.parentName||id)} (${esc(f.girlName||'?')})</option>`).join('')}
      </select>
    </div>`;
  }).join('');
  return `<div class="card" id="dayCoordCard">
      <h2>${t('dayCoord.beheerTitle')}</h2>
      <p class="muted">${t('dayCoord.beheerIntro')}</p>
      ${rows}
    </div>`;
}

export async function saveDayCoordinator(day, familyId){
  if(!db){ showToast(t('data.geen_verbinding_met_opslag')); return false; }
  const next = {...S.dayCoordinators};
  if(familyId) next[day]=familyId; else delete next[day];
  try{
    await db.doc("settings/dayCoordinators").set(next);
    S.dayCoordinators = next;
    showToast(t('dayCoord.saved'));
    return true;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

// Periodes met andere tijden (vakantie, proefwerkweek): the coordinator keeps a LIST of periods, each with a name, first and last day
// (max 10 workdays), when filling in opens and a deadline. Periods never share a day; the filling-in windows may overlap, so the next
// period can be collected while the current one is running. One document per period: periods/<firstDay>. Edits of the form stay in
// S.periodDraft until Opslaan, so a live update from the database cannot wipe what is being typed.
const fmtDay = iso => isoDayLabel(iso);
const fmtDeadline = p => fmtDay(p.deadlineDate)+' '+p.deadlineTime;

export function periodPhaseText(p, nowMs){
  const phase = periodPhase(p, nowMs);
  if(phase==='none') return t('period.phase.none');
  const v = normalizePeriod(p);
  if(phase==='waiting') return t('period.phase.waiting',{p1:fmtDay(v.opensOn)});
  if(phase==='open') return t('period.phase.open',{p1:fmtDeadline(v)});
  if(phase==='closed') return t('period.phase.closed',{p1:fmtDeadline(v)});
  return t('period.phase.over');
}

// Progress of one period: only once filling in has opened and the entries are loaded.
function periodProgressVisible(p, nowMs){
  if(!p || !S.periodEntriesLoaded) return false;
  const phase = periodPhase(p, nowMs);
  return phase==='open' || phase==='closed' || phase==='over';
}

// "Doorgegeven 9 van 14 gezinnen" with a progress bar (Flex families are not counted).
export function periodStatusHtml(p, nowMs){
  if(!periodProgressVisible(p, nowMs)) return '';
  const pr = periodProgress(p, S.families, S.periodEntries);
  const pct = pr.total? Math.round(pr.done/pr.total*100) : 0;
  const value = t('period.status.value',{p1:pr.done, p2:pr.total});
  return `<div class="periodStatus">
      <div class="periodStatusText"><span class="muted">${t('period.status.label')}</span><b>${esc(value)}</b></div>
      <div class="periodBar${pr.total && pr.done===pr.total? ' full' : ''}" role="progressbar" aria-label="${esc(t('period.status.label'))}" aria-valuemin="0" aria-valuemax="${pr.total}" aria-valuenow="${pr.done}" aria-valuetext="${esc(value)}"><span style="width:${pct}%"></span></div>
    </div>`;
}

// Who has handed in and who has not (folded). The fold's subtitle already names the first families that are still missing.
const girlOf = f => (f && (f.girlName || f.parentName)) || '';
const WHO_NAMES_SHOWN = 3;
export function periodWhoHtml(p, nowMs){
  if(!periodProgressVisible(p, nowMs)) return '';
  const pr = periodProgress(p, S.families, S.periodEntries);
  if(!pr.total) return '';
  const todo = pr.rows.filter(r=>!r.done), done = pr.rows.filter(r=>r.done);
  const row = r => {
    const girl = girlOf(r.family), parent = r.family.parentName || '';
    return `<li class="periodWhoRow"><span class="periodWhoMark ${r.done? 'done' : 'todo'}" aria-hidden="true">${r.done? phIcon('check') : ''}</span>
      <span class="periodWhoName"><strong>${esc(girl)}</strong>${parent && parent!==girl? ` <span class="muted">${esc(parent)}</span>` : ''}</span>
      <span class="periodWhoState">${esc(t(r.done? 'period.who.stateDone' : 'period.who.stateTodo'))}</span></li>`;
  };
  const group = (key, rows) => rows.length? `<div class="periodWhoGroup"><div class="periodWhoHead">${esc(t(key,{p1:rows.length}))}</div><ul class="periodWhoList">${rows.map(row).join('')}</ul></div>` : '';
  const names = todo.slice(0, WHO_NAMES_SHOWN).map(r=>girlOf(r.family)).join(', ') + (todo.length>WHO_NAMES_SHOWN? ' '+t('period.who.more',{p1:todo.length-WHO_NAMES_SHOWN}) : '');
  const sub = todo.length? `<span class="periodFoldSub todo">${esc(t('period.who.missing',{p1:names}))}</span>` : `<span class="periodFoldSub done">${esc(t('period.who.allDone'))}</span>`;
  return foldHtml('periodWho|'+p.firstDay, `<span class="periodFoldTitle"><span>${esc(t('period.who.title'))}</span>${sub}</span>`,
    group('period.who.todo', todo) + group('period.who.done', done), 'periodFold');
}

// The label of the delete button when it asks "sure?": says how many families lose what they handed in.
export function periodDeleteConfirmLabel(p){
  const n = periodHasData(p.firstDay).entries, b = periodBackupList(p.firstDay).length;
  if(n && b) return t('period.delete.confirmDataBackups',{p1:n, p2:b});
  if(b) return t('period.delete.confirmBackups',{p1:b});
  return n? t('period.delete.confirmData',{p1:n}) : t('beheer.zeker_nogmaals_klikken');
}

// Back-ups of one period (inside its row, folded): make one, restore one (two taps, with the warning), delete one.
const fmtStamp = ms => new Date(ms).toLocaleString(locale(),{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
export function periodBackupRestoreLabel(b, p){
  const c = changesSince(b, S.periodEntries, S.periodCars, p);
  return c.families? t('period.backup.restoreConfirmLost',{p1:c.families}) : t('period.backup.restoreConfirm');
}
function periodBackupRowHtml(b, p){
  const c = changesSince(b, S.periodEntries, S.periodCars, p);
  const what = t('period.backup.what',{p1:Object.keys(b.entries).length, p2:Object.keys(b.cars).length});
  const since = (c.families || c.shifts)? t('period.backup.since',{p1:c.families, p2:c.shifts}) : c.period? t('period.backup.sincePeriod') : t('period.backup.same');
  return `<div class="periodBackupRow" data-pbrow="${esc(b.id)}">
      <div class="periodBackupMain">
        <div class="periodBackupWhen">${esc(fmtStamp(b.createdAt))}${b.auto? ' <span class="muted">· '+esc(t('period.backup.auto'))+'</span>' : ''}</div>
        <div class="periodBackupMeta">${esc(what)}</div>
        <div class="periodBackupMeta">${esc(since)}</div>
      </div>
      <button type="button" class="iconbtn" data-pbrestore="${esc(b.id)}" aria-label="${esc(t('period.backup.restore'))}" title="${esc(t('period.backup.restore'))}">${phIcon('refresh')}</button>
      <button type="button" class="iconbtn danger" data-pbdelete="${esc(b.id)}" aria-label="${esc(t('period.backup.delete'))}" title="${esc(t('period.backup.delete'))}">${phIcon('trash')}</button>
    </div>`;
}
export function periodBackupsHtml(p){
  const list = periodBackupList(p.firstDay);
  const manual = list.filter(b=>!b.auto).length;
  const body = `<p class="periodHint">${esc(t('period.backup.intro'))}</p>
    <button type="button" class="btn small secondary periodMakeBtn" data-pbmake="${p.firstDay}"${manual>=PERIOD_BACKUP_MAX? ' disabled' : ''}>${esc(t('period.backup.make'))}</button>
    ${list.length? `<div class="periodBackupList">${list.map(b=>periodBackupRowHtml(b, p)).join('')}</div>` : ''}`;
  return foldHtml('periodBackups|'+p.firstDay, `<span class="periodFoldTitle"><span>${esc(t('period.backup.title',{p1:list.length}))}</span></span>`, body, 'periodFold');
}

const PHASE_PILL = { waiting:'period.pill.waiting', open:'period.pill.open', closed:'period.pill.closed', over:'period.pill.over' };
function periodRowHtml(p, nowMs){
  const v = normalizePeriod(p), d = periodHasData(v.firstDay);
  if(S.periodDraft && S.periodDraft.editing===v.firstDay) return periodFormCardHtml();   // edit in place: the form takes the row's spot
  const phase = periodPhase(v, nowMs);
  const pill = PHASE_PILL[phase]? `<span class="periodPill s-${phase}">${esc(t(PHASE_PILL[phase]))}</span>` : '';
  return `<div class="periodItem" data-periodlist="${v.firstDay}">
      <div class="periodHead">
        <div class="periodHeadText">
          <div class="periodTitle"><strong>${esc(v.name)}</strong> <span class="muted">${esc(isoRangeLabel(v.firstDay, v.lastDay))}</span> ${pill}</div>
          <div class="periodInfo">${esc(periodPhaseText(v, nowMs))}</div>
          ${d.rooster? `<div class="periodInfo ok">${phIcon('check')} ${esc(t('period.list.roosterMade'))}</div>` : ''}
        </div>
        <div class="periodActions">
          <button type="button" class="iconbtn" data-plistedit="${v.firstDay}" aria-label="${esc(t('period.list.edit',{p1:v.name}))}" title="${esc(t('period.list.edit',{p1:v.name}))}">${phIcon('pencil')}</button>
          <button type="button" class="iconbtn danger" data-plistdelete="${v.firstDay}" aria-label="${esc(t('period.delete'))}: ${esc(v.name)}" title="${esc(t('period.delete'))}: ${esc(v.name)}">${phIcon('trash')}</button>
        </div>
      </div>
      ${periodStatusHtml(v, nowMs)}
      ${periodWhoHtml(v, nowMs)}
      ${periodBackupsHtml(v)}
    </div>`;
}

function periodFormCardHtml(){
  const dr = S.periodDraft, v = normalizePeriod(dr.value);
  const locked = !!dr.editing && (periodHasData(dr.editing).entries>0 || periodHasData(dr.editing).rooster>0);
  const field = (id,labelKey,type,val,extra='') => `<div style="margin-top:10px;flex:1"><label for="${id}" style="margin-top:0">${t(labelKey)}</label><input type="${type}" id="${id}" class="periodInput" value="${esc(val)}" ${extra}></div>`;
  return `<div class="periodItem periodForm" id="periodDraftForm">
      <h3 class="periodFormTitle">${t(dr.editing? 'period.form.editTitle' : 'period.form.addTitle')}</h3>
      ${field('periodName','period.name','text',v.name,`maxlength="${PERIOD_NAME_MAX}" placeholder="${esc(t('period.namePlaceholder'))}"`)}
      <div class="rowflex" style="gap:8px">
        ${field('periodFirst','period.firstDay','date',v.firstDay, locked? 'disabled' : '')}
        ${field('periodLast','period.lastDay','date',v.lastDay)}
      </div>
      <p class="muted" style="margin-top:3px">${t('period.maxHint',{p1:PERIOD_MAX_WORKDAYS})}${locked? ' '+t('period.firstDayLockedHint') : ''}</p>
      <h4 class="periodFormGroup">${t('period.form.groupFill')}</h4>
      ${field('periodOpens','period.opensOn','date',v.opensOn)}
      <p class="muted" style="margin-top:3px">${t('period.opensHint')}</p>
      <div class="rowflex" style="gap:8px">
        ${field('periodDlDate','period.deadlineDate','date',v.deadlineDate)}
        ${field('periodDlTime','period.deadlineTime','time',v.deadlineTime)}
      </div>
      <p class="muted" style="margin-top:3px">${t('period.deadlineHint')}</p>
      <div class="periodFormActions">
        <button type="button" class="btn small" id="periodDraftSave">${t('period.save')}</button>
        <button type="button" class="btn small secondary" id="periodDraftCancel">${t('period.cancel')}</button>
      </div>
    </div>`;
}

export function periodsCardHtml(nowMs){
  const list = periodList(S.periods);
  const editingListed = !!S.periodDraft && list.some(p => normalizePeriod(p).firstDay===S.periodDraft.editing);
  return `<div class="card" id="periodCard">
      <h2>${t('period.title')}</h2>
      <p class="muted">${t('period.intro')}</p>
      ${list.length? list.map(p => periodRowHtml(p, nowMs)).join('') : (S.periodDraft? '' : `<p class="muted" id="periodPhase">${t('period.phase.none')}</p>`)}
      ${S.periodDraft? (editingListed? '' : periodFormCardHtml()) : `<button type="button" class="btn small secondary" id="periodAdd" data-plistadd style="margin-top:10px">${t('period.add')}</button>`}
    </div>`;
}

const periodField = id => { const el = document.getElementById(id); return el? el.value : ''; };
function readPeriodForm(){
  return normalizePeriod({ name:periodField('periodName'), firstDay:periodField('periodFirst'), lastDay:periodField('periodLast'),
    opensOn:periodField('periodOpens'), deadlineDate:periodField('periodDlDate'), deadlineTime:periodField('periodDlTime') });
}

// Opens the form for a new period (no argument) or to edit one.
export function startPeriodEdit(firstDay){
  S.periodDraft = { editing: firstDay||'', value: firstDay && S.periods[firstDay]? normalizePeriod(S.periods[firstDay]) : normalizePeriod({}) };
  renderBeheer();
}

// Keeps what is typed while the form is open (see the note above).
export function rememberPeriodDraft(){ if(S.periodDraft) S.periodDraft = { editing:S.periodDraft.editing, value:readPeriodForm() }; }

export async function savePeriod(){
  if(!S.periodDraft) return false;
  const editing = S.periodDraft.editing;
  const res = await savePeriodDoc(readPeriodForm(), editing);
  if(!res.ok){
    S.periodDraft = { editing, value:res.value || readPeriodForm() };
    if(res.errors && res.errors.length) showToast(t(res.errors[0],{p1:res.overlap? res.overlap.name : PERIOD_MAX_WORKDAYS}));
    return false;
  }
  S.periodDraft = null;
  showToast(t('period.saved'));
  renderBeheer();
  return true;
}

export function cancelPeriodEdit(){ S.periodDraft = null; renderBeheer(); }

export async function deletePeriod(firstDay){
  const ok = await deletePeriodCompletely(firstDay);
  if(ok && S.periodDraft && S.periodDraft.editing===firstDay) S.periodDraft = null;
  renderBeheer();
  return ok;
}

// US-15 / US-21: the pickup and drop-off places (up to 6) with names and addresses, the destination in Alkmaar,
// the default place per direction and the fixed distances for AFC and ATC. One document: settings/locations.
// An address is a logical address, GPS in decimal degrees, or GPS in degrees-minutes-seconds.
export function locationsCardHtml(){
  const cfg = locationsCfg();
  const placeRows = cfg.places.map(p=>{
    const gps = parseCoordinates(p.address);
    const hint = gps? `<p class="addrHint">${t('loc.gpsRecognized',{p1:gps.lat+', '+gps.lon})}</p>` : '';
    const remove = p.id===BUSSTATION_ID? '' : `<button type="button" class="iconbtn danger locRemove" data-locremove="${p.id}" aria-label="${esc(t('loc.removePlace',{name:p.name}))}" title="${esc(t('loc.removePlace',{name:p.name}))}">${phIcon('trash')}</button>`;
    return `<div class="grid2" style="margin-top:6px">
      <div><label style="margin-top:0" for="locName_${p.id}">${t('loc.placeName')}</label><input type="text" class="locInput" id="locName_${p.id}" value="${esc(p.name)}"></div>
      <div><label style="margin-top:0" for="locAddr_${p.id}">${t('loc.placeAddress')}</label>
        <div class="rowflex" style="gap:6px"><input type="text" class="locInput" id="locAddr_${p.id}" value="${esc(p.address)}" placeholder="${esc(t('loc.addressPlaceholder'))}" style="flex:1;min-width:0">${remove}</div>${hint}</div>
    </div>`;
  }).join('');
  const opts = sel => cfg.places.map(p=>`<option value="${p.id}" ${p.id===sel?'selected':''}>${esc(p.name)}</option>`).join('');
  const add = cfg.places.length<MAX_PLACES
    ? `<button type="button" class="btn small secondary" id="locAdd" style="margin-top:10px">+ ${t('loc.addPlace')}</button>`
    : `<p class="muted" style="margin-top:10px">${t('loc.maxPlaces',{p1:MAX_PLACES})}</p>`;
  return `<div class="card" id="locationsCard">
      <h2>${t('loc.beheerTitle')}</h2>
      <p class="muted">${t('loc.beheerIntro',{p1:MAX_PLACES})}</p>
      ${placeRows}
      ${add}
      <div class="grid2" style="margin-top:10px">
        <div><label style="margin-top:0" for="locDestName">${t('loc.destination')}</label><input type="text" class="locInput" id="locDestName" value="${esc(cfg.destination.name)}"></div>
        <div><label style="margin-top:0" for="locDestAddr">${t('loc.placeAddress')}</label><input type="text" class="locInput" id="locDestAddr" value="${esc(cfg.destination.address)}" placeholder="Straat 1, Alkmaar"></div>
      </div>
      <div class="grid2" style="margin-top:10px">
        <div><label style="margin-top:0" for="locDefHeen">${t('loc.defaultHeen')}</label><select class="locInput" id="locDefHeen">${opts(cfg.defaults.heen)}</select></div>
        <div><label style="margin-top:0" for="locDefTerug">${t('loc.defaultTerug')}</label><select class="locInput" id="locDefTerug">${opts(cfg.defaults.terug)}</select></div>
      </div>
      <p class="muted" style="margin-top:10px">${t('loc.shiftHint')}</p>
      <p class="muted" style="margin-top:10px"><strong>${t('loc.fixedTitle')}</strong> ${t('loc.fixedHint')}</p>
      <div class="grid2">
        <div><label style="margin-top:0" for="locFixAFC">${t('loc.fixedAFC')}</label><input type="number" class="locInput" id="locFixAFC" min="0" step="0.1" value="${cfg.fixedKm.AFC==null?'':cfg.fixedKm.AFC}"></div>
        <div><label style="margin-top:0" for="locFixATC">${t('loc.fixedATC')}</label><input type="number" class="locInput" id="locFixATC" min="0" step="0.1" value="${cfg.fixedKm.ATC==null?'':cfg.fixedKm.ATC}"></div>
      </div>
    </div>`;
}

// API keys that may not sit in the public GitHub folder. Now only the OpenRouteService key (distance of away matches).
// Stored in settings/apiKeys: members can read it (the app needs it), only the coordinator can change it (Firestore rules).
// The key itself is never shown again after saving, only the last 4 characters.
export function apiKeysCardHtml(){
  const has = hasApiKey(S.orsApiKey);
  const status = has
    ? `<p class="fitok">${phIcon('check')} ${t('apikeys.ors_ingesteld',{p1:esc(String(S.orsApiKey).slice(-4))})}</p>`
    : `<p class="muted">${t('apikeys.ors_niet_ingesteld')}</p>`;
  return `<div class="card" id="apiKeysCard">
      <h2>${t('apikeys.titel')}</h2>
      <p class="muted">${t('apikeys.uitleg')}</p>
      ${status}
      <label style="margin-top:0" for="apiKeyOrs">${t('apikeys.ors_label')}</label>
      <input type="password" id="apiKeyOrs" autocomplete="off" spellcheck="false" placeholder="${esc(t('apikeys.ors_placeholder'))}">
      <div class="rowflex" style="gap:6px;margin-top:8px">
        <button type="button" class="btn small secondary" id="apiKeyOrsSave">${t('apikeys.opslaan')}</button>
        ${has? `<button type="button" class="btn small danger" id="apiKeyOrsClear">${t('apikeys.verwijderen')}</button>` : ''}
      </div>
    </div>`;
}

// Saves (or, with value '', removes) the OpenRouteService key. Without an argument it reads the input field.
export async function saveOrsApiKey(value){
  if(!db){ showToast(t('data.geen_verbinding_met_opslag')); return false; }
  const el = document.getElementById('apiKeyOrs');
  const key = String(value!==undefined? value : (el? el.value : '')).trim();
  if(value===undefined && !key){ showToast(t('apikeys.leeg')); return false; }
  if(/\s/.test(key)){ showToast(t('apikeys.spaties')); return false; }
  try{
    await db.doc("settings/apiKeys").set({ ors:key }, { merge:true });
    S.orsApiKey = key;
    if(el) el.value = '';
    showToast(t(key? 'apikeys.opgeslagen' : 'apikeys.verwijderd'));
    renderBeheer(); renderMyWeek();
    return true;
  }catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

// One write of settings/locations (normalised). Every locations save goes through here.
async function writeLocations(raw, toastKey){
  if(!db){ showToast(t('data.geen_verbinding_met_opslag')); return false; }
  const doc = normalizeLocations(raw);
  try{ await db.doc("settings/locations").set(doc); S.locationsDoc = doc; if(toastKey) showToast(t(toastKey)); return true; }
  catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); return false; }
}

export async function saveLocations(){
  if(!db){ showToast(t('data.geen_verbinding_met_opslag')); return false; }
  const val = (id,fb)=>{ const el=document.getElementById(id); return el? el.value : (fb==null?'':fb); };
  const cur = locationsCfg();
  return writeLocations({
    places: cur.places.map(p=>({ id:p.id, name:val('locName_'+p.id,p.name), address:val('locAddr_'+p.id,p.address) })),
    destination: { name:val('locDestName'), address:val('locDestAddr') },
    defaults: { heen:val('locDefHeen',cur.defaults.heen), terug:val('locDefTerug',cur.defaults.terug) },
    shifts: cur.shifts,
    fixedKm: { AFC:val('locFixAFC'), ATC:val('locFixATC') },
  }, 'loc.saved');
}

// Adds an empty place (max 6). The coordinator then types its name and address.
export async function addLocationPlace(){
  const cur = locationsCfg();
  if(cur.places.length>=MAX_PLACES){ showToast(t('loc.maxPlaces',{p1:MAX_PLACES})); return false; }
  return writeLocations({ ...cur, places:[...cur.places, newPlace(cur.places, t('loc.newPlaceName'))] }, 'loc.saved');
}

// Removes a place. Rides that still point at it fall back to the standard place; Busstation cannot be removed.
export async function removeLocationPlace(id){
  const cur = locationsCfg();
  if(id===BUSSTATION_ID || !cur.places.some(p=>p.id===id)) return false;
  return writeLocations({ ...cur, places:cur.places.filter(p=>p.id!==id) }, 'loc.saved');
}

// Standaardrooster: another standard place for one shift (day + direction). placeId '' = follow the heen/terug default.
export async function saveShiftLocation(day,direction,placeId){
  const cur = locationsCfg();
  const shifts = {...cur.shifts};
  if(placeId) shifts[day+'_'+direction]=placeId; else delete shifts[day+'_'+direction];
  const ok = await writeLocations({ ...cur, shifts }, 'loc.shiftSaved');
  if(ok){ recordLastUpdate('Rooster'); renderSchedule(); renderMyWeek(); renderDeviationTab(); }
  return ok;
}

export function renderBeheer(){
  const box=document.getElementById('tab-beheer');
  if(!box) return;
  if(!S.canEdit){ box.innerHTML = `<div class="card"><p class="muted">${t('beheer.deze_pagina_is_alleen_voor')}</p></div>`; return; }

  const claimed = {}; Object.entries(S.links).forEach(([uid,l])=>claimed[l.familyId]=true);
  const byName={};
  Object.entries(S.families).forEach(([id,fd])=>{
    const key=(fd.girlName||'').trim().toLowerCase();
    if(key) (byName[key]=byName[key]||[]).push([id,fd]);
  });
  const dupGroups = Object.values(byName).filter(list=>list.length>1);
  const dupWarning = dupGroups.length? `<div class="group warning" style="margin-bottom:10px">
      <div class="fitbad">${phIcon('warning')} ${t('beheer.mogelijk_dubbele_gezinnen_controleer_en')}</div>
      ${dupGroups.map(list=>`<div style="margin-top:6px"><strong>${esc(list[0][1].girlName)}</strong> (${list.length}x):<br>${list.map(([id,fd])=>`<span class="pill">${esc(fd.parentName||id)} <button type="button" class="iconbtn danger" data-coorddel="${id}" style="margin-left:4px;min-width:30px;min-height:30px" aria-label="${t('beheer.verwijder')}" title="${t('beheer.verwijder')}">${phIcon('trash')}</button></span>`).join(' ')}</div>`).join('')}
    </div>` : '';
  const rows = sortFamEntriesByGirl(Object.entries(S.families)).map(([id,fd])=>{
    const isCoord = S.coordinatorConfig && S.coordinatorConfig.familyId===id;
    // Phone numbers and invite codes are only shown inside "Wijzig"; the list only flags what's missing.
    const missing = [!fd.parentPhone1&&!fd.parentPhone2? 'telefoonnummer' : '', !S.inviteByFamily[id]? 'code' : ''].filter(Boolean);
    return `
    <div class="rowflex" style="padding:10px 0;border-bottom:1px solid var(--border);gap:8px">
      <div style="flex:1;min-width:0">
        <div style="font-size:16px;font-weight:800">${esc(fd.girlName||'(naam?)')}</div>
        <div class="muted">${esc(fd.parentName||'(ouder?)')} ${claimed[id]?t('beheer.span_class_badge_gekoppeld_span'):''} ${isCoord?t('beheer.span_class_badge_rec_coordinator'):''}${fd.familyType==='flex'? ` <span class="badge flexBadge">${t('flex.badge')}</span>` : ''}</div>
        ${missing.length? `<div class="fitbad" style="font-size:12px;margin-top:2px">${phIcon('warning')} ${t('beheer.geen')} ${missing.join(t('beheer.en'))}</div>` : ''}
      </div>
      <span style="display:flex;gap:6px;flex-shrink:0">
        <button type="button" class="btn small secondary" data-coordedit="${id}">${t('beheer.wijzig')}</button>
        <button type="button" class="iconbtn" data-imptest="${id}" aria-label="Test de app als ${esc(fd.parentName||t('beheer.deze_ouder'))}" title="${t('beheer.testweergave_als_deze_ouder')}">${phIcon('eye')}</button>
        <button type="button" class="iconbtn danger" data-coorddel="${id}" aria-label="Verwijder ${esc(fd.girlName||'gezin')}" title="${t('beheer.verwijder')}">${phIcon('trash')}</button>
      </span>
    </div>`;
  }).join('') || `<p class="muted">${t('beheer.nog_geen_gezinnen_toegevoegd')}</p>`;

  // ---- attention strip: things the coordinator should look at, each linking to its card ----
  const noCode = Object.keys(S.families).filter(id=>!S.inviteByFamily[id]).length;
  const noPhone = Object.values(S.families).filter(fd=>!fd.parentPhone1&&!fd.parentPhone2).length;
  const attn = [];
  if(noCode) attn.push(['familiesCard', t('beheer.attn_zonder_code',{p1:noCode})]);
  if(noPhone) attn.push(['familiesCard', t('beheer.attn_zonder_telefoon',{p1:noPhone})]);
  dupGroups.forEach(list=>attn.push(['familiesCard', t('beheer.attn_dubbel',{p1:esc(list[0][1].girlName),p2:list.length})]));
  (S.matchFetchFailedTeams||[]).forEach(f=>attn.push(['feedsCard', t('beheer.attn_kalender_mislukt',{p1:esc(f.label)})]));
  const attnHtml = attn.length? `<div class="begAttn" role="status">
      <div class="begAttnHead">${phIcon('warning')} ${t('beheer.attn_titel',{p1:attn.length})}</div>
      ${attn.map(([id,txt])=>`<button type="button" class="begAttnItem" data-goto="${id}"><span>${txt}</span>${phIcon('chevron-right')}</button>`).join('')}
    </div>` : '';

  // Puts a phIcon name on a card built elsewhere; foldCards shows it in the summary.
  const ic = (icon, html)=>html.replace(/^(\s*)<div class="card/, `$1<div data-icon="${icon}" class="card`);
  const sections = [
    ['gezinnen', 'beheer.chip_gezinnen', 'beheer.sec_gezinnen', [
      ic('users', `<div class="card" id="familiesCard">
        <h2>${t('beheer.gezinnen_beheren')}</h2>
        <p class="muted">${t('beheer.vul_of_wijzig_gegevens_namens')}</p>
        ${dupWarning}
        ${rows}
        <button type="button" class="btn secondary" id="coordNew">${t('beheer.nieuw_gezin_toevoegen')}</button>
        <div id="coordEditArea"></div>
      </div>`),
      ic('user', dayCoordinatorsCardHtml()),
      ic('chart', rideLogCardHtml()),
      ic('list', `<div class="card" id="priorityCard">
        <h2>${t('beheer.selectievolgorde_per_shift')}</h2>
        ${renderPriorityCard()}
      </div>`),
      ic('heart', `<div class="card" id="prefsCard">
        <h2>${t('beheer.reisvoorkeuren')}</h2>
        <p class="muted">${t('beheer.wie_er_logistiek_het_beste')}</p>
        ${renderPrefsCard()}
      </div>`),
      ic('calendar', `<div class="card" id="availabilityCard">
        <h2>${t('beheer.beschikbaarheid_chauffeurs_weekoverzicht')}</h2>
        ${renderAvailabilityTable()}
      </div>`),
    ]],
    ['periodes', 'beheer.chip_periodes', 'beheer.sec_periodes', [
      ic('clock', periodsCardHtml()),
      ic('gear', `<div class="card" id="planningCard">
        <h2>${t('beheer.planning_instellingen')}</h2>
        <p class="muted">${t('beheer.deze_regels_bepalen_hoe_combinaties')}</p>
        <div class="grid4">
          <div><label>${t('beheer.max_tijdsverschil_voor_1_auto')}</label><input type="number" id="setGap" min="0.5" step="0.5" value="${S.settings.gapThresholdHours}"></div>
          <div><label>${t('beheer.rijtijd_aalsmeer_alkmaar_min_vertrektijd')}</label><input type="number" id="setLead" min="0" step="5" value="${S.settings.travelLeadMinutes}"></div>
          <div><label>${t('beheer.marge_reisvookeuren_min')}</label><input type="number" id="setPrefWindow" min="0" step="5" value="${S.settings.prefWindowMinutes}"></div>
          <div><label>${t('beheer.max_wachttijd_om_met_eigen')}</label><input type="number" id="setParentPrefWindow" min="0" step="5" value="${S.settings.parentPrefWindowMinutes}"></div>
        </div>
      </div>`),
      ic('map-pin', locationsCardHtml()),
    ]],
    ['berichten', 'beheer.chip_berichten', 'beheer.sec_berichten', [
      ic('wrench', maintenanceCardHtml()),
      ic('car', ritbeursCardHtml()),
      ic('info', noticeCardHtml()),
      ic('bell', `<div class="card" id="notifCard">
        <h2>${t('beheer.meldingen_bij_gewijzigde_tijden')}</h2>
        <p class="muted">${t('beheer.als_een_ouder_de_aankomst')}</p>
        ${('Notification' in window)
          ? (Notification.permission==='granted'
              ? `<p class="fitok">${phIcon('check')} ${t('beheer.browsermeldingen_staan_aan_op_dit')}</p>`
              : Notification.permission==='denied'
                ? `<p class="fitbad">${t('beheer.browsermeldingen_zijn_geblokkeerd_zet_ze')}</p>`
                : `<button type="button" class="btn small secondary" id="enableNotifBtn">${t('beheer.browsermeldingen_aanzetten')}</button>`)
          : `<p class="muted">${t('beheer.deze_browser_ondersteunt_geen_meldingen')}</p>`}
      </div>`),
    ]],
    ['koppelingen', 'beheer.chip_koppelingen', 'beheer.sec_koppelingen', [
      ic('soccer', `<div class="card" id="feedsCard">
        <h2>${t('beheer.wedstrijdkalenders_google_calendar')}</h2>
        <p class="muted">${t('beheer.deze_agenda_s_voeden_wedstrijden')}</p>
        ${activeMatchFeeds().map((f,i)=>`
          <div class="rowflex" style="margin-top:6px;align-items:flex-end;gap:6px">
            <div class="grid2" style="flex:1">
              <div><label style="margin-top:0">${t('beheer.naam')}</label><input type="text" class="matchFeedLabel" data-feedidx="${i}" value="${esc(f.label)}"></div>
              <div><label style="margin-top:0">${t('beheer.calendar_id')}</label><input type="text" class="matchFeedCalId" data-feedidx="${i}" value="${esc(f.calendarId)}" placeholder="${t('beheer.xxxx_group_v_calendar_google')}"></div>
            </div>
            <button type="button" class="iconbtn danger" data-delfeed="${i}" aria-label="${t('beheer.verwijder_kalender')}" title="${t('beheer.verwijder_kalender')}">${phIcon('trash')}</button>
          </div>`).join('')}
        <div class="cardActions">
          <button type="button" class="btn small secondary" id="addMatchFeedBtn">${t('beheer.nieuwe_kalender_toevoegen')}</button>
          <button type="button" class="btn small secondary" id="refreshMatchesBtn">${phIcon('refresh')} ${t('beheer.nu_verversen')}</button>
        </div>
        ${(S.matchesFetchedAt||S.cachedMatchesAt)? `<p class="muted" style="margin-top:6px">${t('beheer.laatst_opgehaald')} ${new Date(Math.max(S.matchesFetchedAt||0, S.cachedMatchesAt||0)).toLocaleString(locale())}${S.matchFetchFailedTeams.length? t('beheer.mislukt')+esc(S.matchFetchFailedTeams.map(f=>f.label+' ('+f.error+')').join('; ')) : ''}</p>` : ''}
      </div>`),
      ic('key', apiKeysCardHtml()),
      ic('download', familyBackupCardHtml()),
      ic('chart', impactCardHtml()),
    ]],
  ];

  box.innerHTML = `${attnHtml}
    <nav class="begChips" aria-label="${t('beheer.onderdelen')}">${sections.map(([id,chip],i)=>`<button type="button" class="begChip${i===0?' on':''}" data-sec="${id}">${t(chip)}</button>`).join('')}</nav>
    ${sections.map(([id,,title,cards])=>`<section class="begSec" id="begSec-${id}"><div class="begSecTitle">${t(title)}</div>${cards.join('')}</section>`).join('')}`;

  foldCards(box);

  document.querySelectorAll('.begChip').forEach(b=>b.onclick=()=>{
    hapticTap();
    document.querySelectorAll('.begChip').forEach(x=>x.classList.toggle('on', x===b));
    const sec=document.getElementById('begSec-'+b.dataset.sec); if(sec) sec.scrollIntoView({block:'start'});
  });
  document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>{
    hapticTap();
    const card=document.getElementById(b.dataset.goto); if(!card) return;
    card.open=true; if(card.dataset.fold) S.folds[card.dataset.fold]=true;
    card.scrollIntoView({block:'start'});
  });

  try{
    const saveSettingsAuto = async ()=>{
      if(!db){showToast(t('data.geen_verbinding_met_opslag'));return;}
      const gapThresholdHours = parseFloat(document.getElementById('setGap').value)||3;
      const travelLeadMinutes = parseInt(document.getElementById('setLead').value)||60;
      const prefWindowMinutes = parseInt(document.getElementById('setPrefWindow').value);
      const parentPrefWindowMinutes = parseInt(document.getElementById('setParentPrefWindow').value);
      try{ await db.doc("settings/planning").set({gapThresholdHours,travelLeadMinutes,prefWindowMinutes: isNaN(prefWindowMinutes)?30:prefWindowMinutes, parentPrefWindowMinutes: isNaN(parentPrefWindowMinutes)?60:parentPrefWindowMinutes}); showToast(t('data.opgeslagen')); }
      catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
    };
    const setGapEl=document.getElementById('setGap'); if(setGapEl) setGapEl.onchange=saveSettingsAuto;
    const setLeadEl=document.getElementById('setLead'); if(setLeadEl) setLeadEl.onchange=saveSettingsAuto;
    const setPrefWindowEl=document.getElementById('setPrefWindow'); if(setPrefWindowEl) setPrefWindowEl.onchange=saveSettingsAuto;
    const setParentPrefWindowEl=document.getElementById('setParentPrefWindow'); if(setParentPrefWindowEl) setParentPrefWindowEl.onchange=saveSettingsAuto;
    document.querySelectorAll('.dayCoordSel').forEach(sel=>sel.onchange=()=>saveDayCoordinator(sel.dataset.coordday, sel.value));
    wireNoticeCard();
    wireRideLogCard();
    wireMaintenanceCard();
    wireRitbeursCard();
    document.querySelectorAll('.periodInput').forEach(el=>el.oninput=rememberPeriodDraft);
    const perSave=document.getElementById('periodDraftSave'); if(perSave) perSave.onclick=()=>{ hapticTap(); return savePeriod(); };
    const perCancel=document.getElementById('periodDraftCancel'); if(perCancel) perCancel.onclick=()=>cancelPeriodEdit();
    document.querySelectorAll('[data-plistadd]').forEach(b=>b.onclick=()=>{ hapticTap(); startPeriodEdit(); });
    document.querySelectorAll('[data-plistedit]').forEach(b=>b.onclick=()=>{ hapticTap(); startPeriodEdit(b.dataset.plistedit); });
    document.querySelectorAll('[data-plistdelete]').forEach(b=>b.onclick=()=>{ const p=S.periods[b.dataset.plistdelete]; if(p) twoStepConfirm(b, periodDeleteConfirmLabel(p), ()=>deletePeriod(b.dataset.plistdelete)); });
    document.querySelectorAll('[data-pbmake]').forEach(b=>b.onclick=()=>{ hapticTap(); createPeriodBackup(b.dataset.pbmake); });
    document.querySelectorAll('[data-pbrestore]').forEach(b=>b.onclick=()=>{
      const bk = Object.keys(S.periods).flatMap(fd=>periodBackupList(fd)).find(x=>x.id===b.dataset.pbrestore);
      if(bk) twoStepConfirm(b, periodBackupRestoreLabel(bk, S.periods[bk.periodFirstDay]), ()=>restorePeriodBackup(bk.id));
    });
    document.querySelectorAll('[data-pbdelete]').forEach(b=>b.onclick=()=>twoStepConfirm(b, t('beheer.zeker_nogmaals_klikken'), ()=>deletePeriodBackup(b.dataset.pbdelete)));
    document.querySelectorAll('.locInput').forEach(el=>el.onchange=()=>saveLocations());
    const orsSave=document.getElementById('apiKeyOrsSave'); if(orsSave) orsSave.onclick=()=>{ hapticTap(); saveOrsApiKey(); };
    const orsClear=document.getElementById('apiKeyOrsClear'); if(orsClear) orsClear.onclick=()=>twoStepConfirm(orsClear, t('beheer.zeker_nogmaals_klikken'), ()=>saveOrsApiKey(''));
    const locAdd=document.getElementById('locAdd'); if(locAdd) locAdd.onclick=()=>{ hapticTap(); addLocationPlace(); };
    document.querySelectorAll('[data-locremove]').forEach(btn=>btn.onclick=()=>twoStepConfirm(btn, t('beheer.zeker_nogmaals_klikken'), ()=>removeLocationPlace(btn.dataset.locremove)));
    wireImpactCard(renderBeheer);
    wireFamilyBackupCard();
    const atp=document.getElementById('addTogetherPref');
    if(atp) atp.onclick=async ()=>{
      const ids=[...document.querySelectorAll('.prefTogetherPick:checked')].map(c=>c.value);
      if(ids.length<2){showToast(t('beheer.kies_minstens_2_meiden'));return;}
      try{ await db.doc("settings/prefs").set({rules:[...(S.prefs.rules||[]), {type:'together', ids}]}); showToast(t('beheer.toegevoegd')); }
      catch(e){showToast(t('data.mislukt')+(e&&e.message||e));}
    };
    const app_=document.getElementById('addPreferPref');
    if(app_) app_.onclick=async ()=>{
      const girlSel=document.getElementById('preferGirlSelect');
      const girlId=girlSel? girlSel.value : null;
      const withAny=[...document.querySelectorAll('.prefWithPick:checked')].map(c=>c.value).filter(id=>id!==girlId);
      if(!girlId||!withAny.length){showToast(t('beheer.kies_een_meisje_en_minstens'));return;}
      try{ await db.doc("settings/prefs").set({rules:[...(S.prefs.rules||[]), {type:'prefer', girlId, withAny}]}); showToast(t('beheer.toegevoegd')); }
      catch(e){showToast(t('data.mislukt')+(e&&e.message||e));}
    };
    document.querySelectorAll('[data-delpref]').forEach(b=>b.onclick=async ()=>{
      const idx=+b.dataset.delpref;
      const rules=(S.prefs.rules||[]).filter((_,i)=>i!==idx);
      try{ await db.doc("settings/prefs").set({rules}); }catch(e){showToast(t('beheer.verwijderen_mislukt')+(e&&e.message||e));}
    });
    document.querySelectorAll('[data-imptest]').forEach(b=>b.onclick=()=>startImpersonate(b.dataset.imptest));
    const shiftSel=document.getElementById('shiftPrioritySelect');
    if(shiftSel){
      shiftSel.onchange = ()=>{ S.selectedShiftKey=shiftSel.value; renderShiftPriorityRows(S.selectedShiftKey); };
      renderShiftPriorityRows(S.selectedShiftKey);
    }
    const cn=document.getElementById('coordNew');
    if(cn) cn.onclick = ()=>{ S.coordEditId=null; renderCoordEditor(); };
    document.querySelectorAll('[data-coordedit]').forEach(b=>b.onclick=()=>{ S.coordEditId=b.dataset.coordedit; renderCoordEditor(); });
    document.querySelectorAll('[data-coorddel]').forEach(b=>b.onclick=()=>twoStepConfirm(b,t('beheer.zeker_nogmaals_klikken'),async ()=>{
      try{
        const fid=b.dataset.coorddel;
        const batch=db.batch();
        batch.delete('families/'+fid);
        Object.entries(S.invitesByCode).forEach(([c,f])=>{ if(f===fid) batch.delete('invites/'+c); });
        Object.entries(S.groups).forEach(([gid,g])=>{
          const inCar=(g.girlIds||[]).includes(fid), drives=g.driverFamilyId===fid;
          if(inCar||drives) batch.update('groups/'+gid, {girlIds:(g.girlIds||[]).filter(x=>x!==fid), ...(drives?{driverFamilyId:null}:{})});
        });
        await batch.commit();
      }catch(e){showToast(t('beheer.verwijderen_mislukt')+(e&&e.message||e));}
    }));
    if(S.coordEditId!==undefined) renderCoordEditor();
    const saveMatchFeeds = async ()=>{
      const labels=[...document.querySelectorAll('.matchFeedLabel')];
      const calIds=[...document.querySelectorAll('.matchFeedCalId')];
      const feeds = labels.map((el,i)=>({label:el.value.trim(), calendarId:(calIds[i]&&calIds[i].value.trim())||''})).filter(f=>f.calendarId);
      try{ await db.doc("settings/matchFeeds").set({feeds}); showToast(t('data.opgeslagen')); }
      catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
    };
    document.querySelectorAll('.matchFeedLabel,.matchFeedCalId').forEach(el=>el.onchange=saveMatchFeeds);
    const addFeedBtn=document.getElementById('addMatchFeedBtn');
    if(addFeedBtn) addFeedBtn.onclick=()=>{ S.matchFeeds=[...activeMatchFeeds(), {label:'', calendarId:''}]; renderBeheer(); };
    document.querySelectorAll('[data-delfeed]').forEach(b=>b.onclick=async ()=>{
      const idx=+b.dataset.delfeed;
      const feeds = activeMatchFeeds().filter((_,i)=>i!==idx);
      try{ await db.doc("settings/matchFeeds").set({feeds}); showToast(t('beheer.verwijderd')); }
      catch(e){ showToast(t('data.mislukt')+(e&&e.message||e)); }
    });
    const refreshBtn=document.getElementById('refreshMatchesBtn');
    if(refreshBtn) refreshBtn.onclick=()=>{ showToast(t('beheer.wedstrijden_verversen')); loadAllMatches(); };
    const enb=document.getElementById('enableNotifBtn');
    if(enb) enb.onclick=async ()=>{ try{ await Notification.requestPermission(); }catch(e){} renderBeheer(); };
  }catch(e){ showToast(t('beheer.fout_bij_koppelen_knoppen')+(e&&e.message||e)); }
}

export function renderCoordEditor(){
  const area=document.getElementById('coordEditArea');
  if(!area)return;
  if(S.coordEditId===undefined){area.innerHTML='';return;}
  const isNew = S.coordEditId===null;
  const f = isNew? null : fam(S.coordEditId);
  const currentCode = f? (S.inviteByFamily[S.coordEditId]||'') : genCode();
  const isCoordThis = !isNew && S.coordinatorConfig && S.coordinatorConfig.familyId===S.coordEditId;
  const selfLinkedThis = !isNew && !!(S.links[S.me] && S.links[S.me].familyId===S.coordEditId);
  const coordToggleHtml = isNew? '' : `
    <div class="rowflex" style="margin:10px 0;padding:10px;border:1px solid var(--border);border-radius:var(--radius-md);background:var(--bg)">
      <span style="font-size:14px">${isCoordThis? t('beheer.span_class_badge_rec_coordinator') : t('beheer.span_class_muted_nog_geen_2')}</span>
      <button type="button" class="btn small secondary" id="coordToggleBtn">${isCoordThis? t('beheer.coordinator_intrekken') : (selfLinkedThis? t('beheer.maak_coordinator') : phIcon('warning')+t('beheer.maak_coordinator_2'))}</button>
    </div>`;
  area.innerHTML = `<div class="card" style="margin-top:10px;border-color:var(--accent)">
    <h2>${isNew? t('beheer.nieuw_gezin_toevoegen_2') : t('beheer.bewerken')+esc((f.girlName||f.parentName)||'')}</h2>
    ${coordToggleHtml}
    <label>${t('beheer.uitnodigingscode_meerdere_mensen_kunnen_dezelfde')}</label>
    <div class="rowflex" style="gap:6px">
      <input type="text" id="coord_inviteCode" value="${esc(currentCode)}" style="flex:1">
      <button type="button" class="btn small secondary" id="genCodeBtn">${phIcon('dice')} ${t('beheer.nieuwe_code')}</button>
    </div>
    ${familyFormHtml('coord', f)}
    <button type="button" class="btn secondary" id="coordCancel">${t('beheer.sluiten')}</button>
    <p class="muted" style="margin-top:8px">${t('beheer.wijzigingen_worden_automatisch_opgeslagen')}</p>
  </div>`;
  const card=area.querySelector('.card');
  if(card) card.addEventListener('change', ()=>saveCoordFamily());
  wireExclusiveAvailability('coord');
  wireFamilyFormExtras('coord', renderCoordEditor);
  wireIntroWa('coord');
  const ctb=document.getElementById('coordToggleBtn');
  if(ctb) ctb.onclick=()=>{
    const isCurrently = S.coordinatorConfig && S.coordinatorConfig.familyId===S.coordEditId;
    const selfLinked = !!(S.links[S.me] && S.links[S.me].familyId===S.coordEditId);
    if(!isCurrently && !selfLinked){
      twoStepConfirm(ctb, t('beheer.let_op_jij_bent_hier'), ()=>doToggleCoord(S.coordEditId,isCurrently));
    } else if(isCurrently){
      twoStepConfirm(ctb, t('beheer.zeker_de_coordinator_rol_gaat'), ()=>doToggleCoord(S.coordEditId,isCurrently));
    } else {
      doToggleCoord(S.coordEditId,isCurrently);
    }
  };
  document.getElementById('coordCancel').onclick = ()=>{ S.coordEditId=undefined; renderBeheer(); };
  const genBtn=document.getElementById('genCodeBtn');
  if(genBtn) genBtn.onclick=()=>{ document.getElementById('coord_inviteCode').value=genCode(); saveCoordFamily(); };
}

// ---------- Tijdswijzigingen: coordinator sees which passengers changed their times ----------
export function timeChangesCardHtml(){
  if(!S.canEdit) return '';
  const pending = collectPendingChanges(S.families);
  if(!pending.length) return '';
  const total = pending.reduce((n,f)=>n+f.changes.length,0);
  const famHtml = pending.map(f=>{
    const lines = f.changes.map(c=>`<div class="timeChangeLine"><button type="button" class="btn small secondary" data-tcday="${esc(c.day)}" style="padding:2px 8px;min-height:26px;margin-right:6px">${esc(dayUp(c.day))}</button>${esc(describeChange(c).replace(/^\S+ · /,''))}</div>`).join('');
    const when = f.latestAt? new Date(f.latestAt).toLocaleString(locale(),{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}) : '';
    const by = f.changes.find(c=>c.by)?.by || '';
    return `<div class="timeChangeFam">
      <div class="rowflex" style="align-items:flex-start">
        <div><strong>${esc(f.girlName||f.parentName||f.familyId)}</strong>
          <div class="muted" style="font-size:12px">${by? t('beheer.door')+esc(by)+' · ' : ''}${when}</div></div>
        <button type="button" class="btn small secondary" data-tcseen="${esc(f.familyId)}">${phIcon('check')} ${t('beheer.gezien')}</button>
      </div>
      ${lines}
    </div>`;
  }).join('');
  return `<div class="card timeChangeCard">
    <div class="rowflex" style="align-items:baseline">
      <h2 style="margin:0">${phIcon('warning')} ${t('beheer.gewijzigde_tijden')}${total})</h2>
      ${pending.length>1? `<button type="button" class="btn small secondary" id="tcSeenAll">${t('beheer.alles_gezien')}</button>` : ''}
    </div>
    <p class="muted" style="margin:4px 0 6px">${t('beheer.deze_ouders_hebben_hun_aankomst')}</p>
    ${famHtml}
  </div>`;
}

export function wireTimeChangesCard(){
  document.querySelectorAll('[data-tcseen]').forEach(b=>b.onclick=()=>markTimeChangesSeen([b.dataset.tcseen]));
  const all=document.getElementById('tcSeenAll');
  if(all) all.onclick=()=>twoStepConfirm(all,t('beheer.zeker_klik_nogmaals'),()=>markTimeChangesSeen(collectPendingChanges(S.families).map(f=>f.familyId)));
  document.querySelectorAll('[data-tcday]').forEach(b=>b.onclick=()=>{ S.scheduleDay=b.dataset.tcday; hapticTap(); renderSchedule(); });
}

export function updateTimeChangesBadge(){
  const badge=document.getElementById('navRoosterBadge');
  if(!badge) return;
  const n = S.canEdit? countPendingChanges(S.families) : 0;
  badge.textContent = n>9? '9+' : String(n);
  badge.style.display = n? '' : 'none';
}

// Called on every families snapshot: when a NEW change arrives while the coordinator has the
// app open, show a toast (and, if the browser allowed it, a system notification).
export function notifyCoordinatorOfNewTimeChanges(){
  const n = countPendingChanges(S.families);
  const prev = S.lastPendingChangeCount;
  S.lastPendingChangeCount = n;
  if(prev===null || !S.canEdit || n<=prev) return;
  const newest = collectPendingChanges(S.families)[0];
  const who = newest? (newest.girlName||newest.parentName) : '';
  const msg = t('beheer.nieuwe_tijdswijziging_zie_rooster', { p1: who? t('beheer.van')+who : '' });
  showToast(msg);
  try{
    if('Notification' in window && Notification.permission==='granted' && document.visibilityState!=='visible'){
      new Notification(t('beheer.az_carpool'), {body: msg, icon: './icon-192.png'});
    }
  }catch(e){ /* notifications are a bonus; never break the app over them */ }
}
