// ui-common.js — generated by the modularisation of index.html; see README for what lives where.
import { t, locale } from './i18n.js';
import { DIR_TEXT, PH_PATHS } from './constants.js';
import { S } from './state.js';
import { renderProfile } from './ui-profile.js';
import { fam } from './rides.js';
import { myFamilyId } from './coordinator.js';
import { isOverride, normalizeLocations, placeFor, shiftLabel } from './locations.js';

// ============================================================

// ---------- Phosphor-style icon helper ----------
// Inline SVGs (256 viewBox, 16px stroke for outline, solid path for fill) instead of emoji.
// All use currentColor, so every icon automatically follows the surrounding text color —
// including dark mode and the accent-red active nav state — with zero extra CSS.
export function phIcon(name, opts){
  opts = opts||{};
  const size = opts.size || '1em';
  const style = `width:${size};height:${size};vertical-align:-0.15em;flex-shrink:0${opts.style?';'+opts.style:''}`;
  const body = PH_PATHS[name];
  if(!body) return '';
  return `<svg viewBox="0 0 256 256" style="${style}" aria-hidden="true">${body}</svg>`;
}

// The places (pickup / drop-off, destination) as set in Beheer, with defaults filled in.
export function locationsCfg(){ return normalizeLocations(S.locationsDoc); }

// US-15: "07:05 Busstation → AFC '34" for one ride (plain text, no button).
export function isAndroidDevice(){ return /Android/i.test((typeof navigator!=='undefined' && navigator.userAgent) || ''); }

export function shiftLocationHtml(car, direction){
  const cfg = locationsCfg();
  const changed = isOverride(car, direction, cfg)? ` <span class="changedTag">${t('loc.changedTag')}</span>` : '';
  return `<div class="shiftLoc"><span class="shiftLocText">${esc(shiftLabel(car, direction, cfg))}${changed}</span></div>`;
}

export function dirLabelHtml(direction, extra){ return `<span class="dirLabel">${DIR_TEXT[direction]}</span>${extra||''}`; }

// Small bottom sheet with a list of choices (used to move a passenger in Rooster).
export function openSheet(title, subtitle, items){
  closeSheet();
  const ov=document.createElement('div'); ov.className='sheetOverlay'; ov.id='sheetOverlay';
  ov.innerHTML = `<div class="sheet" role="dialog" aria-modal="true" aria-labelledby="sheetTitle">
    <h3 id="sheetTitle">${title}</h3>${subtitle? `<p class="muted" style="margin:0">${subtitle}</p>`:''}
    ${items.map((it,i)=>`<button type="button" class="sheetItem" data-sheetidx="${i}"><span>${it.label}${it.sub? `<br><span class="sub">${it.sub}</span>`:''}</span>${phIcon('arrow-right')}</button>`).join('')}
    <button type="button" class="btn secondary" id="sheetCancel" style="width:100%;margin-top:12px">${t('common.annuleren')}</button>
  </div>`;
  document.body.appendChild(ov);
  ov.addEventListener('click', e=>{ if(e.target===ov) closeSheet(); });
  ov.querySelector('#sheetCancel').onclick=closeSheet;
  ov.querySelectorAll('[data-sheetidx]').forEach(b=>b.onclick=()=>{ const it=items[+b.dataset.sheetidx]; closeSheet(); it.onClick(); });
  const first=ov.querySelector('.sheetItem')||ov.querySelector('#sheetCancel'); if(first) first.focus();
}

export function closeSheet(){ const ov=document.getElementById('sheetOverlay'); if(ov) ov.remove(); }

// Real vibration feedback via the Web Vibration API — Android Chrome supports this; iOS
// Safari has no equivalent API at all, so this silently does nothing there (not faked).
export function hapticTap(){ try{ if(navigator.vibrate) navigator.vibrate(10); }catch(e){} }

export function esc(s){ return String(s==null?'':s).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }

export function lastUpdateFooter(info){
  if(!info || !info.at) return '';
  const d = new Date(info.at);
  const dateStr = d.toLocaleString(locale(), {day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});
  return `<p class="muted" style="margin-top:10px;font-size:11px">${t('common.laatst_bijgewerkt_door')} ${esc(info.by||t('common.onbekend'))} — ${dateStr}</p>`;
}

// ---------- Theme: Licht / Donker only. New users start on Licht; their choice is remembered. ----------
export function applyTheme(pref){
  document.documentElement.setAttribute('data-theme', pref==='dark'?'dark':'light');
  const btn=document.getElementById('themeToggle');
  // Icon only: shows what you switch TO (moon in light mode, sun in dark mode).
  if(btn){
    btn.innerHTML = pref==='dark' ? phIcon('sun') : phIcon('moon');
    const lbl = pref==='dark' ? t('common.licht_thema_aanzetten') : t('common.donker_thema_aanzetten');
    btn.setAttribute('aria-label', lbl); btn.title = lbl;
  }
}

export function cycleTheme(){
  const cur = (()=>{ try{ return localStorage.getItem('theme-pref')||'light'; }catch(e){ return 'light'; } })();
  const next = cur==='light' ? 'dark' : 'light';
  try{ localStorage.setItem('theme-pref',next); }catch(e){}
  applyTheme(next);
}

export function isStandaloneDisplay(){
  try{ return (window.matchMedia && window.matchMedia('(display-mode: standalone)').matches) || window.navigator.standalone===true; }
  catch(e){ return false; }
}

export function isIOSDevice(){ return /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream; }

export function installCardHtml(){
  if(S.appIsInstalled || isStandaloneDisplay()) return '';
  if(S.deferredInstallPrompt){
    return `<div class="card"><h2>${t('common.installeer_de_app')}</h2><p class="muted">${t('common.zet_az_carpool_op_je')}</p><button type="button" class="btn" id="installAppBtn">${t('common.installeer_app')}</button></div>`;
  }
  if(isIOSDevice()){
    return `<div class="card"><h2>${t('common.installeer_de_app')}</h2><p class="muted">${t('common.zet_az_carpool_op_je_2')} <strong>${t('common.zet_op_beginscherm')}</strong>.</p></div>`;
  }
  return '';
}

export function wireInstallCard(){
  const btn=document.getElementById('installAppBtn');
  if(btn) btn.onclick=async ()=>{
    if(!S.deferredInstallPrompt) return;
    S.deferredInstallPrompt.prompt();
    try{ await S.deferredInstallPrompt.userChoice; }catch(e){}
    S.deferredInstallPrompt=null;
    renderProfile();
  };
}

// `warn` puts the SVG warning icon in front (instead of an emoji).
export function setStatus(msg, warn){ const el=document.getElementById('whoami'); if(el) el.innerHTML=(warn? phIcon('warning')+' ':'')+esc(msg); adjustMainPadding(); }

// No-op now: header/nav are normal flex children (not position:fixed) in the new flex-shell
// layout, so `main` never needs JS-computed compensating padding — normal flex flow already
// places it correctly between them. Left in place (rather than removed) since it's still called
// from many render functions; safe to no-op there instead of hunting down every call site.
export function adjustMainPadding(){}

// opts.icon: name of a phIcon shown before the text (e.g. 'warning'), instead of an emoji.
export function showToast(msg, opts){
  let t=document.getElementById('toast');
  if(!t){ t=document.createElement('div'); t.id='toast'; t.setAttribute('role','status'); t.setAttribute('aria-live','polite');
    t.style.cssText='position:fixed;left:50%;bottom:calc(18px + var(--sab));transform:translateX(-50%);background:var(--text);color:var(--card);padding:10px 16px;border-radius:20px;font-size:13px;max-width:90%;text-align:center;z-index:50;box-shadow:0 4px 14px rgba(0,0,0,.2)';
    document.body.appendChild(t);
  }
  t.innerHTML=(opts&&opts.icon? phIcon(opts.icon)+' ' : '')+esc(msg); t.style.display='block';
  clearTimeout(t._h); t._h=setTimeout(()=>{t.style.display='none';},4000);
}

export function twoStepConfirm(btn, confirmLabel, action){
  if(btn.dataset.confirming==='1'){
    clearTimeout(btn._resetTimer);
    btn.dataset.confirming=''; btn.textContent=btn.dataset.origLabel;
    action();
  } else {
    btn.dataset.origLabel = btn.textContent;
    btn.dataset.confirming='1';
    btn.textContent = confirmLabel;
    btn._resetTimer = setTimeout(()=>{ btn.dataset.confirming=''; btn.textContent=btn.dataset.origLabel; }, 4000);
  }
}

// ---------- Mijn gezin tab ----------
// ---------- Firebase connection failed (bad config, offline, etc.) ----------
export function showConnectionError(err){
  const nav=document.querySelector('nav');
  if(nav) nav.style.display='none';
  ['schedule','myweek','deviation','profile','beheer'].forEach(t=>{ const el=document.getElementById('tab-'+t); if(el) el.style.display='none'; });
  const gateDiv=document.getElementById('tab-gate');
  if(gateDiv){
    gateDiv.style.display='block';
    gateDiv.innerHTML = `<div style="max-width:420px;margin:30px auto 0">
      <div class="card">
        <h2>${t('common.geen_verbinding')}</h2>
        <p class="muted">${t('common.kan_geen_verbinding_maken_met')}</p>
        <p class="muted" style="margin-top:8px">${t('common.foutmelding')} ${err&&err.message? err.message : String(err)}</p>
      </div>
    </div>`;
  }
  adjustMainPadding();
}

// Single source of truth for the header line, so it can never go stale relative to the real
// permission state — always recomputed together with canEdit, from wherever that changes.
export function updateStatusLine(){
  const linked = !!(S.links[S.me] && S.links[S.me].familyId) || !!S.impersonateFamilyId;
  let text;
  if(linked){
    const f = fam(myFamilyId());
    text = (f.parentName||t('common.ouder')) + (S.canEdit? t('common.coordinator') : '');
  } else if(S.canEdit){
    text = t('coordinator.coordinator');
  } else if(S.me){
    text = t('common.nog_niet_gekoppeld_ga_naar');
  } else {
    text = '';
  }
  setStatus(text);
}

// Fills the fixed texts of index.html (menu, header) from the translation file. The Dutch text that is
// already in the HTML stays as a fallback in case this never runs.
export function applyStaticTexts(){
  document.querySelectorAll('[data-i18n]').forEach(el=>{ el.textContent = t(el.getAttribute('data-i18n')); });
  document.querySelectorAll('[data-i18n-aria-label]').forEach(el=>{ el.setAttribute('aria-label', t(el.getAttribute('data-i18n-aria-label'))); });
}
