// ui-common.js — generated by the modularisation of index.html; see README for what lives where.
import { t, locale } from './i18n.js';
import { DIR_TEXT, PH_PATHS } from './constants.js';
import { S } from './state.js';
import { renderProfile } from './ui-profile.js';
import { fam } from './rides.js';
import { myFamilyId } from './coordinator.js';
import { isOverride, normalizeLocations, placeFor, shiftLabel } from './locations.js';

// ============================================================

// ---------- Phosphor-style icon helper ----------
// Inline SVGs (256 viewBox, 16px stroke for outline, solid path for fill) instead of emoji.
// All use currentColor, so every icon automatically follows the surrounding text color —
// including dark mode and the accent-red active nav state — with zero extra CSS.
export function phIcon(name, opts){
  opts = opts||{};
  const size = opts.size || '1em';
  const style = `width:${size};height:${size};vertical-align:-0.15em;flex-shrink:0${opts.style?';'+opts.style:''}`;
  const body = PH_PATHS[name];
  if(!body) return '';
  return `<svg viewBox="0 0 256 256" fill="currentColor" style="${style}" aria-hidden="true">${body}</svg>`;
}

// Collapsible section (native <details>), collapsed by default. The open state is kept in S.folds so it survives a redraw.
// `key` must be unique on the page; `cls` styles the wrapper (e.g. "card" or "group").
export function foldHtml(key, titleHtml, bodyHtml, cls, id){
  const open = S.folds && S.folds[key];
  return `<details class="fold ${cls||''}"${id?` id="${id}"`:''} data-fold="${esc(key)}"${open?' open':''}><summary>${titleHtml}</summary><div class="foldBody">${bodyHtml}</div></details>`;
}

// Turns every top-level .card in `box` that starts with an <h2> into a collapsible section (used by Beheer).
export function foldCards(box){
  if(!box) return;
  // Cards may sit directly in `box` or inside a .begSec section (Beheer groups its cards).
  const cards = [];
  [...box.children].forEach(c=>{
    if(c.classList && c.classList.contains('begSec')) cards.push(...c.children); else cards.push(c);
  });
  cards.forEach(card=>{
    if(!card.classList || !card.classList.contains('card')) return;
    const h2 = card.querySelector(':scope > h2'); if(!h2) return;
    const key = 'card|'+(card.id||h2.textContent.trim());
    const det = document.createElement('details');
    det.className = 'fold card'+(card.classList.contains('timeChangeCard')?' timeChangeCard':'');
    det.dataset.fold = key; if(S.folds[key]) det.open = true;
    if(card.id) det.id = card.id;
    const icon = card.dataset && card.dataset.icon ? phIcon(card.dataset.icon) : '';
    const sum = document.createElement('summary');
    sum.innerHTML = icon ? `<span class="foldTitle"><span class="foldIcon">${icon}</span>${h2.innerHTML}</span>` : h2.innerHTML;
    const body = document.createElement('div'); body.className = 'foldBody';
    h2.remove();
    while(card.firstChild) body.appendChild(card.firstChild);
    det.append(sum, body);
    card.replaceWith(det);
  });
}

if(typeof document!=='undefined' && document.addEventListener){
  // 'toggle' does not bubble, so listen in the capture phase.
  document.addEventListener('toggle', e=>{
    const el = e.target;
    if(el && el.dataset && el.dataset.fold) S.folds[el.dataset.fold] = !!el.open;
  }, true);
}

// The places (pickup / drop-off, destination) as set in Beheer, with defaults filled in.
export function locationsCfg(){ return normalizeLocations(S.locationsDoc); }

// US-15: "07:05 Busstation → AFC '34" for one ride (plain text, no button).
export function isAndroidDevice(){ return /Android/i.test((typeof navigator!=='undefined' && navigator.userAgent) || ''); }

// opts.day: the weekday of the ride (the standard place can differ per shift).
// opts.edit + opts.gid: the coordinator's standaardrooster: the place is a button that opens the list of places for that one car (group gid).
export function shiftLocationHtml(car, direction, opts){
  const o = opts || {};
  const cfg = locationsCfg();
  const changed = isOverride(car, direction, cfg, o.day)? ` <span class="changedTag">${t('loc.changedTag')}</span>` : '';
  const label = esc(shiftLabel(car, direction, cfg, o.day));
  if(o.edit && o.gid) return `<div class="shiftLoc"><button type="button" class="shiftLocBtn" data-shiftloc="${esc(o.gid)}" aria-haspopup="dialog" aria-label="${esc(t('loc.shiftChange'))}"><span class="shiftLocText">${label}</span>${phIcon('pencil')}</button></div>`;
  return `<div class="shiftLoc"><span class="shiftLocText">${label}${changed}</span></div>`;
}

export function dirLabelHtml(direction, extra){ return `<span class="dirLabel">${DIR_TEXT[direction]}</span>${extra||''}`; }

// Small bottom sheet with a list of choices (used to move a passenger in Rooster).
export function openSheet(title, subtitle, items){
  closeSheet();
  const ov=document.createElement('div'); ov.className='sheetOverlay'; ov.id='sheetOverlay';
  // Design v2: a handle, a title, one row per choice with its own icon (no arrow, no Annuleren: tap outside or press Escape). `muted` rows (e.g. a full car) stay tappable but dim.
  ov.innerHTML = `<div class="sheet" role="dialog" aria-modal="true" aria-labelledby="sheetTitle">
    <div class="sheet__handle"></div>
    <h3 id="sheetTitle">${title}</h3>${subtitle? `<p class="sheet__sub">${subtitle}</p>`:''}
    ${items.map((it,i)=>`<button type="button" class="sheetItem${it.muted? ' sheetItem--muted' : ''}" data-sheetidx="${i}">${it.icon? phIcon(it.icon) : ''}<span class="sheetItem__label">${it.label}</span>${it.sub? `<span class="sub">${it.sub}</span>`:''}</button>`).join('')}
  </div>`;
  document.body.appendChild(ov);
  ov.addEventListener('click', e=>{ if(e.target===ov) closeSheet(); });
  ov.querySelectorAll('[data-sheetidx]').forEach(b=>b.onclick=()=>{ const it=items[+b.dataset.sheetidx]; closeSheet(); it.onClick(); });
  const first=ov.querySelector('.sheetItem'); if(first) first.focus();
}

export function closeSheet(){ const ov=document.getElementById('sheetOverlay'); if(ov) ov.remove(); }
// Escape closes the open sheet or the Help panel (laptops have no back gesture).
export function closeOnEscape(e){
  if(!e || e.key !== 'Escape') return false;
  const ov = document.getElementById('sheetOverlay') || document.getElementById('helpOverlay');
  if(!ov) return false;
  ov.remove(); return true;
}
if(typeof document!=='undefined' && document.addEventListener) document.addEventListener('keydown', closeOnEscape);

// Real vibration feedback via the Web Vibration API — Android Chrome supports this; iOS
// Safari has no equivalent API at all, so this silently does nothing there (not faked).
export function hapticTap(){ try{ if(navigator.vibrate) navigator.vibrate(10); }catch(e){} }

export function esc(s){ return String(s==null?'':s).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }

export function lastUpdateFooter(info){
  if(!info || !info.at) return '';
  const d = new Date(info.at);
  const dateStr = d.toLocaleString(locale(), {day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});
  return `<p class="muted" style="margin-top:10px;font-size:12px">${t('common.laatst_bijgewerkt_door')} ${esc(info.by||t('common.onbekend'))} — ${dateStr}</p>`;
}

// ---------- Theme: Licht / Donker only. New users start on Licht; their choice is remembered. ----------
export function currentTheme(){
  try{ return localStorage.getItem('theme-pref')==='dark' ? 'dark' : 'light'; }catch(e){ return 'light'; }
}

// Sets the theme on the page and marks the matching button in the Instellingen sheet (when it is open).
export function applyTheme(pref){
  const dark = pref==='dark';
  document.documentElement.setAttribute('data-theme', dark?'dark':'light');
  [['themeLight', !dark], ['themeDark', dark]].forEach(([id, on])=>{
    const b=document.getElementById(id);
    if(b){ if(on) b.classList.add('active'); else b.classList.remove('active'); b.setAttribute('aria-pressed', on?'true':'false'); }
  });
}

// A choice in the Instellingen sheet: applies it and remembers it.
export function setTheme(pref){
  const next = pref==='dark' ? 'dark' : 'light';
  try{ localStorage.setItem('theme-pref',next); }catch(e){}
  applyTheme(next);
}

export function isStandaloneDisplay(){
  try{ return (window.matchMedia && window.matchMedia('(display-mode: standalone)').matches) || window.navigator.standalone===true; }
  catch(e){ return false; }
}

export function isIOSDevice(){ return /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream; }

export function installCardHtml(){
  if(S.appIsInstalled || isStandaloneDisplay()) return '';
  if(S.deferredInstallPrompt){
    return `<div class="card"><h2>${t('common.installeer_de_app')}</h2><p class="muted">${t('common.zet_az_carpool_op_je')}</p><button type="button" class="btn" id="installAppBtn">${t('common.installeer_app')}</button></div>`;
  }
  if(isIOSDevice()){
    return `<div class="card"><h2>${t('common.installeer_de_app')}</h2><p class="muted">${t('common.zet_az_carpool_op_je_2')} <strong>${t('common.zet_op_beginscherm')}</strong>.</p></div>`;
  }
  return '';
}

export function wireInstallCard(){
  const btn=document.getElementById('installAppBtn');
  if(btn) btn.onclick=async ()=>{
    if(!S.deferredInstallPrompt) return;
    S.deferredInstallPrompt.prompt();
    try{ await S.deferredInstallPrompt.userChoice; }catch(e){}
    S.deferredInstallPrompt=null;
    renderProfile();
  };
}

// `warn` puts the SVG warning icon in front (instead of an emoji).
export function setStatus(msg, warn){
  const el=document.getElementById('whoami'); if(el) el.innerHTML=(warn? phIcon('warning')+' ':'')+esc(msg);
  // The name itself sits behind the avatar; only problems (no connection) get a visible line under the header.
  const line=document.getElementById('statusLine'); if(line){ line.hidden=!warn; line.innerHTML=warn? (el?el.innerHTML:''):''; }
  adjustMainPadding();
}

// No-op now: header/nav are normal flex children (not position:fixed) in the new flex-shell
// layout, so `main` never needs JS-computed compensating padding — normal flex flow already
// places it correctly between them. Left in place (rather than removed) since it's still called
// from many render functions; safe to no-op there instead of hunting down every call site.
export function adjustMainPadding(){}

// opts.icon: name of a phIcon shown before the text (e.g. 'warning'), instead of an emoji.
export function showToast(msg, opts){
  let t=document.getElementById('toast');
  if(!t){ t=document.createElement('div'); t.id='toast'; t.className='toast'; t.setAttribute('role','status'); t.setAttribute('aria-live','polite');
    document.body.appendChild(t);
  }
  // opts.action = { label, run }: an extra button in the toast (e.g. "Ongedaan maken"). Such a toast stays a little longer.
  const act = opts && opts.action;
  t.innerHTML=(opts&&opts.icon? phIcon(opts.icon)+' ' : '')+esc(msg)+(act? ` <button type="button" id="toastAction" class="toast__action">${esc(act.label)}</button>` : '');
  t.style.display='flex';
  t.onclick = act? (e)=>{ if(e && e.target && e.target.id==='toastAction'){ t.style.display='none'; clearTimeout(t._h); return act.run(); } } : null;
  clearTimeout(t._h); t._h=setTimeout(()=>{t.style.display='none';}, 3800);   // design v2: 3.8 s, also with an action
}

export function twoStepConfirm(btn, confirmLabel, action){
  if(btn.dataset.confirming==='1'){
    clearTimeout(btn._resetTimer);
    btn.dataset.confirming=''; if(btn.classList) btn.classList.remove('confirming'); btn.innerHTML=btn.dataset.origLabel;
    action();
  } else {
    btn.dataset.origLabel = btn.innerHTML;
    btn.dataset.confirming='1';
    if(btn.classList) btn.classList.add('confirming');   // red: the second tap is the destructive one (design v2)
    btn.textContent = confirmLabel;
    btn._resetTimer = setTimeout(()=>{ btn.dataset.confirming=''; if(btn.classList) btn.classList.remove('confirming'); btn.innerHTML=btn.dataset.origLabel; }, 4000);
  }
}

// ---------- Mijn gezin tab ----------
// ---------- Firebase connection failed (bad config, offline, etc.) ----------
export function showConnectionError(err){
  const nav=document.querySelector('nav');
  if(nav) nav.style.display='none';
  ['schedule','myweek','deviation','profile','beheer'].forEach(t=>{ const el=document.getElementById('tab-'+t); if(el) el.style.display='none'; });
  const gateDiv=document.getElementById('tab-gate');
  if(gateDiv){
    gateDiv.style.display='block';
    gateDiv.innerHTML = `<div style="max-width:420px;margin:30px auto 0">
      <div class="card">
        <h2>${t('common.geen_verbinding')}</h2>
        <p class="muted">${t('common.kan_geen_verbinding_maken_met')}</p>
        <p class="muted" style="margin-top:8px">${t('common.foutmelding')} ${err&&err.message? err.message : String(err)}</p>
      </div>
    </div>`;
  }
  adjustMainPadding();
}

// Single source of truth for the header line, so it can never go stale relative to the real
// permission state — always recomputed together with canEdit, from wherever that changes.
export function updateStatusLine(){
  const linked = !!(S.links[S.me] && S.links[S.me].familyId) || !!S.impersonateFamilyId;
  let text;
  if(linked){
    const f = fam(myFamilyId());
    text = (f.parentName||t('common.ouder')) + (S.canEdit? t('common.coordinator') : '');
  } else if(S.canEdit){
    text = t('coordinator.coordinator');
  } else if(S.me){
    text = t('common.nog_niet_gekoppeld_ga_naar');
  } else {
    text = '';
  }
  setStatus(text);
}

// Fills the fixed texts of index.html (menu, header) from the translation file. The Dutch text that is
// already in the HTML stays as a fallback in case this never runs.
export function applyStaticTexts(){
  document.querySelectorAll('[data-i18n]').forEach(el=>{ el.textContent = t(el.getAttribute('data-i18n')); });
  document.querySelectorAll('[data-i18n-aria-label]').forEach(el=>{ el.setAttribute('aria-label', t(el.getAttribute('data-i18n-aria-label'))); });
}
