// ui-myweek.js — generated by the modularisation of index.html; see README for what lives where.
import { t, locale } from './i18n.js';
import { analyzeMatch, carpoolFor, currentMatchList, docToMatch, matchLabel, matchSlug, matchesThisWeek, myMatchRides } from './matches.js';
import { esc, hapticTap, isAndroidDevice, lastUpdateFooter, locationsCfg, phIcon, shiftLocationHtml, showToast } from './ui-common.js';
import { setReturnByPublicTransport } from './data.js';
import { distanceInfo, hasApiKey } from './distance.js';
import { mapLink } from './locations.js';
import { S } from './state.js';
import { myFamilyId } from './coordinator.js';
import { activeDeviation, effectiveCars, fam, girlName, groupsFor, ovGirlsFor, plainGirlName, seats } from './rides.js';
import { dayChanges } from './day-changes.js';
import { DAYS, DIR_TEXT, KM_COST_EUR, WHATSAPP_SVG, todayKey } from './constants.js';
import { dateForWeekday, dayUp, effectivePlanningDate, startOfWeek } from './dates.js';
import { renderDeviationTab, wireWhatsAppButton } from './ui-deviation.js';
import { matchCarRowHtml, renderMatchesTab } from './ui-matches.js';
import { buildMyWeekWhatsAppMessage } from './message-texts.js';
import { activateTab } from './app.js';
import { dayCoordinatorHtml } from './ui-schedule.js';
import { isFlex, driverNameHtml } from './rides.js';

// US-21: distance (from Busstation Aalsmeer) and carpool cost under a match, home or away.
export function matchDistanceHtml(m){
  const a = analyzeMatch(m.summary);
  const info = distanceInfo({ isHome:a.isHome, location:m.location, stored:S.matchDistances[matchSlug(m)], fixedKm:locationsCfg().fixedKm });
  if(!info) return '';
  if(info.kind==='pending' && !hasApiKey(S.orsApiKey)) return '';   // feature not switched on: say nothing rather than "calculating…"
  // Cost = km x KM_COST_EUR (one way, as the km). A calculated distance is an estimate ("±"); a fixed distance (AFC, ATC) is not.
  const eur = km => (Math.round(km*KM_COST_EUR*100)/100).toFixed(2).replace('.',',');
  const text = info.kind==='km'? t('dist.km', { km: String(info.km).replace('.',',') }) + ' · ' + t('dist.cost', { eur: eur(info.km) })
    : info.kind==='fixed'? t('dist.kmFixed', { km: String(info.km).replace('.',',') }) + ' · ' + t('dist.costFixed', { eur: eur(info.km) })
    : info.kind==='fixedMissing'? t('dist.fixedMissing', { venue: info.venue })
    : info.kind==='pending'? t('dist.pending') : t('dist.unknown');
  return `<div class="matchDist">${esc(text)}</div>`;
}

// US-22: the location as a link that plans a route. Android: generic geo link (phone's own maps app);
// iPhone and laptop: Google Maps. Both start from the current position, not from Busstation Aalsmeer.
export function locationLinkHtml(location){
  const href = mapLink(location, isAndroidDevice());
  if(!href) return esc(location||'');
  return `<a class="geoLink" href="${esc(href)}" aria-label="${esc(t('geo.route', { place: location }))}">${esc(location)}</a>`;
}

// opts.geo: make the location a route link (Mijn week only).
export function matchInfoHtml(m, opts){
  const a = analyzeMatch(m.summary);
  const dayLabel = m.start.toLocaleDateString(locale(),{weekday:'long', day:'numeric', month:'long'});
  const timeLabel = m.start.toLocaleTimeString(locale(),{hour:'2-digit',minute:'2-digit'});
  const homeAway = a.isHome===true? t('myweek.thuis') : a.isHome===false? t('myweek.uit') : '';
  return `<div style="padding:4px 0">
    <div class="matchTitle"><span class="matchBall">${phIcon('soccer',{size:'16px'})}</span><span>${esc(matchLabel(m))}${homeAway} ${t('myweek.vs')} ${esc(a.opponent)}</span></div>
    <div class="muted" style="font-size:12px">${dayLabel} · ${timeLabel}${m.location? ' · '+(opts&&opts.geo? locationLinkHtml(m.location) : esc(m.location)):''}</div>
    ${matchDistanceHtml(m)}
  </div>`;
}

// "Rijdt mee met: <driver>". A car without a (known) driver is a problem to solve, so it becomes an amber warning chip.
export function rideWithHtml(driverFamilyId){
  const known = !!(driverFamilyId && S.families[driverFamilyId] && S.families[driverFamilyId].parentName);
  if(known) return t('myweek.rijdt_mee_met', { p1: phIcon('user'), p2: driverNameHtml(driverFamilyId) });
  return `<span class="statusChip warn">${t('myweek.rijdt_mee_met', { p1: phIcon('warning'), p2: esc(t('driver.none')) })}</span>`;
}

// ---------- Mijn week: a compact, scroll-free view of just what a parent needs ----------
export function renderMyWeek(){
  const box=document.getElementById('tab-myweek');
  if(!box) return;
  if(!S.me){ box.innerHTML=`<div class="card"><h2>${t('myweek.mijn_week')}</h2><p class="muted">${t('deviation.kon_je_account_niet_herkennen')}</p></div>`; return; }
  const linked = !!(S.links[S.me] && S.links[S.me].familyId);
  if(!linked){ box.innerHTML=`<div class="card"><h2>${t('myweek.mijn_week')}</h2><p class="muted">${t('myweek.koppel_eerst_je_dochter_via')}</p></div>`; return; }
  const myId = myFamilyId();
  const myFam = fam(myId);

  function subride(day,direction,label){
    let s = myFam.schedule && myFam.schedule[day] && myFam.schedule[day][direction];
    const cars = effectiveCars(day,direction);
    const isOvMe = direction==='terug' && ovGirlsFor(day).includes(myId);   // US-06: home by public transport
    // Flex: no standard schedule; a ride shows only on days she signed up for (in a car, or driving).
    if(isFlex(myFam)){
      s = '';
      if(!isOvMe && !cars.some(c=>(c.girlIds||[]).includes(myId) || c.driverFamilyId===myId)) return '';
    } else if(!s) return '';
    const daughterIdx = cars.findIndex(c=>c.girlIds.includes(myId));
    const drivingIdx = cars.findIndex(c=>c.driverFamilyId===myId);
    let dep = s, statusHtml, statusClass='';
    if(daughterIdx>=0){
      const g=cars[daughterIdx];
      dep = g.departureTime||s;
      const isMe = g.driverFamilyId===myId;
      if(isMe){
        // Full passenger list, including your own daughter — not just "everyone else".
        const passengers=g.girlIds.map(id=>girlName(id)).join(', ');
        statusHtml = t('myweek.jij_rijdt', { p1: phIcon('user'), p2: phIcon('car'), p3: passengers? ` · ${passengers}`:'' }); statusClass='driving';
      } else {
        statusHtml = rideWithHtml(g.driverFamilyId);
      }
    } else if(isOvMe){
      statusHtml = t('ov.status', { p1: phIcon('check-circle') });
    } else {
      statusHtml = t('myweek.niet_ingepland_2', { p1: phIcon('warning') }); statusClass='unplanned';
    }
    // Own driving duty in a DIFFERENT car than the daughter's own ride — shown as a second line.
    let extraDriving='';
    if(drivingIdx>=0 && drivingIdx!==daughterIdx){
      const dg=cars[drivingIdx];
      const names=dg.girlIds.map(id=>girlName(id)).join(', ');
      extraDriving = `<div class="subrideStatus driving">${phIcon('car')} ${t('myweek.jouw_rijbeurt_om')} ${dg.departureTime||'?'} · ${names}</div>${shiftLocationHtml(dg,direction,{day})}`;
      statusClass = statusClass? statusClass : ''; // the driving BORDER below reflects the daughter's own car only, not this second one
    }
    // Only a ride that really differs from the standard rooster gets the tag (a saved deviation that changes nothing does not).
    const differsFromStandard = !!activeDeviation(day,direction) && dayChanges(groupsFor(day,direction).map(([,g])=>g), cars).length>0;
    const devTag = differsFromStandard? `<div class="subrideStatus changed">${phIcon('lightning')} ${t('myweek.wijziging_actief')}</div>` : '';
    // US-15: where the ride starts and ends. US-06: parent toggle "Terug met OV" (no reason needed), not for days already past.
    const ownCar = daughterIdx>=0? cars[daughterIdx] : null;
    const locHtml = ownCar? shiftLocationHtml(ownCar,direction,{day}) : '';
    const dayPassed = dateForWeekday(day) < new Date(new Date().setHours(0,0,0,0));
    const ovBtn = direction==='terug' && !dayPassed && !isFlex(myFam)
      ? `<button type="button" class="btn small secondary ovBtn" data-ovtoggle="${day}" data-ovon="${isOvMe?0:1}" aria-pressed="${isOvMe}">${t(isOvMe?'ov.undo':'ov.button')}</button>` : '';
    return `<div class="subride ${drivingIdx>=0?'driving':''} ${statusClass==='unplanned'?'unplanned':''}">
      <div class="subrideHead"><span>${label}</span><span class="subrideDep">${isOvMe? '–' : dep}</span></div>
      <div class="subrideStatus ${statusClass}">${statusHtml}</div>
      ${locHtml}${extraDriving}${devTag}${ovBtn}
    </div>`;
  }

  // Wedstrijdcarpool rides (spontaneous, per match) — violet + football so they never get
  // mistaken for the regular weekday carpool. Grouped per calendar date.
  const matchRidesByDate = {}, matchDateByKey = {};
  myMatchRides(myId).forEach(r=>{
    const d=new Date(r.doc.startMs); d.setHours(0,0,0,0); const k=d.toDateString();
    matchDateByKey[k]=d; (matchRidesByDate[k]=matchRidesByDate[k]||[]).push(r);
  });
  function matchRideHtml(r){
    const a = analyzeMatch(r.doc.summary||'');
    const kickoff = new Date(r.doc.startMs).toLocaleTimeString(locale(),{hour:'2-digit',minute:'2-digit'});
    const homeAway = a.isHome===true? t('myweek.thuis') : a.isHome===false? t('myweek.uit') : '';
    const passengers = (r.car.girlIds||[]).map(id=>girlName(id)).join(', ');
    const status = r.driving
      ? t('myweek.jij_rijdt', { p1: r.daughter? phIcon('user'):'', p2: phIcon('car'), p3: passengers? ` · ${passengers}`:'' })
      : rideWithHtml(r.car.driverFamilyId);
    return `<div class="subride matchRide">
      <div class="subrideHead"><span style="display:inline-flex;align-items:center;gap:5px">${phIcon('soccer')} ${t('myweek.wedstrijd')} ${esc(matchLabel(r.doc))}${homeAway} ${t('myweek.vs')} ${esc(a.opponent)}</span><span class="subrideDep">${esc(r.car.departureTime||'--:--')}</span></div>
      <div class="subrideStatus ${r.driving?'driving':''}">${status}</div>
      <div class="subrideStatus" style="font-size:12px">${t('myweek.aftrap')} ${kickoff}${r.doc.location? ' · '+locationLinkHtml(r.doc.location):''}</div>
      ${matchDistanceHtml(docToMatch(r.doc))}
    </div>`;
  }
  function matchRidesFor(date){ return (matchRidesByDate[date.toDateString()]||[]).map(matchRideHtml).join(''); }
  const matchTagHtml = `<span class="matchTag">${phIcon('soccer')} ${t('myweek.wedstrijd_2')}</span>`;
  const todayStr = new Date().toDateString();

  const weekdayDates = new Set(DAYS.map(([k])=>dateForWeekday(k).toDateString()));
  const dayCards = DAYS.map(([k,label])=>{
    const isToday = k===todayKey;
    const heenHtml = subride(k,'heen',DIR_TEXT.heen);
    const terugHtml = subride(k,'terug',DIR_TEXT.terug);
    const matchHtml = matchRidesFor(dateForWeekday(k));
    if(!heenHtml && !terugHtml && !matchHtml) return '';
    const heenTime = (myFam.schedule&&myFam.schedule[k]&&myFam.schedule[k].heen) || '';
    const terugTime = (myFam.schedule&&myFam.schedule[k]&&myFam.schedule[k].terug) || '';
    const dateLabel = dateForWeekday(k).toLocaleDateString(locale(),{day:'numeric',month:'short'});
    const onlyMatch = !heenHtml && !terugHtml;
    return `<div class="dayCard ${isToday?'today':''} ${matchHtml?'matchDay':''} ${onlyMatch?'matchOnly':''}">
      <div class="dayCardHead">
        <span class="dayBadge">${dayUp(k)}</span>
        <span class="dayCardTitle">${dateLabel}</span>
        ${isToday? t('myweek.span_class_todaytag_vandaag_span') : ''}
        ${matchHtml? matchTagHtml : ''}
        ${(onlyMatch||isFlex(myFam))? '' : `<span class="dayTimes">${heenTime||'–'} / ${terugTime||'–'}</span>`}
      </div>
      ${heenHtml}${terugHtml}${matchHtml}
    </div>`;
  });
  // Match rides on days outside Ma–Vr of the planning week (the weekend) get their own card.
  const extraCard = (key)=>{
    const d = matchDateByKey[key];
    const badge = d.toLocaleDateString(locale(),{weekday:'short'}).replace('.','');
    const dateLabel = d.toLocaleDateString(locale(),{day:'numeric',month:'short'});
    const isToday = key===todayStr;
    return `<div class="dayCard matchDay matchOnly ${isToday?'today':''}">
      <div class="dayCardHead">
        <span class="dayBadge">${esc(badge.slice(0,2).toUpperCase())}</span>
        <span class="dayCardTitle">${dateLabel}</span>
        ${isToday? t('myweek.span_class_todaytag_vandaag_span') : ''}
        ${matchTagHtml}
      </div>
      ${matchRidesFor(d)}
    </div>`;
  };
  const planningMonday = startOfWeek(effectivePlanningDate());
  const extraKeys = Object.keys(matchRidesByDate).filter(k=>!weekdayDates.has(k)).sort((a,b)=>matchDateByKey[a]-matchDateByKey[b]);
  const beforeCards = extraKeys.filter(k=>matchDateByKey[k]<planningMonday).map(extraCard).join('');
  const afterCards = extraKeys.filter(k=>matchDateByKey[k]>=planningMonday).map(extraCard).join('');
  const allDayCards = beforeCards + dayCards.join('') + afterCards;
  const dayCardsHtml = allDayCards || `<p class="muted">${t('myweek.geen_dagen_met_een_tijd')}</p>`;

  const weekMatches = matchesThisWeek(currentMatchList());
  const matchStatusNote = S.matchesSource==='live'
    ? ''
    : (S.cachedMatchesAt? `<p class="muted" style="font-size:12px;margin-top:6px">${t('beheer.laatst_opgehaald')} ${new Date(S.cachedMatchesAt).toLocaleString(locale())}</p>` : '');
  const matchFailNote = S.matchFetchFailedTeams.length? `<p class="fitbad" style="font-size:12px;margin-top:6px">${t('myweek.kon_niet_ophalen')} ${esc(S.matchFetchFailedTeams.map(f=>f.label+' ('+f.error+')').join('; '))}</p>` : '';
  const weekMatchesHtml = weekMatches.length? weekMatches.map(m=>{
    const d = carpoolFor(m).doc;
    const cars = (d && d.cars) || [];
    const carsHtml = cars.length
      ? cars.map(c=>matchCarRowHtml(c,{highlightId:myId})).join('')
      : t('deviation.p_class_muted_style_font');
    return `<div class="group matchGroup">${matchInfoHtml(m,{geo:true})}${carsHtml}</div>`;
  }).join('') : t('myweek.p_class_muted_geen_wedstrijden');
  const matchesCardHtml = `<div class="card">
    <div class="rowflex" style="align-items:center"><h2 style="margin:0">${t('myweek.wedstrijden_deze_week')}</h2>
      <button type="button" class="btn small secondary" data-gomatchcarpool="1">${phIcon('soccer')} ${t('myweek.carpool_regelen')}</button></div>
    <div style="margin-top:8px">${weekMatchesHtml}</div>
    ${matchFailNote}${matchStatusNote}
  </div>`;

  // Rides of the daughter that have no car yet — today first, then the rest of the week.
  const todayMidnight = new Date(); todayMidnight.setHours(0,0,0,0);
  const unplannedRows = [];
  DAYS.forEach(([k,label])=>{
    if(dateForWeekday(k) < todayMidnight) return; // days already past
    ['heen','terug'].forEach(direction=>{
      const s = myFam.schedule && myFam.schedule[k] && myFam.schedule[k][direction];
      if(!s || isFlex(myFam)) return; // Flex is never auto-planned, so nothing is 'missing'
      if(effectiveCars(k,direction).some(c=>(c.girlIds||[]).includes(myId))) return;
      if(direction==='terug' && ovGirlsFor(k).includes(myId)) return;   // goes home by public transport
      const when = k===todayKey? t('myweek.vandaag') : label;
      unplannedRows.push(`<div class="row"><span><strong>${when}</strong> · ${direction==='heen'?t('dir.heenShort'):t('dir.terugShort')} (${s}${t('myweek.niet_ingepland')}</span>
        <button type="button" class="btn small" data-gowijzig="${k}">${t('myweek.regelen')}</button></div>`);
    });
  });
  const unplannedHtml = unplannedRows.length? `<div class="unplacedAlert" role="alert">
      <div class="ttl">${phIcon('warning')} ${esc(myFam.girlName||t('myweek.je_dochter'))} ${t('myweek.heeft_nog_geen_rit')}</div>
      ${unplannedRows.join('')}
    </div>` : '';

  box.innerHTML = `
    <div class="heroCard compact">
      <div class="heroText">
        <span class="heroName">${esc(myFam.girlName||'')}</span>
        <span class="heroSub">${esc(myFam.parentName||'')} · ${seats(myFam)} ${t('myweek.plekken')}</span>
      </div>
      <button type="button" class="waIconBtn" id="wa-hero" aria-label="${t('myweek.deel_mijn_week_via_whatsapp')}" title="${t('myweek.deel_via_whatsapp')}">${WHATSAPP_SVG}</button>
    </div>
    ${dayCoordinatorHtml()}${unplannedHtml}
    <div class="legendLine"><span>${phIcon('user')} ${t('myweek.rit_dochter')}</span><span>${phIcon('car')} ${t('myweek.jouw_rijbeurt')}</span><span>${phIcon('lightning')} ${t('myweek.wijziging')}</span><span>${phIcon('soccer')} ${t('myweek.wedstrijdrit')}</span></div>
    ${dayCardsHtml}
    ${matchesCardHtml}
    ${lastUpdateFooter([S.lastUpdateRooster,S.lastUpdateDeviation].filter(Boolean).sort((a,b)=>(b.at||0)-(a.at||0))[0])}
  `;
  wireWhatsAppButton('wa-hero', buildMyWeekWhatsAppMessage);
  box.querySelectorAll('[data-gowijzig]').forEach(b=>b.onclick=()=>goToWijzigen(b.dataset.gowijzig));
  box.querySelectorAll('[data-ovtoggle]').forEach(b=>b.onclick=async ()=>{
    const on = b.dataset.ovon==='1';
    const day = b.dataset.ovtoggle;
    if(await setReturnByPublicTransport(day, myId, on)){
      // Toast with an Undo action: one tap puts it back the way it was.
      showToast(t(on? 'ov.on' : 'ov.off', { p1: plainGirlName(myId) }), { action: { label: t('ov.toastUndo'), run: async ()=>{
        if(await setReturnByPublicTransport(day, myId, !on)) showToast(t(on? 'ov.off' : 'ov.on', { p1: plainGirlName(myId) }));
      } } });
    }
  });
  box.querySelectorAll('[data-gomatchcarpool]').forEach(b=>b.onclick=()=>goToMatchCarpool());
}

// Jump to the Wijzigen tab, optionally straight into one day.
export function goToWijzigen(day){
  if(day) S.deviationDay = day; // no day given: keep the day that was open
  S.openMatchCarpoolForm = null;
  renderDeviationTab(); activateTab('deviation'); hapticTap();
}

// Jump to the Wedstrijden tab (where the match carpools are set up).
export function goToMatchCarpool(){
  S.openMatchCarpoolForm = null;
  renderMatchesTab(); activateTab('matches'); hapticTap();
}
