// ui-myweek.js — generated by the modularisation of index.html; see README for what lives where.
import { t, locale } from './i18n.js';
import { analyzeMatch, carpoolFor, currentMatchList, docToMatch, matchLabel, matchSlug, matchesThisWeek, myMatchRides } from './matches.js';
import { esc, hapticTap, isAndroidDevice, lastUpdateFooter, locationsCfg, phIcon, showToast } from './ui-common.js';
import { setReturnByPublicTransport } from './data.js';
import { distanceInfo, hasApiKey } from './distance.js';
import { mapLink, destinationFor, isOverride, routeLabel } from './locations.js';
import { S } from './state.js';
import { myFamilyId } from './coordinator.js';
import { activeDeviation, baseCars, effectiveCars, fam, girlName, ovGirlsFor, plainGirlName, rideTime, sortGirlIds } from './rides.js';
import { dayChanges } from './day-changes.js';
import { DAYS, KM_COST_EUR, todayKeyNow } from './constants.js';
import { dateForWeekday, dayUp, effectivePlanningDate, startOfWeek } from './dates.js';
import { renderDeviationTab } from './ui-deviation.js';
import { matchCarRowHtml, renderMatchesTab } from './ui-matches.js';
import { activateTab } from './app.js';
import { dayCoordinatorHtml } from './ui-schedule.js';
import { isFlex, driverNameHtml } from './rides.js';

// US-21: distance (from Busstation Aalsmeer) and carpool cost under a match, home or away.
export function matchDistanceText(m){
  const a = analyzeMatch(m.summary);
  const info = distanceInfo({ isHome:a.isHome, location:m.location, stored:S.matchDistances[matchSlug(m)], fixedKm:locationsCfg().fixedKm });
  if(!info) return '';
  if(info.kind==='pending' && !hasApiKey(S.orsApiKey)) return '';   // feature not switched on: say nothing rather than "calculating…"
  // Cost = km x KM_COST_EUR (one way, as the km). A calculated distance is an estimate ("±"); a fixed distance (AFC, ATC) is not.
  const eur = km => (Math.round(km*KM_COST_EUR*100)/100).toFixed(2).replace('.',',');
  return info.kind==='km'? t('dist.km', { km: String(info.km).replace('.',',') }) + ' · ' + t('dist.cost', { eur: eur(info.km) })
    : info.kind==='fixed'? t('dist.kmFixed', { km: String(info.km).replace('.',',') }) + ' · ' + t('dist.costFixed', { eur: eur(info.km) })
    : info.kind==='fixedMissing'? t('dist.fixedMissing', { venue: info.venue })
    : info.kind==='pending'? t('dist.pending') : t('dist.unknown');
}
export function matchDistanceHtml(m){
  const text = matchDistanceText(m);
  return text ? `<div class="matchDist">${esc(text)}</div>` : '';
}

// US-22: the location as a link that plans a route. Android: generic geo link (phone's own maps app);
// iPhone and laptop: Google Maps. Both start from the current position, not from Busstation Aalsmeer.
export function locationLinkHtml(location){
  const href = mapLink(location, isAndroidDevice());
  if(!href) return esc(location||'');
  return `<a class="geoLink" href="${esc(href)}" aria-label="${esc(t('geo.route', { place: location }))}">${esc(location)}</a>`;
}

// opts.geo: make the location a route link (Mijn week only).
export function matchInfoHtml(m, opts){
  const a = analyzeMatch(m.summary);
  const dayLabel = m.start.toLocaleDateString(locale(),{weekday:'long', day:'numeric', month:'long'});
  const timeLabel = m.start.toLocaleTimeString(locale(),{hour:'2-digit',minute:'2-digit'});
  const homeAway = a.isHome===true? t('myweek.thuis') : a.isHome===false? t('myweek.uit') : '';
  return `<div class="matchInfo">
    <div class="matchTitle"><span class="matchBall">${phIcon('soccer',{size:'16px'})}</span><span>${esc(matchLabel(m))}${homeAway} ${t('myweek.vs')} ${esc(a.opponent)}</span></div>
    <div class="noteLine matchWhen">${dayLabel} · ${timeLabel}${m.location? ' · '+(opts&&opts.geo? locationLinkHtml(m.location) : esc(m.location)):''}</div>
    ${matchDistanceHtml(m)}
  </div>`;
}

// ---------- Mijn week: today first, then the rest of the week (design system v2) ----------
// "Naam >" button that opens the contact sheet; a car without a known driver is an amber problem line instead.
function driverButtonHtml(driverFamilyId, tagsHtml){
  const known = !!(driverFamilyId && S.families[driverFamilyId] && S.families[driverFamilyId].parentName);
  if(!known) return `<div class="rideRow__none">${esc(t('driver.none'))}</div>`;
  return `<button type="button" class="rideRow__driver" data-contact="${esc(driverFamilyId)}">${driverNameHtml(driverFamilyId)}${phIcon('caret-right')}${tagsHtml||''}</button>`;
}

const dirName = direction => direction==='heen' ? t('dir.heenShort') : t('dir.terugShort');

export function renderMyWeek(){
  const box=document.getElementById('tab-myweek');
  if(!box) return;
  if(!S.me){ box.innerHTML=`<div class="card"><h2>${t('myweek.mijn_week')}</h2><p class="muted">${t('deviation.kon_je_account_niet_herkennen')}</p></div>`; return; }
  const linked = !!(S.links[S.me] && S.links[S.me].familyId);
  if(!linked){ box.innerHTML=`<div class="card"><h2>${t('myweek.mijn_week')}</h2><p class="muted">${t('myweek.koppel_eerst_je_dochter_via')}</p></div>`; return; }
  const myId = myFamilyId();
  const myFam = fam(myId);
  const cfg = locationsCfg();
  const initial = esc((plainGirlName(myId)||'?').trim().charAt(0).toUpperCase());

  // One ride row: departure time, route, who drives, her own time, and the "rides along" switch.
  function rideRow(day,direction){
    let s = rideTime(myId, day, direction);   // the handed-in time where the temporary rooster applies, else the standard time
    const cars = effectiveCars(day,direction);
    const isOvMe = ovGirlsFor(day,undefined,direction).includes(myId);   // US-06: marked "Rijdt niet mee" on this shift
    // Flex: no standard schedule; a ride shows only on days she signed up for (in a car, or driving).
    if(isFlex(myFam)){
      s = '';
      if(!isOvMe && !cars.some(c=>(c.girlIds||[]).includes(myId) || c.driverFamilyId===myId)) return '';
    } else if(!s) return '';
    const daughterIdx = cars.findIndex(c=>c.girlIds.includes(myId));
    const drivingIdx = cars.findIndex(c=>c.driverFamilyId===myId);
    const ownCar = daughterIdx>=0 ? cars[daughterIdx] : null;
    const dep = ownCar ? (ownCar.departureTime||s) : s;
    // Only a ride that really differs from the standard rooster gets the tag (a saved deviation that changes nothing does not).
    const differsFromStandard = !!activeDeviation(day,direction) && dayChanges(baseCars(day,direction), cars).length>0;
    const changedTag = (differsFromStandard || (ownCar && isOverride(ownCar,direction,cfg,day))) ? `<span class="tag tag--warn">${esc(t('myweek.gewijzigd'))}</span>` : '';
    const route = `${dirName(direction)} · ${routeLabel(ownCar||{},direction,cfg,day)}`;

    let status = '';
    if(ownCar){
      if(ownCar.driverFamilyId===myId){
        // Full passenger list, including your own daughter — not just "everyone else".
        const passengers = sortGirlIds(ownCar.girlIds).map(id=>girlName(id)).join(', ');
        status = `<div class="rideRow__drives"><span class="tag tag--ok">${phIcon('steering-wheel-fill')}${esc(t('myweek.jij_rijdt_tag'))}</span>${changedTag}</div>${passengers? `<div class="rideRow__pass">${passengers}</div>`:''}`;
      } else {
        status = driverButtonHtml(ownCar.driverFamilyId, changedTag);
      }
    } else if(isOvMe){
      status = `<div class="rideRow__off">${esc(t('myweek.rijdt_niet_mee', { name: plainGirlName(myId) }))}</div>`;
    } else {
      status = `<div class="rideRow__none">${esc(t('myweek.nog_geen_rit'))}</div>`;
    }
    if(!ownCar && changedTag) status += `<div class="rideRow__drives">${changedTag}</div>`;
    // Own driving duty in a DIFFERENT car than the daughter's own ride — shown as a second line.
    if(drivingIdx>=0 && drivingIdx!==daughterIdx){
      const dg = cars[drivingIdx];
      const names = sortGirlIds(dg.girlIds).map(id=>girlName(id)).join(', ');
      status += `<div class="rideRow__extra">${phIcon('steering-wheel-fill')} ${esc(t('myweek.jouw_rijbeurt_om'))} ${esc(dg.departureTime||'?')} · ${names}</div>`;
    }
    // Her own time: when she has to be there (heen) / when she is done (terug).
    const dest = destinationFor(ownCar||{}, cfg).name;
    const daughterLine = s ? `<div class="daughterTime"><span class="daughterTime__initial">${initial}</span><span>${direction==='heen' ? esc(t('myweek.daughter_heen', { place: dest })) : esc(t('myweek.daughter_terug'))} <b>${esc(s)}</b></span></div>` : '';
    // US-06: parent switch "Rijdt niet mee" (no reason needed), not for days already past, and not for Flex.
    const dayPassed = dateForWeekday(day) < new Date(new Date().setHours(0,0,0,0));
    const sw = !dayPassed && !isFlex(myFam)
      ? `<button type="button" class="switch${isOvMe?'':' on'}" role="switch" aria-checked="${!isOvMe}" aria-label="${esc(t('ov.switchLabel', { p1: dirName(direction), p2: DAYS.find(([k])=>k===day)[1] }))}" data-ovtoggle="${day}" data-ovdir="${direction}" data-ovon="${isOvMe?0:1}"><span class="switch__track"><span class="switch__knob">${phIcon(isOvMe?'x-bold':'car-profile-bold')}</span></span></button>` : '';
    return `<div class="rideRow${isOvMe?' rideRow--off':''}" data-rideday="${day}" data-ridedir="${direction}">
      <div class="rideRow__time"><div class="rideRow__dep">${isOvMe? '–' : esc(dep)}</div><div class="rideRow__sub">${esc(t('myweek.vertrek'))}</div></div>
      <div class="rideRow__main"><div class="rideRow__route">${esc(route)}</div>${status}${daughterLine}</div>
      ${sw}
    </div>`;
  }

  // Wedstrijdcarpool rides (spontaneous, per match) — violet + football so they never get
  // mistaken for the regular weekday carpool. Grouped per calendar date.
  const matchRidesByDate = {}, matchDateByKey = {};
  myMatchRides(myId).forEach(r=>{
    const d=new Date(r.doc.startMs); d.setHours(0,0,0,0); const k=d.toDateString();
    matchDateByKey[k]=d; (matchRidesByDate[k]=matchRidesByDate[k]||[]).push(r);
  });
  function matchRideRow(r){
    const a = analyzeMatch(r.doc.summary||'');
    const kickoff = new Date(r.doc.startMs).toLocaleTimeString(locale(),{hour:'2-digit',minute:'2-digit'});
    const homeAway = a.isHome===true? t('myweek.thuis') : a.isHome===false? t('myweek.uit') : '';
    const passengers = sortGirlIds(r.car.girlIds||[]).map(id=>girlName(id)).join(', ');
    const status = r.driving
      ? `<div class="rideRow__drives"><span class="tag tag--ok">${phIcon('steering-wheel-fill')}${esc(t('myweek.jij_rijdt_tag'))}</span></div>${passengers? `<div class="rideRow__pass">${passengers}</div>`:''}`
      : driverButtonHtml(r.car.driverFamilyId);
    return `<div class="rideRow rideRow--match">
      <div class="rideRow__time"><div class="rideRow__dep">${esc(r.car.departureTime||'--:--')}</div><div class="rideRow__sub">${esc(t('myweek.vertrek'))}</div></div>
      <div class="rideRow__main">
        <div class="rideRow__route"><span class="tag tag--match">${phIcon('soccer')} ${esc(t('myweek.wedstrijd_2'))}</span> ${esc(matchLabel(r.doc))}${homeAway} ${t('myweek.vs')} ${esc(a.opponent)}</div>
        ${status}
        <div class="rideRow__pass">${t('myweek.aftrap')} ${kickoff}${r.doc.location? ' · '+locationLinkHtml(r.doc.location):''}</div>
        ${matchDistanceHtml(docToMatch(r.doc))}
      </div>
    </div>`;
  }
  const matchRowsFor = date => (matchRidesByDate[date.toDateString()]||[]).map(matchRideRow).join('');

  const todayStr = new Date().toDateString();
  const weekdayDates = new Set(DAYS.map(([k])=>dateForWeekday(k).toDateString()));
  const dayInfo = DAYS.map(([k,label])=>{
    const rows = rideRow(k,'heen') + rideRow(k,'terug') + matchRowsFor(dateForWeekday(k));
    return { key:k, label, date:dateForWeekday(k), rows, isToday: k===todayKeyNow() };
  }).filter(d=>d.rows);
  const dateText = d => d.toLocaleDateString(locale(),{day:'numeric',month:'short'});
  const dayCardHtml = d => `<div class="rideCard"><div class="rideCard__head">${esc(d.label)} <small>${dateText(d.date)}</small></div>${d.rows}</div>`;

  // Match rides on days outside Ma–Vr of the planning week (the weekend) get their own card.
  const planningMonday = startOfWeek(effectivePlanningDate());
  const extraKeys = Object.keys(matchRidesByDate).filter(k=>!weekdayDates.has(k)).sort((a,b)=>matchDateByKey[a]-matchDateByKey[b]);
  const extraCard = key => {
    const d = matchDateByKey[key];
    const name = d.toLocaleDateString(locale(),{weekday:'long'});
    return `<div class="rideCard${key===todayStr?' rideCard--match':''}"><div class="rideCard__head">${esc(name.charAt(0).toUpperCase()+name.slice(1))} <small>${dateText(d)}</small></div>${matchRowsFor(d)}</div>`;
  };
  const afterCards = extraKeys.filter(k=>matchDateByKey[k]>=planningMonday).map(extraCard).join('');

  const todayDay = dayInfo.find(d=>d.isToday);
  const todayCardHtml = todayDay ? `<div class="rideCard rideCard--today">
      <div class="rideCard__today"><span class="rideCard__dot"></span><span class="rideCard__todayLabel">${esc(t('myweek.vandaag'))}</span><span class="rideCard__date">${esc(todayDay.date.toLocaleDateString(locale(),{weekday:'long', day:'numeric', month:'short'}))}</span></div>
      ${todayDay.rows}</div>` : '';
  const todayIdx = DAYS.findIndex(([k])=>k===todayKeyNow());
  const upcoming = dayInfo.filter(d=>!d.isToday && (todayIdx<0 || DAYS.findIndex(([k])=>k===d.key)>todayIdx));
  const restHtml = (upcoming.length||afterCards) ? `<div class="sectionLabel">${esc(t('myweek.rest_van_de_week'))}</div>${upcoming.map(dayCardHtml).join('')}${afterCards}` : '';
  const noRidesHtml = (!todayCardHtml && !restHtml) ? `<p class="muted">${t('myweek.geen_dagen_met_een_tijd')}</p>` : '';

  // This week's matches: one tile each, linking to the Wedstrijd tab where the carpool is arranged.
  const weekMatches = matchesThisWeek(currentMatchList());
  const matchTiles = weekMatches.map(m=>{
    const a = analyzeMatch(m.summary);
    const homeAway = a.isHome===true? t('myweek.thuis') : a.isHome===false? t('myweek.uit') : '';
    const cars = ((carpoolFor(m).doc||{}).cars||[]).length;
    const when = m.start.toLocaleDateString(locale(),{weekday:'short', day:'numeric', month:'short'}).replace('.','');
    const kick = m.start.toLocaleTimeString(locale(),{hour:'2-digit',minute:'2-digit'});
    const sub = [`${t('myweek.aftrap')} ${kick}`, matchDistanceText(m), cars===1? t('myweek.match_cars_one') : cars? t('myweek.match_cars', { n: cars }) : t('myweek.match_geen_carpool')].filter(Boolean).join(' · ');
    return `<button type="button" class="matchTile" data-gomatchcarpool="1"><span class="matchTile__icon">${phIcon('soccer-ball-fill')}</span>
      <span class="matchTile__text"><div class="matchTile__title">${esc(when)} · ${esc(matchLabel(m))}${esc(homeAway)} · ${esc(a.opponent)}</div>
      <div class="matchTile__sub">${esc(sub)}</div></span>
      <span class="matchTile__more">${phIcon('caret-right')}</span></button>${m.location? `<div class="noteLine matchTileRoute">${phIcon('map-pin')} ${locationLinkHtml(m.location)}</div>` : ''}`;
  }).join('');
  const matchStatusNote = S.matchesSource==='live' ? '' : (S.cachedMatchesAt? `<p class="noteLine">${t('beheer.laatst_opgehaald')} ${new Date(S.cachedMatchesAt).toLocaleString(locale())}</p>` : '');
  const matchFailNote = S.matchFetchFailedTeams.length? `<p class="noteLine">${t('myweek.kon_niet_ophalen')} ${esc(S.matchFetchFailedTeams.map(f=>f.label+' ('+f.error+')').join('; '))}</p>` : '';

  // Rides of the daughter that have no car yet — today first, then the rest of the week.
  const todayMidnight = new Date(); todayMidnight.setHours(0,0,0,0);
  const alertRows = [];
  DAYS.forEach(([k,label])=>{
    if(dateForWeekday(k) < todayMidnight) return; // days already past
    ['heen','terug'].forEach(direction=>{
      const s = rideTime(myId, k, direction);
      if(!s || isFlex(myFam)) return; // Flex is never auto-planned, so nothing is 'missing'
      if(effectiveCars(k,direction).some(c=>(c.girlIds||[]).includes(myId))) return;
      if(ovGirlsFor(k,undefined,direction).includes(myId)) return;   // marked "Rijdt niet mee"
      const when = label.slice(0,2);   // "Do terug · klaar 20:00" (design v2)
      const doneText = direction==='heen' ? t('myweek.alert_heen', { time: s }) : t('myweek.alert_terug', { time: s });
      alertRows.push(`<div class="alertCard"><span class="alertCard__icon">${phIcon('warning-circle-fill')}</span>
        <div class="alertCard__text"><b>${esc(when)} ${esc(dirName(direction).toLowerCase())} · ${esc(doneText)}</b><br>${esc(plainGirlName(myId))} ${t('myweek.heeft_nog_geen_rit')}</div>
        <button type="button" class="btn" data-gowijzig="${k}">${t('myweek.regelen')}</button></div>`);
    });
  });

  box.innerHTML = `
    ${todayCardHtml}${alertRows.join('')}${noRidesHtml}${restHtml}
    ${matchTiles}${matchFailNote}${matchStatusNote}
    ${dayCoordinatorHtml()}
    ${lastUpdateFooter([S.lastUpdateRooster,S.lastUpdateDeviation].filter(Boolean).sort((a,b)=>(b.at||0)-(a.at||0))[0])}
  `;
  box.querySelectorAll('[data-gowijzig]').forEach(b=>b.onclick=()=>goToWijzigen(b.dataset.gowijzig));
  box.querySelectorAll('[data-ovtoggle]').forEach(b=>b.onclick=async ()=>{
    const on = b.dataset.ovon==='1';
    const day = b.dataset.ovtoggle, direction = b.dataset.ovdir;
    if(await setReturnByPublicTransport(day, myId, on, direction)){
      // Toast with an Undo action: one tap puts it back the way it was.
      showToast(t(on? 'ov.on' : 'ov.off', { p1: plainGirlName(myId) }), { action: { label: t('ov.toastUndo'), run: async ()=>{
        if(await setReturnByPublicTransport(day, myId, !on, direction)) showToast(t(on? 'ov.off' : 'ov.on', { p1: plainGirlName(myId) }));
      } } });
    }
  });
  box.querySelectorAll('[data-gomatchcarpool]').forEach(b=>b.onclick=()=>goToMatchCarpool());
}

// Jump to the Wijzigen tab, optionally straight into one day.
export function goToWijzigen(day){
  if(day) S.deviationDay = day; // no day given: keep the day that was open
  S.openMatchCarpoolForm = null;
  renderDeviationTab(); activateTab('deviation'); hapticTap();
}

// Jump to the Wedstrijden tab (where the match carpools are set up).
export function goToMatchCarpool(){
  S.openMatchCarpoolForm = null;
  renderMatchesTab(); activateTab('matches'); hapticTap();
}
