// ui-profile.js — generated by the modularisation of index.html; see README for what lives where.
import { t } from './i18n.js';
import { S } from './state.js';
import { adjustMainPadding, esc, hapticTap, installCardHtml, phIcon, showToast, twoStepConfirm, updateStatusLine, wireInstallCard } from './ui-common.js';
import { fam } from './rides.js';
import { isValidInviteCode, myDisplayInfo, myFamilyId, needsGate, normalizePhone, recomputeCanEdit } from './coordinator.js';
import { activateTab, afterLinksChanged, renderAll } from './app.js';
import { APP_URL, DAYS, DIR_TEXT, WA_ICON_SMALL } from './constants.js';
import { waPhone } from './ui-schedule.js';
import { dayUp } from './dates.js';
import { db } from './data.js';
import { goToWijzigen } from './ui-myweek.js';
import { describeWeekschemaChange } from './ui-deviation.js';
import { diffSchedules, diffWeekschema, mergePendingChanges } from './schedule-changes.js';

// ---------- Coordinator test mode: view the app as a specific parent, without losing real rights ----------
export function renderImpersonateBanner(){
  const el=document.getElementById('impersonateBanner');
  if(!el) return;
  if(S.impersonateFamilyId){
    el.style.display='block';
    el.style.cssText='display:block;background:var(--warn2);color:var(--warn);padding:8px 16px;font-size:12px;text-align:center;font-weight:600;border-bottom:1px solid var(--border)';
    el.innerHTML = `${phIcon('flask')} ${t('profile.testweergave_als')} ${esc(fam(S.impersonateFamilyId).girlName||fam(S.impersonateFamilyId).parentName||S.impersonateFamilyId)} <button type="button" class="btn small secondary" id="stopImpersonateBtn" style="margin-left:8px">${t('profile.stop_testen')}</button>`;
    const btn=document.getElementById('stopImpersonateBtn');
    if(btn) btn.onclick=stopImpersonate;
  } else {
    el.style.display='none'; el.innerHTML='';
  }
}

export function startImpersonate(familyId){
  if(!familyId) return;
  S.impersonateFamilyId=familyId;
  recomputeCanEdit();
  const navB=document.getElementById('navBeheer'); if(navB) navB.style.display='none';
  showToast(t('profile.testweergave_gestart'));
  S.roosterMode='week';
  renderAll();
  activateTab('myweek');
}

export function stopImpersonate(){
  S.impersonateFamilyId=null;
  recomputeCanEdit();
  const navB=document.getElementById('navBeheer'); if(navB) navB.style.display=S.canEdit?'':'none';
  showToast(t('profile.terug_naar_coordinatorweergave'));
  S.roosterMode='standard';
  renderAll();
  activateTab('beheer');
}

// ---------- Weekschema edits wait for confirmation ----------
// A change to the Weekschema (times, "Rijdt", "Back-up") changes the standard planning for every week, so it is
// NOT saved straight away. S.weekschemaBase holds the saved Weekschema, S.weekschemaEdit the edited one.
// The warning offers two ways out: Bevestigen (save, for every week) or Eenmalig wijzigen (undo the edit and
// open Wijzigen, prepared with what the parent wanted).
const clone = o => JSON.parse(JSON.stringify(o||{}));

export function weekschemaChanges(){
  return S.weekschemaBase && S.weekschemaEdit? diffWeekschema(S.weekschemaBase, S.weekschemaEdit) : [];
}

export function weekschemaWarningInnerHtml(){
  const changes = weekschemaChanges();
  return `<p class="devAlertTitle">${phIcon('warning')} ${t('profile.weekschema_waarschuwing_titel')}</p>
    <ul class="devIntentList">${changes.map(c=>`<li>${esc(describeWeekschemaChange(c))}</li>`).join('')}</ul>
    <p class="devAlertBody" style="font-size:12px">${t('profile.weekschema_waarschuwing_tekst')}</p>
    <div class="rowflex" style="justify-content:flex-start;gap:8px;flex-wrap:wrap;margin-top:8px">
      <button type="button" class="btn small" id="weekschemaConfirm">${t('profile.weekschema_bevestigen')}</button>
      <button type="button" class="btn small secondary" id="weekschemaToWijzigen">${phIcon('lightning')} ${t('profile.weekschema_naar_wijzigen')}</button>
    </div>
    <p class="devAlertBody" style="font-size:11px">${t('profile.weekschema_eenmalig_uitleg')}</p>`;
}

export function weekschemaWarningHtml(){
  const has = weekschemaChanges().length>0;
  return `<div class="devAlert" id="weekschemaWarn" role="status" aria-live="polite" style="margin:8px 0 0"${has? '' : ' hidden'}>${has? weekschemaWarningInnerHtml() : ''}</div>`;
}

// Redraws just the warning (no full re-render, so typing and focus are not disturbed).
export function refreshWeekschemaWarning(){
  const el=document.getElementById('weekschemaWarn'); if(!el) return;
  const has = weekschemaChanges().length>0;
  el.hidden = !has;
  el.innerHTML = has? weekschemaWarningInnerHtml() : '';
  wireWeekschemaWarning();
}

export function wireWeekschemaWarning(){
  const ok=document.getElementById('weekschemaConfirm'); if(ok) ok.onclick=()=>confirmWeekschema();
  const one=document.getElementById('weekschemaToWijzigen'); if(one) one.onclick=()=>weekschemaOneOff();
}

// A Weekschema field changed: compare the form with the saved Weekschema and (un)show the warning.
export function onWeekschemaEdited(){
  const effId = myFamilyId();
  if(!S.weekschemaBase){
    const f = fam(effId);
    S.weekschemaBase = {schedule: clone(f.schedule), availability: clone(f.availability)};
  }
  const live = readFamilyForm('me');
  S.weekschemaEdit = {schedule: live.schedule, availability: live.availability};
  if(!weekschemaChanges().length){ S.weekschemaBase = null; S.weekschemaEdit = null; } // edited back to the original
  refreshWeekschemaWarning();
}

// "Bevestigen": save the edit for every week; the warning clears.
export async function confirmWeekschema(){
  if(!S.weekschemaBase) return;
  const effId = myFamilyId();
  const live = readFamilyForm('me');
  S.weekschemaBase = null; S.weekschemaEdit = null;
  await saveProfile();
  if(S.families[effId]) S.families[effId] = {...S.families[effId], schedule:live.schedule, availability:live.availability};
  refreshWeekschemaWarning();
  showToast(t('profile.weekschema_bevestigd'));
}

// "Eenmalig wijzigen": undo the edit, clear the warning, open Wijzigen on the right day with the intended change.
export function weekschemaOneOff(){
  const changes = weekschemaChanges();
  if(!changes.length) return;
  const effId = myFamilyId();
  const base = S.weekschemaBase;
  if(S.families[effId]) S.families[effId] = {...S.families[effId], schedule:clone(base.schedule), availability:clone(base.availability)};
  S.weekschemaBase = null; S.weekschemaEdit = null;
  S.deviationIntent = changes;
  refreshWeekschemaWarning();
  renderProfile();
  goToWijzigen(changes[0].day);
}

// While an edit waits for confirmation it is laid over the family data, so a re-render (for instance after a
// live update from the database) does not lose it.
export function overlayWeekschemaEdit(effId){
  if(S.weekschemaBase && S.weekschemaEdit && S.families[effId]){
    S.families[effId] = {...S.families[effId], schedule:S.weekschemaEdit.schedule, availability:S.weekschemaEdit.availability};
  }
}

// True when a form field belongs to the Weekschema (times or availability), not to name/phone/capacity.
export function isWeekschemaField(id){
  return /^me_(sch|av|bkH|bkT)_/.test(id||'');
}

// Beheer only: WhatsApp link that sends a fixed login intro ("Hi!", no parent name) to `phone`.
// Empty href while there is no usable number.
export function introWaHref(phone, code){
  const num = waPhone(phone);
  if(!num) return '';
  const text = code? t('profile.wa_intro_text', { url: APP_URL, code }) : t('profile.wa_intro_text_nocode', { url: APP_URL });
  return 'https://wa.me/'+num+'?text='+encodeURIComponent(text);
}
function introWaIconHtml(key, phone, code){
  const href = introWaHref(phone, code);
  return `<a class="waIntro" data-waintro="${key}" ${href? `href="${esc(href)}"` : 'hidden'} target="_blank" rel="noopener noreferrer" aria-label="${esc(t('profile.wa_intro_label'))}" title="${esc(t('profile.wa_intro_label'))}">${WA_ICON_SMALL}</a>`;
}
// Keeps the icons' links in step with what is typed in the phone / code fields.
export function wireIntroWa(prefix){
  const code = ()=>{ const el=document.getElementById(`${prefix}_inviteCode`); return el? el.value.trim() : ''; };
  const refresh = ()=>['parentPhone1','parentPhone2'].forEach((field,i)=>{
    const a=document.querySelector(`[data-waintro="${i+1}"]`), input=document.getElementById(`${prefix}_${field}`);
    if(!a||!input) return;
    const href=introWaHref(input.value, code());
    if(href){ a.href=href; a.hidden=false; } else { a.removeAttribute('href'); a.hidden=true; }
  });
  [`${prefix}_parentPhone1`,`${prefix}_parentPhone2`,`${prefix}_inviteCode`].forEach(id=>{
    const el=document.getElementById(id); if(el) el.addEventListener('input',refresh);
  });
  refresh();
  const gen=document.getElementById('genCodeBtn'); if(gen) gen.addEventListener('click',()=>setTimeout(refresh,0));
}

export function familyFormHtml(prefix,f){
  f = f || {parentName:"",girlName:"",capacity:4,schedule:{},availability:{}};
  const activeDay = S.formSelectedDay[prefix]||'Ma';
  const dayTabs = DAYS.map(([k,label])=>
    `<button type="button" class="dayTabBtn ${k===activeDay?'active':''}" data-daytab="${prefix}|${k}" aria-label="${label}">${dayUp(k)}</button>`
  ).join('');
  const s=(f.schedule&&f.schedule[activeDay])||{};
  const a=(f.availability&&f.availability[activeDay])||{};
  const dayLabel = DAYS.find(([k])=>k===activeDay)[1];
  const dayDetail = `<div class="dayFormCard">
      <div class="rowflex" style="align-items:baseline">
        <h3 style="margin:0;font-size:16px;font-weight:800">${dayLabel}</h3>
        <span class="muted" style="font-family:var(--font-mono)">${s.heen? t('profile.aankomst')+s.heen : ''}${s.heen&&s.terug? ' · ':''}${s.terug? t('profile.klaar')+s.terug : ''}</span>
      </div>
      <div class="grid2" style="margin-top:10px">
        <div><label style="margin-top:0">${t('profile.heen_aankomst_alkmaar_nodig')}</label><input type="time" id="${prefix}_sch_${activeDay}_heen" value="${s.heen||''}"></div>
        <div><label style="margin-top:0">${t('profile.terug_klaar_om_op_te')}</label><input type="time" id="${prefix}_sch_${activeDay}_terug" value="${s.terug||''}"></div>
      </div>
      <p style="margin:14px 0 6px;font-size:14px;font-weight:700">${t('profile.kan_jij_deze_dag_rijden')}</p>
      <p class="muted" style="margin:0 0 4px">${DIR_TEXT.heen}</p>
      <div class="driveToggleGroup">
        <input type="checkbox" class="driveToggleInput" id="${prefix}_av_${activeDay}_heen" ${a.heen?'checked':''}>
        <label for="${prefix}_av_${activeDay}_heen" class="driveToggleBtn driveToggleBtn-standard"><span class="driveToggleCheck">${phIcon('check')}</span>${t('profile.beschikbaar')}</label>
        <input type="checkbox" class="driveToggleInput" id="${prefix}_bkH_${activeDay}" ${a.backupHeen?'checked':''}>
        <label for="${prefix}_bkH_${activeDay}" class="driveToggleBtn driveToggleBtn-backup"><span class="driveToggleCheck">${phIcon('check')}</span>${t('profile.back_up')}</label>
      </div>
      <p class="muted" style="margin:14px 0 4px">${DIR_TEXT.terug}</p>
      <div class="driveToggleGroup">
        <input type="checkbox" class="driveToggleInput" id="${prefix}_av_${activeDay}_terug" ${a.terug?'checked':''}>
        <label for="${prefix}_av_${activeDay}_terug" class="driveToggleBtn driveToggleBtn-standard"><span class="driveToggleCheck">${phIcon('check')}</span>${t('profile.beschikbaar')}</label>
        <input type="checkbox" class="driveToggleInput" id="${prefix}_bkT_${activeDay}" ${a.backupTerug?'checked':''}>
        <label for="${prefix}_bkT_${activeDay}" class="driveToggleBtn driveToggleBtn-backup"><span class="driveToggleCheck">${phIcon('check')}</span>${t('profile.back_up')}</label>
      </div>
    </div>`;
  // A hidden input per OTHER day preserves its own read/write ids so readFamilyForm keeps
  // working unchanged even though only the active day's inputs are visible at once.
  const hiddenOtherDays = DAYS.filter(([k])=>k!==activeDay).map(([k])=>{
    const os=(f.schedule&&f.schedule[k])||{}; const oa=(f.availability&&f.availability[k])||{};
    return `<input type="hidden" id="${prefix}_sch_${k}_heen" value="${os.heen||''}">
      <input type="hidden" id="${prefix}_sch_${k}_terug" value="${os.terug||''}">
      <input type="checkbox" style="display:none" id="${prefix}_av_${k}_heen" ${oa.heen?'checked':''}>
      <input type="checkbox" style="display:none" id="${prefix}_av_${k}_terug" ${oa.terug?'checked':''}>
      <input type="checkbox" style="display:none" id="${prefix}_bkH_${k}" ${oa.backupHeen?'checked':''}>
      <input type="checkbox" style="display:none" id="${prefix}_bkT_${k}" ${oa.backupTerug?'checked':''}>`;
  }).join('');
  const seats = Math.max(0,(f.capacity||4)-1);
  const phoneField = (n,placeholder)=>{
    const input = `<input type="tel" inputmode="tel" autocomplete="off" ${prefix==='coord'? 'style="flex:1;min-width:0" ' : ''}id="${prefix}_parentPhone${n}" value="${esc(f['parentPhone'+n]||'')}" placeholder="${placeholder}">`;
    if(prefix!=='coord') return input;
    const code = (S.inviteByFamily[S.coordEditId]||'');
    return `<div class="rowflex" style="gap:6px">${input}${introWaIconHtml(n, f['parentPhone'+n]||'', code)}</div>`;
  };
  const phoneInput1 = phoneField(1,'06-12345678'), phoneInput2 = phoneField(2,'06-...');
  return `
    <div class="grid2">
      <div><label style="margin-top:0">${t('profile.naam_ouder')}</label><input type="text" id="${prefix}_parentName" value="${esc(f.parentName||'')}"></div>
      <div><label style="margin-top:0">${t('profile.naam_dochter')}</label><input type="text" id="${prefix}_girlName" value="${esc(f.girlName||'')}"></div>
    </div>${prefix==='coord'? `
    <label>${t('profile.gezinstype')}</label>
    <select id="${prefix}_familyType">
      <option value="vast" ${f.familyType==='flex'?'':'selected'}>${t('profile.gezinstype.vast')}</option>
      <option value="flex" ${f.familyType==='flex'?'selected':''}>${t('profile.gezinstype.flex')}</option>
    </select>` : ''}
    <div class="grid2">
      <div><label style="margin-top:8px">${prefix==='me'? t('profile.tel_nr_1_wa') : t('profile.tel_nr_1')}</label>${phoneInput1}</div>
      <div><label style="margin-top:8px">${t('profile.tel_nr_2')}</label>${phoneInput2}</div>
    </div>
    <label>${t('profile.totale_autocapaciteit_incl_bestuurder')}</label>
    <div class="stepperCard">
      <div class="stepperInfo">${phIcon('car')}<div>
        <div class="stepperTitle" id="${prefix}_capacityTitle">${f.capacity||4} ${t('profile.zitplaatsen_totaal')}</div>
        <div class="stepperSub">${t('profile.plek_voor')} <strong id="${prefix}_capacityHint">${seats}</strong> ${t('profile.passagiers')}</div>
      </div></div>
      <div class="stepperControls">
        <button type="button" class="stepperBtn" data-stepdown="${prefix}" aria-label="${t('profile.minder_zitplaatsen')}">−</button>
        <span class="stepperValue" id="${prefix}_capacityValue">${f.capacity||4}</span>
        <button type="button" class="stepperBtn" data-stepup="${prefix}" aria-label="${t('profile.meer_zitplaatsen')}">+</button>
      </div>
    </div>
    <input type="hidden" id="${prefix}_capacity" value="${f.capacity||4}">
    <div class="rowflex" style="margin-top:16px;align-items:baseline">
      <p style="margin:0;font-size:14px;font-weight:700">${t('profile.weekschema_beschikbaarheid_per_dag')}</p>
    </div>
    ${prefix==='me'? weekschemaWarningHtml() : ''}
    <div class="grid5" style="margin-top:8px">${dayTabs}</div>
    ${dayDetail}
    ${hiddenOtherDays}`;
}

export function wireFamilyFormExtras(prefix, rerenderFn){
  DAYS.forEach(([k])=>{
    const btn=document.querySelector(`[data-daytab="${prefix}|${k}"]`);
    if(btn) btn.onclick=()=>{
      // Merge in whatever's currently typed (even not-yet-blurred edits) before switching
      // days, so a fast tab-switch can never silently discard an in-progress edit.
      try{
        const live = readFamilyForm(prefix);
        const targetId = prefix==='me'? myFamilyId() : S.coordEditId;
        if(targetId!=null && S.families[targetId]) S.families[targetId] = {...S.families[targetId], ...live};
      }catch(e){ /* nothing persisted yet to merge with (e.g. brand new family) — safe to skip */ }
      S.formSelectedDay[prefix]=k; hapticTap(); rerenderFn();
    };
  });
  const hidden=document.getElementById(`${prefix}_capacity`);
  const valueEl=document.getElementById(`${prefix}_capacityValue`);
  const titleEl=document.getElementById(`${prefix}_capacityTitle`);
  const hintEl=document.getElementById(`${prefix}_capacityHint`);
  function step(delta){
    let v=(parseInt(hidden.value)||4)+delta;
    v=Math.max(1,Math.min(9,v));
    hidden.value=v;
    if(valueEl) valueEl.textContent=v;
    if(titleEl) titleEl.textContent=v+t('profile.zitplaatsen_totaal_2');
    if(hintEl) hintEl.textContent=Math.max(0,v-1);
    hapticTap();
    hidden.dispatchEvent(new Event('change',{bubbles:true}));
  }
  const downBtn=document.querySelector(`[data-stepdown="${prefix}"]`);
  const upBtn=document.querySelector(`[data-stepup="${prefix}"]`);
  if(downBtn) downBtn.onclick=()=>step(-1);
  if(upBtn) upBtn.onclick=()=>step(1);
}

// "Rijdt X" and "Back-up X" are mutually exclusive: ticking one unticks the other.
export function wireExclusiveAvailability(prefix){
  DAYS.forEach(([k])=>{
    const heen=document.getElementById(`${prefix}_av_${k}_heen`);
    const bkH=document.getElementById(`${prefix}_bkH_${k}`);
    const terug=document.getElementById(`${prefix}_av_${k}_terug`);
    const bkT=document.getElementById(`${prefix}_bkT_${k}`);
    if(heen && bkH){
      heen.addEventListener('change', ()=>{ if(heen.checked) bkH.checked=false; });
      bkH.addEventListener('change', ()=>{ if(bkH.checked) heen.checked=false; });
    }
    if(terug && bkT){
      terug.addEventListener('change', ()=>{ if(terug.checked) bkT.checked=false; });
      bkT.addEventListener('change', ()=>{ if(bkT.checked) terug.checked=false; });
    }
  });
}

export function readFamilyForm(prefix){
  const schedule={}, availability={};
  DAYS.forEach(([k])=>{
    schedule[k]={heen:document.getElementById(`${prefix}_sch_${k}_heen`).value, terug:document.getElementById(`${prefix}_sch_${k}_terug`).value};
    availability[k]={
      heen:document.getElementById(`${prefix}_av_${k}_heen`).checked,
      terug:document.getElementById(`${prefix}_av_${k}_terug`).checked,
      backupHeen:document.getElementById(`${prefix}_bkH_${k}`).checked,
      backupTerug:document.getElementById(`${prefix}_bkT_${k}`).checked
    };
  });
  // Only the coordinator's form has this field; a parent's own save leaves the type untouched (merge).
  const typeEl = prefix==='coord'? document.getElementById(`${prefix}_familyType`) : null;
  const familyType = typeEl && (typeEl.value==='flex' || typeEl.value==='vast')? { familyType: typeEl.value } : {};
  return {
    ...familyType,
    parentName:document.getElementById(`${prefix}_parentName`).value.trim(),
    girlName:document.getElementById(`${prefix}_girlName`).value.trim(),
    parentPhone1:document.getElementById(`${prefix}_parentPhone1`).value.trim(),
    parentPhone2:document.getElementById(`${prefix}_parentPhone2`).value.trim(),
    // Normalised copies, checked by the Firestore rules when someone passes the gate.
    phoneKeys:[`${prefix}_parentPhone1`,`${prefix}_parentPhone2`].map(id=>normalizePhone(document.getElementById(id).value)).filter(Boolean),
    capacity:parseInt(document.getElementById(`${prefix}_capacity`).value)||4,
    schedule, availability
  };
}

// ---------- First-run: nobody has claimed coordinator yet ----------
export function renderClaimCoordinator(){
  const box=document.getElementById('tab-gate');
  if(!box) return;
  box.innerHTML = `<div style="max-width:420px;margin:30px auto 0">
    <div class="card">
      <h2>${t('profile.welkom_bij_az_carpool')}</h2>
      <p class="muted">${t('profile.er_is_nog_geen_coordinator')}</p>
      <button type="button" class="btn" id="claimCoordBtn">${t('profile.ik_ben_de_coordinator')}</button>
      <p class="muted" style="margin-top:10px">${t('profile.ben_je_een_ouder_en')}</p>
    </div>
  </div>`;
  const btn=document.getElementById('claimCoordBtn');
  if(btn) btn.onclick=async ()=>{
    try{
      const cfg={uid:S.me, claimedAt:Date.now()};
      await db.doc("config/coordinator").set(cfg);
      S.coordinatorConfig=cfg; S.coordinatorExists=true;
      recomputeCanEdit();
      const navB=document.getElementById('navBeheer'); if(navB) navB.style.display=S.canEdit?'':'none';
      showToast(t('profile.je_bent_nu_coordinator'));
      renderAll();
    }catch(e){ showToast(t('profile.mislukt_mogelijk_had_iemand_anders')+(e&&e.message||e)); }
  };
}

export function renderGateOrApp(){
  const nav=document.querySelector('nav');
  const gateDiv=document.getElementById('tab-gate');
  if(!gateDiv) return;
  if(!S.appReady || !S.linksLoaded){
    // Still determining auth/coordinator state — never show the claim screen (or anything else)
    // until we actually know whether a coordinator already exists.
    if(nav) nav.style.display='none';
    ['schedule','myweek','deviation','profile','beheer'].forEach(t=>{ const el=document.getElementById('tab-'+t); if(el) el.style.display='none'; });
    gateDiv.style.display='block';
    gateDiv.innerHTML = `<div style="max-width:420px;margin:30px auto 0"><div class="card"><p class="muted">${t('profile.laden')}</p></div></div>`;
    adjustMainPadding();
    return;
  }
  if(!S.coordinatorExists && !S.canEdit){
    if(nav) nav.style.display='none';
    ['schedule','myweek','deviation','profile','beheer'].forEach(t=>{ const el=document.getElementById('tab-'+t); if(el) el.style.display='none'; });
    gateDiv.style.display='block';
    renderClaimCoordinator();
    adjustMainPadding();
    return;
  }
  if(needsGate()){
    if(nav) nav.style.display='none';
    ['schedule','myweek','deviation','profile','beheer'].forEach(t=>{ const el=document.getElementById('tab-'+t); if(el) el.style.display='none'; });
    gateDiv.style.display='block';
    renderGate();
  } else {
    if(nav) nav.style.display='flex';
    gateDiv.style.display='none';
    const activeBtn=document.querySelector('nav button.active');
    const activeTab=activeBtn? activeBtn.dataset.tab : 'myweek';
    ['schedule','myweek','deviation','profile','beheer'].forEach(t=>{
      const el=document.getElementById('tab-'+t);
      if(el) el.style.display=(t===activeTab)?'block':'none';
    });
  }
  adjustMainPadding();
}

export function renderGate(){
  const box=document.getElementById('tab-gate');
  if(!box) return;
  box.innerHTML = `<div style="max-width:420px;margin:30px auto 0">
    <div class="card">
      <h2>${t('profile.toegang_tot_az_carpool')}</h2>
      <p class="muted">${t('profile.vul_je_telefoonnummer_en_de')}</p>
      <label>${t('profile.telefoonnummer')}</label>
      <input type="tel" id="gatePhone" inputmode="tel" autocomplete="tel" placeholder="06-12345678">
      <label>${t('profile.code')}</label>
      <input type="text" id="gateCode" inputmode="numeric" autocomplete="one-time-code" maxlength="32" placeholder="${t('profile.code_van_de_coordinator')}">
      <button type="button" class="btn" id="gateSubmit">${t('profile.toegang_aanvragen')}</button>
      <p id="gateMsg" class="muted" style="margin-top:8px"></p>
    </div>
  </div>`;
  const btn=document.getElementById('gateSubmit');
  if(btn) btn.onclick=submitGate;
}

// The real check happens in the Firestore rules: a links/{uid} doc is only accepted when `code`
// is an existing invite for `familyId` AND `phoneKey` is one of that family's phoneKeys.
export async function submitGate(){
  if(!db||!S.me){ showToast(t('profile.geen_verbinding_herlaad_de_pagina')); return; }
  const phone=(document.getElementById('gatePhone').value||'').trim();
  const code=(document.getElementById('gateCode').value||'').trim();
  const msg=document.getElementById('gateMsg');
  const say=t=>{ if(msg) msg.textContent=t; };
  if(!phone||!code){ say(t('profile.vul_alle_velden_in')); return; }
  if(!isValidInviteCode(code)){ say(t('profile.code_klopt_niet_controleer_en')); return; }
  const btn=document.getElementById('gateSubmit'); if(btn) btn.disabled=true;
  try{
    const inv = await db.doc("invites/"+code).get();
    const familyId = inv.exists? inv.data().familyId : null;
    if(!familyId){ say(t('profile.code_klopt_niet_controleer_en')); return; }
    const link={familyId, code, phoneKey:normalizePhone(phone), linkedAt:Date.now()};
    await db.doc("links/"+S.me).set(link);
    // The server accepted it. Firestore doesn't send a new snapshot for "pending -> confirmed",
    // so apply it here (the links/{me} listener deliberately ignores the pending version).
    S.links[S.me]=link; afterLinksChanged();
    showToast(t('profile.toegang_verleend'));
  }catch(e){
    say(e && e.code==='permission-denied'
      ? t('profile.dit_telefoonnummer_hoort_niet_bij')
      : t('data.mislukt')+(e&&e.message||e));
  }finally{ if(btn) btn.disabled=false; }
}

export function renderProfile(){
  const box=document.getElementById('tab-profile');
  if(!box) return;
  let html=installCardHtml();
  if(!S.me){
    html += `<div class="card"><h2>${t('profile.mijn_gezin')}</h2><p class="muted">${t('deviation.kon_je_account_niet_herkennen')}</p></div>`;
  } else {
    const linked = !!S.impersonateFamilyId || !!(S.links[S.me] && S.links[S.me].familyId);
    if(linked){
      const effId = myFamilyId();
      overlayWeekschemaEdit(effId);
      const lf = fam(effId);
      const unlinkCtl = S.impersonateFamilyId? '' : `<div style="border-top:1px solid var(--border);margin-top:14px;padding-top:4px"><button type="button" class="linkbtn danger" id="unlinkBtn">${t('profile.ontkoppelen_van_deze_dochter')}</button></div>`;
      html += `<div class="card">
        <div class="rowflex" style="align-items:flex-start">
          <div><h2 style="margin-bottom:2px">${t('profile.mijn_gezin')}</h2><p class="muted" style="margin:0">${t('profile.contactgegevens_autocapaciteit')}</p></div>
        </div>
        <p class="muted" style="margin-top:8px">${t('profile.gekoppeld_aan')} <strong>${esc(lf.girlName||lf.parentName||effId)}</strong></p>
        ${familyFormHtml('me', fam(effId))}
        <p class="muted" style="margin-top:8px">${t('beheer.wijzigingen_worden_automatisch_opgeslagen')}</p>
        ${unlinkCtl}
      </div>`;
    } else {
      const options = Object.entries(S.families);
      html += `<div class="card"><h2>${t('profile.mijn_gezin')}</h2>
        <p class="muted">${t('profile.welkom_selecteer_je_dochter_om')}</p>
        ${options.length? `<label>${t('profile.mijn_dochter')}</label><select id="linkSelect">${options.map(([id,f])=>`<option value="${id}">${esc(f.girlName||f.parentName||id)}</option>`).join('')}</select>
        <button type="button" class="btn secondary" id="linkBtn">${t('profile.dit_is_mijn_dochter')}</button>
        <span id="linkMsg" class="muted"></span>` : `<p class="muted">${t('profile.er_zijn_nog_geen_gezinnen')}</p>`}
      </div>`;
    }
  }
  box.innerHTML = html;
  wireInstallCard();
  if(S.me){
    const linked = !!S.impersonateFamilyId || !!(S.links[S.me] && S.links[S.me].familyId);
    if(linked){
      const card=box.querySelector('.card');
      if(card) card.addEventListener('change', e=>{
        if(e && e.target && isWeekschemaField(e.target.id)){ onWeekschemaEdited(); return; } // wait for confirmation
        saveProfile();
      });
      wireWeekschemaWarning();
      wireExclusiveAvailability('me');
      wireFamilyFormExtras('me', renderProfile);
      const ub=document.getElementById('unlinkBtn'); if(ub) ub.onclick=()=>twoStepConfirm(ub,t('profile.zeker_tik_nogmaals_om_te'),async ()=>{
        try{ await db.doc("links/"+S.me).delete(); showToast(t('profile.ontkoppeld')); }catch(e){showToast(t('data.mislukt')+(e&&e.message||e));}
      });
    } else {
      const lb=document.getElementById('linkBtn'); if(lb) lb.onclick=async ()=>{
        const sel=document.getElementById('linkSelect'); if(!sel||!db)return;
        try{ const link={familyId:sel.value, linkedAt:Date.now()}; await db.doc("links/"+S.me).set(link); S.links[S.me]=link; afterLinksChanged(); showToast(t('profile.gekoppeld')); }
        catch(e){showToast(t('profile.koppelen_mislukt')+(e&&e.message||e));}
      };
    }
  }
  updateStatusLine();
  renderGateOrApp();
}

export async function saveProfile(){
  if(!db){showToast(t('profile.geen_verbinding_met_opslag_herlaad'));return;}
  if(!S.me){showToast(t('profile.je_account_kon_niet_herkend'));return;}
  const effId = myFamilyId();
  const data = readFamilyForm('me');
  // An edit that still waits for confirmation must not be saved along with other fields.
  if(S.weekschemaBase){ data.schedule = clone(S.weekschemaBase.schedule); data.availability = clone(S.weekschemaBase.availability); }
  // A parent (not the coordinator) changing their daughter's times gets flagged for the
  // coordinator, stored on the family doc itself as `timeChanges` until marked as seen.
  const timeChanges = S.canEdit? [] : diffSchedules(S.serverSchedules[effId], data.schedule);
  if(timeChanges.length){
    data.timeChanges = mergePendingChanges(fam(effId).timeChanges, timeChanges, {at:Date.now(), by:myDisplayInfo().name});
  }
  try{
    await db.doc("families/"+effId).set(data,{merge:true});
    S.serverSchedules[effId] = JSON.parse(JSON.stringify(data.schedule));
    if(data.timeChanges && S.families[effId]) S.families[effId] = {...S.families[effId], timeChanges:data.timeChanges};
    showToast(timeChanges.length? t('profile.opgeslagen_de_coordinator_ziet_je') : t('data.opgeslagen'));
  }
  catch(e){showToast(t('data.opslaan_mislukt')+(e&&e.message||e));}
}
